import type { Mnemonic } from "@/types/content";

export const cirugiaMnemonics: Mnemonic[] = [
  {
    id: "nm-cx-001",
    topicId: "cirugia",
    subtopic: "Vía biliar",
    title: "Factores de riesgo de litiasis biliar",
    keyword: "Las 4 F (en inglés)",
    breakdown: [
      { letter: "F", meaning: "Female (sexo femenino)" },
      { letter: "F", meaning: "Forty (alrededor de los 40 años)" },
      { letter: "F", meaning: "Fertile / múltiple pariFy (multiparidad)" },
      { letter: "F", meaning: "Fat (obesidad)" },
    ],
    usage: "Perfil clásico de riesgo para colelitiasis, útil para reconocer al paciente típico en un caso clínico.",
    source: { label: "Sabiston Textbook of Surgery, 21.ª ed." },
  },
  {
    id: "nm-cx-002",
    topicId: "cirugia",
    subtopic: "Preoperatorio",
    title: "Evaluación preoperatoria básica",
    keyword: "AMPLIA",
    breakdown: [
      { letter: "A", meaning: "Alergias" },
      { letter: "M", meaning: "Medicamentos actuales" },
      { letter: "P", meaning: "Patologías previas (antecedentes)" },
      { letter: "L", meaning: "Libaciones/última ingesta (ayuno)" },
      { letter: "I", meaning: "Incidentes/eventos relacionados al problema actual" },
      { letter: "A", meaning: "Ambiente (contexto del evento, ej. trauma)" },
    ],
    usage: "Historia clínica dirigida rápida (equivalente a 'AMPLE' en inglés), usada en la evaluación preoperatoria y de trauma.",
    source: { label: "ATLS Student Course Manual, 10.ª ed." },
  },
  {
    id: "nm-cx-003",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    title: "Causas de abdomen agudo quirúrgico por cuadrante",
    keyword: "FID: Ap-Ov-Hern",
    breakdown: [
      { letter: "Ap", meaning: "Apendicitis aguda (fosa ilíaca derecha)" },
      { letter: "Ov", meaning: "Patología ovárica (quiste roto, torsión) en mujeres" },
      { letter: "Hern", meaning: "Hernia inguinal complicada" },
    ],
    usage: "Ayuda a generar diagnóstico diferencial estructurado de dolor en fosa ilíaca derecha, el cuadrante más preguntado en abdomen agudo.",
    source: { label: "Schwartz's Principles of Surgery, 11.ª ed." },
  },
  {
    id: "nm-cx-004",
    topicId: "cirugia",
    subtopic: "Suturas de piel",
    title: "Técnica del punto colchonero vertical (Blair-Donati)",
    keyword: "Lejos-Lejos, Cerca-Cerca",
    breakdown: [
      { letter: "Lejos", meaning: "Primer paso de la aguja, 5-10 mm del borde de la herida (toma profunda de dermis)" },
      { letter: "Lejos", meaning: "Se repite en el borde opuesto a la misma distancia 'Lejos'" },
      { letter: "Cerca", meaning: "Se reingresa la aguja cerca del borde inicial, a 2-3 mm (toma superficial de dermis)" },
      { letter: "Cerca", meaning: "Se sale en el borde opuesto a la misma distancia 'Cerca' y se anuda" },
    ],
    usage: "Nemotecnia clásica para recordar la secuencia de pasos del punto colchonero vertical, usado para disminuir la tensión de la herida y evertir sus bordes.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 3: Suturas de piel" },
  },
  {
    id: "nm-cx-005",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    title: "Zonas de lesión de una quemadura (Jackson)",
    keyword: "C-E-H (centro hacia afuera)",
    breakdown: [
      { letter: "C", meaning: "Coagulación — zona central, tejido más grave, coagulado/necrótico" },
      { letter: "E", meaning: "Éstasis — vasoconstricción e isquemia, similar a quemadura de 2do grado" },
      { letter: "H", meaning: "Hiperemia — periferia, cicatrización mínima, similar a lesión de 1er grado" },
    ],
    usage: "Ayuda a recordar las 3 zonas concéntricas de una quemadura descritas por Jackson, de mayor a menor gravedad desde el centro hacia la periferia.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "nm-cx-006",
    topicId: "cirugia",
    subtopic: "Choque",
    title: "Los 6 tipos de choque",
    keyword: "Hi-Ca-Se-Ne-Tra-Ob",
    breakdown: [
      { letter: "Hi", meaning: "Hipovolémico" },
      { letter: "Ca", meaning: "Cardiogénico" },
      { letter: "Se", meaning: "Séptico (vasodilatador)" },
      { letter: "Ne", meaning: "Neurógeno" },
      { letter: "Tra", meaning: "Por traumatismo" },
      { letter: "Ob", meaning: "Obstructivo" },
    ],
    usage: "Lista completa y actualizada de los 6 tipos de choque reconocidos en la práctica clínica reciente, ampliando las 4 categorías clásicas de 1934.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 6: Choque - Schwartz" },
  },
];
