import type { Mnemonic } from "@/types/content";

export const ginecoObstetriciaMnemonics: Mnemonic[] = [
  {
    id: "nm-go-001",
    topicId: "gineco-obstetricia",
    subtopic: "Hemorragia obstétrica",
    title: "Causas de hemorragia posparto",
    keyword: "Las 4 T",
    breakdown: [
      { letter: "T", meaning: "Tono (atonía uterina — la causa más frecuente)" },
      { letter: "T", meaning: "Trauma (laceraciones de canal de parto, ruptura uterina)" },
      { letter: "T", meaning: "Tejido (restos placentarios retenidos)" },
      { letter: "T", meaning: "Trombina (coagulopatías)" },
    ],
    usage: "Estructura el diagnóstico diferencial sistemático ante una hemorragia posparto, en orden de frecuencia decreciente.",
    source: { label: "FIGO/OMS — Manejo de la hemorragia posparto" },
  },
  {
    id: "nm-go-002",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    title: "Síntomas de severidad en preeclampsia",
    keyword: "CHEET",
    breakdown: [
      { letter: "C", meaning: "Cefalea persistente" },
      { letter: "H", meaning: "Hipertensión severa (≥160/110)" },
      { letter: "E", meaning: "Epigastralgia / dolor en hipocondrio derecho" },
      { letter: "E", meaning: "Escotomas / alteraciones visuales" },
      { letter: "T", meaning: "Trombocitopenia <100,000 y elevación de transaminasas" },
    ],
    usage: "Ayuda a identificar rápidamente los síntomas y signos que definen preeclampsia con criterios de severidad y ameritan sulfato de magnesio.",
    source: { label: "ACOG Practice Bulletin — Gestational Hypertension and Preeclampsia" },
  },
  {
    id: "nm-go-003",
    topicId: "gineco-obstetricia",
    subtopic: "Atención del parto",
    title: "Movimientos cardinales del trabajo de parto",
    keyword: "EDFRERE",
    breakdown: [
      { letter: "E", meaning: "Encajamiento" },
      { letter: "D", meaning: "Descenso" },
      { letter: "F", meaning: "Flexión" },
      { letter: "R", meaning: "Rotación interna" },
      { letter: "E", meaning: "Extensión" },
      { letter: "R", meaning: "Rotación externa" },
      { letter: "E", meaning: "Expulsión" },
    ],
    usage: "Recuerda el orden secuencial de los movimientos cardinales que realiza el feto en presentación cefálica de vértice durante el descenso por el canal del parto.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 3: Parto normal" },
  },
  {
    id: "nm-go-004",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    title: "Criterios de Gibbs para corioamnionitis clínica",
    keyword: "FIEBRE + 2",
    breakdown: [
      { letter: "F", meaning: "Fiebre materna axilar >39°, o >38° con 2 o más de los siguientes" },
      { letter: "T", meaning: "Taquicardia materna (>100 lpm)" },
      { letter: "T", meaning: "Taquicardia fetal (>180 lpm)" },
      { letter: "L", meaning: "Leucocitosis materna (>15,000 WBC)" },
      { letter: "D", meaning: "Dolor a la palpación uterina, y/o líquido amniótico o secreción vaginal fétida" },
    ],
    usage: "Sistematiza los criterios diagnósticos de corioamnionitis clínica ante una ruptura de membranas; la fiebre es el único hallazgo consistentemente confiable, ya que la leucocitosis aislada no lo es.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 13: Ruptura prematura de membranas ovulares" },
  },
  {
    id: "nm-go-005",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    title: "Causas de pérdida habitual del embarazo (RPL)",
    keyword: "CAE",
    breakdown: [
      { letter: "C", meaning: "Cromosómicas — anomalías cromosómicas parentales" },
      { letter: "A", meaning: "Anticuerpos — síndrome de anticuerpos antifosfolípidos" },
      { letter: "E", meaning: "Estructurales — anomalías estructurales del útero (sinequias, leiomiomas, malformaciones congénitas)" },
    ],
    usage: "Resume las tres causas principales investigadas en el estudio de la pérdida habitual del embarazo (2 o más pérdidas confirmadas).",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 7: Aborto" },
  },
];
