import type { Mnemonic } from "@/types/content";

export const medicinaInternaMnemonics: Mnemonic[] = [
  {
    id: "nm-mi-001",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    title: "Factores de riesgo cardiovascular modificables",
    keyword: "SODA HELP",
    breakdown: [
      { letter: "S", meaning: "Smoking (tabaquismo)" },
      { letter: "O", meaning: "Obesidad" },
      { letter: "D", meaning: "Diabetes" },
      { letter: "A", meaning: "Alcohol / sedentarismo (Actividad física baja)" },
      { letter: "H", meaning: "Hipertensión" },
      { letter: "E", meaning: "Elevación de lípidos (dislipidemia)" },
      { letter: "L", meaning: "(estrés) psicosociaL" },
      { letter: "P", meaning: "Poca ingesta de frutas/verduras (dieta)" },
    ],
    usage:
      "Ayuda a repasar rápidamente los factores de riesgo cardiovascular modificables al evaluar prevención primaria en consulta o en preguntas de caso clínico.",
    source: { label: "Adaptado de factores de riesgo INTERHEART Study, Lancet 2004" },
  },
  {
    id: "nm-mi-002",
    topicId: "medicina-interna",
    subtopic: "Neurología",
    title: "Signos de alarma ('banderas rojas') de cefalea secundaria",
    keyword: "SNOOP4",
    breakdown: [
      { letter: "S", meaning: "Systemic symptoms (fiebre, pérdida de peso), Secondary risk factors (VIH, cáncer)" },
      { letter: "N", meaning: "Neurologic signs/symptoms (focalización, alteración de consciencia)" },
      { letter: "O", meaning: "Onset súbito (cefalea en trueno)" },
      { letter: "O", meaning: "Older age (inicio después de los 50 años)" },
      { letter: "P4", meaning: "Pattern change, Positional, Papiledema, Precipitada por Valsalva/tos/ejercicio" },
    ],
    usage:
      "Se usa para decidir cuándo una cefalea requiere neuroimagen urgente y estudio adicional en lugar de manejo como cefalea primaria (migraña/tensional).",
    source: { label: "American Headache Society — SNNOOP10 red flags for headache" },
  },
  {
    id: "nm-mi-003",
    topicId: "medicina-interna",
    subtopic: "Endocrinología",
    title: "Síntomas cardinales de diabetes descompensada",
    keyword: "Las 3 P",
    breakdown: [
      { letter: "P", meaning: "Poliuria" },
      { letter: "P", meaning: "Polidipsia" },
      { letter: "P", meaning: "Polifagia (con pérdida de peso paradójica)" },
    ],
    usage: "Tríada clásica de presentación de diabetes mellitus no controlada, útil para sospecha diagnóstica inicial.",
    source: { label: "ADA — Standards of Care in Diabetes 2024" },
  },
  {
    id: "nm-mi-004",
    topicId: "medicina-interna",
    subtopic: "Nefrología",
    title: "Indicaciones de diálisis urgente",
    keyword: "AEIOU",
    breakdown: [
      { letter: "A", meaning: "Acidosis metabólica refractaria" },
      { letter: "E", meaning: "Electrolitos (hiperkalemia refractaria)" },
      { letter: "I", meaning: "Intoxicaciones (dializables)" },
      { letter: "O", meaning: "Overload / sObrecarga de volumen refractaria" },
      { letter: "U", meaning: "Uremia sintomática (encefalopatía, pericarditis urémica)" },
    ],
    usage: "Recordatorio clásico para identificar indicaciones de terapia de reemplazo renal urgente en falla renal aguda o crónica.",
    source: { label: "KDIGO Clinical Practice Guideline for Acute Kidney Injury" },
  },
  {
    id: "nm-mi-005",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    title: "Contraindicaciones relativas de los bloqueadores β en angina",
    keyword: "ASMAB",
    breakdown: [
      { letter: "A", meaning: "Asma y obstrucción reversible de la vía respiratoria (EPOC)" },
      { letter: "S", meaning: "Síndrome de disfunción sinusal" },
      { letter: "M", meaning: "bloqueo AV Marcado (trastornos de la conducción)" },
      { letter: "A", meaning: "Antecedente de depresión" },
      { letter: "B", meaning: "Bradicardia intensa" },
    ],
    usage: "Ayuda a recordar cuándo evitar o usar con cautela los bloqueadores β en pacientes con angina de pecho estable, considerando alternativas como los antagonistas del calcio.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 11: Angina de pecho estable" },
  },
  {
    id: "nm-mi-006",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    title: "Indicaciones de intubación endotraqueal urgente",
    keyword: "HOPE",
    breakdown: [
      { letter: "H", meaning: "Hipoxemia refractaria" },
      { letter: "O", meaning: "Obstrucción de la vía aérea" },
      { letter: "P", meaning: "Paro respiratorio" },
      { letter: "E", meaning: "Encefalopatía o inadecuada protección de la vía aérea (también: hipercapnia/acidemia, signos de aumento del trabajo respiratorio)" },
    ],
    usage: "Resume las indicaciones clave para proceder a intubación endotraqueal en falla respiratoria aguda, como la observada en COVID-19 severo.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 13: SARS-CoV-2 / COVID-19" },
  },
  {
    id: "nm-mi-007",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    title: "Criterios que definen el síndrome de distrés respiratorio agudo (SDRA)",
    keyword: "IHEC",
    breakdown: [
      { letter: "I", meaning: "Inicio agudo del cuadro" },
      { letter: "H", meaning: "Hipoxemia severa" },
      { letter: "E", meaning: "Edema pulmonar no explicado por falla cardíaca ni sobrecarga de volumen" },
      { letter: "C", meaning: "infiltrados bilaterales en la imagen de tóraX (radiografía o TAC)" },
    ],
    usage: "Ayuda a verificar sistemáticamente los cuatro criterios que definen al SDRA antes de atribuir la hipoxemia a otra causa cardíaca o de sobrecarga hídrica.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 13: SARS-CoV-2 / COVID-19" },
  },
];
