import type { Mnemonic } from "@/types/content";

export const pediatriaMnemonics: Mnemonic[] = [
  {
    id: "nm-ped-001",
    topicId: "pediatria",
    subtopic: "Neonatología",
    title: "Componentes del puntaje de APGAR",
    keyword: "APGAR",
    breakdown: [
      { letter: "A", meaning: "Apariencia (color de piel)" },
      { letter: "P", meaning: "Pulso (frecuencia cardíaca)" },
      { letter: "G", meaning: "Gesto / irritabilidad refleja" },
      { letter: "A", meaning: "Actividad (tono muscular)" },
      { letter: "R", meaning: "Respiración (esfuerzo respiratorio)" },
    ],
    usage: "Evaluación estandarizada del recién nacido al minuto 1 y 5 de vida; también funciona como acrónimo del apellido del Dr. Virginia Apgar, su creadora.",
    source: { label: "American Academy of Pediatrics" },
  },
  {
    id: "nm-ped-002",
    topicId: "pediatria",
    subtopic: "Urgencias pediátricas",
    title: "Signos de peligro en general (AIEPI)",
    keyword: "No puede B-C-V",
    breakdown: [
      { letter: "B", meaning: "no puede Beber ni tomar el pecho" },
      { letter: "C", meaning: "Convulsiones" },
      { letter: "V", meaning: "Vomita todo lo que ingiere" },
      { letter: "+", meaning: "Letárgico o inconsciente" },
    ],
    usage: "Signos de peligro en general de AIEPI que obligan a clasificar como enfermedad grave y referir de urgencia, sin importar el motivo de consulta inicial.",
    source: { label: "OPS/OMS — AIEPI: Atención Integrada a las Enfermedades Prevalentes de la Infancia" },
  },
  {
    id: "nm-ped-003",
    topicId: "pediatria",
    subtopic: "Nutrición",
    title: "Signos de desnutrición aguda severa",
    keyword: "PEED",
    breakdown: [
      { letter: "P", meaning: "Peso muy bajo para la talla (< -3 DE)" },
      { letter: "E", meaning: "Edema bilateral de miembros (Kwashiorkor)" },
      { letter: "E", meaning: "Emaciación visible severa" },
      { letter: "D", meaning: "Disminución del perímetro braquial (<11.5 cm en 6-59 meses)" },
    ],
    usage: "Criterios clave para identificar desnutrición aguda severa que requiere manejo hospitalario o en programa terapéutico.",
    source: { label: "OMS — Manejo de la desnutrición aguda severa en niños" },
  },
  {
    id: "nm-ped-004",
    topicId: "pediatria",
    subtopic: "Neonatología",
    title: "Mecanismos de pérdida de calor en el recién nacido",
    keyword: "CCRE",
    breakdown: [
      { letter: "C", meaning: "Conducción (contacto con superficies frías)" },
      { letter: "C", meaning: "Convección (corrientes de aire)" },
      { letter: "R", meaning: "Radiación (hacia objetos fríos cercanos sin contacto directo)" },
      { letter: "E", meaning: "Evaporación (piel húmeda, sobre todo justo tras el nacimiento)" },
    ],
    usage: "Ayuda a recordar los cuatro mecanismos físicos por los que un recién nacido puede perder calor y a diseñar medidas específicas de cuidado térmico para cada uno.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 2: El recién nacido" },
  },
  {
    id: "nm-ped-005",
    topicId: "pediatria",
    subtopic: "Urgencias pediátricas",
    title: "Criterios diagnósticos del síndrome de respuesta inflamatoria sistémica (SRIS)",
    keyword: "TTRL",
    breakdown: [
      { letter: "T", meaning: "Temperatura anormal (>38.5°C o <36°C) — obligatorio o el siguiente" },
      { letter: "T", meaning: "Taquicardia" },
      { letter: "R", meaning: "Respiración: frecuencia respiratoria >2 DE por encima de lo normal, o necesidad aguda de ventilación mecánica" },
      { letter: "L", meaning: "Leucocitos: recuento anormal (elevado o deprimido) para la edad — obligatorio o el primero" },
    ],
    usage: "Se requieren 2 de estos 4 criterios, siendo obligatorio que 1 de ellos sea temperatura o leucocitos anormales, para diagnosticar SRIS y avanzar hacia el diagnóstico de sepsis.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 14: Estado de choque" },
  },
  {
    id: "nm-ped-006",
    topicId: "pediatria",
    subtopic: "Urgencias pediátricas",
    title: "Los 5 tipos principales de choque (shock)",
    keyword: "HCDOS",
    breakdown: [
      { letter: "H", meaning: "Hipovolémico (pérdida de precarga por hemorragia, diarrea, vómitos, quemaduras)" },
      { letter: "C", meaning: "Cardiogénico (fallo de la bomba cardíaca)" },
      { letter: "D", meaning: "Distributivo (tono vasomotor anómalo: anafiláctico, neurogénico)" },
      { letter: "O", meaning: "Obstructivo (impedimento físico al flujo de salida cardíaco)" },
      { letter: "S", meaning: "Séptico (combinación de distributivo, hipovolémico y cardiogénico)" },
    ],
    usage: "Ordena sistemáticamente el diagnóstico diferencial ante un niño en estado de choque, orientando el mecanismo fisiopatológico predominante y el tratamiento específico.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 14: Estado de choque" },
  },
];
