import type { ReferenceTable } from "@/types/content";

const BIO_SOURCES = {
  audesirk: { label: "Audesirk, Audesirk, Byers — Biología: La vida en la Tierra con Fisiología, 9.ª ed. (Pearson, 2012)" },
  solomon: { label: "Solomon, Berg, Martin — Biología, 9.ª ed. (Cengage Learning, 2013)" },
  curtis: { label: "Curtis, Barnes, Schnek, Massarini — Biología, 7.ª ed. (Panamericana, 2008)" },
  starr: { label: "Starr, Taggart — Biología: La Unidad y Diversidad de la Vida, 11.ª ed. (Cengage Learning, 2008)" },
};

const CHEM_SOURCES = {
  brown: { label: "Brown, LeMay, Bursten et al. — Química: La Ciencia Central, 1.ª ed. español (Pearson, 2021)" },
  chang: { label: "Chang, Goldsby — Química, 12.ª ed. (McGraw-Hill, 2016)" },
  petrucci: { label: "Petrucci, Herring, et al. — Química General, 11.ª ed. (Pearson, 2017)" },
};

export const cienciasBasicasTables: ReferenceTable[] = [
  {
    id: "tb-cb-001",
    topicId: "ciencias-basicas",
    subtopic: "Niveles de organización",
    title: "Los 12 niveles de organización de la vida",
    columns: ["Nivel", "Descripción"],
    rows: [
      ["Átomo", "Unidad básica de la materia (protones, neutrones, electrones)"],
      ["Molécula", "Dos o más átomos unidos por enlaces químicos"],
      ["Organelo", "Estructura subcelular especializada (ej. mitocondria, núcleo)"],
      ["Célula", "Unidad estructural y funcional básica de todo ser vivo"],
      ["Tejido", "Grupo de células similares organizadas para una función común"],
      ["Órgano", "Dos o más tejidos que trabajan juntos para una función específica"],
      ["Sistema de órganos", "Grupo de órganos que cooperan en una función fisiológica mayor"],
      ["Organismo", "Ser vivo individual completo"],
      ["Población", "Individuos de la misma especie en la misma área geográfica"],
      ["Comunidad", "Todas las poblaciones de distintas especies que interactúan en un área"],
      ["Ecosistema", "Una comunidad más los factores abióticos del ambiente"],
      ["Biosfera", "La suma de todos los ecosistemas del planeta"],
    ],
    source: BIO_SOURCES.solomon,
  },
  {
    id: "tb-cb-002",
    topicId: "ciencias-basicas",
    subtopic: "Biomoléculas",
    title: "Las 4 biomoléculas orgánicas principales",
    columns: ["Biomolécula", "Monómero / unidad básica", "Función principal"],
    rows: [
      ["Carbohidratos (hidratos de carbono)", "Monosacáridos (ej. glucosa)", "Fuente primaria de energía; función estructural (celulosa, quitina)"],
      ["Lípidos", "Ácidos grasos + glicerol (no son polímeros verdaderos)", "Reserva energética a largo plazo; componente estructural de membranas"],
      ["Proteínas", "Aminoácidos", "Función estructural, enzimática, de transporte, defensa y regulación"],
      ["Ácidos nucleicos", "Nucleótidos", "Almacenamiento y transmisión de la información genética (ADN, ARN)"],
    ],
    source: BIO_SOURCES.starr,
  },
  {
    id: "tb-cb-003",
    topicId: "ciencias-basicas",
    subtopic: "Célula",
    title: "Mecanismos de transporte a través de la membrana celular",
    columns: ["Mecanismo", "Dirección del gradiente", "¿Requiere proteína?", "¿Requiere ATP?"],
    rows: [
      ["Difusión simple", "A favor del gradiente", "No", "No"],
      ["Difusión facilitada", "A favor del gradiente", "Sí (canal o transportador)", "No"],
      ["Ósmosis", "A favor del gradiente (agua)", "No (a veces acuaporinas)", "No"],
      ["Transporte activo", "En contra del gradiente", "Sí (bomba/transportador)", "Sí"],
      ["Endocitosis / exocitosis", "Independiente del gradiente", "Sí (vesículas)", "Sí"],
    ],
    source: BIO_SOURCES.audesirk,
  },
  {
    id: "tb-cb-004",
    topicId: "ciencias-basicas",
    subtopic: "Célula",
    title: "Organelos celulares y su función principal",
    columns: ["Organelo", "Función principal"],
    rows: [
      ["Núcleo", "Alberga y protege el material genético (ADN); controla la actividad celular"],
      ["Nucléolo", "Ensamblaje de subunidades ribosómicas dentro del núcleo"],
      ["Mitocondria", "Respiración celular aeróbica; síntesis de la mayor parte del ATP"],
      ["Citoesqueleto", "Da forma y soporte estructural; permite el movimiento celular y el transporte intracelular"],
      ["Retículo endoplásmico liso", "Síntesis de lípidos, metabolismo de carbohidratos y detoxificación"],
      ["Retículo endoplásmico rugoso", "Síntesis de proteínas (posee ribosomas adheridos)"],
      ["Complejo de Golgi", "Modifica, empaqueta y distribuye proteínas y lípidos"],
    ],
    source: BIO_SOURCES.curtis,
  },
  {
    id: "tb-cb-005",
    topicId: "ciencias-basicas",
    subtopic: "Célula",
    title: "Célula procariota vs. célula eucariota",
    columns: ["Característica", "Procariota", "Eucariota"],
    rows: [
      ["Núcleo delimitado por membrana", "Ausente", "Presente"],
      ["Organelos membranosos", "Ausentes", "Presentes (mitocondrias, RE, Golgi, etc.)"],
      ["Tamaño típico", "Menor (1–10 µm)", "Mayor (10–100 µm)"],
      ["Material genético", "ADN circular, en el citoplasma (región nucleoide)", "ADN lineal, dentro del núcleo, asociado a histonas"],
      ["Ejemplos", "Bacterias, arqueas", "Animales, plantas, hongos, protistas"],
    ],
    source: BIO_SOURCES.curtis,
  },
  {
    id: "tb-cb-006",
    topicId: "ciencias-basicas",
    subtopic: "Metabolismo celular",
    title: "Etapas de la respiración celular aeróbica",
    columns: ["Etapa", "Ubicación celular", "Producto principal"],
    rows: [
      ["Glucólisis", "Citosol", "2 ATP netos, 2 NADH, piruvato"],
      ["Ciclo de Krebs (ácido cítrico)", "Matriz mitocondrial", "CO2, NADH, FADH2, 2 ATP"],
      ["Cadena de transporte de electrones", "Membrana mitocondrial interna", "La mayor parte del ATP celular (fosforilación oxidativa)"],
    ],
    source: BIO_SOURCES.curtis,
  },
  {
    id: "tb-cb-007",
    topicId: "ciencias-basicas",
    subtopic: "División celular",
    title: "Fases del ciclo celular eucarionte",
    columns: ["Fase", "Qué ocurre"],
    rows: [
      ["G1", "Crecimiento celular, síntesis de proteínas y organelos"],
      ["S (síntesis)", "Replicación completa del ADN"],
      ["G2", "Crecimiento adicional y preparación final para la división"],
      ["M (mitosis + citocinesis)", "División del núcleo (mitosis) y del citoplasma (citocinesis)"],
    ],
    source: BIO_SOURCES.solomon,
  },
  {
    id: "tb-cb-008",
    topicId: "ciencias-basicas",
    subtopic: "División celular",
    title: "Mitosis vs. meiosis",
    columns: ["Característica", "Mitosis", "Meiosis"],
    rows: [
      ["Número de divisiones", "1", "2 (meiosis I y meiosis II)"],
      ["Células resultantes", "2", "4"],
      ["Dotación cromosómica resultante", "Diploide (2n)", "Haploide (n)"],
      ["Identidad genética", "Idénticas entre sí y a la célula madre", "Genéticamente distintas entre sí (por entrecruzamiento y distribución independiente)"],
      ["Función biológica", "Crecimiento, reparación y renovación celular", "Formación de gametos (reproducción sexual)"],
    ],
    source: BIO_SOURCES.curtis,
  },
  {
    id: "tb-cb-009",
    topicId: "ciencias-basicas",
    subtopic: "Genética mendeliana",
    title: "Las dos leyes de Mendel",
    columns: ["Ley", "Enunciado"],
    rows: [
      ["1.ª — Ley de la segregación", "Los dos alelos de un gen se separan durante la formación de gametos; cada gameto recibe solo uno de ellos"],
      ["2.ª — Ley de la distribución (segregación) independiente", "Los alelos de genes ubicados en cromosomas diferentes se heredan de forma independiente entre sí"],
    ],
    source: BIO_SOURCES.solomon,
  },
  {
    id: "tb-cb-010",
    topicId: "ciencias-basicas",
    subtopic: "ADN",
    title: "Componentes del nucleótido y bases nitrogenadas del ADN",
    columns: ["Componente", "Descripción"],
    rows: [
      ["Grupo fosfato", "Ácido fosfórico; forma el esqueleto azúcar-fosfato de la cadena"],
      ["Pentosa", "Desoxirribosa (en el ADN) o ribosa (en el ARN)"],
      ["Bases púricas", "Adenina y guanina (estructura de doble anillo)"],
      ["Bases pirimidínicas", "Citosina y timina en el ADN; citosina y uracilo en el ARN (estructura de anillo simple)"],
    ],
    source: BIO_SOURCES.solomon,
  },
  {
    id: "tb-cb-011",
    topicId: "ciencias-basicas",
    subtopic: "Estructura atómica",
    title: "Partículas subatómicas fundamentales",
    columns: ["Partícula", "Carga", "Ubicación", "Masa relativa"],
    rows: [
      ["Protón", "Positiva (+1)", "Núcleo", "~1 uma"],
      ["Neutrón", "Sin carga (0)", "Núcleo", "~1 uma"],
      ["Electrón", "Negativa (−1)", "Nube electrónica (fuera del núcleo)", "~1/1836 uma (despreciable)"],
    ],
    source: CHEM_SOURCES.chang,
  },
  {
    id: "tb-cb-012",
    topicId: "ciencias-basicas",
    subtopic: "Tabla periódica",
    title: "Tendencias de las propiedades periódicas",
    columns: ["Propiedad", "Al aumentar Z en un período (izquierda→derecha)", "Al descender en un grupo"],
    rows: [
      ["Radio atómico", "Disminuye", "Aumenta"],
      ["Electronegatividad", "Aumenta", "Disminuye"],
      ["Energía de ionización", "Aumenta", "Disminuye"],
      ["Carácter metálico", "Disminuye", "Aumenta"],
    ],
    source: CHEM_SOURCES.brown,
  },
  {
    id: "tb-cb-013",
    topicId: "ciencias-basicas",
    subtopic: "Tabla periódica",
    title: "Clasificación de los elementos en la tabla periódica",
    columns: ["Categoría", "Características principales"],
    rows: [
      ["Metales", "Mayoría de los elementos; ceden electrones (forman cationes), buenos conductores, brillo, maleables y dúctiles"],
      ["No metales", "Ubicados a la derecha; tienden a ganar electrones (forman aniones), malos conductores"],
      ["Metaloides", "Propiedades intermedias entre metales y no metales (ej. silicio, germanio); semiconductores"],
      ["Elementos representativos", "Grupos 1, 2 y 13-18; también llamados de los grupos principales"],
      ["Elementos de transición", "Grupos 3-12; metales con orbitales d parcialmente llenos"],
      ["Elementos de transición interna", "Lantánidos y actínidos; orbitales f parcialmente llenos"],
      ["Elementos diatómicos", "H2, N2, O2, F2, Cl2, Br2, I2 — existen naturalmente como moléculas de dos átomos"],
    ],
    source: CHEM_SOURCES.brown,
  },
  {
    id: "tb-cb-014",
    topicId: "ciencias-basicas",
    subtopic: "Nomenclatura química",
    title: "Sistemas de nomenclatura de compuestos inorgánicos",
    columns: ["Sistema", "Cómo indica el estado de oxidación", "Ejemplo (Fe₂O₃)"],
    rows: [
      ["Clásico (tradicional)", "Terminación '-oso' (menor) o '-ico' (mayor) en el nombre del elemento", "Óxido férrico"],
      ["Stock (Werner)", "Número romano entre paréntesis después del nombre del elemento", "Óxido de hierro(III)"],
      ["Estequiométrico (de prefijos)", "Prefijos griegos (mono-, di-, tri-, tetra-) según el número de átomos", "Trióxido de dihierro"],
    ],
    source: CHEM_SOURCES.chang,
  },
  {
    id: "tb-cb-015",
    topicId: "ciencias-basicas",
    subtopic: "Enlaces químicos",
    title: "Tipos de enlaces químicos",
    columns: ["Tipo", "Mecanismo", "Ejemplo típico"],
    rows: [
      ["Iónico", "Transferencia completa de electrones entre un metal y un no metal", "NaCl (cloruro de sodio)"],
      ["Covalente polar", "Compartición desigual de electrones (diferencia moderada de electronegatividad)", "H2O (agua)"],
      ["Covalente apolar (no polar)", "Compartición equitativa de electrones (electronegatividades similares)", "O2, N2 (moléculas diatómicas del mismo elemento)"],
      ["Metálico", "Cationes metálicos inmersos en un 'mar' de electrones deslocalizados", "Cu, Fe, Al (metales puros y aleaciones)"],
    ],
    source: CHEM_SOURCES.brown,
  },
  {
    id: "tb-cb-016",
    topicId: "ciencias-basicas",
    subtopic: "Reacciones químicas",
    title: "Tipos de reacciones químicas",
    columns: ["Tipo", "Patrón general", "Ejemplo"],
    rows: [
      ["Síntesis (combinación)", "A + B → AB", "2H2 + O2 → 2H2O"],
      ["Descomposición", "AB → A + B", "2H2O2 → 2H2O + O2"],
      ["Desplazamiento simple", "A + BC → AC + B", "Zn + 2HCl → ZnCl2 + H2"],
      ["Doble desplazamiento (metátesis)", "AB + CD → AD + CB", "AgNO3 + NaCl → AgCl + NaNO3"],
    ],
    source: CHEM_SOURCES.chang,
  },
  {
    id: "tb-cb-017",
    topicId: "ciencias-basicas",
    subtopic: "Tabla periódica",
    title: "Conversiones estequiométricas comunes",
    columns: ["De", "A", "Relación / vía"],
    rows: [
      ["Moles", "Átomos, moléculas o iones", "Multiplicar por el número de Avogadro (6.022 × 10²³/mol)"],
      ["Moles", "Gramos", "Multiplicar por la masa molar (g/mol) del elemento o compuesto"],
      ["Gramos", "Miligramos", "Multiplicar por 1,000 (y viceversa, dividir por 1,000)"],
      ["Litro", "Mililitro", "Multiplicar por 1,000 (y viceversa, dividir por 1,000)"],
      ["Kilogramo", "Gramo", "Multiplicar por 1,000 (y viceversa, dividir por 1,000)"],
    ],
    source: CHEM_SOURCES.petrucci,
  },
];
