import type { ReferenceTable } from "@/types/content";

export const cirugiaTables: ReferenceTable[] = [
  {
    id: "tb-cx-001",
    topicId: "cirugia",
    subtopic: "Preoperatorio",
    title: "Clasificación ASA del estado físico",
    columns: ["Clase", "Descripción"],
    rows: [
      ["ASA I", "Paciente sano"],
      ["ASA II", "Enfermedad sistémica leve, sin limitación funcional"],
      ["ASA III", "Enfermedad sistémica grave, con limitación funcional"],
      ["ASA IV", "Enfermedad sistémica grave que es amenaza constante para la vida"],
      ["ASA V", "Moribundo, no se espera que sobreviva sin la cirugía"],
      ["ASA VI", "Paciente con muerte cerebral, donante de órganos"],
    ],
    source: { label: "American Society of Anesthesiologists — ASA Physical Status Classification System" },
  },
  {
    id: "tb-cx-002",
    topicId: "cirugia",
    subtopic: "Heridas",
    title: "Clasificación de heridas quirúrgicas (CDC)",
    columns: ["Clase", "Descripción", "Riesgo de infección aproximado"],
    rows: [
      ["I – Limpia", "No infectada, sin inflamación, cierre por primera intención", "1–5%"],
      ["II – Limpia-contaminada", "Apertura controlada de tracto GI/respiratorio/genitourinario", "5–10%"],
      ["III – Contaminada", "Ruptura de técnica estéril, derrame de contenido GI", "10–20%"],
      ["IV – Sucia-infectada", "Infección clínica preexistente, tejido desvitalizado", ">20%"],
    ],
    source: { label: "CDC — Guideline for Prevention of Surgical Site Infection" },
  },
  {
    id: "tb-cx-003",
    topicId: "cirugia",
    subtopic: "Trauma",
    title: "Clasificación de shock hemorrágico (ATLS)",
    columns: ["Clase", "Pérdida de sangre", "Frecuencia cardíaca", "Presión arterial"],
    rows: [
      ["I", "<15% (<750 mL)", "<100 lpm", "Normal"],
      ["II", "15–30% (750–1500 mL)", ">100 lpm", "Normal (disminuye presión de pulso)"],
      ["III", "30–40% (1500–2000 mL)", ">120 lpm", "Disminuida"],
      ["IV", ">40% (>2000 mL)", ">140 lpm", "Marcadamente disminuida"],
    ],
    source: { label: "American College of Surgeons — ATLS Student Course Manual, 10.ª ed." },
  },
  {
    id: "tb-cx-004",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    title: "Escala de Coma de Glasgow (ECG) revisada",
    description: "Puntuación de 3 (mínima) a 15 (máxima), sumando los 3 componentes.",
    columns: ["Componente", "Respuesta", "Puntuación"],
    rows: [
      ["Apertura ocular (O)", "Espontánea", "4"],
      ["Apertura ocular (O)", "Al sonido", "3"],
      ["Apertura ocular (O)", "A la presión", "2"],
      ["Apertura ocular (O)", "Ninguna", "1"],
      ["Respuesta verbal (V)", "Orientada", "5"],
      ["Respuesta verbal (V)", "Confusa", "4"],
      ["Respuesta verbal (V)", "Palabras", "3"],
      ["Respuesta verbal (V)", "Sonidos", "2"],
      ["Respuesta verbal (V)", "Ninguna", "1"],
      ["Mejor respuesta motora (M)", "Obedece órdenes", "6"],
      ["Mejor respuesta motora (M)", "Localiza el dolor", "5"],
      ["Mejor respuesta motora (M)", "Flexión normal (retirada)", "4"],
      ["Mejor respuesta motora (M)", "Flexión anormal (decorticación)", "3"],
      ["Mejor respuesta motora (M)", "Extensión (descerebración)", "2"],
      ["Mejor respuesta motora (M)", "Ninguna (flacidez)", "1"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico (Tabla 6-2)" },
  },
  {
    id: "tb-cx-005",
    topicId: "cirugia",
    subtopic: "Suturas de piel",
    title: "Tiempo de retiro de puntos por área corporal",
    columns: ["Área suturada", "Tiempo de retiro (días)"],
    rows: [
      ["Párpados", "2–4"],
      ["Cara", "4–6"],
      ["Cuello", "5–7"],
      ["Tronco", "7–12"],
      ["Extremidades", "10–14"],
      ["Cuero cabelludo", "10–14"],
      ["Mano", "7–10"],
      ["Sobre articulación", "14–21"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 3: Suturas de piel" },
  },
  {
    id: "tb-cx-006",
    topicId: "cirugia",
    subtopic: "Colecistitis",
    title: "Criterios de Tokio para colangitis y colecistitis agudas",
    description: "Diagnóstico sospechoso: 1 ítem de A + 1 ítem de B. Diagnóstico definitivo: 1 ítem de A + B + C.",
    columns: ["Categoría", "Signos"],
    rows: [
      ["A — Inflamación local/sistémica", "Signo de Murphy o dolor/sensibilidad en hipocondrio derecho (colecistitis); fiebre, leucocitosis, PCR elevada (colangitis)"],
      ["B — Inflamación sistémica / colestasis", "Fiebre, leucocitosis, PCR elevada (colecistitis); bilirrubina >2 mg/dL o enzimas hepáticas elevadas (colangitis)"],
      ["C — Hallazgo imagenológico", "Engrosamiento de pared >4 mm, agrandamiento vesicular, cálculos retenidos (colecistitis); dilatación de vía biliar o evidencia de la causa (colangitis)"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 4: Colecistitis" },
  },
  {
    id: "tb-cx-007",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    title: "Regla de los 9 (superficie corporal quemada, adulto)",
    description: "Fórmula rápida para estimar el porcentaje de superficie corporal total (TBSA) quemada; en niños <3 años la cabeza tiene proporcionalmente mayor superficie.",
    columns: ["Región corporal", "% de superficie corporal"],
    rows: [
      ["Cabeza y cuello", "9%"],
      ["Cada brazo completo", "9%"],
      ["Tórax/abdomen anterior", "18%"],
      ["Espalda/tórax posterior", "18%"],
      ["Cada pierna completa", "18%"],
      ["Periné/genitales", "1%"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "tb-cx-008",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    title: "Clasificación de quemaduras por profundidad",
    columns: ["Grado", "Características"],
    rows: [
      ["1er grado (superficial)", "Dolorosas, forman vesículas, no afectan capas profundas"],
      ["2do grado (espesor parcial)", "Muy dolorosas, forman ampollas y exudado; se subdividen en superficiales y profundas"],
      ["3er grado (espesor total)", "Duras, indoloras, no palidecen a la presión"],
      ["4to grado", "Afecta tejidos blandos subyacentes (músculo, hueso, tendón)"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "tb-cx-009",
    topicId: "cirugia",
    subtopic: "Choque",
    title: "Respuestas hemodinámicas según el tipo de choque",
    description: "↓ disminuido, ↑ aumentado, ↑↑/↓↓ cambio marcado, → poco efecto.",
    columns: ["Tipo de choque", "Índice cardíaco", "Resistencia vascular sistémica", "Presión venosa central"],
    rows: [
      ["Hipovolémico", "↓", "↑", "↓"],
      ["Séptico", "↑↑", "↓", "↑ (luego ↓)"],
      ["Cardiogénico", "↓↓", "↑↑", "↑"],
      ["Neurógeno", "↑", "↓", "→"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 6: Choque - Schwartz (Cuadro 5-2)" },
  },
  {
    id: "tb-cx-010",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    title: "Localización del dolor referido y sus causas",
    columns: ["Localización", "Causas más frecuentes"],
    rows: [
      ["Hombro derecho", "Hígado, vesícula biliar, hemidiafragma derecho"],
      ["Hombro izquierdo", "Corazón, cola del páncreas, bazo, hemidiafragma izquierdo"],
      ["Escroto y testículos", "Uréter (cólico renoureteral)"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 8: Abdomen agudo (Cuadro 45-3)" },
  },
];
