import type { ReferenceTable } from "@/types/content";

export const cirugiaTables: ReferenceTable[] = [
  {
    id: "tb-cx-001",
    topicId: "cirugia",
    subtopic: "Preoperatorio",
    title: "Clasificación ASA del estado físico",
    columns: ["Clase", "Descripción"],
    rows: [
      ["ASA I", "Paciente sano"],
      ["ASA II", "Enfermedad sistémica leve, sin limitación funcional"],
      ["ASA III", "Enfermedad sistémica grave, con limitación funcional"],
      ["ASA IV", "Enfermedad sistémica grave que es amenaza constante para la vida"],
      ["ASA V", "Moribundo, no se espera que sobreviva sin la cirugía"],
      ["ASA VI", "Paciente con muerte cerebral, donante de órganos"],
    ],
    source: { label: "American Society of Anesthesiologists — ASA Physical Status Classification System" },
  },
  {
    id: "tb-cx-002",
    topicId: "cirugia",
    subtopic: "Heridas",
    title: "Clasificación de heridas quirúrgicas (CDC)",
    columns: ["Clase", "Descripción", "Riesgo de infección aproximado"],
    rows: [
      ["I – Limpia", "No infectada, sin inflamación, cierre por primera intención", "1–5%"],
      ["II – Limpia-contaminada", "Apertura controlada de tracto GI/respiratorio/genitourinario", "5–10%"],
      ["III – Contaminada", "Ruptura de técnica estéril, derrame de contenido GI", "10–20%"],
      ["IV – Sucia-infectada", "Infección clínica preexistente, tejido desvitalizado", ">20%"],
    ],
    source: { label: "CDC — Guideline for Prevention of Surgical Site Infection" },
  },
  {
    id: "tb-cx-003",
    topicId: "cirugia",
    subtopic: "Trauma",
    title: "Clasificación de shock hemorrágico (ATLS)",
    columns: ["Clase", "Pérdida de sangre", "Frecuencia cardíaca", "Presión arterial"],
    rows: [
      ["I", "<15% (<750 mL)", "<100 lpm", "Normal"],
      ["II", "15–30% (750–1500 mL)", ">100 lpm", "Normal (disminuye presión de pulso)"],
      ["III", "30–40% (1500–2000 mL)", ">120 lpm", "Disminuida"],
      ["IV", ">40% (>2000 mL)", ">140 lpm", "Marcadamente disminuida"],
    ],
    source: { label: "American College of Surgeons — ATLS Student Course Manual, 10.ª ed." },
  },
  {
    id: "tb-cx-004",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    title: "Escala de Coma de Glasgow (ECG) revisada",
    description: "Puntuación de 3 (mínima) a 15 (máxima), sumando los 3 componentes.",
    columns: ["Componente", "Respuesta", "Puntuación"],
    rows: [
      ["Apertura ocular (O)", "Espontánea", "4"],
      ["Apertura ocular (O)", "Al sonido", "3"],
      ["Apertura ocular (O)", "A la presión", "2"],
      ["Apertura ocular (O)", "Ninguna", "1"],
      ["Respuesta verbal (V)", "Orientada", "5"],
      ["Respuesta verbal (V)", "Confusa", "4"],
      ["Respuesta verbal (V)", "Palabras", "3"],
      ["Respuesta verbal (V)", "Sonidos", "2"],
      ["Respuesta verbal (V)", "Ninguna", "1"],
      ["Mejor respuesta motora (M)", "Obedece órdenes", "6"],
      ["Mejor respuesta motora (M)", "Localiza el dolor", "5"],
      ["Mejor respuesta motora (M)", "Flexión normal (retirada)", "4"],
      ["Mejor respuesta motora (M)", "Flexión anormal (decorticación)", "3"],
      ["Mejor respuesta motora (M)", "Extensión (descerebración)", "2"],
      ["Mejor respuesta motora (M)", "Ninguna (flacidez)", "1"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico (Tabla 6-2)" },
  },
  {
    id: "tb-cx-005",
    topicId: "cirugia",
    subtopic: "Suturas de piel",
    title: "Tiempo de retiro de puntos por área corporal",
    columns: ["Área suturada", "Tiempo de retiro (días)"],
    rows: [
      ["Párpados", "2–4"],
      ["Cara", "4–6"],
      ["Cuello", "5–7"],
      ["Tronco", "7–12"],
      ["Extremidades", "10–14"],
      ["Cuero cabelludo", "10–14"],
      ["Mano", "7–10"],
      ["Sobre articulación", "14–21"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 3: Suturas de piel" },
  },
  {
    id: "tb-cx-006",
    topicId: "cirugia",
    subtopic: "Colecistitis",
    title: "Criterios de Tokio para colangitis y colecistitis agudas",
    description: "Diagnóstico sospechoso: 1 ítem de A + 1 ítem de B. Diagnóstico definitivo: 1 ítem de A + B + C.",
    columns: ["Categoría", "Signos"],
    rows: [
      ["A — Inflamación local/sistémica", "Signo de Murphy o dolor/sensibilidad en hipocondrio derecho (colecistitis); fiebre, leucocitosis, PCR elevada (colangitis)"],
      ["B — Inflamación sistémica / colestasis", "Fiebre, leucocitosis, PCR elevada (colecistitis); bilirrubina >2 mg/dL o enzimas hepáticas elevadas (colangitis)"],
      ["C — Hallazgo imagenológico", "Engrosamiento de pared >4 mm, agrandamiento vesicular, cálculos retenidos (colecistitis); dilatación de vía biliar o evidencia de la causa (colangitis)"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 4: Colecistitis" },
  },
  {
    id: "tb-cx-007",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    title: "Regla de los 9 (superficie corporal quemada, adulto)",
    description: "Fórmula rápida para estimar el porcentaje de superficie corporal total (TBSA) quemada; en niños <3 años la cabeza tiene proporcionalmente mayor superficie.",
    columns: ["Región corporal", "% de superficie corporal"],
    rows: [
      ["Cabeza y cuello", "9%"],
      ["Cada brazo completo", "9%"],
      ["Tórax/abdomen anterior", "18%"],
      ["Espalda/tórax posterior", "18%"],
      ["Cada pierna completa", "18%"],
      ["Periné/genitales", "1%"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "tb-cx-008",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    title: "Clasificación de quemaduras por profundidad",
    columns: ["Grado", "Características"],
    rows: [
      ["1er grado (superficial)", "Dolorosas, forman vesículas, no afectan capas profundas"],
      ["2do grado (espesor parcial)", "Muy dolorosas, forman ampollas y exudado; se subdividen en superficiales y profundas"],
      ["3er grado (espesor total)", "Duras, indoloras, no palidecen a la presión"],
      ["4to grado", "Afecta tejidos blandos subyacentes (músculo, hueso, tendón)"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "tb-cx-009",
    topicId: "cirugia",
    subtopic: "Choque",
    title: "Respuestas hemodinámicas según el tipo de choque",
    description: "↓ disminuido, ↑ aumentado, ↑↑/↓↓ cambio marcado, → poco efecto.",
    columns: ["Tipo de choque", "Índice cardíaco", "Resistencia vascular sistémica", "Presión venosa central"],
    rows: [
      ["Hipovolémico", "↓", "↑", "↓"],
      ["Séptico", "↑↑", "↓", "↑ (luego ↓)"],
      ["Cardiogénico", "↓↓", "↑↑", "↑"],
      ["Neurógeno", "↑", "↓", "→"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 6: Choque - Schwartz (Cuadro 5-2)" },
  },
  {
    id: "tb-cx-010",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    title: "Localización del dolor referido y sus causas",
    columns: ["Localización", "Causas más frecuentes"],
    rows: [
      ["Hombro derecho", "Hígado, vesícula biliar, hemidiafragma derecho"],
      ["Hombro izquierdo", "Corazón, cola del páncreas, bazo, hemidiafragma izquierdo"],
      ["Escroto y testículos", "Uréter (cólico renoureteral)"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 8: Abdomen agudo (Cuadro 45-3)" },
  },
  {
    id: "tb-cx-011",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    title: "Signos clínicos de fractura de base de cráneo por fosa",
    columns: ["Hallazgo", "Fosa anterior", "Fosa media/posterior"],
    rows: [
      ["Tipo de hematoma", "Equimosis periorbitaria (signo de mapache)", "Equimosis retroauricular (signo de Battle)"],
      ["Hemorragia", "Epistaxis", "Otorragia"],
      ["Salida de LCR", "Rinorraquia", "Otorraquia"],
      ["Lesión de pares craneales", "I al VI", "VII y VIII (media), IX al XII (posterior)"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "tb-cx-012",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    title: "Reversión de la anticoagulación en TCE",
    columns: ["Anticoagulante", "Tratamiento de reversión"],
    rows: [
      ["Antiagregantes plaquetarios (aspirina, Plavix®)", "Plaquetas"],
      ["Warfarina (Coumadin®)", "Plasma fresco congelado, vitamina K, concentrado de complejo protrombínico (Kcentra), Factor VIIa"],
      ["Heparina", "Sulfato de protamina"],
      ["Heparina de bajo peso molecular (enoxaparina)", "Sulfato de protamina"],
      ["Inhibidores directos de trombina (dabigatrán)", "Idarucizumab (Praxbind)"],
      ["Rivaroxabán (Xarelto®)", "No es aplicable (sin reversor específico validado)"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico (Tabla 6-6)" },
  },
  {
    id: "tb-cx-013",
    topicId: "cirugia",
    subtopic: "Suturas de piel",
    title: "Anestésicos locales más utilizados",
    columns: ["Anestésico", "Dosis máxima", "Duración"],
    rows: [
      ["Lidocaína 1%", "4 mg/kg de peso", "30–120 min"],
      ["Lidocaína 1% con epinefrina", "7 mg/kg de peso", "60–180 min"],
      ["Bupivacaína 0.25%", "1.5–2.5 mg/kg", "120–240 min"],
      ["Bupivacaína con epinefrina 0.25%", "3 mg/kg", "240–480 min"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 3: Suturas de piel (Tabla 1)" },
  },
  {
    id: "tb-cx-014",
    topicId: "cirugia",
    subtopic: "Colecistitis",
    title: "Indicaciones para ERCP (CPRE) en coledocolitiasis",
    columns: ["Categoría", "Criterios"],
    rows: [
      ["Muy fuertes", "Clínica de colangitis; bilirrubina total >4 mg/dL; cálculo en la vía biliar por ecografía"],
      ["Fuertes", "Bilirrubina total 1.8–4 mg/dL; dilatación del conducto biliar común >6 mm por ecografía"],
      ["Moderados", "Edad >55 años; perfil hepático alterado; clínica de pancreatitis biliar"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 4: Colecistitis" },
  },
  {
    id: "tb-cx-015",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    title: "Criterios de referencia a un centro de atención de quemados",
    columns: ["Criterio"],
    rows: [
      ["Quemaduras de espesor parcial que afectan más del 10% de la superficie corporal total (TBSA)"],
      ["Quemaduras que afectan cara, manos, pies, genitales, periné o articulaciones mayores"],
      ["Quemaduras de tercer grado en cualquier grupo de edad"],
      ["Quemaduras eléctricas, incluidas lesiones por rayo"],
      ["Quemaduras químicas"],
      ["Lesión por inhalación"],
      ["Quemaduras en pacientes con enfermedades preexistentes complicadas"],
      ["Pacientes con quemaduras y traumatismos simultáneos donde la quemadura es el mayor riesgo"],
      ["Niños quemados en hospitales sin personal calificado para su atención"],
      ["Quemaduras en pacientes que requieren intervenciones especiales de tipo social, emocional o de rehabilitación"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "tb-cx-016",
    topicId: "cirugia",
    subtopic: "Choque",
    title: "Surviving Sepsis Campaign — paquetes de tratamiento",
    description: "Conjuntos de medidas a completar en las primeras 3 y 6 horas ante sospecha de choque séptico.",
    columns: ["Plazo", "Acciones"],
    rows: [
      ["Antes de 3 horas", "1) Medir lactato. 2) Hemocultivos antes de antibióticos. 3) Antibióticos de amplio espectro. 4) Cristaloide 30 mL/kg si hipotensión o lactato ≥4 mmol/L"],
      ["Antes de 6 horas", "5) Vasopresores si la hipotensión no responde a líquidos, para PAM ≥65 mmHg. 6) Si persiste hipotensión o lactato inicial ≥4 mmol/L: medir PVC y saturación venosa central de O2. 7) Remedir el lactato si estaba elevado"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 6: Choque - Schwartz" },
  },
  {
    id: "tb-cx-017",
    topicId: "cirugia",
    subtopic: "Shock - ATLS",
    title: "Patrones de respuesta a la reanimación inicial con líquidos",
    columns: ["Parámetro", "Respuesta rápida", "Respuesta transitoria", "Mínima o nula"],
    rows: [
      ["Signos vitales", "Regreso a la normalidad", "Mejoría temporal, luego recurrencia", "Permanece anormal"],
      ["Pérdida sanguínea estimada", "Mínima (<15%)", "Moderada y persistente (15–40%)", "Grave (>40%)"],
      ["Necesidad de transfusión", "Baja", "Moderada a alta", "Inmediata"],
      ["Necesidad de intervención quirúrgica", "Posible", "Probable", "Muy probable"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 7: Shock - ATLS (Tabla 3-2)" },
  },
  {
    id: "tb-cx-018",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    title: "Hipertensión intraabdominal por grados",
    description: "Presión intraabdominal normal en reposo: 5–7 mmHg.",
    columns: ["Grado", "Presión intraabdominal", "Tratamiento"],
    rows: [
      ["Normal", "5–7 mmHg", "Ninguno"],
      ["Grado 1", "12–15 mmHg", "Mantenimiento de la euvolemia"],
      ["Grado 2", "16–20 mmHg", "Descompresión no quirúrgica (SNG, laxantes, líquidos hipotónicos)"],
      ["Grado 3", "21–25 mmHg", "Descompresión quirúrgica"],
      ["Grado 4", ">25 mmHg", "Descompresión quirúrgica; reexploración"],
    ],
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 8: Abdomen agudo (Tabla 45-2)" },
  },
];
