import type { ReferenceTable } from "@/types/content";

export const ginecoObstetriciaTables: ReferenceTable[] = [
  {
    id: "tb-go-001",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    title: "Clasificación de trastornos hipertensivos del embarazo",
    columns: ["Tipo", "Características principales"],
    rows: [
      ["Hipertensión gestacional", "PA ≥140/90 después de 20 semanas, sin proteinuria"],
      ["Preeclampsia", "Hipertensión + proteinuria significativa (o disfunción de órgano) después de 20 semanas"],
      ["Preeclampsia con criterios de severidad", "PA ≥160/110 y/o síntomas de severidad (cefalea, epigastralgia, alteración visual, plaquetas <100,000)"],
      ["Eclampsia", "Preeclampsia + convulsiones tónico-clónicas no atribuibles a otra causa"],
      ["Síndrome HELLP", "Hemólisis, enzimas hepáticas elevadas, plaquetopenia (Low Platelets)"],
    ],
    source: { label: "ACOG Practice Bulletin — Gestational Hypertension and Preeclampsia" },
  },
  {
    id: "tb-go-002",
    topicId: "gineco-obstetricia",
    subtopic: "Atención del parto",
    title: "Fases del trabajo de parto",
    columns: ["Fase", "Dilatación cervical", "Duración esperada (nulípara)"],
    rows: [
      ["Fase latente", "0–5 cm", "Variable, hasta 20 horas"],
      ["Fase activa", "6–10 cm", "Progreso mínimo esperado ~1 cm/hora"],
      ["Segundo período (expulsivo)", "10 cm (completa) hasta nacimiento", "Hasta 3 horas (con analgesia epidural puede prolongarse)"],
      ["Tercer período (alumbramiento)", "Nacimiento hasta expulsión de placenta", "Hasta 30 minutos"],
    ],
    source: { label: "ACOG/SMFM — Safe Prevention of the Primary Cesarean Delivery" },
  },
  {
    id: "tb-go-003",
    topicId: "gineco-obstetricia",
    subtopic: "Control prenatal",
    title: "Pruebas de laboratorio prenatales según trimestre",
    columns: ["Prueba", "Primera visita", "15–20 sem", "24–28 sem", "29–41 sem"],
    rows: [
      ["Hematócrito/hemoglobina", "Sí", "—", "Sí", "—"],
      ["Tipo de sangre y factor Rh", "Sí", "—", "—", "—"],
      ["Pantalla de anticuerpos", "Sí", "—", "Repetir si Rh negativo", "—"],
      ["Prueba de tolerancia a la glucosa", "—", "—", "Sí (24–28 sem)", "—"],
      ["Serología de sífilis", "Sí", "—", "—", "Repetir en alto riesgo"],
      ["Cultivo estreptococo grupo B", "—", "—", "—", "Sí (35–37 sem)"],
      ["Serología VIH", "Sí", "—", "—", "Repetir en alto riesgo"],
    ],
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 1: Atención prenatal" },
  },
  {
    id: "tb-go-004",
    topicId: "gineco-obstetricia",
    subtopic: "Atención del parto",
    title: "Componentes del índice de Bishop",
    columns: ["Componente", "0 puntos", "Puntaje creciente indica"],
    rows: [
      ["Dilatación cervical", "0 cm (cerrado)", "Mayor dilatación → cuello más favorable"],
      ["Borramiento", "0–30%", "Mayor borramiento → cuello más favorable"],
      ["Estación fetal", "-3", "Estación más descendida (0, +1, +2) → más favorable"],
      ["Consistencia cervical", "Firme", "Blanda → más favorable"],
      ["Posición cervical", "Posterior", "Media/anterior → más favorable"],
    ],
    description: "Puntaje total ≥8 predice éxito de la inducción del trabajo de parto; puntajes bajos sugieren maduración cervical previa.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 3: Parto normal" },
  },
  {
    id: "tb-go-005",
    topicId: "gineco-obstetricia",
    subtopic: "Monitoreo fetal",
    title: "Clasificación de desaceleraciones de la frecuencia cardíaca fetal",
    columns: ["Tipo", "Relación con la contracción", "Mecanismo habitual"],
    rows: [
      ["Temprana", "Inicio, nadir y fin coinciden con la contracción (imagen especular)", "Compresión de la cabeza fetal — habitualmente benigna"],
      ["Tardía", "Inicia, tiene su nadir y termina después del pico de la contracción", "Insuficiencia uteroplacentaria — requiere vigilancia"],
      ["Variable", "Inicio, profundidad y duración variables, sin relación fija", "Compresión del cordón umbilical"],
      ["Prolongada", "Descenso ≥15 lpm por 2 a 10 minutos", "Múltiples causas — evaluar urgentemente el estado fetal"],
    ],
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 4: Monitoreo fetal intraparto" },
  },
  {
    id: "tb-go-006",
    topicId: "gineco-obstetricia",
    subtopic: "Atención del parto",
    title: "Patrones de trabajo de parto anómalo (distocias)",
    columns: ["Patrón", "Criterio diagnóstico (nulípara)", "Tratamiento preferido"],
    rows: [
      ["Fase latente prolongada", ">20 horas", "Reposo en cama"],
      ["Retraso de la dilatación en fase activa", "<1.2 cm/hora", "Expectante y apoyo"],
      ["Descenso retrasado", "<1 cm/hora", "Expectante y apoyo"],
      ["Detención secundaria de la dilatación", "Sin cambio cervical por ≥2 horas", "Evaluar desproporción cefalopélvica; cesárea si está presente"],
      ["Detención del descenso", "Sin descenso por ≥1 hora", "Evaluar desproporción cefalopélvica; cesárea si está presente"],
    ],
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 5: Distocias" },
  },
  {
    id: "tb-go-007",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    title: "Clasificación clínica del aborto espontáneo",
    columns: ["Tipo", "Hallazgos clave"],
    rows: [
      ["Amenaza de aborto", "Sangrado con cérvix cerrado, embrión/feto viable"],
      ["Aborto inevitable", "Sangrado, dolor y dilatación cervical, sin expulsión aún"],
      ["Aborto incompleto", "Expulsión parcial de los productos de la concepción, cérvix dilatado"],
      ["Aborto completo", "Expulsión completa de todo el embarazo, orificio cervical cerrado posteriormente"],
      ["Aborto diferido", "Muerte embrionaria/fetal confirmada, retenida con orificio cervical cerrado"],
      ["Aborto séptico", "Cualquiera de los anteriores complicado por infección (parametritis, peritonitis, sepsis)"],
    ],
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 7: Aborto" },
  },
  {
    id: "tb-go-008",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    title: "Distribución anatómica del embarazo ectópico tubárico",
    columns: ["Localización", "Frecuencia aproximada"],
    rows: [
      ["Ampular", "70%"],
      ["Ístmico", "12%"],
      ["Fimbrial", "11%"],
      ["Intersticial", "2%"],
      ["Otro (ovario, cavidad peritoneal, cuello, cicatriz de cesárea)", "5%"],
    ],
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 8: Embarazo ectópico" },
  },
  {
    id: "tb-go-009",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    title: "Mola completa vs. mola parcial",
    columns: ["Característica", "Mola parcial", "Mola completa"],
    rows: [
      ["Cariotipo", "69,XXX o 69,XXY (triploide)", "46,XX (diploide, de origen paterno)"],
      ["Tejido embrionario/fetal", "A menudo presente", "Ausente"],
      ["Niveles iniciales de hCG", "<100,000 mIU/mL", ">100,000 mIU/mL"],
      ["Tasa de neoplasia trofoblástica gestacional (GTN) subsecuente", "1–5% de los casos", "15–20% de los casos"],
    ],
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 9: Mola hidatiforme" },
  },
  {
    id: "tb-go-010",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    title: "Antihipertensivos para hipertensión severa aguda en el embarazo",
    columns: ["Fármaco", "Dosis inicial"],
    rows: [
      ["Hidralazina", "5 a 10 mg IV; repetir 10 mg cada 15–20 minutos según respuesta"],
      ["Labetalol", "10 a 20 mg IV en bolo; duplicar dosis cada 10 minutos hasta máximo 220 mg por ciclo"],
      ["Nifedipino", "10 mg oral de liberación inmediata; repetir 10–20 mg a los 20–30 minutos si es necesario"],
    ],
    description: "Meta de tratamiento: PA sistólica ≤160 mmHg y PA diastólica ≤110 mmHg.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 12: Trastornos hipertensivos del embarazo" },
  },
  {
    id: "tb-go-011",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    title: "Comparación de infecciones vaginales frecuentes",
    columns: ["Infección", "pH vaginal", "Hallazgo característico", "Tratamiento de elección"],
    rows: [
      ["Vaginosis bacteriana", ">4.5", "Flujo grisáceo homogéneo, 'clue cells', prueba de aminas positiva", "Metronidazol"],
      ["Tricomoniasis", ">5", "Secreción purulenta espumosa, tricomonas móviles al microscopio, cuello en fresa", "Metronidazol (tratar también a la pareja)"],
      ["Candidiasis vulvovaginal", "Normal (4.0–4.5)", "Flujo grumoso ('queso cottage'), prurito intenso, levaduras/micelios", "Azoles tópicos o fluconazol oral"],
    ],
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 16: Infecciones urogenitales y ETS" },
  },
  {
    id: "tb-go-012",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    title: "Sistema Bethesda de clasificación citológica cervical",
    columns: ["Categoría", "Significado", "Equivalente histológico"],
    rows: [
      ["ASC-US", "Células escamosas atípicas de significado incierto", "10–20% de riesgo de CIN 1; 1–5% de riesgo de CIN 2/3"],
      ["ASC-H", "Células escamosas atípicas, no se excluye lesión de alto grado", "Mayor riesgo de CIN 2/3 que ASC-US"],
      ["LSIL", "Lesión intraepitelial escamosa de bajo grado", "CIN 1 / cambios por VPH (atipia coilocítica)"],
      ["HSIL", "Lesión intraepitelial escamosa de alto grado", "CIN 2 y CIN 3 (displasia moderada/grave)"],
    ],
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 18: Detección del cáncer de cérvix" },
  },
  {
    id: "tb-go-013",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    title: "Técnicas de biopsia de masas mamarias",
    columns: ["Técnica", "Indicación principal", "Limitación"],
    rows: [
      ["Punción y aspiración con aguja fina (PAAF)", "Lesiones palpables o quistes, bajo control ecográfico", "Índice de falsos negativos 10–15%; no evalúa receptores hormonales"],
      ["Biopsia con aguja gruesa (BAG)", "Lesiones palpables y no palpables; técnica de elección", "Menos invasiva que la biopsia abierta, pero requiere más tejido que la PAAF"],
      ["Biopsia abierta (quirúrgica)", "Cuando la PAAF/BAG no da diagnóstico definitivo o hay lesión de alto riesgo (hiperplasia ductal atípica, carcinoma lobulillar in situ)", "Mayor invasividad; se reserva como último recurso"],
    ],
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 19: Detección del cáncer de mama" },
  },
];
