import type { ReferenceTable } from "@/types/content";

export const medicinaInternaTables: ReferenceTable[] = [
  {
    id: "tb-mi-001",
    topicId: "medicina-interna",
    subtopic: "Nefrología",
    title: "Estadios de enfermedad renal crónica (KDIGO)",
    description: "Clasificación por tasa de filtración glomerular (TFG) estimada.",
    columns: ["Estadio", "TFG (mL/min/1.73m²)", "Descripción"],
    rows: [
      ["G1", "≥90", "Normal o alta (con daño renal)"],
      ["G2", "60–89", "Ligeramente disminuida"],
      ["G3a", "45–59", "Ligera a moderadamente disminuida"],
      ["G3b", "30–44", "Moderada a severamente disminuida"],
      ["G4", "15–29", "Severamente disminuida"],
      ["G5", "<15", "Falla renal (requiere terapia de reemplazo renal)"],
    ],
    source: { label: "KDIGO Clinical Practice Guideline for CKD Evaluation and Management, 2024" },
  },
  {
    id: "tb-mi-002",
    topicId: "medicina-interna",
    subtopic: "Signos vitales",
    title: "Valores normales de signos vitales en el adulto",
    columns: ["Parámetro", "Valor normal"],
    rows: [
      ["Frecuencia cardíaca", "60–100 lpm"],
      ["Frecuencia respiratoria", "12–20 rpm"],
      ["Presión arterial", "<120/80 mmHg (óptima)"],
      ["Temperatura corporal", "36.5–37.5 °C"],
      ["Saturación de oxígeno (SpO2)", "≥95%"],
    ],
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed." },
  },
  {
    id: "tb-mi-003",
    topicId: "medicina-interna",
    subtopic: "Metabolismo",
    title: "Clasificación de la glucemia (ADA)",
    columns: ["Categoría", "Glucemia en ayunas", "HbA1c"],
    rows: [
      ["Normal", "<100 mg/dL", "<5.7%"],
      ["Prediabetes", "100–125 mg/dL", "5.7–6.4%"],
      ["Diabetes mellitus", "≥126 mg/dL", "≥6.5%"],
    ],
    source: { label: "American Diabetes Association — Standards of Care in Diabetes 2024" },
  },
  {
    id: "tb-mi-004",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    title: "Criterios GOLD de intensidad de la obstrucción del flujo de aire en EPOC",
    columns: ["Etapa GOLD", "Intensidad", "Datos de espirometría"],
    rows: [
      ["I", "Leve", "FEV1/FVC <0.7 y FEV1 ≥80% de la cifra prevista"],
      ["II", "Moderada", "FEV1/FVC <0.7 y FEV1 50–79% de la cifra prevista"],
      ["III", "Intensa", "FEV1/FVC <0.7 y FEV1 30–49% de la cifra prevista"],
      ["IV", "Muy intensa", "FEV1/FVC <0.7 y FEV1 <30% de la cifra prevista"],
    ],
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 6: Enfermedad pulmonar obstructiva crónica" },
  },
  {
    id: "tb-mi-005",
    topicId: "medicina-interna",
    subtopic: "Infectología",
    title: "Profilaxis primaria de infecciones oportunistas en VIH según CD4",
    columns: ["Infección oportunista", "Umbral de CD4", "Profilaxis"],
    rows: [
      ["Pneumocystis jirovecii", "<200 células/µL", "Trimetoprim-sulfametoxazol (TMP-SMX)"],
      ["Toxoplasma gondii", "<100 células/µL", "TMP-SMX"],
      ["Complejo Mycobacterium avium (MAC)", "<50 células/µL", "Azitromicina"],
    ],
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 1: VIH" },
  },
  {
    id: "tb-mi-006",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    title: "Clasificación de la presión arterial",
    columns: ["Clasificación", "Presión sistólica", "Presión diastólica"],
    rows: [
      ["Normal", "<120 mmHg", "y <80 mmHg"],
      ["Prehipertensión", "120–139 mmHg", "o 80–89 mmHg"],
      ["Hipertensión en etapa 1", "140–159 mmHg", "o 90–99 mmHg"],
      ["Hipertensión en etapa 2", "≥160 mmHg", "o ≥100 mmHg"],
      ["Hipertensión sistólica aislada", "≥140 mmHg", "y <90 mmHg"],
    ],
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 8: Hipertensión arterial" },
  },
  {
    id: "tb-mi-007",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    title: "Antihipertensivos parenterales preferidos en urgencias hipertensivas",
    columns: ["Situación clínica", "Fármacos preferidos"],
    rows: [
      ["Encefalopatía hipertensiva", "Nitroprusiato, nicardipino, labetalol"],
      ["Hipertensión maligna", "Labetalol, nicardipino, nitroprusiato, enalaprilat"],
      ["Apoplejía (ACV)", "Nicardipino, labetalol, nitroprusiato"],
      ["Infarto de miocardio/angina inestable", "Nitroglicerina, nicardipino, labetalol, esmolol"],
      ["Insuficiencia ventricular izquierda aguda", "Nitroglicerina, enalaprilat, diuréticos de asa"],
      ["Disección de aorta", "Nitroprusiato, esmolol, labetalol"],
      ["Crisis adrenérgica", "Fentolamina, nitroprusiato"],
      ["Preeclampsia/eclampsia del embarazo", "Hidralazina, labetalol, nicardipino"],
    ],
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 8: Hipertensión arterial" },
  },
  {
    id: "tb-mi-008",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    title: "Clasificación de Killip en el IAMCEST",
    columns: ["Clase", "Hallazgos clínicos"],
    rows: [
      ["I", "No hay signos de insuficiencia cardíaca izquierda"],
      ["II", "Estertores pulmonares, ruido S3, taquipnea, aumento de la presión venosa yugular"],
      ["III", "Edema agudo de pulmón"],
      ["IV", "Choque cardiogénico (PAS <90 mmHg) y signos de vasoconstricción periférica (cianosis, oliguria, confusión)"],
    ],
    description: "Estima el riesgo de muerte hospitalaria en pacientes con IAMCEST según la ausencia o presencia de disfunción ventricular.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 9: Infarto agudo de miocardio con elevación del ST" },
  },
  {
    id: "tb-mi-009",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    title: "Clasificación funcional de la angina (NYHA vs. Canadian Cardiovascular Society)",
    columns: ["Clase", "NYHA", "Canadian Cardiovascular Society (CCS)"],
    rows: [
      ["I", "Cardiopatía sin limitación de la actividad física ordinaria", "La actividad física habitual (caminar, subir escaleras) no causa angina"],
      ["II", "Limitación leve de la actividad física", "Limitación leve: angina al caminar rápido, subir escaleras después de comer, con frío o estrés"],
      ["III", "Limitación notable de la actividad física", "Limitación considerable: angina al caminar 1–2 cuadras o subir un tramo de escaleras en condiciones normales"],
      ["IV", "Síntomas presentes incluso en reposo", "Imposibilidad de realizar cualquier actividad física sin angina; puede aparecer en reposo"],
    ],
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 11: Angina de pecho estable" },
  },
  {
    id: "tb-mi-010",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    title: "Tratamiento farmacológico de la IC con fracción de expulsión reducida",
    columns: ["Clase farmacológica", "Ejemplos"],
    rows: [
      ["Inhibidores de la ECA", "Lisinopril, enalapril, captopril, trandolapril"],
      ["Antagonistas del receptor de angiotensina", "Losartán, valsartán, candesartán"],
      ["Antagonistas de la aldosterona", "Eplerenona, espironolactona"],
      ["Bloqueadores β", "Succinato de metoprolol CR/XL, carvedilol, bisoprolol"],
      ["Vasodilatadores arteriovenosos", "Hidralazina + dinitrato de isosorbida"],
    ],
    description: "Cada clase se titula gradualmente desde una dosis de inicio hasta la dosis ideal tolerada, según el Cuadro 280-2.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 12: Insuficiencia cardíaca" },
  },
  {
    id: "tb-mi-011",
    topicId: "medicina-interna",
    subtopic: "Infectología",
    title: "Clasificación de severidad de la COVID-19",
    columns: ["Categoría", "Criterios"],
    rows: [
      ["Leve", "Síntomas leves (fiebre, tos, anosmia, ageusia) sin disnea"],
      ["Moderada", "Evidencia clínica o radiográfica de enfermedad del tracto respiratorio inferior, SatO2 >94% con FiO2 de 21%"],
      ["Severa", "Taquipnea (>30 rpm), SatO2 <94%, relación PaFi <300, infiltrados pulmonares en >50% del pulmón"],
      ["Crítica", "Falla ventilatoria, choque, falla multiorgánica"],
    ],
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 13: SARS-CoV-2 / COVID-19" },
  },
  {
    id: "tb-mi-012",
    topicId: "medicina-interna",
    subtopic: "Metabolismo",
    title: "Criterios diagnósticos de síndrome metabólico (NCEP:ATPIII 2001)",
    columns: ["Componente", "Umbral"],
    rows: [
      ["Obesidad central", "Perímetro abdominal >102 cm (hombres) o >88 cm (mujeres)"],
      ["Hipertrigliceridemia", "Triglicéridos ≥150 mg/100 mL, o uso de fármaco específico"],
      ["Colesterol HDL bajo", "<40 mg/100 mL en varones y <50 mg/100 mL en mujeres, o uso de fármaco específico"],
      ["Hipertensión", "Presión sistólica ≥130 mmHg o diastólica ≥85 mmHg, o uso de fármaco específico"],
      ["Glucosa plasmática en ayuno elevada", "≥100 mg/100 mL, uso de fármaco específico, o DM tipo 2 diagnosticada"],
    ],
    description: "Se requieren 3 o más de los 5 componentes para el diagnóstico de síndrome metabólico.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 5: Síndrome metabólico" },
  },
];
