import type { ReferenceTable } from "@/types/content";

export const pediatriaTables: ReferenceTable[] = [
  {
    id: "tb-ped-001",
    topicId: "pediatria",
    subtopic: "Neonatología",
    title: "Escala de APGAR",
    columns: ["Signo", "0 puntos", "1 punto", "2 puntos"],
    rows: [
      ["Apariencia (color)", "Cianosis/palidez global", "Cuerpo rosado, extremidades cianóticas", "Completamente rosado"],
      ["Pulso", "Ausente", "<100 lpm", ">100 lpm"],
      ["Gesto (irritabilidad)", "Sin respuesta", "Muecas", "Llanto/tos vigorosa"],
      ["Actividad (tono)", "Flácido", "Alguna flexión", "Movimiento activo"],
      ["Respiración", "Ausente", "Irregular/débil", "Llanto fuerte"],
    ],
    source: { label: "American Academy of Pediatrics — Escala de APGAR" },
  },
  {
    id: "tb-ped-002",
    topicId: "pediatria",
    subtopic: "Signos vitales",
    title: "Frecuencia cardíaca y respiratoria normal por edad",
    columns: ["Edad", "FC (lpm)", "FR (rpm)"],
    rows: [
      ["Recién nacido", "100–160", "30–60"],
      ["Lactante (1–12 meses)", "100–150", "25–40"],
      ["1–3 años", "90–140", "20–30"],
      ["3–6 años", "80–120", "18–25"],
      ["6–12 años", "70–110", "16–22"],
      [">12 años", "60–100", "12–20"],
    ],
    source: { label: "American Academy of Pediatrics — Pediatric Advanced Life Support (PALS) reference ranges" },
  },
  {
    id: "tb-ped-003",
    topicId: "pediatria",
    subtopic: "Inmunizaciones",
    title: "Esquema Nacional de Vacunación de Guatemala (resumen primeros 12 meses)",
    columns: ["Edad", "Vacunas"],
    rows: [
      ["Al nacer", "BCG, Hepatitis B (primera dosis)"],
      ["2 meses", "Pentavalente (1.ª), Polio (1.ª), Rotavirus (1.ª), Neumococo (1.ª)"],
      ["4 meses", "Pentavalente (2.ª), Polio (2.ª), Rotavirus (2.ª), Neumococo (2.ª)"],
      ["6 meses", "Pentavalente (3.ª), Polio (3.ª)"],
      ["12 meses", "SPR (Sarampión, Paperas, Rubéola), Neumococo (refuerzo)"],
    ],
    source: { label: "MSPAS Guatemala — Esquema Nacional de Vacunación vigente (verificar actualizaciones anuales)" },
  },
  {
    id: "tb-ped-004",
    topicId: "pediatria",
    subtopic: "Nutrición",
    title: "Kwashiorkor vs. Marasmo vs. Kwashiorkor marásmico",
    columns: ["Tipo", "Definición", "Cara", "Piel/cabello"],
    rows: [
      ["Marasmo", "Emaciación grave (peso para la talla <-3 DE) sin edema", "Cara 'simiesca'", "Piel arrugada; cabello mate y escaso"],
      ["Kwashiorkor", "Edema bilateral (con o sin emaciación)", "Cara de 'luna llena'", "Piel flácida/edematosa con dermatosis en 'pintura desconchada'; cabello con signo de la bandera"],
      ["Kwashiorkor marásmico", "Emaciación grave + edema bilateral simultáneos", "Combina hallazgos de ambos", "Combina hallazgos de ambos"],
    ],
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 12: Nutrición, seguridad alimentaria y salud" },
  },
  {
    id: "tb-ped-005",
    topicId: "pediatria",
    subtopic: "Inmunizaciones",
    title: "Dosis totales por vacuna — Esquema Nacional de Guatemala",
    columns: ["Vacuna", "N.º de dosis", "Edades de aplicación"],
    rows: [
      ["Hepatitis B", "Dosis única", "Antes de cumplir 24 horas de vida"],
      ["BCG", "Dosis única", "De 0 a <1 año de edad"],
      ["Polio (IPV/OPV)", "5 dosis", "2, 4, 6, 18 meses y 4 años"],
      ["Pentavalente (DPT, Hib, HB)", "3 dosis", "2, 4 y 6 meses"],
      ["Neumococo", "3 dosis", "2, 4 y 12 meses"],
      ["Rotavirus", "2 dosis", "2 y 4 meses (ventana estricta: 1.ª antes de 14 sem 6 días; final antes de los 8 meses)"],
      ["SPR (sarampión, paperas, rubéola)", "2 dosis", "12 y 18 meses"],
      ["DPT", "2 refuerzos", "18 meses y 4 años"],
    ],
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 9: Inmunizaciones" },
  },
  {
    id: "tb-ped-006",
    topicId: "pediatria",
    subtopic: "Infecciones respiratorias",
    title: "Clasificación de la gravedad del asma en niños (sin tratamiento controlador previo)",
    columns: ["Componente", "Intermitente", "Persistente leve", "Persistente moderada", "Persistente grave"],
    rows: [
      ["Síntomas diurnos", "≤2 días/semana", ">2 días/semana pero no diarios", "Diarios", "A lo largo de todo el día"],
      ["Despertares nocturnos (5-11 años)", "≤2×/mes", "3-4×/mes", ">1×/semana pero no nocturnos", "Frecuentes (a menudo 7×/semana)"],
      ["Uso de SABA para síntomas", "≤2 días/semana", ">2 días/semana, no diario", "Diario", "Varias veces al día"],
      ["Función pulmonar (VEMS)", "Normal entre exacerbaciones, >80% predicho", "≥80% predicho", "60-80% predicho", "<60% predicho"],
    ],
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 11: Asma" },
  },
  {
    id: "tb-ped-007",
    topicId: "pediatria",
    subtopic: "Enfermedad diarreica",
    title: "Signos asociados con el grado de deshidratación",
    columns: ["Signo", "Mínima/sin deshidratación (<3%)", "Leve a moderada (3-9%)", "Intensa (>9%)"],
    rows: [
      ["Nivel de consciencia", "Bien, alerta", "Normal, fatigado o inquieto/irritable", "Apático, letárgico o inconsciente"],
      ["Sed", "Bebe normalmente", "Sediento, deseoso de beber", "Bebe con dificultad, incapaz de beber"],
      ["Frecuencia cardíaca", "Normal", "Normal o aumentada", "Taquicardia, con bradicardia en casos graves"],
      ["Ojos", "Normales", "Ligeramente hundidos", "Muy hundidos"],
      ["Pliegue cutáneo", "Retracción instantánea", "Retracción en <2 segundos", "Retracción en >2 segundos"],
      ["Relleno capilar", "Normal", "Prolongado", "Prolongado, mínimo"],
    ],
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 10: Gastroenteritis aguda en niños" },
  },
  {
    id: "tb-ped-008",
    topicId: "pediatria",
    subtopic: "Urgencias pediátricas",
    title: "Fisiopatología de los 5 tipos de choque",
    columns: ["Tipo", "Mecanismo principal", "Ejemplos de etiología"],
    rows: [
      ["Hipovolémico", "Disminución de la precarga por pérdidas internas o externas", "Hemorragias, quemaduras, diarrea/vómitos"],
      ["Cardiogénico", "Fallo de la bomba cardíaca secundario a hipofunción miocárdica", "Cardiopatías congénitas, miocardiopatías, arritmias"],
      ["Distributivo", "Anomalías del tono vasomotor secundarias a pérdida de capacidad venosa y arterial", "Anafilaxia, lesión del tono simpático (neurogénico)"],
      ["Obstructivo", "Disminución del gasto cardíaco por impedimento directo al flujo de las cavidades", "Neumotórax a tensión, taponamiento pericárdico, tromboembolismo pulmonar"],
      ["Séptico", "Combinación de choque distributivo, hipovolémico y cardiogénico", "Bacteriana, viral, micótica"],
    ],
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 14: Estado de choque" },
  },
  {
    id: "tb-ped-009",
    topicId: "pediatria",
    subtopic: "Infecciones respiratorias",
    title: "Patógenos bacterianos de neumonía según grupo de edad",
    columns: ["Grupo de edad", "Patógenos frecuentes (orden de frecuencia)"],
    rows: [
      ["Recién nacidos (<3 semanas)", "Estreptococos del grupo B, Escherichia coli, otros bacilos gramnegativos, Streptococcus pneumoniae, Haemophilus influenzae"],
      ["3 semanas-3 meses", "Virus respiratorios comunes, S. pneumoniae, H. influenzae; considerar Chlamydia trachomatis si afebril"],
      ["4 meses-4 años", "Virus respiratorios comunes, S. pneumoniae, H. influenzae, Mycoplasma pneumoniae, estreptococos del grupo A"],
      ["≥5 años", "M. pneumoniae, S. pneumoniae, Chlamydophila pneumoniae, H. influenzae, virus respiratorios"],
    ],
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 13: Neumonía adquirida en la comunidad" },
  },
  {
    id: "tb-ped-010",
    topicId: "pediatria",
    subtopic: "Neonatología",
    title: "Problemas neonatales asociados a los lactantes prematuros, por sistema",
    columns: ["Sistema", "Problemas asociados"],
    rows: [
      ["Respiratorio", "Síndrome de dificultad respiratoria, displasia broncopulmonar, neumotórax, apnea"],
      ["Cardiovascular", "Conducto arterioso permeable, hipotensión, bradicardia con apnea"],
      ["Gastrointestinal", "Motilidad deficiente, enterocolitis necrosante, hiperbilirrubinemia"],
      ["Metabólico-endocrino", "Hipocalcemia, hipoglucemia, hiperglucemia, hipotermia"],
      ["Sistema nervioso central", "Hemorragia intraventricular, leucomalacia periventricular, retinopatía de la prematuridad"],
      ["Renales", "Hiponatremia, hipernatremia, hiperpotasemia, acidosis tubular renal"],
    ],
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 5: Prematuridad y crecimiento intrauterino retardado (Tabla 97-6)" },
  },
  {
    id: "tb-ped-011",
    topicId: "pediatria",
    subtopic: "Nutrición",
    title: "Clasificación de la desnutrición (Gomez, Waterlow, OMS)",
    columns: ["Clasificación", "Índice", "Grados"],
    rows: [
      ["Gomez", "Peso para la edad", "Leve: 90-75% de la mediana; Moderado: 75-60%; Grave: <60%"],
      ["Waterlow (emaciación)", "Peso para la talla", "Leve: 80-90% de la mediana; Grave: <70%"],
      ["Waterlow (retraso del crecimiento)", "Talla para la edad", "Leve: 95-90% de la mediana; Moderado: 90-85%; Grave: <85%"],
      ["OMS (emaciación)", "Peso para la talla (puntuación z)", "Moderado: <-2 y >-3 DE; Grave: <-3 DE"],
      ["OMS (retraso del crecimiento)", "Talla para la edad (puntuación z)", "Moderado: <-2 y >-3 DE; Grave: <-3 DE"],
    ],
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 12: Nutrición, seguridad alimentaria y salud (Tabla 46-2)" },
  },
  {
    id: "tb-ped-012",
    topicId: "pediatria",
    subtopic: "Infecciones respiratorias",
    title: "Diferenciación del líquido pleural: trasudado vs. empiema",
    columns: ["Parámetro", "Trasudado", "Empiema"],
    rows: [
      ["Aspecto", "Transparente", "Turbio o purulento"],
      ["Recuento celular (por mm³)", "<1,000", "Con frecuencia >50,000"],
      ["Tipo celular", "Linfocitos, monocitos", "Leucocitos polimorfonucleares (neutrófilos)"],
      ["Glucosa", "Normal", "Baja (<40 mg/dL)"],
      ["pH", "Normal (7.40-7.60)", "<7.10"],
      ["Tinción de Gram", "Negativa", "Positiva en ocasiones (menos de un tercio de los casos)"],
    ],
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 13: Neumonía adquirida en la comunidad (Tabla 400-6)" },
  },
];
