import type { QuizQuestion } from "@/types/content";

const BIO_SOURCES = {
  audesirk: { label: "Audesirk, Audesirk, Byers — Biología: La vida en la Tierra con Fisiología, 9.ª ed. (Pearson, 2012)" },
  solomon: { label: "Solomon, Berg, Martin — Biología, 9.ª ed. (Cengage Learning, 2013)" },
  curtis: { label: "Curtis, Barnes, Schnek, Massarini — Biología, 7.ª ed. (Panamericana, 2008)" },
  starr: { label: "Starr, Taggart — Biología: La Unidad y Diversidad de la Vida, 11.ª ed. (Cengage Learning, 2008)" },
};

const CHEM_SOURCES = {
  brown: { label: "Brown, LeMay, Bursten et al. — Química: La Ciencia Central, 1.ª ed. español (Pearson, 2021)" },
  chang: { label: "Chang, Goldsby — Química, 12.ª ed. (McGraw-Hill, 2016)" },
  petrucci: { label: "Petrucci, Herring, et al. — Química General, 11.ª ed. (Pearson, 2017)" },
  timberlake: { label: "Timberlake — Química General, Orgánica y Biológica: Estructuras de la Vida, 4.ª ed. (Pearson, 2013)" },
};

export const cienciasBasicasQuestions: QuizQuestion[] = [
  // ---- Bloque 1: Niveles de organización de la vida ----
  {
    id: "cb-001",
    topicId: "ciencias-basicas",
    subtopic: "Niveles de organización",
    difficulty: "basico",
    stem: "¿Cuál es el orden correcto de los niveles de organización biológica, de menor a mayor complejidad?",
    options: [
      "Átomo → molécula → célula → tejido → órgano → sistema de órganos → organismo → población → comunidad → ecosistema → biosfera",
      "Célula → átomo → molécula → tejido → organismo → órgano → sistema de órganos",
      "Biosfera → ecosistema → comunidad → población → organismo → célula → átomo",
      "Átomo → célula → molécula → órgano → tejido → sistema de órganos",
    ],
    correctIndex: 0,
    explanation:
      "Los niveles de organización van desde lo más simple (átomo) hasta lo más complejo (biosfera): átomo, molécula, organelo, célula, tejido, órgano, sistema de órganos, organismo, población, comunidad, ecosistema y biosfera.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-002",
    topicId: "ciencias-basicas",
    subtopic: "Niveles de organización",
    difficulty: "basico",
    stem: "¿Cómo se define la homeostasis en los seres vivos?",
    options: [
      "El proceso de división celular continua",
      "La capacidad de un organismo de mantener condiciones internas relativamente estables pese a los cambios del ambiente externo",
      "La transferencia de energía de un organismo a otro",
      "La variación genética dentro de una población",
    ],
    correctIndex: 1,
    explanation:
      "La homeostasis es la capacidad de mantener un ambiente interno relativamente constante (temperatura, pH, concentración de solutos) a pesar de las fluctuaciones del entorno externo; es una característica fundamental de todos los seres vivos.",
    source: BIO_SOURCES.audesirk,
  },
  {
    id: "cb-003",
    topicId: "ciencias-basicas",
    subtopic: "Niveles de organización",
    difficulty: "intermedio",
    stem: "¿Cuál de las siguientes combinaciones de características distingue mejor a los seres vivos de la materia inanimada?",
    options: [
      "Estar compuestos de átomos y tener masa",
      "Organización celular, metabolismo, homeostasis, crecimiento, reproducción y capacidad de respuesta a estímulos",
      "Ocupar espacio y tener un color definido",
      "Estar formados exclusivamente por carbono",
    ],
    correctIndex: 1,
    explanation:
      "Los seres vivos comparten un conjunto de propiedades fundamentales: organización celular, metabolismo, homeostasis, crecimiento y desarrollo, reproducción, capacidad de respuesta a estímulos y adaptación evolutiva; la materia inanimada no reúne todas estas propiedades a la vez.",
    source: BIO_SOURCES.curtis,
  },
  {
    id: "cb-004",
    topicId: "ciencias-basicas",
    subtopic: "Niveles de organización",
    difficulty: "basico",
    stem: "Un grupo de células del mismo tipo, especializadas y organizadas para cumplir una función común, constituye un(a):",
    options: ["Órgano", "Tejido", "Sistema de órganos", "Organelo"],
    correctIndex: 1,
    explanation:
      "Un tejido es un conjunto de células similares, organizadas estructural y funcionalmente, que trabajan juntas para realizar una función específica (ej. tejido muscular, tejido epitelial).",
    source: BIO_SOURCES.starr,
  },
  {
    id: "cb-005",
    topicId: "ciencias-basicas",
    subtopic: "Niveles de organización",
    difficulty: "intermedio",
    stem: "Un conjunto de individuos de la misma especie que habitan la misma área geográfica y pueden reproducirse entre sí constituye una:",
    options: ["Comunidad", "Especie polimórfica", "Población", "Biosfera"],
    correctIndex: 2,
    explanation:
      "Una población es el conjunto de individuos de una misma especie que coexisten en un área geográfica determinada y comparten un acervo genético común, con capacidad de reproducirse entre sí.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-006",
    topicId: "ciencias-basicas",
    subtopic: "Niveles de organización",
    difficulty: "avanzado",
    stem: "¿En qué se diferencia una comunidad biológica de un ecosistema?",
    options: [
      "Son sinónimos exactos, no existe diferencia",
      "La comunidad incluye solo las poblaciones de distintas especies que interactúan en un área; el ecosistema añade además los factores abióticos (agua, suelo, clima)",
      "El ecosistema siempre es más pequeño que la comunidad",
      "La comunidad incluye factores abióticos y el ecosistema no",
    ],
    correctIndex: 1,
    explanation:
      "La comunidad biológica agrupa a todas las poblaciones de distintas especies que interactúan en un área determinada; el ecosistema es un nivel más amplio que integra esa comunidad junto con los factores físicos y químicos del ambiente (abióticos) con los que interactúa.",
    source: BIO_SOURCES.curtis,
  },

  // ---- Bloque 2: Biomoléculas ----
  {
    id: "cb-007",
    topicId: "ciencias-basicas",
    subtopic: "Biomoléculas",
    difficulty: "intermedio",
    stem: "¿Por qué el carbono es considerado el elemento central de las moléculas orgánicas que forman a los seres vivos?",
    options: [
      "Es el elemento más abundante en la corteza terrestre",
      "Puede formar hasta cuatro enlaces covalentes estables, lo que permite estructuras moleculares grandes, complejas y diversas",
      "Es altamente reactivo exclusivamente con el oxígeno",
      "Solo forma enlaces iónicos con otros elementos",
    ],
    correctIndex: 1,
    explanation:
      "El carbono tiene cuatro electrones de valencia, lo que le permite formar hasta cuatro enlaces covalentes estables con otros átomos de carbono u otros elementos, generando cadenas, ramificaciones y anillos: la base estructural de toda la química orgánica y de la vida.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-008",
    topicId: "ciencias-basicas",
    subtopic: "Biomoléculas",
    difficulty: "intermedio",
    stem: "¿Cuál propiedad del agua explica su importante papel como regulador térmico en los seres vivos?",
    options: [
      "Su alto calor específico, que le permite absorber o liberar grandes cantidades de calor con cambios mínimos de temperatura",
      "Su bajo punto de ebullición",
      "Su carácter completamente apolar",
      "Su baja densidad en estado líquido comparada con el sólido",
    ],
    correctIndex: 0,
    explanation:
      "El agua tiene un calor específico inusualmente alto (debido a los puentes de hidrógeno entre sus moléculas), lo que le permite absorber o ceder grandes cantidades de energía calórica con cambios mínimos de temperatura, estabilizando la temperatura corporal y ambiental.",
    source: BIO_SOURCES.audesirk,
  },
  {
    id: "cb-009",
    topicId: "ciencias-basicas",
    subtopic: "Biomoléculas",
    difficulty: "intermedio",
    stem: "La cohesión entre moléculas de agua, responsable de fenómenos como la tensión superficial y la capilaridad, se debe principalmente a:",
    options: [
      "Enlaces iónicos entre los átomos de hidrógeno y oxígeno",
      "Puentes de hidrógeno entre moléculas de agua adyacentes",
      "Enlaces covalentes apolares",
      "Fuerzas de Van der Waals exclusivamente",
    ],
    correctIndex: 1,
    explanation:
      "La naturaleza polar del agua permite la formación de puentes de hidrógeno entre moléculas vecinas, lo que genera cohesión (atracción entre moléculas de agua) y adhesión (atracción a otras superficies polares), explicando la tensión superficial y la capilaridad.",
    source: BIO_SOURCES.audesirk,
  },
  {
    id: "cb-010",
    topicId: "ciencias-basicas",
    subtopic: "Biomoléculas",
    difficulty: "basico",
    stem: "¿Cuál es la unidad estructural básica (monómero) de las proteínas?",
    options: ["Monosacáridos", "Ácidos grasos", "Aminoácidos", "Nucleótidos"],
    correctIndex: 2,
    explanation:
      "Las proteínas son polímeros formados por la unión de aminoácidos (existen 20 aminoácidos estándar) mediante enlaces peptídicos, que se pliegan en estructuras tridimensionales específicas.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-011",
    topicId: "ciencias-basicas",
    subtopic: "Biomoléculas",
    difficulty: "basico",
    stem: "¿Cuál es la función biológica principal de los hidratos de carbono (carbohidratos)?",
    options: [
      "Fuente primaria de energía y componente estructural (ej. celulosa en plantas, quitina en artrópodos)",
      "Catálisis exclusiva de reacciones enzimáticas",
      "Almacenamiento de la información genética",
      "Transporte de oxígeno en la sangre",
    ],
    correctIndex: 0,
    explanation:
      "Los carbohidratos (hidratos de carbono) son la principal fuente de energía inmediata para las células y también cumplen funciones estructurales, como la celulosa en la pared celular vegetal o la quitina en el exoesqueleto de los artrópodos.",
    source: BIO_SOURCES.starr,
  },
  {
    id: "cb-012",
    topicId: "ciencias-basicas",
    subtopic: "Biomoléculas",
    difficulty: "basico",
    stem: "¿Cuál biomolécula almacena la información genética y dirige la síntesis de proteínas?",
    options: ["Lípidos", "Polisacáridos de reserva", "Ácidos nucleicos (ADN y ARN)", "Aminoácidos libres"],
    correctIndex: 2,
    explanation:
      "Los ácidos nucleicos (ADN y ARN), formados por cadenas de nucleótidos, almacenan y transmiten la información genética, y dirigen la síntesis de proteínas mediante los procesos de transcripción y traducción.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-013",
    topicId: "ciencias-basicas",
    subtopic: "Biomoléculas",
    difficulty: "intermedio",
    stem: "¿Qué característica define principalmente a los lípidos como grupo de biomoléculas?",
    options: [
      "Ser altamente solubles en agua",
      "Ser insolubles o poco solubles en agua (hidrofóbicos); forman parte de las membranas celulares y constituyen reservas energéticas",
      "Ser siempre polímeros lineales de aminoácidos",
      "Estar cargados eléctricamente en solución acuosa",
    ],
    correctIndex: 1,
    explanation:
      "Los lípidos son un grupo heterogéneo de biomoléculas unidas por su carácter hidrofóbico (insolubilidad en agua); incluyen triglicéridos (reserva energética), fosfolípidos (estructura de membranas) y esteroides.",
    source: BIO_SOURCES.audesirk,
  },

  // ---- Bloque 3: Estructura y funciones de la célula ----
  {
    id: "cb-014",
    topicId: "ciencias-basicas",
    subtopic: "Célula",
    difficulty: "basico",
    stem: "¿Qué establece la teoría celular?",
    options: [
      "Todas las células provienen de virus preexistentes",
      "Todos los seres vivos están formados por células; la célula es la unidad básica de la vida; y toda célula proviene de una célula preexistente",
      "Solo los organismos multicelulares están formados por células",
      "Las células solo existen en organismos eucariotas",
    ],
    correctIndex: 1,
    explanation:
      "La teoría celular (Schleiden, Schwann, Virchow) establece tres postulados fundamentales: todos los seres vivos están compuestos por una o más células; la célula es la unidad estructural y funcional básica de la vida; y toda célula se origina de una célula preexistente.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-015",
    topicId: "ciencias-basicas",
    subtopic: "Célula",
    difficulty: "basico",
    stem: "¿Cuál es la principal diferencia estructural entre células procariotas y eucariotas?",
    options: [
      "Las procariotas no tienen núcleo delimitado por membrana ni organelos membranosos; las eucariotas sí los poseen",
      "Las células eucariotas nunca tienen pared celular",
      "Las procariotas siempre son de mayor tamaño que las eucariotas",
      "Solo las células eucariotas contienen material genético (ADN)",
    ],
    correctIndex: 0,
    explanation:
      "Las células procariotas (bacterias, arqueas) carecen de núcleo delimitado por membrana y de organelos membranosos; las células eucariotas (animales, plantas, hongos, protistas) poseen un núcleo verdadero y organelos membranosos especializados.",
    source: BIO_SOURCES.curtis,
  },
  {
    id: "cb-016",
    topicId: "ciencias-basicas",
    subtopic: "Célula",
    difficulty: "intermedio",
    stem: "Según el modelo de mosaico fluido, la membrana plasmática está compuesta estructuralmente por:",
    options: [
      "Una bicapa de fosfolípidos con proteínas integradas que pueden desplazarse lateralmente",
      "Una sola capa de proteínas rígidas",
      "Celulosa pura organizada en fibras",
      "ADN y ARN entrelazados",
    ],
    correctIndex: 0,
    explanation:
      "El modelo de mosaico fluido describe la membrana plasmática como una bicapa de fosfolípidos (con las colas hidrofóbicas hacia el interior) en la que se insertan proteínas periféricas e integrales, además de colesterol y carbohidratos, todos con capacidad de desplazamiento lateral.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-017",
    topicId: "ciencias-basicas",
    subtopic: "Célula",
    difficulty: "intermedio",
    stem: "El paso neto de agua a través de una membrana semipermeable, desde una región de menor concentración de soluto hacia una de mayor concentración, se denomina:",
    options: ["Difusión simple", "Transporte activo", "Ósmosis", "Exocitosis"],
    correctIndex: 2,
    explanation:
      "La ósmosis es la difusión neta de agua a través de una membrana semipermeable, desde una zona de menor concentración de soluto (mayor concentración de agua) hacia una de mayor concentración de soluto, sin gasto de energía celular.",
    source: BIO_SOURCES.audesirk,
  },
  {
    id: "cb-018",
    topicId: "ciencias-basicas",
    subtopic: "Célula",
    difficulty: "avanzado",
    stem: "¿Qué diferencia a la difusión facilitada de la difusión simple a través de la membrana celular?",
    options: [
      "La difusión facilitada requiere proteínas transportadoras o canales, pero sigue ocurriendo a favor del gradiente de concentración, sin gasto de ATP",
      "La difusión facilitada siempre requiere gasto de ATP",
      "La difusión simple requiere proteínas específicas de membrana",
      "Ambos procesos son exactamente idénticos",
    ],
    correctIndex: 0,
    explanation:
      "Tanto la difusión simple como la facilitada mueven sustancias a favor de su gradiente de concentración sin gasto energético; la diferencia es que la difusión facilitada requiere proteínas de membrana (canales o transportadores) para que moléculas polares o de gran tamaño puedan atravesar la bicapa lipídica.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-019",
    topicId: "ciencias-basicas",
    subtopic: "Célula",
    difficulty: "intermedio",
    stem: "El transporte activo a través de la membrana celular se caracteriza por:",
    options: [
      "Mover sustancias a favor de su gradiente de concentración, sin gasto de energía",
      "Mover sustancias en contra de su gradiente de concentración, con gasto de energía (ATP)",
      "Ocurrir exclusivamente mediante ósmosis",
      "No requerir ninguna proteína de membrana",
    ],
    correctIndex: 1,
    explanation:
      "El transporte activo mueve sustancias en contra de su gradiente de concentración (de menor a mayor concentración), lo cual requiere el gasto de energía celular en forma de ATP y proteínas transportadoras específicas (ej. la bomba sodio-potasio).",
    source: BIO_SOURCES.audesirk,
  },
  {
    id: "cb-020",
    topicId: "ciencias-basicas",
    subtopic: "Célula",
    difficulty: "basico",
    stem: "¿Cuál organelo celular es responsable de la síntesis de la mayor parte del ATP mediante la respiración celular aeróbica?",
    options: ["Retículo endoplásmico", "Mitocondria", "Aparato de Golgi", "Lisosoma"],
    correctIndex: 1,
    explanation:
      "La mitocondria es el organelo donde ocurre el ciclo de Krebs (en la matriz) y la cadena de transporte de electrones (en la membrana interna), procesos que generan la mayor parte del ATP celular durante la respiración aeróbica.",
    source: BIO_SOURCES.curtis,
  },
  {
    id: "cb-021",
    topicId: "ciencias-basicas",
    subtopic: "Célula",
    difficulty: "intermedio",
    stem: "¿En qué se distingue funcionalmente el retículo endoplásmico rugoso del liso?",
    options: [
      "El rugoso tiene ribosomas adheridos y participa en la síntesis de proteínas; el liso no tiene ribosomas y participa en la síntesis de lípidos y la detoxificación",
      "El liso tiene ribosomas y el rugoso no",
      "Ambos cumplen exactamente la misma función",
      "El retículo rugoso solo existe en células procariotas",
    ],
    correctIndex: 0,
    explanation:
      "El retículo endoplásmico rugoso (RER) tiene ribosomas adheridos a su superficie citosólica y sintetiza proteínas destinadas a secreción o a otros organelos; el retículo endoplásmico liso (REL) carece de ribosomas y participa en la síntesis de lípidos, el metabolismo de carbohidratos y la detoxificación.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-022",
    topicId: "ciencias-basicas",
    subtopic: "Célula",
    difficulty: "basico",
    stem: "¿Cuál es la función principal del complejo o aparato de Golgi?",
    options: [
      "Síntesis de ADN",
      "Modificación, empaquetamiento y distribución de proteínas y lípidos sintetizados en el retículo endoplásmico",
      "Generación de la mayor parte del ATP celular",
      "Digestión intracelular exclusiva de macromoléculas",
    ],
    correctIndex: 1,
    explanation:
      "El aparato de Golgi recibe las proteínas y lípidos sintetizados en el retículo endoplásmico, los modifica (glicosilación, plegamiento adicional), los empaqueta en vesículas y los distribuye hacia su destino final dentro o fuera de la célula.",
    source: BIO_SOURCES.curtis,
  },

  // ---- Bloque 4: Energía y metabolismo celular ----
  {
    id: "cb-023",
    topicId: "ciencias-basicas",
    subtopic: "Metabolismo celular",
    difficulty: "basico",
    stem: "La primera ley de la termodinámica establece que:",
    options: [
      "La energía no se crea ni se destruye, solo se transforma de una forma a otra",
      "La entropía del universo siempre disminuye",
      "La energía se pierde por completo en cada transformación",
      "Los sistemas biológicos violan la conservación de la energía",
    ],
    correctIndex: 0,
    explanation:
      "La primera ley de la termodinámica (ley de conservación de la energía) establece que la energía total de un sistema aislado permanece constante: la energía no se crea ni se destruye, solo se transforma de una forma a otra (ej. energía química a energía mecánica).",
    source: BIO_SOURCES.starr,
  },
  {
    id: "cb-024",
    topicId: "ciencias-basicas",
    subtopic: "Metabolismo celular",
    difficulty: "intermedio",
    stem: "¿Qué establece la segunda ley de la termodinámica en relación con las transformaciones de energía?",
    options: [
      "Toda transformación de energía tiende a aumentar la entropía (desorden) del universo, y ninguna transformación de energía es 100% eficiente",
      "La energía se conserva perfectamente sin pérdidas",
      "Los organismos vivos son un sistema cerrado que no intercambia energía",
      "El ATP nunca se degrada ni pierde energía",
    ],
    correctIndex: 0,
    explanation:
      "La segunda ley de la termodinámica indica que en toda transformación de energía parte de ella se dispersa como calor no utilizable, aumentando la entropía (desorden) del universo; por eso ninguna transformación energética es 100% eficiente.",
    source: BIO_SOURCES.starr,
  },
  {
    id: "cb-025",
    topicId: "ciencias-basicas",
    subtopic: "Metabolismo celular",
    difficulty: "basico",
    stem: "¿Por qué el ATP (adenosín trifosfato) se considera la principal 'moneda energética' de la célula?",
    options: [
      "Sus enlaces fosfato de alta energía se hidrolizan liberando energía utilizable para acoplarse a reacciones celulares que la requieren",
      "Es un carbohidrato de reserva energética a largo plazo",
      "Forma parte estructural de la membrana celular",
      "Es uno de los 20 aminoácidos esenciales",
    ],
    correctIndex: 0,
    explanation:
      "El ATP almacena energía en los enlaces de sus grupos fosfato; al hidrolizarse a ADP + fosfato inorgánico, libera energía que la célula acopla a procesos que la requieren (síntesis de moléculas, transporte activo, contracción muscular, entre otros).",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-026",
    topicId: "ciencias-basicas",
    subtopic: "Metabolismo celular",
    difficulty: "intermedio",
    stem: "¿Cómo favorecen las enzimas las reacciones bioquímicas?",
    options: [
      "Aumentando la energía de activación necesaria para que ocurra la reacción",
      "Disminuyendo la energía de activación necesaria, lo que acelera la reacción sin consumirse ni alterar el resultado termodinámico final",
      "Cambiando el producto final de la reacción química",
      "Funcionando exclusivamente a temperaturas extremas",
    ],
    correctIndex: 1,
    explanation:
      "Las enzimas son catalizadores biológicos que disminuyen la energía de activación necesaria para que una reacción ocurra, acelerando la velocidad de la reacción sin ser consumidas en el proceso ni modificar el equilibrio termodinámico final.",
    source: BIO_SOURCES.audesirk,
  },
  {
    id: "cb-027",
    topicId: "ciencias-basicas",
    subtopic: "Metabolismo celular",
    difficulty: "basico",
    stem: "¿Cuál es la diferencia fundamental entre anabolismo y catabolismo?",
    options: [
      "El anabolismo construye moléculas complejas a partir de simples (consume energía); el catabolismo degrada moléculas complejas en simples (libera energía)",
      "Son procesos idénticos con distinto nombre",
      "El catabolismo requiere siempre luz solar directa",
      "El anabolismo solo ocurre en organismos fotosintéticos",
    ],
    correctIndex: 0,
    explanation:
      "El metabolismo celular incluye reacciones anabólicas (síntesis de moléculas complejas a partir de precursores simples, con consumo neto de energía) y reacciones catabólicas (degradación de moléculas complejas en componentes simples, con liberación neta de energía).",
    source: BIO_SOURCES.starr,
  },
  {
    id: "cb-028",
    topicId: "ciencias-basicas",
    subtopic: "Metabolismo celular",
    difficulty: "intermedio",
    stem: "¿Cuál es la diferencia principal entre la respiración celular aeróbica y la anaeróbica (fermentación)?",
    options: [
      "La aeróbica requiere oxígeno como aceptor final de electrones y produce mucho más ATP; la anaeróbica no requiere oxígeno y produce mucho menos ATP",
      "La fermentación (anaeróbica) produce más ATP que la respiración aeróbica",
      "Ambos procesos requieren oxígeno de forma obligatoria",
      "Son términos sinónimos para el mismo proceso",
    ],
    correctIndex: 0,
    explanation:
      "La respiración celular aeróbica utiliza oxígeno como aceptor final de electrones en la cadena de transporte de electrones y rinde un total aproximado de 30-38 ATP por molécula de glucosa; la fermentación (anaeróbica) no requiere oxígeno y rinde únicamente los 2 ATP netos de la glucólisis.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-029",
    topicId: "ciencias-basicas",
    subtopic: "Metabolismo celular",
    difficulty: "intermedio",
    stem: "¿En qué compartimento celular ocurre la glucólisis?",
    options: ["En la matriz mitocondrial", "En el citoplasma (citosol)", "En el núcleo celular", "En el retículo endoplásmico"],
    correctIndex: 1,
    explanation:
      "La glucólisis, la primera vía de la degradación de la glucosa, ocurre en el citosol de la célula y no requiere oxígeno; produce piruvato, un rendimiento neto de 2 ATP y 2 NADH.",
    source: BIO_SOURCES.curtis,
  },
  {
    id: "cb-030",
    topicId: "ciencias-basicas",
    subtopic: "Metabolismo celular",
    difficulty: "intermedio",
    stem: "El ciclo de Krebs (ciclo del ácido cítrico) ocurre en:",
    options: ["El citosol", "La matriz mitocondrial", "La membrana plasmática", "El núcleo celular"],
    correctIndex: 1,
    explanation:
      "El ciclo de Krebs se lleva a cabo en la matriz mitocondrial; oxida completamente el acetil-CoA (derivado del piruvato) liberando CO2 y generando NADH y FADH2, que alimentarán la cadena de transporte de electrones.",
    source: BIO_SOURCES.curtis,
  },
  {
    id: "cb-031",
    topicId: "ciencias-basicas",
    subtopic: "Metabolismo celular",
    difficulty: "avanzado",
    stem: "La cadena de transporte de electrones, donde se genera la mayor parte del ATP en la respiración celular aeróbica, se localiza en:",
    options: ["La membrana mitocondrial interna", "El citosol", "El núcleo celular", "El aparato de Golgi"],
    correctIndex: 0,
    explanation:
      "La cadena de transporte de electrones se ubica en la membrana mitocondrial interna; utiliza los electrones transportados por el NADH y el FADH2 para bombear protones y generar un gradiente electroquímico que impulsa la síntesis de ATP mediante la ATP sintasa (fosforilación oxidativa).",
    source: BIO_SOURCES.solomon,
  },

  // ---- Bloque 5: División celular y reproducción ----
  {
    id: "cb-032",
    topicId: "ciencias-basicas",
    subtopic: "División celular",
    difficulty: "basico",
    stem: "¿Qué es la cromatina?",
    options: [
      "El complejo de ADN y proteínas histonas que forma los cromosomas, en su forma dispersa y descondensada durante la interfase",
      "Únicamente ARN mensajero libre en el citoplasma",
      "Una proteína estructural exclusiva de la membrana celular",
      "Un tipo de organelo citoplasmático",
    ],
    correctIndex: 0,
    explanation:
      "La cromatina es el complejo de ADN asociado a proteínas histonas (y no histonas) presente en el núcleo durante la interfase, en un estado relativamente descondensado; se condensa en cromosomas visibles durante la división celular.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-033",
    topicId: "ciencias-basicas",
    subtopic: "División celular",
    difficulty: "intermedio",
    stem: "¿Cuáles son las fases principales del ciclo celular eucarionte, en orden?",
    options: [
      "Interfase (G1, S, G2) seguida de la fase M (mitosis y citocinesis)",
      "Solo mitosis y meiosis, sin interfase",
      "G1, mitosis, G2, S, en ese orden",
      "Únicamente interfase, sin división celular",
    ],
    correctIndex: 0,
    explanation:
      "El ciclo celular consta de la interfase (subdividida en G1 —crecimiento—, S —síntesis/replicación del ADN— y G2 —preparación final—) seguida de la fase M, que incluye la mitosis (división nuclear) y la citocinesis (división del citoplasma).",
    source: BIO_SOURCES.curtis,
  },
  {
    id: "cb-034",
    topicId: "ciencias-basicas",
    subtopic: "División celular",
    difficulty: "basico",
    stem: "¿En qué fase del ciclo celular se replica el ADN?",
    options: ["G1", "Fase S (síntesis)", "G2", "Profase de la mitosis"],
    correctIndex: 1,
    explanation:
      "El ADN se replica durante la fase S (síntesis) de la interfase, de modo que al iniciar la mitosis cada cromosoma ya cuenta con dos cromátidas hermanas idénticas.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-035",
    topicId: "ciencias-basicas",
    subtopic: "División celular",
    difficulty: "intermedio",
    stem: "¿Cuál es el resultado final de la mitosis en una célula somática humana?",
    options: [
      "4 células hijas con la mitad del número de cromosomas",
      "2 células hijas genéticamente idénticas a la célula madre, con el mismo número de cromosomas (diploide)",
      "2 células hijas con el doble de cromosomas de la célula madre",
      "Una sola célula sin ningún cambio en su contenido genético",
    ],
    correctIndex: 1,
    explanation:
      "La mitosis produce dos células hijas diploides, genéticamente idénticas entre sí y a la célula madre original; es el mecanismo de crecimiento, reparación y renovación celular en organismos multicelulares.",
    source: BIO_SOURCES.curtis,
  },
  {
    id: "cb-036",
    topicId: "ciencias-basicas",
    subtopic: "División celular",
    difficulty: "avanzado",
    stem: "¿Qué función cumplen los puntos de control (checkpoints) del ciclo celular?",
    options: [
      "El ciclo celular no posee ningún mecanismo de control",
      "Son puntos de regulación en G1, G2 y durante la mitosis que verifican el tamaño celular, la integridad del ADN y el correcto alineamiento cromosómico antes de permitir que el ciclo continúe",
      "Solo existe un punto de control, al final de la meiosis",
      "Los puntos de control actúan exclusivamente en células cancerosas",
    ],
    correctIndex: 1,
    explanation:
      "Los puntos de control (en G1, G2 y en la transición metafase-anafase de la mitosis) regulan el avance del ciclo celular verificando condiciones críticas —tamaño celular adecuado, ADN sin daños, cromosomas correctamente alineados—; su falla está implicada en el desarrollo de cáncer.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-037",
    topicId: "ciencias-basicas",
    subtopic: "División celular",
    difficulty: "intermedio",
    stem: "¿Cuál es la diferencia fundamental entre mitosis y meiosis?",
    options: [
      "La mitosis produce 2 células diploides genéticamente idénticas; la meiosis produce 4 células haploides genéticamente distintas (gametos)",
      "Son procesos idénticos con distinto nombre",
      "La meiosis ocurre en todas las células somáticas del cuerpo",
      "La mitosis reduce el número de cromosomas a la mitad",
    ],
    correctIndex: 0,
    explanation:
      "La mitosis mantiene el número cromosómico (diploide → 2 células diploides idénticas) y ocurre en células somáticas; la meiosis reduce el número cromosómico a la mitad (diploide → 4 células haploides genéticamente distintas) y produce los gametos en la reproducción sexual.",
    source: BIO_SOURCES.curtis,
  },
  {
    id: "cb-038",
    topicId: "ciencias-basicas",
    subtopic: "División celular",
    difficulty: "avanzado",
    stem: "El entrecruzamiento (crossing-over), que aumenta la variabilidad genética entre gametos, ocurre durante:",
    options: ["La mitosis", "La profase I de la meiosis", "La citocinesis", "La interfase, sin relación con la división celular"],
    correctIndex: 1,
    explanation:
      "El entrecruzamiento ocurre durante la profase I de la meiosis, cuando los cromosomas homólogos se aparean y sus cromátidas intercambian segmentos de ADN, generando nuevas combinaciones de alelos y aumentando la variabilidad genética de los gametos resultantes.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-039",
    topicId: "ciencias-basicas",
    subtopic: "División celular",
    difficulty: "basico",
    stem: "¿Cómo se denomina el proceso de formación de gametos masculinos y femeninos, respectivamente?",
    options: [
      "Espermatogénesis y ovogénesis",
      "Mitosis y meiosis exclusivamente, sin nombre específico",
      "Fecundación y gestación",
      "Citocinesis y cariocinesis",
    ],
    correctIndex: 0,
    explanation:
      "La espermatogénesis (formación de espermatozoides en los testículos) y la ovogénesis (formación de óvulos en los ovarios) son los procesos de gametogénesis que utilizan la meiosis para producir células sexuales haploides.",
    source: BIO_SOURCES.curtis,
  },
  {
    id: "cb-040",
    topicId: "ciencias-basicas",
    subtopic: "División celular",
    difficulty: "basico",
    stem: "La fusión de un gameto masculino (espermatozoide) y uno femenino (óvulo) para formar un cigoto diploide se denomina:",
    options: ["Meiosis", "Fecundación", "Mitosis", "Gametogénesis"],
    correctIndex: 1,
    explanation:
      "La fecundación es la unión de dos gametos haploides (espermatozoide y óvulo) para formar un cigoto diploide, restableciendo el número cromosómico característico de la especie y dando inicio al desarrollo embrionario.",
    source: BIO_SOURCES.solomon,
  },

  // ---- Bloque 6: Herencia y genética mendeliana ----
  {
    id: "cb-041",
    topicId: "ciencias-basicas",
    subtopic: "Genética mendeliana",
    difficulty: "intermedio",
    stem: "Según la primera ley de Mendel (ley de la segregación), durante la formación de gametos:",
    options: [
      "Los dos alelos de un gen se segregan (separan) de manera que cada gameto recibe solo uno de ellos",
      "Los alelos de un gen se mezclan de forma permanente en el gameto",
      "Todos los gametos producidos son genéticamente idénticos entre sí",
      "Los genes ubicados en cromosomas diferentes siempre se heredan juntos",
    ],
    correctIndex: 0,
    explanation:
      "La ley de la segregación de Mendel establece que los dos alelos de un gen (uno de origen materno, otro paterno) se separan durante la formación de gametos, de modo que cada gameto recibe únicamente uno de los dos alelos.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-042",
    topicId: "ciencias-basicas",
    subtopic: "Genética mendeliana",
    difficulty: "intermedio",
    stem: "La segunda ley de Mendel (ley de la distribución o segregación independiente) establece que:",
    options: [
      "Los alelos de genes ubicados en cromosomas diferentes se heredan de forma independiente entre sí",
      "Todos los genes se heredan siempre ligados entre sí",
      "Solo aplica cuando se analiza un único gen a la vez",
      "Los genes ligados en el mismo cromosoma se segregan de forma independiente",
    ],
    correctIndex: 0,
    explanation:
      "La ley de la distribución (segregación) independiente establece que los alelos de genes localizados en cromosomas diferentes se distribuyen a los gametos de manera independiente unos de otros; no aplica de forma estricta a genes ligados en el mismo cromosoma.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-043",
    topicId: "ciencias-basicas",
    subtopic: "Genética mendeliana",
    difficulty: "basico",
    stem: "Un individuo con genotipo Aa para un gen determinado se denomina:",
    options: ["Homocigoto dominante", "Heterocigoto", "Homocigoto recesivo", "Hemicigoto"],
    correctIndex: 1,
    explanation:
      "Un individuo heterocigoto posee dos alelos diferentes para un mismo gen (uno dominante y uno recesivo, ej. Aa); un homocigoto posee dos alelos idénticos (AA o aa).",
    source: BIO_SOURCES.curtis,
  },
  {
    id: "cb-044",
    topicId: "ciencias-basicas",
    subtopic: "Genética mendeliana",
    difficulty: "basico",
    stem: "¿Cuál es la diferencia entre genotipo y fenotipo?",
    options: [
      "El genotipo es la constitución genética de un individuo; el fenotipo es la expresión observable (física, bioquímica) de ese genotipo",
      "Son términos sinónimos que se usan indistintamente",
      "El fenotipo determina directamente al genotipo",
      "El genotipo se refiere únicamente a rasgos visibles a simple vista",
    ],
    correctIndex: 0,
    explanation:
      "El genotipo es la composición genética (alelos) de un individuo para un gen o conjunto de genes; el fenotipo es la manifestación observable de esos genes, resultado de la interacción entre el genotipo y el ambiente.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-045",
    topicId: "ciencias-basicas",
    subtopic: "Genética mendeliana",
    difficulty: "intermedio",
    stem: "Los cromosomas homólogos son:",
    options: [
      "Cromosomas con secuencia de ADN idéntica en todos sus genes",
      "Pares de cromosomas (uno de origen materno y otro paterno) con los mismos genes en las mismas posiciones, aunque pueden portar alelos distintos",
      "Únicamente los cromosomas sexuales (X e Y)",
      "Cromosomas presentes solo en células haploides",
    ],
    correctIndex: 1,
    explanation:
      "Los cromosomas homólogos son un par de cromosomas (uno heredado de cada progenitor) que contienen los mismos genes en el mismo orden y posición (loci), aunque pueden portar alelos diferentes para esos genes.",
    source: BIO_SOURCES.curtis,
  },
  {
    id: "cb-046",
    topicId: "ciencias-basicas",
    subtopic: "Genética mendeliana",
    difficulty: "basico",
    stem: "En los seres humanos, el sexo cromosómico masculino se determina por la combinación:",
    options: ["XX", "XY", "XXY, siempre", "YY"],
    correctIndex: 1,
    explanation:
      "En la especie humana, el sexo cromosómico masculino se determina por la combinación XY (un cromosoma X materno y un cromosoma Y paterno); el sexo femenino corresponde a la combinación XX.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-047",
    topicId: "ciencias-basicas",
    subtopic: "Genética mendeliana",
    difficulty: "intermedio",
    stem: "¿Qué son los autosomas?",
    options: [
      "Los cromosomas sexuales (X, Y)",
      "Los cromosomas no sexuales, iguales en número y tipo en ambos sexos (en humanos, 22 pares)",
      "Cromosomas exclusivos de las células germinales",
      "Fragmentos de ADN mitocondrial",
    ],
    correctIndex: 1,
    explanation:
      "Los autosomas son los cromosomas que no participan en la determinación del sexo; en la especie humana existen 22 pares de autosomas, además del par de cromosomas sexuales (23.º par: XX o XY).",
    source: BIO_SOURCES.curtis,
  },

  // ---- Bloque 7: ADN ----
  {
    id: "cb-048",
    topicId: "ciencias-basicas",
    subtopic: "ADN",
    difficulty: "basico",
    stem: "¿Cuáles son los tres componentes estructurales de un nucleótido?",
    options: [
      "Un grupo fosfato, un azúcar de 5 carbonos (pentosa) y una base nitrogenada",
      "Un aminoácido, un azúcar simple y un lípido",
      "Dos bases nitrogenadas unidas a un grupo fosfato",
      "Solo una base nitrogenada libre",
    ],
    correctIndex: 0,
    explanation:
      "Cada nucleótido está formado por tres componentes: un grupo fosfato (ácido fosfórico), un azúcar de cinco carbonos (pentosa: desoxirribosa en el ADN, ribosa en el ARN) y una base nitrogenada.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-049",
    topicId: "ciencias-basicas",
    subtopic: "ADN",
    difficulty: "basico",
    stem: "¿Cuáles son las cuatro bases nitrogenadas presentes en el ADN?",
    options: [
      "Adenina, guanina, citosina y uracilo",
      "Adenina, guanina, citosina y timina",
      "Únicamente adenina y timina",
      "Uracilo y citosina exclusivamente",
    ],
    correctIndex: 1,
    explanation:
      "El ADN contiene cuatro bases nitrogenadas: dos purinas (adenina y guanina) y dos pirimidinas (citosina y timina). El uracilo reemplaza a la timina específicamente en el ARN.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-050",
    topicId: "ciencias-basicas",
    subtopic: "ADN",
    difficulty: "intermedio",
    stem: "Según la regla de complementariedad de bases en la doble hélice del ADN:",
    options: [
      "La adenina se aparea con la guanina",
      "La adenina se aparea con la timina, y la guanina se aparea con la citosina",
      "Todas las bases nitrogenadas se aparean indistintamente entre sí",
      "La citosina se aparea con la timina",
    ],
    correctIndex: 1,
    explanation:
      "Por complementariedad de bases, la adenina siempre se aparea con la timina (mediante 2 puentes de hidrógeno) y la guanina siempre se aparea con la citosina (mediante 3 puentes de hidrógeno), manteniendo constante el diámetro de la doble hélice.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-051",
    topicId: "ciencias-basicas",
    subtopic: "ADN",
    difficulty: "intermedio",
    stem: "La estructura del ADN descrita por Watson y Crick corresponde a una:",
    options: [
      "Hélice simple de una sola cadena",
      "Doble hélice antiparalela, con las bases nitrogenadas orientadas hacia el interior y unidas por puentes de hidrógeno",
      "Estructura lineal completamente sin torsión",
      "Triple hélice de tres cadenas de nucleótidos",
    ],
    correctIndex: 1,
    explanation:
      "El modelo de Watson y Crick (1953) describe al ADN como una doble hélice antiparalela: dos cadenas de nucleótidos enrolladas entre sí, con los esqueletos de azúcar-fosfato hacia el exterior y las bases nitrogenadas complementarias, unidas por puentes de hidrógeno, hacia el interior.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-052",
    topicId: "ciencias-basicas",
    subtopic: "ADN",
    difficulty: "avanzado",
    stem: "¿Por qué se describe el proceso de replicación del ADN como semiconservativo?",
    options: [
      "Porque cada molécula de ADN hija conserva una cadena original (molde) y sintetiza una cadena nueva complementaria",
      "Porque ambas cadenas hijas son completamente nuevas, sin material original",
      "Porque ambas cadenas hijas son completamente originales, sin síntesis nueva",
      "Porque solo se replica la mitad de la molécula de ADN",
    ],
    correctIndex: 0,
    explanation:
      "La replicación del ADN es semiconservativa: la doble hélice se separa, y cada una de las dos cadenas originales sirve de molde para sintetizar una nueva cadena complementaria, de modo que cada molécula de ADN hija conserva una cadena original y una nueva.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "cb-053",
    topicId: "ciencias-basicas",
    subtopic: "ADN",
    difficulty: "intermedio",
    stem: "¿Qué enzima es la principal responsable de sintetizar la nueva cadena de ADN durante la replicación, uniendo los nucleótidos complementarios?",
    options: ["ARN polimerasa", "ADN polimerasa", "Ligasa, exclusivamente", "Helicasa, exclusivamente"],
    correctIndex: 1,
    explanation:
      "La ADN polimerasa es la enzima principal encargada de leer la cadena molde y añadir los nucleótidos complementarios para sintetizar la nueva cadena de ADN; otras enzimas como la helicasa (desenrolla la doble hélice) y la ligasa (une fragmentos) también participan en el proceso.",
    source: BIO_SOURCES.solomon,
  },

  // ---- Bloque 8: Estructura atómica ----
  {
    id: "cb-054",
    topicId: "ciencias-basicas",
    subtopic: "Estructura atómica",
    difficulty: "basico",
    stem: "¿Cuáles son las tres partículas subatómicas fundamentales y sus cargas eléctricas?",
    options: [
      "Protón (positiva), electrón (negativa), neutrón (sin carga)",
      "Protón (negativa), electrón (positiva), neutrón (sin carga)",
      "Protón (positiva), electrón (positiva), neutrón (negativa)",
      "Las tres partículas tienen carga positiva",
    ],
    correctIndex: 0,
    explanation:
      "Las tres partículas subatómicas fundamentales son el protón (carga positiva, en el núcleo), el electrón (carga negativa, en la nube electrónica) y el neutrón (sin carga eléctrica, en el núcleo).",
    source: CHEM_SOURCES.chang,
  },
  {
    id: "cb-055",
    topicId: "ciencias-basicas",
    subtopic: "Estructura atómica",
    difficulty: "basico",
    stem: "¿Dónde se localizan los protones y neutrones dentro del átomo?",
    options: ["En la nube electrónica", "En el núcleo atómico", "Fuera de los límites del átomo", "Dispersos uniformemente en todo el volumen atómico"],
    correctIndex: 1,
    explanation:
      "Los protones y neutrones (nucleones) se localizan en el núcleo atómico, que concentra casi toda la masa del átomo en un volumen muy pequeño; los electrones ocupan la región circundante (nube electrónica).",
    source: CHEM_SOURCES.petrucci,
  },
  {
    id: "cb-056",
    topicId: "ciencias-basicas",
    subtopic: "Estructura atómica",
    difficulty: "intermedio",
    stem: "El número atómico (Z) de un elemento representa:",
    options: [
      "El número de neutrones en el núcleo",
      "El número de protones en el núcleo, que identifica de forma única a cada elemento químico",
      "La suma de protones y neutrones (número de masa)",
      "El número de electrones de valencia únicamente",
    ],
    correctIndex: 1,
    explanation:
      "El número atómico (Z) corresponde al número de protones en el núcleo de un átomo; es la propiedad que identifica de forma única a cada elemento químico y determina su posición en la tabla periódica.",
    source: CHEM_SOURCES.brown,
  },
  {
    id: "cb-057",
    topicId: "ciencias-basicas",
    subtopic: "Estructura atómica",
    difficulty: "intermedio",
    stem: "Los isótopos de un mismo elemento químico se caracterizan por tener:",
    options: [
      "El mismo número de protones pero diferente número de neutrones",
      "Diferente número de protones entre sí",
      "El mismo número de neutrones pero diferente número de protones",
      "Diferente número atómico entre sí",
    ],
    correctIndex: 0,
    explanation:
      "Los isótopos son átomos de un mismo elemento (mismo número atómico, es decir, mismo número de protones) que difieren en su número de neutrones, y por lo tanto en su número de masa.",
    source: CHEM_SOURCES.chang,
  },
  {
    id: "cb-058",
    topicId: "ciencias-basicas",
    subtopic: "Estructura atómica",
    difficulty: "basico",
    stem: "Un átomo es eléctricamente neutro cuando:",
    options: [
      "Tiene más protones que electrones",
      "El número de protones es igual al número de electrones",
      "No posee neutrones en su núcleo",
      "Tiene más neutrones que protones",
    ],
    correctIndex: 1,
    explanation:
      "Un átomo es eléctricamente neutro cuando el número de cargas positivas (protones) es igual al número de cargas negativas (electrones), de modo que las cargas se cancelan entre sí.",
    source: CHEM_SOURCES.petrucci,
  },

  // ---- Bloque 9: Tabla periódica ----
  {
    id: "cb-059",
    topicId: "ciencias-basicas",
    subtopic: "Tabla periódica",
    difficulty: "basico",
    stem: "En la tabla periódica moderna, los elementos están organizados principalmente según:",
    options: [
      "Su color característico",
      "Su número atómico creciente, agrupados según propiedades químicas similares",
      "Su estado físico exclusivamente (sólido, líquido, gaseoso)",
      "Orden alfabético de su nombre",
    ],
    correctIndex: 1,
    explanation:
      "La tabla periódica moderna organiza los elementos por número atómico creciente, en filas (períodos) y columnas (grupos) que agrupan elementos con propiedades químicas similares por compartir configuraciones electrónicas de valencia análogas.",
    source: CHEM_SOURCES.brown,
  },
  {
    id: "cb-060",
    topicId: "ciencias-basicas",
    subtopic: "Tabla periódica",
    difficulty: "intermedio",
    stem: "¿Cómo se define la electronegatividad de un elemento?",
    options: [
      "La capacidad de un átomo de atraer hacia sí los electrones compartidos en un enlace químico",
      "El tamaño del radio atómico de un elemento",
      "La cantidad de protones presentes en el núcleo",
      "La energía necesaria para remover un electrón del átomo",
    ],
    correctIndex: 0,
    explanation:
      "La electronegatividad es la tendencia relativa de un átomo a atraer hacia sí los electrones que comparte en un enlace químico con otro átomo; el flúor es el elemento más electronegativo de la tabla periódica.",
    source: CHEM_SOURCES.brown,
  },
  {
    id: "cb-061",
    topicId: "ciencias-basicas",
    subtopic: "Tabla periódica",
    difficulty: "intermedio",
    stem: "En general, ¿cómo varía el radio atómico al descender dentro de un mismo grupo (columna) de la tabla periódica?",
    options: [
      "Disminuye progresivamente",
      "Aumenta, porque se añaden nuevos niveles de energía electrónica",
      "Permanece prácticamente constante",
      "Varía de forma aleatoria sin ningún patrón",
    ],
    correctIndex: 1,
    explanation:
      "Al descender en un mismo grupo, el radio atómico aumenta porque cada elemento sucesivo añade un nuevo nivel principal de energía (capa electrónica), alejando los electrones más externos del núcleo.",
    source: CHEM_SOURCES.chang,
  },
  {
    id: "cb-062",
    topicId: "ciencias-basicas",
    subtopic: "Tabla periódica",
    difficulty: "intermedio",
    stem: "¿Cómo se define la energía de ionización de un átomo?",
    options: [
      "La energía liberada al formar un nuevo enlace químico",
      "La energía mínima necesaria para remover un electrón de un átomo en estado gaseoso",
      "La energía de un electrón cuando el átomo está en reposo",
      "La masa total de un átomo",
    ],
    correctIndex: 1,
    explanation:
      "La energía de ionización es la energía mínima requerida para remover el electrón más externo de un átomo neutro en estado gaseoso, formando un catión; en general, aumenta de izquierda a derecha en un período y disminuye al descender en un grupo.",
    source: CHEM_SOURCES.petrucci,
  },
  {
    id: "cb-063",
    topicId: "ciencias-basicas",
    subtopic: "Tabla periódica",
    difficulty: "basico",
    stem: "Los elementos ubicados en el lado izquierdo y central de la tabla periódica (excluyendo al hidrógeno) se clasifican principalmente como:",
    options: [
      "No metales",
      "Metales, con tendencia a ceder electrones y formar cationes",
      "Gases nobles exclusivamente",
      "Metaloides exclusivamente",
    ],
    correctIndex: 1,
    explanation:
      "La mayoría de los elementos de la tabla periódica (ubicados a la izquierda y el centro) son metales: tienden a ceder electrones formando cationes, son buenos conductores de calor y electricidad, y presentan brillo característico.",
    source: CHEM_SOURCES.brown,
  },
  {
    id: "cb-064",
    topicId: "ciencias-basicas",
    subtopic: "Tabla periódica",
    difficulty: "basico",
    stem: "¿Qué es un mol, como unidad química fundamental?",
    options: [
      "Una unidad de masa exclusiva para los gases",
      "La cantidad de sustancia que contiene 6.022 × 10²³ partículas (número de Avogadro)",
      "Un tipo específico de enlace químico",
      "La masa de un solo átomo aislado",
    ],
    correctIndex: 1,
    explanation:
      "El mol es la unidad del Sistema Internacional para la cantidad de sustancia; un mol contiene exactamente 6.022 × 10²³ entidades elementales (átomos, moléculas, iones), conocido como número de Avogadro.",
    source: CHEM_SOURCES.chang,
  },
  {
    id: "cb-065",
    topicId: "ciencias-basicas",
    subtopic: "Tabla periódica",
    difficulty: "intermedio",
    stem: "El número de Avogadro (6.022 × 10²³) representa específicamente:",
    options: [
      "El número de moles contenidos en un átomo",
      "El número de partículas (átomos, moléculas o iones) contenidas en un mol de sustancia",
      "El número de protones presentes en el núcleo de cualquier átomo",
      "La masa molar del hidrógeno expresada en gramos",
    ],
    correctIndex: 1,
    explanation:
      "El número de Avogadro (6.022 × 10²³) es la cantidad de partículas elementales (átomos, moléculas o iones) contenidas en exactamente un mol de cualquier sustancia; es la constante que conecta la escala atómica con la escala macroscópica (gramos).",
    source: CHEM_SOURCES.chang,
  },
  {
    id: "cb-066",
    topicId: "ciencias-basicas",
    subtopic: "Tabla periódica",
    difficulty: "intermedio",
    stem: "¿Qué describe la configuración electrónica de un elemento?",
    options: [
      "La distribución de los electrones en los distintos niveles y subniveles de energía alrededor del núcleo",
      "Únicamente la masa total del átomo",
      "El número de neutrones presentes en el núcleo",
      "La forma geométrica exacta del núcleo atómico",
    ],
    correctIndex: 0,
    explanation:
      "La configuración electrónica describe cómo se distribuyen los electrones de un átomo en los niveles de energía (capas) y subniveles (s, p, d, f) siguiendo el principio de Aufbau, el principio de exclusión de Pauli y la regla de Hund.",
    source: CHEM_SOURCES.petrucci,
  },
  {
    id: "cb-067",
    topicId: "ciencias-basicas",
    subtopic: "Tabla periódica",
    difficulty: "intermedio",
    stem: "¿Qué son los electrones de valencia?",
    options: [
      "Todos los electrones que posee un átomo, sin distinción",
      "Los electrones ubicados en el nivel de energía más externo (capa de valencia), responsables del comportamiento químico y la formación de enlaces",
      "Únicamente los electrones que permanecen en el núcleo",
      "Los electrones perdidos durante un proceso de ionización",
    ],
    correctIndex: 1,
    explanation:
      "Los electrones de valencia son los electrones del nivel de energía más externo de un átomo; determinan la reactividad química del elemento y su capacidad de formar enlaces con otros átomos.",
    source: CHEM_SOURCES.brown,
  },

  // ---- Bloque 10: Nomenclatura de compuestos inorgánicos ----
  {
    id: "cb-068",
    topicId: "ciencias-basicas",
    subtopic: "Nomenclatura química",
    difficulty: "intermedio",
    stem: "En el sistema de nomenclatura Stock, el estado de oxidación del metal en un compuesto se indica mediante:",
    options: [
      "Un prefijo griego (mono-, di-, tri-)",
      "Un número romano entre paréntesis inmediatamente después del nombre del elemento",
      "Siempre con la terminación '-ico'",
      "No se indica en absoluto en este sistema",
    ],
    correctIndex: 1,
    explanation:
      "El sistema Stock (o de Werner) indica el estado de oxidación del elemento metálico mediante un número romano entre paréntesis colocado justo después del nombre del elemento, por ejemplo: óxido de hierro(III).",
    source: CHEM_SOURCES.chang,
  },
  {
    id: "cb-069",
    topicId: "ciencias-basicas",
    subtopic: "Nomenclatura química",
    difficulty: "intermedio",
    stem: "En la nomenclatura clásica (tradicional), cuando un metal tiene dos posibles estados de oxidación, la terminación '-oso' se emplea para nombrar:",
    options: [
      "El estado de oxidación mayor de los dos posibles",
      "El estado de oxidación menor de los dos posibles",
      "Ambos estados de oxidación indistintamente",
      "Solamente compuestos que no contienen oxígeno",
    ],
    correctIndex: 1,
    explanation:
      "En la nomenclatura clásica, cuando un elemento presenta dos estados de oxidación, la terminación '-oso' corresponde al estado de oxidación menor, y la terminación '-ico' al estado de oxidación mayor (ej. ion ferroso Fe²⁺ vs. ion férrico Fe³⁺).",
    source: CHEM_SOURCES.chang,
  },
  {
    id: "cb-070",
    topicId: "ciencias-basicas",
    subtopic: "Nomenclatura química",
    difficulty: "basico",
    stem: "Usando el sistema estequiométrico (de prefijos), el compuesto CO₂ se nombra como:",
    options: ["Monóxido de carbono", "Dióxido de carbono", "Óxido carbónico", "Carbonato de hidrógeno"],
    correctIndex: 1,
    explanation:
      "En el sistema estequiométrico, los prefijos griegos (mono-, di-, tri-, tetra-) indican el número de átomos de cada elemento; CO₂ (un átomo de carbono, dos átomos de oxígeno) se nombra dióxido de carbono.",
    source: CHEM_SOURCES.brown,
  },
  {
    id: "cb-071",
    topicId: "ciencias-basicas",
    subtopic: "Nomenclatura química",
    difficulty: "intermedio",
    stem: "Un óxido se forma típicamente por la combinación de:",
    options: [
      "Un metal (o no metal) con oxígeno",
      "Dos elementos no metálicos, sin presencia de oxígeno",
      "Un ácido con una base en una reacción de neutralización",
      "Hidrógeno con un halógeno exclusivamente",
    ],
    correctIndex: 0,
    explanation:
      "Los óxidos son compuestos binarios formados por la combinación de oxígeno con un metal (óxidos básicos, ej. óxido de calcio) o con un no metal (óxidos ácidos o anhídridos, ej. dióxido de azufre).",
    source: CHEM_SOURCES.chang,
  },

  // ---- Bloque 11: Enlaces químicos ----
  {
    id: "cb-072",
    topicId: "ciencias-basicas",
    subtopic: "Enlaces químicos",
    difficulty: "intermedio",
    stem: "¿Cómo se caracteriza el enlace iónico?",
    options: [
      "Por la compartición equitativa de electrones entre dos átomos",
      "Por la transferencia completa de uno o más electrones de un átomo a otro, generando iones de cargas opuestas que se atraen electrostáticamente",
      "Por ocurrir exclusivamente entre elementos no metálicos",
      "Por no involucrar ningún tipo de carga eléctrica",
    ],
    correctIndex: 1,
    explanation:
      "El enlace iónico se forma por la transferencia completa de uno o más electrones desde un átomo de baja electronegatividad (generalmente un metal) hacia uno de alta electronegatividad (generalmente un no metal), generando un catión y un anión que se atraen electrostáticamente.",
    source: CHEM_SOURCES.brown,
  },
  {
    id: "cb-073",
    topicId: "ciencias-basicas",
    subtopic: "Enlaces químicos",
    difficulty: "intermedio",
    stem: "Un enlace covalente polar se forma cuando:",
    options: [
      "Dos átomos comparten electrones de manera desigual debido a una diferencia de electronegatividad, generando polos parcialmente positivo y negativo",
      "Los electrones se transfieren por completo de un átomo a otro",
      "Los dos átomos involucrados tienen electronegatividades idénticas",
      "No existe compartición de electrones entre los átomos",
    ],
    correctIndex: 0,
    explanation:
      "En un enlace covalente polar, los átomos comparten electrones de forma desigual debido a una diferencia moderada de electronegatividad, generando una distribución asimétrica de la carga (dipolo) con un extremo parcialmente positivo y otro parcialmente negativo.",
    source: CHEM_SOURCES.brown,
  },
  {
    id: "cb-074",
    topicId: "ciencias-basicas",
    subtopic: "Enlaces químicos",
    difficulty: "avanzado",
    stem: "¿Cómo se describe el enlace metálico?",
    options: [
      "Como una red de cationes metálicos inmersos en un 'mar' de electrones deslocalizados, lo que explica la conductividad eléctrica y térmica de los metales",
      "Como un enlace que ocurre exclusivamente entre dos elementos no metálicos",
      "Como idéntico en todo sentido al enlace iónico",
      "Como la transferencia directa de protones entre átomos",
    ],
    correctIndex: 0,
    explanation:
      "El enlace metálico se describe como una red ordenada de cationes metálicos rodeados por un 'mar' de electrones de valencia deslocalizados y compartidos colectivamente, lo que explica propiedades como la conductividad eléctrica, la conductividad térmica y la maleabilidad de los metales.",
    source: CHEM_SOURCES.chang,
  },
  {
    id: "cb-075",
    topicId: "ciencias-basicas",
    subtopic: "Enlaces químicos",
    difficulty: "intermedio",
    stem: "¿Qué representan las estructuras de Lewis?",
    options: [
      "Únicamente la carga nuclear total de un átomo",
      "Los electrones de valencia de un átomo o molécula, representados mediante puntos alrededor del símbolo químico, mostrando enlaces y pares de electrones libres",
      "La estructura tridimensional exacta y precisa de una molécula",
      "Solamente los protones y neutrones del núcleo",
    ],
    correctIndex: 1,
    explanation:
      "Las estructuras (o diagramas) de Lewis representan los electrones de valencia de átomos, iones o moléculas mediante puntos alrededor del símbolo químico, mostrando cómo se distribuyen en enlaces (pares compartidos) y en pares de electrones no compartidos (libres).",
    source: CHEM_SOURCES.petrucci,
  },

  // ---- Bloque 12: Reacción y ecuación química ----
  {
    id: "cb-076",
    topicId: "ciencias-basicas",
    subtopic: "Reacciones químicas",
    difficulty: "basico",
    stem: "¿Qué representa una ecuación química?",
    options: [
      "La representación simbólica de una reacción química, mostrando las fórmulas de reactivos y productos junto con sus cantidades relativas",
      "Únicamente el nombre de los compuestos involucrados en la reacción",
      "Una lista de propiedades físicas de las sustancias",
      "La estructura atómica interna de un solo elemento",
    ],
    correctIndex: 0,
    explanation:
      "Una ecuación química es la representación simbólica y abreviada de una reacción química: muestra las fórmulas de los reactivos (lado izquierdo) y de los productos (lado derecho), junto con sus proporciones estequiométricas (coeficientes).",
    source: CHEM_SOURCES.brown,
  },
  {
    id: "cb-077",
    topicId: "ciencias-basicas",
    subtopic: "Reacciones químicas",
    difficulty: "intermedio",
    stem: "Balancear una ecuación química significa:",
    options: [
      "Cambiar los subíndices dentro de las fórmulas químicas de los compuestos",
      "Ajustar los coeficientes estequiométricos para que el número de átomos de cada elemento sea igual en reactivos y productos, cumpliendo la ley de conservación de la masa",
      "Sustituir los reactivos originales por productos completamente diferentes",
      "Eliminar por completo los productos de la reacción",
    ],
    correctIndex: 1,
    explanation:
      "Balancear una ecuación consiste en ajustar los coeficientes estequiométricos (nunca los subíndices de las fórmulas) para que el número de átomos de cada elemento sea idéntico en ambos lados de la ecuación, en cumplimiento de la ley de conservación de la masa de Lavoisier.",
    source: CHEM_SOURCES.chang,
  },
  {
    id: "cb-078",
    topicId: "ciencias-basicas",
    subtopic: "Reacciones químicas",
    difficulty: "intermedio",
    stem: "En una reacción de síntesis (o combinación):",
    options: [
      "Dos o más sustancias reactivas se combinan para formar un único producto más complejo",
      "Un compuesto se descompone en dos o más sustancias más simples",
      "Un elemento libre desplaza a otro elemento dentro de un compuesto",
      "Dos compuestos intercambian sus componentes entre sí",
    ],
    correctIndex: 0,
    explanation:
      "En una reacción de síntesis o combinación, dos o más reactivos (elementos o compuestos simples) se combinan para formar un único producto de mayor complejidad estructural (ej. 2H₂ + O₂ → 2H₂O).",
    source: CHEM_SOURCES.brown,
  },
  {
    id: "cb-079",
    topicId: "ciencias-basicas",
    subtopic: "Reacciones químicas",
    difficulty: "intermedio",
    stem: "En una reacción de descomposición:",
    options: [
      "Dos sustancias simples se combinan para formar un compuesto",
      "Un compuesto se descompone en dos o más sustancias más simples",
      "La reacción ocurre siempre espontáneamente a temperatura ambiente",
      "Nunca se requiere energía externa para que ocurra",
    ],
    correctIndex: 1,
    explanation:
      "En una reacción de descomposición, un único compuesto se rompe en dos o más sustancias más simples (elementos u otros compuestos), frecuentemente requiriendo un aporte de energía (calor, luz o electricidad) para iniciarse.",
    source: CHEM_SOURCES.chang,
  },
  {
    id: "cb-080",
    topicId: "ciencias-basicas",
    subtopic: "Reacciones químicas",
    difficulty: "avanzado",
    stem: "En una reacción de desplazamiento simple (sustitución simple):",
    options: [
      "Dos compuestos intercambian iones entre sí",
      "Un elemento libre reemplaza a otro elemento dentro de un compuesto",
      "Dos elementos se combinan directamente para formar un único compuesto",
      "Un compuesto se descompone por completo en sus elementos constituyentes",
    ],
    correctIndex: 1,
    explanation:
      "En una reacción de desplazamiento (sustitución) simple, un elemento libre más reactivo desplaza a otro elemento menos reactivo dentro de un compuesto, ocupando su lugar (ej. Zn + 2HCl → ZnCl₂ + H₂).",
    source: CHEM_SOURCES.brown,
  },
  {
    id: "cb-081",
    topicId: "ciencias-basicas",
    subtopic: "Reacciones químicas",
    difficulty: "intermedio",
    stem: "¿Qué símbolo se utiliza en una ecuación química para indicar que una reacción es reversible (ocurre en ambas direcciones)?",
    options: ["Una sola flecha (→)", "Dos flechas opuestas (⇌)", "Un signo de igual (=)", "Un asterisco (*)"],
    correctIndex: 1,
    explanation:
      "El símbolo de dos flechas opuestas (⇌) indica que una reacción química es reversible: los reactivos forman productos y, simultáneamente, los productos pueden regenerar los reactivos, hasta alcanzar un estado de equilibrio químico.",
    source: CHEM_SOURCES.petrucci,
  },
];
