import type { QuizQuestion } from "@/types/content";

export const cirugiaQuestions: QuizQuestion[] = [
  {
    id: "cx-001",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    difficulty: "basico",
    stem: "Paciente de 22 años con dolor que migró de epigastrio a fosa ilíaca derecha, fiebre baja, náuseas y signo de McBurney positivo. ¿Cuál es el diagnóstico más probable?",
    options: ["Colecistitis aguda", "Apendicitis aguda", "Diverticulitis", "Pancreatitis aguda"],
    correctIndex: 1,
    explanation:
      "La migración clásica del dolor periumbilical hacia la fosa ilíaca derecha con dolor a la palpación en el punto de McBurney es el cuadro típico de apendicitis aguda.",
    source: { label: "Schwartz's Principles of Surgery, 11.ª ed. — Apendicitis aguda" },
  },
  {
    id: "cx-002",
    topicId: "cirugia",
    subtopic: "Vía biliar",
    difficulty: "intermedio",
    stem: "Mujer de 45 años con dolor en hipocondrio derecho, fiebre, ictericia y Murphy positivo. Se sospecha colangitis aguda. ¿Cuál es la tríada clásica que sustenta este diagnóstico?",
    options: [
      "Tríada de Charcot: dolor en hipocondrio derecho, fiebre e ictericia",
      "Tríada de Virchow: éstasis, hipercoagulabilidad y daño endotelial",
      "Tríada de Beck: hipotensión, ingurgitación yugular y ruidos cardíacos velados",
      "Tríada de Cushing: hipertensión, bradicardia e irregularidad respiratoria",
    ],
    correctIndex: 0,
    explanation:
      "La tríada de Charcot (dolor en hipocondrio derecho, fiebre e ictericia) es característica de colangitis aguda; si se agregan hipotensión y confusión se denomina péntada de Reynolds, indicando colangitis supurativa grave.",
    source: { label: "Sabiston Textbook of Surgery, 21.ª ed. — Vía biliar" },
  },
  {
    id: "cx-003",
    topicId: "cirugia",
    subtopic: "Trauma",
    difficulty: "intermedio",
    stem: "En la evaluación inicial de un paciente politraumatizado según ATLS, ¿cuál es el orden correcto del abordaje primario?",
    options: [
      "Exposición, circulación, vía aérea, respiración, déficit neurológico",
      "Vía aérea con control cervical, respiración/ventilación, circulación con control de hemorragia, déficit neurológico, exposición",
      "Circulación, vía aérea, exposición, respiración, déficit neurológico",
      "Déficit neurológico, vía aérea, circulación, respiración, exposición",
    ],
    correctIndex: 1,
    explanation:
      "El ABCDE del ATLS establece: A (vía Aérea con control de columna cervical), B (Buena respiración/ventilación), C (Circulación con control de hemorragia), D (Déficit neurológico), E (Exposición y control ambiental).",
    source: { label: "American College of Surgeons — ATLS Student Course Manual, 10.ª ed." },
  },
  {
    id: "cx-004",
    topicId: "cirugia",
    subtopic: "Preoperatorio",
    difficulty: "basico",
    stem: "¿Qué clasificación se utiliza universalmente para estimar el riesgo anestésico-quirúrgico según el estado físico del paciente?",
    options: ["Escala de Glasgow", "Clasificación ASA", "Escala de Alvarado", "Clasificación de Child-Pugh"],
    correctIndex: 1,
    explanation:
      "La clasificación ASA (American Society of Anesthesiologists), de I a VI, estratifica el estado físico preoperatorio del paciente y se correlaciona con el riesgo perioperatorio.",
    source: { label: "American Society of Anesthesiologists — ASA Physical Status Classification System" },
  },
  {
    id: "cx-005",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    difficulty: "avanzado",
    stem: "Paciente con pancreatitis aguda. ¿Cuáles de los siguientes son criterios que se usan en escalas pronósticas tempranas (ej. Ranson o BISAP) para predecir gravedad?",
    options: [
      "Edad, leucocitosis, glucemia, LDH y AST al ingreso (Ranson inicial)",
      "Únicamente el nivel de amilasa sérica",
      "Solo la presencia de dolor abdominal",
      "Únicamente la bilirrubina total",
    ],
    correctIndex: 0,
    explanation:
      "Los criterios de Ranson al ingreso incluyen edad >55 años, leucocitos >16,000, glucosa >200 mg/dL, LDH >350 UI/L y AST >250 UI/L, entre otros; la amilasa/lipasa confirma el diagnóstico pero no forma parte de las escalas pronósticas de gravedad.",
    source: { label: "American College of Gastroenterology — Guideline: Management of Acute Pancreatitis, 2013 (vigente)" },
  },
  {
    id: "cx-006",
    topicId: "cirugia",
    subtopic: "Heridas",
    difficulty: "basico",
    stem: "Herida quirúrgica limpia, cerrada por primera intención, sin signos de infección. ¿Cómo se clasifica esta herida según el sistema de clasificación de heridas quirúrgicas del CDC?",
    options: ["Clase I: Limpia", "Clase II: Limpia-contaminada", "Clase III: Contaminada", "Clase IV: Sucia-infectada"],
    correctIndex: 0,
    explanation:
      "Las heridas Clase I (limpias) son aquellas no infectadas, sin inflamación, sin penetración a tractos respiratorio, digestivo, genital o urinario no infectado, cerradas por primera intención.",
    source: { label: "CDC — Guideline for Prevention of Surgical Site Infection" },
  },
  {
    id: "cx-007",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    difficulty: "intermedio",
    stem: "Paciente con distensión abdominal, ausencia de canalización de gases y heces por 3 días, vómitos y radiografía con niveles hidroaéreos. ¿Cuál es el diagnóstico más probable?",
    options: ["Íleo biliar", "Obstrucción intestinal mecánica", "Gastroenteritis aguda", "Colitis ulcerativa"],
    correctIndex: 1,
    explanation:
      "La tríada de distensión, ausencia de canalización de gases/heces y niveles hidroaéreos en la radiografía es característica de obstrucción intestinal mecánica; el íleo biliar es una causa específica pero menos frecuente que debe sospecharse con aerobilia.",
    source: { label: "Sabiston Textbook of Surgery, 21.ª ed. — Obstrucción intestinal" },
  },
  {
    id: "cx-008",
    topicId: "cirugia",
    subtopic: "Trauma",
    difficulty: "intermedio",
    stem: "Paciente con trauma torácico, hipotensión, ingurgitación yugular y ruidos cardíacos velados (tríada de Beck). ¿Cuál es el diagnóstico más probable?",
    options: ["Neumotórax simple", "Taponamiento cardíaco", "Hemotórax masivo", "Contusión pulmonar"],
    correctIndex: 1,
    explanation:
      "La tríada de Beck (hipotensión, ingurgitación yugular y ruidos cardíacos apagados) sugiere taponamiento cardíaco, una emergencia que requiere pericardiocentesis o toracotomía inmediata.",
    source: { label: "American College of Surgeons — ATLS Student Course Manual, 10.ª ed." },
  },
  {
    id: "cx-009",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    difficulty: "intermedio",
    stem: "Paciente con TCE que responde a órdenes sencillas pero está confuso y somnoliento, con ECG 10. ¿Cómo se clasifica y qué conducta corresponde?",
    options: [
      "TCE leve; alta con observación domiciliaria",
      "TCE moderado; TAC de cráneo, hospitalización y exámenes neurológicos seriados",
      "TCE severo; craneotomía de emergencia inmediata",
      "No requiere TAC salvo que aparezcan nuevos síntomas",
    ],
    correctIndex: 1,
    explanation:
      "Un ECG 9-12 clasifica el TCE como moderado. Estos pacientes requieren TAC de cráneo en todos los casos, hospitalización para observación y exámenes neurológicos seriados, ya que 10-20% se deterioran y caen en coma.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "cx-010",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    difficulty: "avanzado",
    stem: "Paciente con TCE que presenta pérdida de la consciencia, seguida de un intervalo de lucidez y luego deterioro neurológico rápido. La TAC muestra una lesión hiperdensa en forma de lente biconvexa que respeta las líneas de sutura. ¿Cuál es el diagnóstico?",
    options: ["Hematoma subdural", "Hematoma epidural", "Hemorragia subaracnoidea", "Lesión axonal difusa"],
    correctIndex: 1,
    explanation:
      "La secuencia clásica (pérdida de consciencia → intervalo lúcido → deterioro neurológico rápido) junto con una imagen en lente biconvexa que respeta las suturas craneales es característica del hematoma epidural, típicamente por desgarro de la arteria meníngea media.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "cx-011",
    topicId: "cirugia",
    subtopic: "Cicatrización de heridas",
    difficulty: "basico",
    stem: "¿Cuál es el orden correcto de las fases de la cicatrización normal de una herida?",
    options: [
      "Proliferación → hemostasia/inflamación → maduración y remodelación",
      "Hemostasia e inflamación → proliferación → maduración y remodelación",
      "Maduración y remodelación → hemostasia → proliferación",
      "Epitelización → hemostasia → proliferación",
    ],
    correctIndex: 1,
    explanation:
      "La cicatrización normal sigue un patrón predecible de fases superpuestas: a) hemostasia e inflamación, b) proliferación, y c) maduración y remodelación.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 2: Cicatrización de heridas" },
  },
  {
    id: "cx-012",
    topicId: "cirugia",
    subtopic: "Cicatrización de heridas",
    difficulty: "intermedio",
    stem: "Una herida contaminada se deja abierta intencionalmente por unos días para luego colocar las suturas y cerrarla. ¿Cómo se denomina este tipo de cicatrización?",
    options: ["Primera intención", "Segunda intención", "Cierre primario tardío o tercera intención", "Cicatrización excesiva"],
    correctIndex: 2,
    explanation:
      "El cierre primario tardío (tercera intención) combina las dos primeras formas: se deja la herida abierta unos días para permitir que disminuya la contaminación/inflamación y luego se cierra con suturas.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 2: Cicatrización de heridas" },
  },
  {
    id: "cx-013",
    topicId: "cirugia",
    subtopic: "Suturas de piel",
    difficulty: "basico",
    stem: "¿En cuánto tiempo, aproximadamente, deben retirarse los puntos de sutura en la cara, para minimizar el riesgo de marcas visibles?",
    options: ["2-4 días", "4-6 días", "10-14 días", "14-21 días"],
    correctIndex: 1,
    explanation:
      "En la cara, por su buena vascularización y por razones estéticas, los puntos se retiran a los 4-6 días. Otras zonas requieren más tiempo: tronco 7-12 días, extremidades y cuero cabelludo 10-14 días, y sobre articulaciones 14-21 días.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 3: Suturas de piel" },
  },
  {
    id: "cx-014",
    topicId: "cirugia",
    subtopic: "Suturas de piel",
    difficulty: "intermedio",
    stem: "¿En cuáles de las siguientes zonas anatómicas está contraindicado el uso de anestésico local con epinefrina para suturar una herida?",
    options: [
      "Dedos de manos y pies, orejas, nariz y pene",
      "Cuero cabelludo y espalda",
      "Tronco y abdomen",
      "Muslos y brazos",
    ],
    correctIndex: 0,
    explanation:
      "No debe utilizarse epinefrina en heridas de los dedos, orejas, nariz o pene por el riesgo de necrosis tisular secundaria a vasoespasmo de las arteriolas terminales en estas estructuras.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 3: Suturas de piel" },
  },
  {
    id: "cx-015",
    topicId: "cirugia",
    subtopic: "Colecistitis",
    difficulty: "intermedio",
    stem: "¿Qué estructuras delimitan el triángulo de Calot, referencia anatómica clave durante la colecistectomía?",
    options: [
      "Conducto cístico, conducto hepático común y borde inferior del hígado",
      "Colédoco, arteria hepática y vena porta",
      "Conducto pancreático, colédoco y duodeno",
      "Arteria cística, arteria hepática y vena cava inferior",
    ],
    correctIndex: 0,
    explanation:
      "El triángulo de Calot está delimitado por el conducto cístico, el conducto hepático común y el borde inferior del hígado. La arteria cística se localiza casi siempre dentro de este triángulo, por lo que es clave identificarlo durante la colecistectomía para evitar lesiones de la vía biliar.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 4: Colecistitis" },
  },
  {
    id: "cx-016",
    topicId: "cirugia",
    subtopic: "Colecistitis",
    difficulty: "avanzado",
    stem: "Según los criterios de Tokio, ¿qué se requiere para un diagnóstico definitivo de colangitis aguda?",
    options: [
      "Solo fiebre",
      "Un ítem de inflamación sistémica (A) + un ítem de colestasis (B)",
      "Un ítem de inflamación sistémica (A) + un ítem de colestasis (B) + un hallazgo imagenológico (C)",
      "Únicamente el hallazgo imagenológico (C)",
    ],
    correctIndex: 2,
    explanation:
      "Los criterios de Tokio para colangitis aguda requieren: A) signos de inflamación sistémica (fiebre >38°, leucocitosis o PCR elevada), B) signos de colestasis (bilirrubina >2 mg/dL o enzimas hepáticas elevadas >1.5 veces), y C) hallazgo imagenológico (dilatación de la vía biliar o evidencia de la causa). El diagnóstico definitivo requiere un ítem de A + B + C.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 4: Colecistitis" },
  },
  {
    id: "cx-017",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    difficulty: "intermedio",
    stem: "Un adulto sufre quemaduras de espesor parcial en todo el tórax anterior (18%) y en todo el brazo derecho (9%). Según la regla de los 9, ¿cuál es el porcentaje aproximado de superficie corporal total quemada?",
    options: ["9%", "18%", "27%", "36%"],
    correctIndex: 2,
    explanation:
      "Según la regla de los 9 en el adulto, el tórax/abdomen anterior representa 18% y cada brazo completo 9%. Sumando ambas áreas: 18% + 9% = 27% de superficie corporal total quemada.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "cx-018",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    difficulty: "avanzado",
    stem: "Según la fórmula de Parkland/Baxter, ¿cómo se administra el volumen de reanimación con líquidos calculado para las primeras 24 horas en un paciente quemado?",
    options: [
      "Todo el volumen en las primeras 8 horas",
      "La mitad del volumen en las primeras 8 horas desde la quemadura, y la otra mitad en las siguientes 16 horas",
      "Un tercio en cada período de 8 horas de forma equitativa",
      "Todo el volumen distribuido uniformemente en 24 horas",
    ],
    correctIndex: 1,
    explanation:
      "La fórmula de Parkland/Baxter calcula 3-4 mL/kg por % de superficie quemada de solución Ringer lactato; la mitad se administra en las primeras 8 horas después de la quemadura (no desde el ingreso) y la otra mitad en las 16 horas siguientes.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "cx-019",
    topicId: "cirugia",
    subtopic: "Choque",
    difficulty: "basico",
    stem: "Según la clasificación clínica actual (Schwartz), ¿cuáles son los 6 tipos de choque?",
    options: [
      "Hipovolémico, cardiogénico, séptico (vasodilatador), neurógeno, por traumatismo y obstructivo",
      "Solo hipovolémico y cardiogénico",
      "Anafiláctico, hipovolémico y neurógeno únicamente",
      "Séptico, hemorrágico y quirúrgico",
    ],
    correctIndex: 0,
    explanation:
      "La clínica reciente describe 6 tipos de choque: hipovolémico, cardiogénico, séptico (vasodilatador), neurógeno, por traumatismo y obstructivo. Las 4 categorías clásicas de 1934 (hipovolémico, vasógeno, neurógeno, cardiogénico) se ampliaron con obstructivo y por traumatismo.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 6: Choque - Schwartz" },
  },
  {
    id: "cx-020",
    topicId: "cirugia",
    subtopic: "Choque",
    difficulty: "avanzado",
    stem: "Paciente con lesión medular cervical presenta hipotensión sin taquicardia compensatoria y extremidades calientes. ¿Cuál es el diagnóstico más probable y su mecanismo?",
    options: [
      "Choque hipovolémico por hemorragia oculta",
      "Choque neurógeno por pérdida del tono vasomotor simpático",
      "Choque cardiogénico por contusión miocárdica",
      "Choque séptico por infección concomitante",
    ],
    correctIndex: 1,
    explanation:
      "El choque neurógeno, causado por lesión medular con pérdida del tono simpático, se caracteriza por hipotensión SIN la taquicardia compensatoria típica de otros tipos de choque, y con frecuencia extremidades calientes por vasodilatación, a diferencia del choque hipovolémico.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 6: Choque - Schwartz / Cap. 7: Shock - ATLS" },
  },
  {
    id: "cx-021",
    topicId: "cirugia",
    subtopic: "Shock - ATLS",
    difficulty: "intermedio",
    stem: "Paciente traumatizado con frecuencia cardíaca de 118 lpm, presión arterial disminuida, presión de pulso disminuida, frecuencia respiratoria de 24 y estado confuso. Según la clasificación ATLS de hemorragia, ¿a qué grado corresponde?",
    options: ["Grado I (<15%)", "Grado II (15-30%)", "Grado III (31-40%)", "Grado IV (>40%)"],
    correctIndex: 2,
    explanation:
      "La combinación de taquicardia marcada, caída de la presión sistólica y de pulso, taquipnea y alteración del estado mental corresponde a hemorragia Grado III (31-40% de pérdida del volumen sanguíneo), que típicamente requiere transfusión sanguínea.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 7: Shock - ATLS" },
  },
  {
    id: "cx-022",
    topicId: "cirugia",
    subtopic: "Shock - ATLS",
    difficulty: "basico",
    stem: "¿Cuál es el bolo inicial recomendado de solución cristaloide isotónica para la reanimación de un paciente adulto en shock hemorrágico?",
    options: ["250 mL", "1 L (con reevaluación según respuesta)", "5 L de una sola vez", "No se administran cristaloides, solo sangre"],
    correctIndex: 1,
    explanation:
      "Se administra inicialmente un bolo de 1 L de solución electrolítica isotónica tibia en adultos (20 mL/kg en pacientes pediátricos <40 kg), evaluando la respuesta del paciente para decidir bolos adicionales, hemoderivados o control quirúrgico.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 7: Shock - ATLS" },
  },
  {
    id: "cx-023",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    difficulty: "intermedio",
    stem: "¿Cómo se caracteriza clásicamente el dolor abdominal visceral en comparación con el dolor parietal?",
    options: [
      "El visceral es agudo y bien localizado; el parietal es vago",
      "El visceral es vago, poco localizado y periumbilical/epigástrico; el parietal es más marcado y localizado",
      "Ambos tienen las mismas características",
      "El visceral siempre indica perforación; el parietal siempre indica cólico",
    ],
    correctIndex: 1,
    explanation:
      "El dolor visceral, producido por distensión de una víscera hueca, suele ser vago y poco localizado en epigastrio, región periumbilical o hipogastrio. El dolor parietal, al comprometer las raíces nerviosas segmentarias del peritoneo, es más marcado y localizado.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 8: Abdomen agudo" },
  },
  {
    id: "cx-024",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    difficulty: "intermedio",
    stem: "Paciente con dolor abdominal agudo que se irradia al hombro derecho. ¿Cuáles son las causas más probables de este dolor referido?",
    options: [
      "Corazón, cola del páncreas o bazo",
      "Hígado, vesícula biliar o hemidiafragma derecho",
      "Útero o vejiga",
      "Riñón izquierdo únicamente",
    ],
    correctIndex: 1,
    explanation:
      "El dolor referido al hombro derecho se asocia clásicamente a patología hepática, de la vesícula biliar o irritación del hemidiafragma derecho. El dolor referido al hombro izquierdo se asocia a corazón, cola del páncreas, bazo o hemidiafragma izquierdo.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 8: Abdomen agudo" },
  },
  {
    id: "cx-025",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    difficulty: "avanzado",
    stem: "Paciente con TCE presenta equimosis periorbitaria bilateral (signo de mapache), rinorrea y lesión de pares craneales I al VI. ¿En qué fosa craneal se localiza la fractura de base de cráneo sospechada?",
    options: ["Fosa anterior", "Fosa media", "Fosa posterior", "No es posible localizarla con estos signos"],
    correctIndex: 0,
    explanation:
      "El signo de mapache (equimosis periorbitaria), la rinorrea (salida de LCR) y la lesión de los pares craneales I-VI son característicos de fractura de la fosa craneal anterior. La fosa media/posterior se asocia a signo de Battle, otorrea/otorraquia y lesión de pares VII-XII.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "cx-026",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    difficulty: "intermedio",
    stem: "¿Cuál es el valor normal de la presión intracraneal (PIC) en reposo y a partir de qué valor se asocia a mal pronóstico?",
    options: [
      "Normal ~10 mmHg; mal pronóstico >22 mmHg",
      "Normal ~30 mmHg; mal pronóstico >50 mmHg",
      "Normal ~5 mmHg; mal pronóstico >10 mmHg",
      "Normal ~60 mmHg; mal pronóstico >90 mmHg",
    ],
    correctIndex: 0,
    explanation:
      "La PIC normal para un paciente en reposo es aproximadamente 10 mmHg. Presiones mayores a 22 mmHg están asociadas a mal pronóstico neurológico.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "cx-027",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    difficulty: "avanzado",
    stem: "¿Cuál es una contraindicación importante para el uso de manitol en un paciente con TCE y PIC elevada?",
    options: ["Hipertensión arterial", "Hipotensión o hipovolemia", "Fiebre", "Bradicardia"],
    correctIndex: 1,
    explanation:
      "El manitol es un diurético osmótico contraindicado en pacientes hipotensos o hipovolémicos, ya que en ese contexto no reduce la PIC de forma efectiva y puede empeorar la perfusión. Se administra en bolo de 0.25-1 g/kg manteniendo euvolemia y PAS >90 mmHg.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "cx-028",
    topicId: "cirugia",
    subtopic: "Cicatrización de heridas",
    difficulty: "avanzado",
    stem: "Paciente con laceración nerviosa que conserva la lámina basal de las células de Schwann pero pierde la continuidad axonal. ¿Qué tipo de lesión neural presenta?",
    options: ["Neuropraxia", "Axonotmesis", "Neurotmesis", "Ninguna, es una contusión simple"],
    correctIndex: 1,
    explanation:
      "La axonotmesis se caracteriza por interrupción de la continuidad axonal con preservación de la lámina basal de las células de Schwann. La neuropraxia es solo desmielinización focal (sin lesión axonal), y la neurotmesis es la transección completa del nervio.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 2: Cicatrización de heridas" },
  },
  {
    id: "cx-029",
    topicId: "cirugia",
    subtopic: "Cicatrización de heridas",
    difficulty: "intermedio",
    stem: "¿Qué tipo de apósito es más útil en el tratamiento de quemaduras por su alto índice de evaporación sin alterar la hidratación de la herida?",
    options: ["Apósitos oclusivos/semioclusivos", "Apósitos de hidrocoloides e hidrogel", "Apósitos absorbentes de algodón", "Alginatos"],
    correctIndex: 1,
    explanation:
      "Los apósitos de hidrocoloides e hidrogel combinan los beneficios de la oclusión y la absorción, permitiendo un índice alto de evaporación sin alterar la hidratación de la herida, lo que los hace útiles en el tratamiento de quemaduras.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 2: Cicatrización de heridas" },
  },
  {
    id: "cx-030",
    topicId: "cirugia",
    subtopic: "Suturas de piel",
    difficulty: "intermedio",
    stem: "¿Cuál es la dosis máxima aproximada de lidocaína al 1% sin epinefrina para anestesia local?",
    options: ["1 mg/kg de peso", "4 mg/kg de peso", "15 mg/kg de peso", "No tiene dosis máxima"],
    correctIndex: 1,
    explanation:
      "La dosis máxima de lidocaína al 1% sin epinefrina es de 4 mg/kg de peso, con inicio de acción rápido (~3 min) y duración de 30-120 minutos. Con epinefrina, la dosis máxima aumenta a 7 mg/kg y la duración se prolonga a 60-180 minutos.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 3: Suturas de piel" },
  },
  {
    id: "cx-031",
    topicId: "cirugia",
    subtopic: "Colecistitis",
    difficulty: "avanzado",
    stem: "¿Cuáles son los criterios diagnósticos de pancreatitis biliar (se requieren 2 de 3)?",
    options: [
      "Dolor abdominal en hemiabdomen superior irradiado en cinturón, elevación de amilasa/lipasa 3 veces su valor normal, y hallazgo imagenológico compatible",
      "Solo elevación de la bilirrubina total",
      "Únicamente fiebre y leucocitosis",
      "Solo la presencia de cálculos en la vesícula biliar",
    ],
    correctIndex: 0,
    explanation:
      "El diagnóstico de pancreatitis (biliar) se establece con 2 o más de: 1) dolor abdominal en cuadrante superior irradiado en hemicinturón, 2) elevación de amilasa o lipasa 3 veces su valor normal, y 3) hallazgo imagenológico compatible.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 4: Colecistitis" },
  },
  {
    id: "cx-032",
    topicId: "cirugia",
    subtopic: "Colecistitis",
    difficulty: "avanzado",
    stem: "¿Cuál de los siguientes es un criterio 'muy fuerte' para indicar una CPRE (ERCP) en sospecha de coledocolitiasis?",
    options: [
      "Edad mayor de 55 años",
      "Bilirrubina total >4 mg/dL o cálculo en la vía biliar evidenciado por ecografía",
      "Perfil hepático levemente alterado",
      "Clínica de pancreatitis biliar leve aislada",
    ],
    correctIndex: 1,
    explanation:
      "Los criterios 'muy fuertes' para CPRE incluyen: clínica de colangitis, bilirrubina total >4 mg/dL, o cálculo en la vía biliar evidenciado por ecografía. Los criterios 'fuertes' incluyen bilirrubina 1.8-4 mg/dL o dilatación del colédoco >6mm; los 'moderados' incluyen edad >55 años.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 4: Colecistitis" },
  },
  {
    id: "cx-033",
    topicId: "cirugia",
    subtopic: "Colecistitis",
    difficulty: "avanzado",
    stem: "Paciente en UCI con quemaduras extensas y nutrición parenteral desarrolla colecistitis sin cálculos biliares evidenciados en la ecografía. ¿Cuál es el tratamiento de elección?",
    options: [
      "Colecistectomía laparoscópica electiva en 6 semanas",
      "Colecistostomía percutánea guiada por ecografía o TAC",
      "Manejo expectante con antibióticos orales ambulatorios",
      "ERCP diagnóstica",
    ],
    correctIndex: 1,
    explanation:
      "La colecistitis acalculosa requiere intervención de urgencia. El tratamiento de elección en estos pacientes graves, que a menudo no son elegibles para cirugía, es la colecistostomía percutánea guiada por ecografía o TAC; casi 90% mejora con este procedimiento.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 4: Colecistitis" },
  },
  {
    id: "cx-034",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    difficulty: "intermedio",
    stem: "¿Cuál de los siguientes pacientes quemados debe referirse a un centro especializado de atención de quemados?",
    options: [
      "Quemadura de 1er grado en el antebrazo que afecta 3% de superficie corporal",
      "Quemadura de espesor parcial que afecta manos, pies, genitales o periné",
      "Quemadura superficial sin afectación de articulaciones",
      "Cualquier quemadura en un paciente sano menor de 5% de superficie corporal",
    ],
    correctIndex: 1,
    explanation:
      "Las guías de referencia a un centro de quemados incluyen: quemaduras de espesor parcial >10% de TBSA, quemaduras que afectan cara, manos, pies, genitales, periné o articulaciones mayores, quemaduras de 3er grado en cualquier edad, quemaduras eléctricas o químicas, y lesión por inhalación, entre otras.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "cx-035",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    difficulty: "avanzado",
    stem: "Paciente con quemaduras por inhalación de humo en un incendio cerrado presenta acidosis láctica persistente pese a ventilación adecuada. ¿Qué tratamiento inmediato está indicado ante sospecha de intoxicación por cianuro?",
    options: ["Tiosulfato de sodio como primera línea", "Hidroxicobalamina", "Solo observación", "Carbón activado"],
    correctIndex: 1,
    explanation:
      "La hidroxicobalamina se recomienda como tratamiento inmediato de la toxicidad por cianuro de hidrógeno en lesión por inhalación de humo. El tiosulfato de sodio no es eficaz en el tratamiento agudo y se reserva como manejo posterior si la acidosis láctica no resuelve con ventilación.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "cx-036",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    difficulty: "intermedio",
    stem: "¿Cuál es una contraindicación importante del uso de sulfadiazina de plata en el tratamiento tópico de quemaduras?",
    options: [
      "No tiene contraindicaciones",
      "Está contraindicada en quemaduras programadas para nuevos injertos, ya que destruye los injertos cutáneos",
      "Solo puede usarse en quemaduras de 1er grado",
      "Está contraindicada en todas las quemaduras de espesor parcial",
    ],
    correctIndex: 1,
    explanation:
      "La sulfadiazina de plata destruye los injertos cutáneos y está contraindicada en quemaduras programadas para nuevos injertos. También puede retardar la migración epitelial en quemaduras de espesor parcial en fase de cicatrización.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "cx-037",
    topicId: "cirugia",
    subtopic: "Choque",
    difficulty: "avanzado",
    stem: "Según los conjuntos de la Surviving Sepsis Campaign, ¿qué debe completarse dentro de las primeras 3 horas en un paciente con sospecha de choque séptico?",
    options: [
      "Solo iniciar vasopresores",
      "Medir lactato, obtener hemocultivos antes de antibióticos, administrar antibióticos de amplio espectro y cristaloide (30 mL/kg) si hay hipotensión o lactato ≥4 mmol/L",
      "Únicamente medir la presión venosa central",
      "Iniciar hidrocortisona de forma sistemática",
    ],
    correctIndex: 1,
    explanation:
      "El paquete de 3 horas de la Surviving Sepsis Campaign incluye: 1) medir el lactato, 2) obtener hemocultivos antes de administrar antibióticos, 3) administrar antibióticos de amplio espectro, y 4) administrar 30 mL/kg de cristaloide en caso de hipotensión o lactato ≥4 mmol/L.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 6: Choque - Schwartz" },
  },
  {
    id: "cx-038",
    topicId: "cirugia",
    subtopic: "Choque",
    difficulty: "avanzado",
    stem: "¿Cuáles son los criterios hemodinámicos que definen el estado de choque cardiogénico?",
    options: [
      "PAS <90 mmHg por al menos 30 min, índice cardíaco <2.2 L/min/m², y presión en cuña de arteria pulmonar >15 mmHg",
      "Únicamente frecuencia cardíaca elevada",
      "PVC baja y gasto cardíaco normal",
      "Solamente la presencia de dolor torácico",
    ],
    correctIndex: 0,
    explanation:
      "Los criterios hemodinámicos del choque cardiogénico incluyen hipotensión sostenida (PAS <90 mmHg por al menos 30 min), índice cardíaco reducido (<2.2 L/min/m²) y presión en cuña de la arteria pulmonar alta (>15 mmHg), con volumen intravascular adecuado.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 6: Choque - Schwartz" },
  },
  {
    id: "cx-039",
    topicId: "cirugia",
    subtopic: "Shock - ATLS",
    difficulty: "intermedio",
    stem: "¿A partir de qué frecuencia cardíaca se considera taquicardia (y posible signo de shock) en un adulto, según los criterios pediátricos/adultos del ATLS?",
    options: ["Mayor de 60 lpm", "Mayor de 100 lpm", "Mayor de 160 lpm", "Mayor de 200 lpm"],
    correctIndex: 1,
    explanation:
      "Se diagnostica taquicardia cuando la FC es mayor de 160 lpm en un infante, 140 lpm en un niño en edad preescolar, 120 lpm entre la edad escolar y la pubertad, y 100 lpm en un adulto. La taquicardia es la señal circulatoria medible más temprana del estado de shock.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 7: Shock - ATLS" },
  },
  {
    id: "cx-040",
    topicId: "cirugia",
    subtopic: "Shock - ATLS",
    difficulty: "avanzado",
    stem: "Un paciente traumatizado recibe un bolo inicial de cristaloide y mejora transitoriamente, pero luego vuelve a presentar deterioro de la perfusión. ¿Qué patrón de respuesta a la reanimación presenta y qué implica?",
    options: [
      "Respuesta rápida; no requiere más intervención",
      "Respuesta transitoria; sugiere hemorragia persistente y probable necesidad de control quirúrgico/angiográfico",
      "Respuesta mínima o nula; indica hemorragia leve autolimitada",
      "Este patrón no está descrito en la literatura",
    ],
    correctIndex: 1,
    explanation:
      "La respuesta transitoria (mejoría inicial seguida de deterioro) indica una pérdida sanguínea estimada de 15-40% (hemorragia grado II-III) con sangrado persistente o reanimación inadecuada, y sugiere que el paciente requiere control quirúrgico o angiográfico de la hemorragia.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 7: Shock - ATLS" },
  },
  {
    id: "cx-041",
    topicId: "cirugia",
    subtopic: "Shock - ATLS",
    difficulty: "intermedio",
    stem: "¿Qué hallazgo contraindica la colocación de una sonda transuretral antes de descartar una lesión uretral en un paciente traumatizado?",
    options: [
      "Hematuria microscópica aislada",
      "Sangre en el meato uretral o hematoma/contusión perineal",
      "Dolor abdominal difuso",
      "Fractura de fémur cerrada",
    ],
    correctIndex: 1,
    explanation:
      "La presencia de sangre en el meato uretral o hematoma/contusión perineal es una contraindicación para la inserción de una sonda transuretral antes de descartar lesión uretral, ya que podría convertir una lesión parcial en completa.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 7: Shock - ATLS" },
  },
  {
    id: "cx-042",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    difficulty: "avanzado",
    stem: "¿Cuál es la presión intraabdominal normal en reposo y a partir de qué valor se considera hipertensión abdominal de grado 3 (que suele requerir descompresión quirúrgica)?",
    options: [
      "Normal 5-7 mmHg; grado 3 entre 21-25 mmHg",
      "Normal 20-30 mmHg; grado 3 mayor a 100 mmHg",
      "Normal 0 mmHg; grado 3 mayor a 5 mmHg",
      "Normal 40-50 mmHg; grado 3 mayor a 60 mmHg",
    ],
    correctIndex: 0,
    explanation:
      "La presión intraabdominal normal es de 5-7 mmHg en decúbito supino. La hipertensión abdominal grado 3 (21-25 mmHg) a menudo requiere descompresión quirúrgica, a diferencia de los grados 1-2 que se manejan médicamente.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 8: Abdomen agudo" },
  },
  {
    id: "cx-043",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    difficulty: "intermedio",
    stem: "¿Cuál es la enfermedad no obstétrica más frecuente que requiere cirugía durante el embarazo?",
    options: ["Colecistitis aguda", "Apendicitis aguda", "Obstrucción intestinal", "Pancreatitis"],
    correctIndex: 1,
    explanation:
      "La apendicitis es la enfermedad no obstétrica más frecuente que requiere cirugía durante el embarazo, registrándose en aproximadamente 1 de cada 1,500 embarazos. Sus síntomas 'típicos' solo se presentan en 50-60% de los casos por los cambios anatómicos del embarazo.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 8: Abdomen agudo" },
  },
  {
    id: "cx-044",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    difficulty: "intermedio",
    stem: "Un paciente presenta abdomen agudo por perforación de una úlcera gastroduodenal. Según el mecanismo fisiopatológico, ¿en qué categoría de causa quirúrgica se clasifica?",
    options: ["Hemorragia", "Perforación", "Obstrucción", "Isquemia"],
    correctIndex: 1,
    explanation:
      "Las causas quirúrgicas de abdomen agudo se agrupan por mecanismo en: hemorragia, infección, perforación, obstrucción e isquemia. La úlcera gastrointestinal perforada, el síndrome de Boerhaave y el divertículo perforado son ejemplos clásicos de la categoría de perforación.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 8: Abdomen agudo" },
  },
  {
    id: "cx-045",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    difficulty: "intermedio",
    stem: "¿Entre qué dos capas meníngeas se localiza el espacio subdural, sitio potencial de hemorragia por desgarro de venas puente?",
    options: [
      "Entre el cráneo y la duramadre",
      "Entre la duramadre y la aracnoides",
      "Entre la aracnoides y la piamadre",
      "Dentro del parénquima cerebral",
    ],
    correctIndex: 1,
    explanation:
      "El espacio subdural es un espacio potencial entre la duramadre y la aracnoides. El espacio epidural está entre el cráneo y la duramadre (sitio de hematomas epidurales por lesión de la arteria meníngea media), y el espacio subaracnoideo (entre aracnoides y piamadre) contiene el LCR.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "cx-046",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    difficulty: "avanzado",
    stem: "Paciente con TCE severo presenta midriasis (dilatación pupilar) del lado derecho y hemiparesia del lado izquierdo. ¿Qué proceso explica este cuadro?",
    options: [
      "Herniación uncal derecha, con compresión del III par craneal derecho y del tracto corticoespinal en el mesencéfalo",
      "Un accidente cerebrovascular isquémico bilateral",
      "Una lesión medular cervical aislada",
      "Hipoglucemia severa",
    ],
    correctIndex: 0,
    explanation:
      "La dilatación pupilar ipsilateral asociada a hemiparesia contralateral es el signo clásico de la herniación uncal: el uncus (parte medial del lóbulo temporal) hernia a través de la muesca tentorial, comprimiendo el III par craneal (midriasis ipsilateral) y el tracto corticoespinal en el mesencéfalo (hemiparesia contralateral).",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "cx-047",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    difficulty: "basico",
    stem: "¿Qué estructura divide la cavidad craneal en los compartimentos supratentorial e infratentorial?",
    options: ["La hoz del cerebro", "La tienda del cerebelo", "El foramen magno", "El acueducto cerebral"],
    correctIndex: 1,
    explanation:
      "La tienda del cerebelo divide la cavidad craneal en los compartimentos supratentorial e infratentorial (fosa posterior). La hoz del cerebro, en cambio, separa los hemisferios cerebrales derecho e izquierdo.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "cx-048",
    topicId: "cirugia",
    subtopic: "Cicatrización de heridas",
    difficulty: "intermedio",
    stem: "¿Cuál es el factor quimiotáctico más potente para los fibroblastos durante la fase de proliferación de la cicatrización?",
    options: [
      "Factor de crecimiento derivado de plaquetas (PDGF)",
      "Interleucina-10 (IL-10)",
      "Factor activador de plaquetas (PAF)",
      "Óxido nítrico",
    ],
    correctIndex: 0,
    explanation:
      "El PDGF, liberado inicialmente por los gránulos alfa de las plaquetas, es el factor quimiotáctico más potente para los fibroblastos, que infiltran la herida durante la fase de proliferación y sintetizan colágeno.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 2: Cicatrización de heridas" },
  },
  {
    id: "cx-049",
    topicId: "cirugia",
    subtopic: "Cicatrización de heridas",
    difficulty: "avanzado",
    stem: "¿Por qué las anastomosis del esófago y el recto tienen tasas de fracaso más altas que otros segmentos del tubo digestivo?",
    options: [
      "Porque son segmentos extraperitoneales que carecen de serosa",
      "Porque tienen mayor irrigación sanguínea que el resto del tubo digestivo",
      "Porque están compuestos únicamente de mucosa",
      "No existe diferencia real en las tasas de fracaso",
    ],
    correctIndex: 0,
    explanation:
      "El esófago y el recto son segmentos extraperitoneales que carecen de serosa, una capa importante para la resistencia mecánica temprana de una anastomosis; esto explica sus altas tasas de fracaso anastomótico en comparación con segmentos intraperitoneales con serosa.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 2: Cicatrización de heridas" },
  },
  {
    id: "cx-050",
    topicId: "cirugia",
    subtopic: "Cicatrización de heridas",
    difficulty: "intermedio",
    stem: "En la cicatrización de una fractura ósea, ¿qué caracteriza a la etapa del 'callo blando'?",
    options: [
      "Es la etapa final donde el hueso ya está remodelado completamente",
      "Se forma 3-4 días después de la lesión, uniendo los segmentos fracturados con tejido fibrocartilaginoso, previo a la mineralización",
      "Ocurre antes de la formación del hematoma de fractura",
      "Se asocia únicamente a fracturas expuestas",
    ],
    correctIndex: 1,
    explanation:
      "El callo blando se forma 3-4 días después de la lesión, cuando el tejido blando forma un puente fibrocartilaginoso entre los segmentos óseos fracturados, sirviendo de férula interna. Posteriormente, el callo blando se mineraliza (etapa de callo duro) en un plazo de hasta 2-3 meses.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 2: Cicatrización de heridas" },
  },
  {
    id: "cx-051",
    topicId: "cirugia",
    subtopic: "Choque",
    difficulty: "avanzado",
    stem: "¿Qué factores del complemento activados durante el choque se correlacionan con el desarrollo de SDRA (síndrome de dificultad respiratoria aguda) y disfunción orgánica múltiple?",
    options: ["C3a, C4a y C5a", "Solo la vía clásica del complemento", "IgG e IgM únicamente", "El complemento no se relaciona con estas complicaciones"],
    correctIndex: 0,
    explanation:
      "Los factores del complemento activados C3a, C4a y C5a son mediadores potentes del incremento de la permeabilidad vascular, contracción de músculo liso, liberación de histamina, TNFα e IL-1, y adhesión de neutrófilos al endotelio. El desarrollo de SDRA y disfunción orgánica múltiple se correlaciona con la intensidad de la activación del complemento.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 6: Choque - Schwartz" },
  },
  {
    id: "cx-052",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    difficulty: "avanzado",
    stem: "Paciente con quemadura circunferencial de espesor total en el antebrazo presenta parestesias, dolor progresivo y disminución del llenado capilar. ¿Cuál es el diagnóstico y el tratamiento indicado?",
    options: [
      "Síndrome compartimental inminente; requiere escarotomía",
      "Reacción alérgica local; requiere antihistamínicos",
      "Infección de la herida; requiere antibióticos sistémicos",
      "Es normal en toda quemadura circunferencial y no requiere intervención",
    ],
    correctIndex: 0,
    explanation:
      "Parestesias, dolor, disminución del llenado capilar y progresión a ausencia de pulsos distales son signos de síndrome compartimental inminente por el efecto de torniquete de la escara rígida en una quemadura circunferencial. El tratamiento es la escarotomía para liberar la presión.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "cx-053",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    difficulty: "intermedio",
    stem: "¿Por qué la piel cabelluda es un sitio donante de injerto particularmente útil?",
    options: [
      "Porque es delgada y sin folículos pilosos",
      "Porque tiene muchos folículos pilosos que favorecen una cicatrización rápida del sitio donante",
      "Porque no requiere hemostasia",
      "Porque nunca se usa como sitio donante",
    ],
    correctIndex: 1,
    explanation:
      "La piel cabelluda es gruesa y cuenta con muchos folículos pilosos, lo que favorece que el sitio donante cicatrice con rapidez. Se recomienda el goteo con solución de epinefrina para la hemostasia de esta región, muy vascularizada.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "cx-054",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    difficulty: "intermedio",
    stem: "¿En qué áreas del cuerpo se debe evitar la técnica de autoinjerto 'en malla' por razones estéticas?",
    options: [
      "Muslos y espalda",
      "Cara, cuello y manos",
      "Nalgas",
      "No existe ninguna zona de excepción",
    ],
    correctIndex: 1,
    explanation:
      "Aunque los autoinjertos en malla permiten cubrir un área más extensa y facilitan el drenaje de sangre y líquido seroso, las áreas de importancia estética como cara, cuello y manos deben tratarse con injertos que no incluyan la técnica de malla para lograr un mejor resultado estético.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "cx-055",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    difficulty: "avanzado",
    stem: "En la exposición a radiación, ¿qué indica la aparición de vómito dentro de la primera hora tras la exposición?",
    options: [
      "Que la exposición fue mínima y sin riesgo",
      "Una dosis de radiación mínima de 4 Sv (dosis letal alta)",
      "Que se trata únicamente de ansiedad, sin relación con la dosis",
      "Que no se requiere ninguna medida de descontaminación",
    ],
    correctIndex: 1,
    explanation:
      "El tiempo hasta la aparición del vómito es un indicador útil de la dosis de exposición a radiación: vómito en un plazo de 2 horas sugiere una dosis media letal de al menos 3 Sv, mientras que su aparición en 1 hora indica una dosis mínima de 4 Sv. Ausencia de vómito en 4 horas sugiere que no habrá efectos clínicos graves.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
];
