import type { QuizQuestion } from "@/types/content";

export const cirugiaQuestions: QuizQuestion[] = [
  {
    id: "cx-001",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    difficulty: "basico",
    stem: "Paciente de 22 años con dolor que migró de epigastrio a fosa ilíaca derecha, fiebre baja, náuseas y signo de McBurney positivo. ¿Cuál es el diagnóstico más probable?",
    options: ["Colecistitis aguda", "Apendicitis aguda", "Diverticulitis", "Pancreatitis aguda"],
    correctIndex: 1,
    explanation:
      "La migración clásica del dolor periumbilical hacia la fosa ilíaca derecha con dolor a la palpación en el punto de McBurney es el cuadro típico de apendicitis aguda.",
    source: { label: "Schwartz's Principles of Surgery, 11.ª ed. — Apendicitis aguda" },
  },
  {
    id: "cx-002",
    topicId: "cirugia",
    subtopic: "Vía biliar",
    difficulty: "intermedio",
    stem: "Mujer de 45 años con dolor en hipocondrio derecho, fiebre, ictericia y Murphy positivo. Se sospecha colangitis aguda. ¿Cuál es la tríada clásica que sustenta este diagnóstico?",
    options: [
      "Tríada de Charcot: dolor en hipocondrio derecho, fiebre e ictericia",
      "Tríada de Virchow: éstasis, hipercoagulabilidad y daño endotelial",
      "Tríada de Beck: hipotensión, ingurgitación yugular y ruidos cardíacos velados",
      "Tríada de Cushing: hipertensión, bradicardia e irregularidad respiratoria",
    ],
    correctIndex: 0,
    explanation:
      "La tríada de Charcot (dolor en hipocondrio derecho, fiebre e ictericia) es característica de colangitis aguda; si se agregan hipotensión y confusión se denomina péntada de Reynolds, indicando colangitis supurativa grave.",
    source: { label: "Sabiston Textbook of Surgery, 21.ª ed. — Vía biliar" },
  },
  {
    id: "cx-003",
    topicId: "cirugia",
    subtopic: "Trauma",
    difficulty: "intermedio",
    stem: "En la evaluación inicial de un paciente politraumatizado según ATLS, ¿cuál es el orden correcto del abordaje primario?",
    options: [
      "Exposición, circulación, vía aérea, respiración, déficit neurológico",
      "Vía aérea con control cervical, respiración/ventilación, circulación con control de hemorragia, déficit neurológico, exposición",
      "Circulación, vía aérea, exposición, respiración, déficit neurológico",
      "Déficit neurológico, vía aérea, circulación, respiración, exposición",
    ],
    correctIndex: 1,
    explanation:
      "El ABCDE del ATLS establece: A (vía Aérea con control de columna cervical), B (Buena respiración/ventilación), C (Circulación con control de hemorragia), D (Déficit neurológico), E (Exposición y control ambiental).",
    source: { label: "American College of Surgeons — ATLS Student Course Manual, 10.ª ed." },
  },
  {
    id: "cx-004",
    topicId: "cirugia",
    subtopic: "Preoperatorio",
    difficulty: "basico",
    stem: "¿Qué clasificación se utiliza universalmente para estimar el riesgo anestésico-quirúrgico según el estado físico del paciente?",
    options: ["Escala de Glasgow", "Clasificación ASA", "Escala de Alvarado", "Clasificación de Child-Pugh"],
    correctIndex: 1,
    explanation:
      "La clasificación ASA (American Society of Anesthesiologists), de I a VI, estratifica el estado físico preoperatorio del paciente y se correlaciona con el riesgo perioperatorio.",
    source: { label: "American Society of Anesthesiologists — ASA Physical Status Classification System" },
  },
  {
    id: "cx-005",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    difficulty: "avanzado",
    stem: "Paciente con pancreatitis aguda. ¿Cuáles de los siguientes son criterios que se usan en escalas pronósticas tempranas (ej. Ranson o BISAP) para predecir gravedad?",
    options: [
      "Edad, leucocitosis, glucemia, LDH y AST al ingreso (Ranson inicial)",
      "Únicamente el nivel de amilasa sérica",
      "Solo la presencia de dolor abdominal",
      "Únicamente la bilirrubina total",
    ],
    correctIndex: 0,
    explanation:
      "Los criterios de Ranson al ingreso incluyen edad >55 años, leucocitos >16,000, glucosa >200 mg/dL, LDH >350 UI/L y AST >250 UI/L, entre otros; la amilasa/lipasa confirma el diagnóstico pero no forma parte de las escalas pronósticas de gravedad.",
    source: { label: "American College of Gastroenterology — Guideline: Management of Acute Pancreatitis, 2013 (vigente)" },
  },
  {
    id: "cx-006",
    topicId: "cirugia",
    subtopic: "Heridas",
    difficulty: "basico",
    stem: "Herida quirúrgica limpia, cerrada por primera intención, sin signos de infección. ¿Cómo se clasifica esta herida según el sistema de clasificación de heridas quirúrgicas del CDC?",
    options: ["Clase I: Limpia", "Clase II: Limpia-contaminada", "Clase III: Contaminada", "Clase IV: Sucia-infectada"],
    correctIndex: 0,
    explanation:
      "Las heridas Clase I (limpias) son aquellas no infectadas, sin inflamación, sin penetración a tractos respiratorio, digestivo, genital o urinario no infectado, cerradas por primera intención.",
    source: { label: "CDC — Guideline for Prevention of Surgical Site Infection" },
  },
  {
    id: "cx-007",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    difficulty: "intermedio",
    stem: "Paciente con distensión abdominal, ausencia de canalización de gases y heces por 3 días, vómitos y radiografía con niveles hidroaéreos. ¿Cuál es el diagnóstico más probable?",
    options: ["Íleo biliar", "Obstrucción intestinal mecánica", "Gastroenteritis aguda", "Colitis ulcerativa"],
    correctIndex: 1,
    explanation:
      "La tríada de distensión, ausencia de canalización de gases/heces y niveles hidroaéreos en la radiografía es característica de obstrucción intestinal mecánica; el íleo biliar es una causa específica pero menos frecuente que debe sospecharse con aerobilia.",
    source: { label: "Sabiston Textbook of Surgery, 21.ª ed. — Obstrucción intestinal" },
  },
  {
    id: "cx-008",
    topicId: "cirugia",
    subtopic: "Trauma",
    difficulty: "intermedio",
    stem: "Paciente con trauma torácico, hipotensión, ingurgitación yugular y ruidos cardíacos velados (tríada de Beck). ¿Cuál es el diagnóstico más probable?",
    options: ["Neumotórax simple", "Taponamiento cardíaco", "Hemotórax masivo", "Contusión pulmonar"],
    correctIndex: 1,
    explanation:
      "La tríada de Beck (hipotensión, ingurgitación yugular y ruidos cardíacos apagados) sugiere taponamiento cardíaco, una emergencia que requiere pericardiocentesis o toracotomía inmediata.",
    source: { label: "American College of Surgeons — ATLS Student Course Manual, 10.ª ed." },
  },
  {
    id: "cx-009",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    difficulty: "intermedio",
    stem: "Paciente con TCE que responde a órdenes sencillas pero está confuso y somnoliento, con ECG 10. ¿Cómo se clasifica y qué conducta corresponde?",
    options: [
      "TCE leve; alta con observación domiciliaria",
      "TCE moderado; TAC de cráneo, hospitalización y exámenes neurológicos seriados",
      "TCE severo; craneotomía de emergencia inmediata",
      "No requiere TAC salvo que aparezcan nuevos síntomas",
    ],
    correctIndex: 1,
    explanation:
      "Un ECG 9-12 clasifica el TCE como moderado. Estos pacientes requieren TAC de cráneo en todos los casos, hospitalización para observación y exámenes neurológicos seriados, ya que 10-20% se deterioran y caen en coma.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "cx-010",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    difficulty: "avanzado",
    stem: "Paciente con TCE que presenta pérdida de la consciencia, seguida de un intervalo de lucidez y luego deterioro neurológico rápido. La TAC muestra una lesión hiperdensa en forma de lente biconvexa que respeta las líneas de sutura. ¿Cuál es el diagnóstico?",
    options: ["Hematoma subdural", "Hematoma epidural", "Hemorragia subaracnoidea", "Lesión axonal difusa"],
    correctIndex: 1,
    explanation:
      "La secuencia clásica (pérdida de consciencia → intervalo lúcido → deterioro neurológico rápido) junto con una imagen en lente biconvexa que respeta las suturas craneales es característica del hematoma epidural, típicamente por desgarro de la arteria meníngea media.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "cx-011",
    topicId: "cirugia",
    subtopic: "Cicatrización de heridas",
    difficulty: "basico",
    stem: "¿Cuál es el orden correcto de las fases de la cicatrización normal de una herida?",
    options: [
      "Proliferación → hemostasia/inflamación → maduración y remodelación",
      "Hemostasia e inflamación → proliferación → maduración y remodelación",
      "Maduración y remodelación → hemostasia → proliferación",
      "Epitelización → hemostasia → proliferación",
    ],
    correctIndex: 1,
    explanation:
      "La cicatrización normal sigue un patrón predecible de fases superpuestas: a) hemostasia e inflamación, b) proliferación, y c) maduración y remodelación.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 2: Cicatrización de heridas" },
  },
  {
    id: "cx-012",
    topicId: "cirugia",
    subtopic: "Cicatrización de heridas",
    difficulty: "intermedio",
    stem: "Una herida contaminada se deja abierta intencionalmente por unos días para luego colocar las suturas y cerrarla. ¿Cómo se denomina este tipo de cicatrización?",
    options: ["Primera intención", "Segunda intención", "Cierre primario tardío o tercera intención", "Cicatrización excesiva"],
    correctIndex: 2,
    explanation:
      "El cierre primario tardío (tercera intención) combina las dos primeras formas: se deja la herida abierta unos días para permitir que disminuya la contaminación/inflamación y luego se cierra con suturas.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 2: Cicatrización de heridas" },
  },
  {
    id: "cx-013",
    topicId: "cirugia",
    subtopic: "Suturas de piel",
    difficulty: "basico",
    stem: "¿En cuánto tiempo, aproximadamente, deben retirarse los puntos de sutura en la cara, para minimizar el riesgo de marcas visibles?",
    options: ["2-4 días", "4-6 días", "10-14 días", "14-21 días"],
    correctIndex: 1,
    explanation:
      "En la cara, por su buena vascularización y por razones estéticas, los puntos se retiran a los 4-6 días. Otras zonas requieren más tiempo: tronco 7-12 días, extremidades y cuero cabelludo 10-14 días, y sobre articulaciones 14-21 días.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 3: Suturas de piel" },
  },
  {
    id: "cx-014",
    topicId: "cirugia",
    subtopic: "Suturas de piel",
    difficulty: "intermedio",
    stem: "¿En cuáles de las siguientes zonas anatómicas está contraindicado el uso de anestésico local con epinefrina para suturar una herida?",
    options: [
      "Dedos de manos y pies, orejas, nariz y pene",
      "Cuero cabelludo y espalda",
      "Tronco y abdomen",
      "Muslos y brazos",
    ],
    correctIndex: 0,
    explanation:
      "No debe utilizarse epinefrina en heridas de los dedos, orejas, nariz o pene por el riesgo de necrosis tisular secundaria a vasoespasmo de las arteriolas terminales en estas estructuras.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 3: Suturas de piel" },
  },
  {
    id: "cx-015",
    topicId: "cirugia",
    subtopic: "Colecistitis",
    difficulty: "intermedio",
    stem: "¿Qué estructuras delimitan el triángulo de Calot, referencia anatómica clave durante la colecistectomía?",
    options: [
      "Conducto cístico, conducto hepático común y borde inferior del hígado",
      "Colédoco, arteria hepática y vena porta",
      "Conducto pancreático, colédoco y duodeno",
      "Arteria cística, arteria hepática y vena cava inferior",
    ],
    correctIndex: 0,
    explanation:
      "El triángulo de Calot está delimitado por el conducto cístico, el conducto hepático común y el borde inferior del hígado. La arteria cística se localiza casi siempre dentro de este triángulo, por lo que es clave identificarlo durante la colecistectomía para evitar lesiones de la vía biliar.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 4: Colecistitis" },
  },
  {
    id: "cx-016",
    topicId: "cirugia",
    subtopic: "Colecistitis",
    difficulty: "avanzado",
    stem: "Según los criterios de Tokio, ¿qué se requiere para un diagnóstico definitivo de colangitis aguda?",
    options: [
      "Solo fiebre",
      "Un ítem de inflamación sistémica (A) + un ítem de colestasis (B)",
      "Un ítem de inflamación sistémica (A) + un ítem de colestasis (B) + un hallazgo imagenológico (C)",
      "Únicamente el hallazgo imagenológico (C)",
    ],
    correctIndex: 2,
    explanation:
      "Los criterios de Tokio para colangitis aguda requieren: A) signos de inflamación sistémica (fiebre >38°, leucocitosis o PCR elevada), B) signos de colestasis (bilirrubina >2 mg/dL o enzimas hepáticas elevadas >1.5 veces), y C) hallazgo imagenológico (dilatación de la vía biliar o evidencia de la causa). El diagnóstico definitivo requiere un ítem de A + B + C.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 4: Colecistitis" },
  },
  {
    id: "cx-017",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    difficulty: "intermedio",
    stem: "Un adulto sufre quemaduras de espesor parcial en todo el tórax anterior (18%) y en todo el brazo derecho (9%). Según la regla de los 9, ¿cuál es el porcentaje aproximado de superficie corporal total quemada?",
    options: ["9%", "18%", "27%", "36%"],
    correctIndex: 2,
    explanation:
      "Según la regla de los 9 en el adulto, el tórax/abdomen anterior representa 18% y cada brazo completo 9%. Sumando ambas áreas: 18% + 9% = 27% de superficie corporal total quemada.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "cx-018",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    difficulty: "avanzado",
    stem: "Según la fórmula de Parkland/Baxter, ¿cómo se administra el volumen de reanimación con líquidos calculado para las primeras 24 horas en un paciente quemado?",
    options: [
      "Todo el volumen en las primeras 8 horas",
      "La mitad del volumen en las primeras 8 horas desde la quemadura, y la otra mitad en las siguientes 16 horas",
      "Un tercio en cada período de 8 horas de forma equitativa",
      "Todo el volumen distribuido uniformemente en 24 horas",
    ],
    correctIndex: 1,
    explanation:
      "La fórmula de Parkland/Baxter calcula 3-4 mL/kg por % de superficie quemada de solución Ringer lactato; la mitad se administra en las primeras 8 horas después de la quemadura (no desde el ingreso) y la otra mitad en las 16 horas siguientes.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "cx-019",
    topicId: "cirugia",
    subtopic: "Choque",
    difficulty: "basico",
    stem: "Según la clasificación clínica actual (Schwartz), ¿cuáles son los 6 tipos de choque?",
    options: [
      "Hipovolémico, cardiogénico, séptico (vasodilatador), neurógeno, por traumatismo y obstructivo",
      "Solo hipovolémico y cardiogénico",
      "Anafiláctico, hipovolémico y neurógeno únicamente",
      "Séptico, hemorrágico y quirúrgico",
    ],
    correctIndex: 0,
    explanation:
      "La clínica reciente describe 6 tipos de choque: hipovolémico, cardiogénico, séptico (vasodilatador), neurógeno, por traumatismo y obstructivo. Las 4 categorías clásicas de 1934 (hipovolémico, vasógeno, neurógeno, cardiogénico) se ampliaron con obstructivo y por traumatismo.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 6: Choque - Schwartz" },
  },
  {
    id: "cx-020",
    topicId: "cirugia",
    subtopic: "Choque",
    difficulty: "avanzado",
    stem: "Paciente con lesión medular cervical presenta hipotensión sin taquicardia compensatoria y extremidades calientes. ¿Cuál es el diagnóstico más probable y su mecanismo?",
    options: [
      "Choque hipovolémico por hemorragia oculta",
      "Choque neurógeno por pérdida del tono vasomotor simpático",
      "Choque cardiogénico por contusión miocárdica",
      "Choque séptico por infección concomitante",
    ],
    correctIndex: 1,
    explanation:
      "El choque neurógeno, causado por lesión medular con pérdida del tono simpático, se caracteriza por hipotensión SIN la taquicardia compensatoria típica de otros tipos de choque, y con frecuencia extremidades calientes por vasodilatación, a diferencia del choque hipovolémico.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 6: Choque - Schwartz / Cap. 7: Shock - ATLS" },
  },
  {
    id: "cx-021",
    topicId: "cirugia",
    subtopic: "Shock - ATLS",
    difficulty: "intermedio",
    stem: "Paciente traumatizado con frecuencia cardíaca de 118 lpm, presión arterial disminuida, presión de pulso disminuida, frecuencia respiratoria de 24 y estado confuso. Según la clasificación ATLS de hemorragia, ¿a qué grado corresponde?",
    options: ["Grado I (<15%)", "Grado II (15-30%)", "Grado III (31-40%)", "Grado IV (>40%)"],
    correctIndex: 2,
    explanation:
      "La combinación de taquicardia marcada, caída de la presión sistólica y de pulso, taquipnea y alteración del estado mental corresponde a hemorragia Grado III (31-40% de pérdida del volumen sanguíneo), que típicamente requiere transfusión sanguínea.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 7: Shock - ATLS" },
  },
  {
    id: "cx-022",
    topicId: "cirugia",
    subtopic: "Shock - ATLS",
    difficulty: "basico",
    stem: "¿Cuál es el bolo inicial recomendado de solución cristaloide isotónica para la reanimación de un paciente adulto en shock hemorrágico?",
    options: ["250 mL", "1 L (con reevaluación según respuesta)", "5 L de una sola vez", "No se administran cristaloides, solo sangre"],
    correctIndex: 1,
    explanation:
      "Se administra inicialmente un bolo de 1 L de solución electrolítica isotónica tibia en adultos (20 mL/kg en pacientes pediátricos <40 kg), evaluando la respuesta del paciente para decidir bolos adicionales, hemoderivados o control quirúrgico.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 7: Shock - ATLS" },
  },
  {
    id: "cx-023",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    difficulty: "intermedio",
    stem: "¿Cómo se caracteriza clásicamente el dolor abdominal visceral en comparación con el dolor parietal?",
    options: [
      "El visceral es agudo y bien localizado; el parietal es vago",
      "El visceral es vago, poco localizado y periumbilical/epigástrico; el parietal es más marcado y localizado",
      "Ambos tienen las mismas características",
      "El visceral siempre indica perforación; el parietal siempre indica cólico",
    ],
    correctIndex: 1,
    explanation:
      "El dolor visceral, producido por distensión de una víscera hueca, suele ser vago y poco localizado en epigastrio, región periumbilical o hipogastrio. El dolor parietal, al comprometer las raíces nerviosas segmentarias del peritoneo, es más marcado y localizado.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 8: Abdomen agudo" },
  },
  {
    id: "cx-024",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    difficulty: "intermedio",
    stem: "Paciente con dolor abdominal agudo que se irradia al hombro derecho. ¿Cuáles son las causas más probables de este dolor referido?",
    options: [
      "Corazón, cola del páncreas o bazo",
      "Hígado, vesícula biliar o hemidiafragma derecho",
      "Útero o vejiga",
      "Riñón izquierdo únicamente",
    ],
    correctIndex: 1,
    explanation:
      "El dolor referido al hombro derecho se asocia clásicamente a patología hepática, de la vesícula biliar o irritación del hemidiafragma derecho. El dolor referido al hombro izquierdo se asocia a corazón, cola del páncreas, bazo o hemidiafragma izquierdo.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 8: Abdomen agudo" },
  },
];
