import type { QuizQuestion } from "@/types/content";

export const ginecoObstetriciaQuestions: QuizQuestion[] = [
  {
    id: "go-001",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    difficulty: "intermedio",
    stem: "Embarazada de 32 semanas con presión arterial 160/110 mmHg, proteinuria significativa y cefalea intensa. ¿Cuál es el diagnóstico más probable y el fármaco de elección para prevenir convulsiones?",
    options: [
      "Hipertensión gestacional; labetalol oral",
      "Preeclampsia con criterios de severidad; sulfato de magnesio",
      "Eclampsia establecida; difenilhidantoína",
      "Síndrome HELLP; solo transfusión plaquetaria",
    ],
    correctIndex: 1,
    explanation:
      "PA ≥160/110 con proteinuria y cefalea (síntoma de severidad) define preeclampsia con criterios de severidad. El sulfato de magnesio es el fármaco de elección para prevenir/tratar convulsiones eclámpticas.",
    source: { label: "ACOG Practice Bulletin — Gestational Hypertension and Preeclampsia" },
  },
  {
    id: "go-002",
    topicId: "gineco-obstetricia",
    subtopic: "Control prenatal",
    difficulty: "basico",
    stem: "Según los lineamientos de control prenatal, ¿cuántas consultas mínimas se recomiendan durante un embarazo de bajo riesgo?",
    options: ["Al menos 2", "Al menos 4", "Al menos 8", "No es necesario un mínimo definido"],
    correctIndex: 2,
    explanation:
      "La OMS recomienda un modelo de al menos 8 contactos prenatales para reducir la mortalidad perinatal y mejorar la experiencia de atención, actualizando el modelo previo de 4 visitas.",
    source: { label: "OMS — Recomendaciones sobre atención prenatal para una experiencia positiva del embarazo" },
  },
  {
    id: "go-003",
    topicId: "gineco-obstetricia",
    subtopic: "Hemorragia obstétrica",
    difficulty: "avanzado",
    stem: "Paciente puérpera inmediata con sangrado vaginal abundante y útero blando, no contraído, a la palpación. ¿Cuál es la causa más frecuente de hemorragia posparto y el primer paso de manejo?",
    options: [
      "Atonía uterina; masaje uterino bimanual y uterotónicos (oxitocina de primera línea)",
      "Retención de restos placentarios; histerectomía inmediata",
      "Laceración cervical; solo observación",
      "Coagulopatía; transfusión sin evaluar el útero",
    ],
    correctIndex: 0,
    explanation:
      "La atonía uterina es la causa más común de hemorragia posparto (~70%). El manejo inicial incluye masaje uterino bimanual y uterotónicos, siendo la oxitocina de primera línea, seguida de ergometrina o misoprostol y medidas quirúrgicas si no responde.",
    source: { label: "FIGO/OMS — Guías para el manejo de la hemorragia posparto" },
  },
  {
    id: "go-004",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    difficulty: "intermedio",
    stem: "Mujer de 29 años con flujo vaginal blanco-grisáceo, olor a pescado, pH vaginal >4.5 y presencia de 'clue cells' en el examen microscópico. ¿Cuál es el diagnóstico más probable?",
    options: ["Candidiasis vulvovaginal", "Vaginosis bacteriana", "Tricomoniasis", "Cervicitis gonocócica"],
    correctIndex: 1,
    explanation:
      "Los criterios de Amsel (flujo blanco-grisáceo homogéneo, olor a aminas/pescado, pH >4.5 y clue cells) son diagnósticos de vaginosis bacteriana, causada típicamente por Gardnerella vaginalis.",
    source: { label: "CDC — Sexually Transmitted Infections Treatment Guidelines" },
  },
  {
    id: "go-005",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    difficulty: "intermedio",
    stem: "Embarazada de 8 semanas con sangrado vaginal leve, cérvix cerrado en el examen y embrión con actividad cardíaca presente en el ultrasonido. ¿Cuál es el diagnóstico más probable?",
    options: ["Aborto inevitable", "Amenaza de aborto", "Aborto incompleto", "Embarazo ectópico"],
    correctIndex: 1,
    explanation:
      "El sangrado con cérvix cerrado y viabilidad embrionaria confirmada corresponde a una amenaza de aborto, que en muchos casos evoluciona favorablemente con reposo relativo y seguimiento.",
    source: { label: "ACOG Practice Bulletin — Early Pregnancy Loss" },
  },
  {
    id: "go-006",
    topicId: "gineco-obstetricia",
    subtopic: "Planificación familiar",
    difficulty: "basico",
    stem: "¿Cuál de los siguientes métodos anticonceptivos tiene la mayor eficacia (menor tasa de falla) con uso típico?",
    options: [
      "Preservativo masculino",
      "Píldora anticonceptiva combinada",
      "Dispositivo intrauterino (DIU) o implante subdérmico",
      "Método del ritmo/calendario",
    ],
    correctIndex: 2,
    explanation:
      "Los anticonceptivos reversibles de acción prolongada (DIU e implante subdérmico) tienen tasas de falla con uso típico menores al 1%, muy superiores en eficacia a los métodos de barrera o de conocimiento de la fertilidad.",
    source: { label: "CDC — U.S. Medical Eligibility Criteria for Contraceptive Use" },
  },
  {
    id: "go-007",
    topicId: "gineco-obstetricia",
    subtopic: "Atención del parto",
    difficulty: "intermedio",
    stem: "Durante el trabajo de parto, la dilatación cervical se detiene en 6 cm por más de 4 horas con dinámica uterina adecuada. ¿Cómo se denomina esta alteración?",
    options: ["Fase latente prolongada", "Detención de la fase activa (distocia)", "Parto precipitado", "Período expulsivo prolongado"],
    correctIndex: 1,
    explanation:
      "Con contracciones adecuadas y sin progreso de dilatación por ≥4 horas (o ≥6 horas con actividad inadecuada) en fase activa, se define detención de la fase activa del trabajo de parto.",
    source: { label: "ACOG/SMFM — Safe Prevention of the Primary Cesarean Delivery" },
  },
  {
    id: "go-008",
    topicId: "gineco-obstetricia",
    subtopic: "Control prenatal",
    difficulty: "basico",
    stem: "Primigrávida en su primera visita prenatal a las 8 semanas de amenorrea. ¿Cuál es el método más preciso para calcular la edad gestacional en este momento?",
    options: [
      "Ecografía del primer trimestre (longitud céfalo-nalga)",
      "Fecha de última regla exclusivamente",
      "Altura del fondo uterino",
      "Percepción materna de movimientos fetales",
    ],
    correctIndex: 0,
    explanation:
      "El ultrasonido del primer trimestre es el método más preciso para establecer la edad gestacional: hasta las 12 semanas, la longitud céfalo-nalga predice la edad gestacional dentro de un margen de 4 días.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 1: Atención prenatal" },
  },
  {
    id: "go-009",
    topicId: "gineco-obstetricia",
    subtopic: "Control prenatal",
    difficulty: "basico",
    stem: "Una paciente tiene fecha de última regla confiable el 10 de enero. Aplicando la Regla de Naegele, ¿cómo se calcula la fecha probable de parto?",
    options: [
      "Se restan 7 días y se suman 9 meses a la FUR",
      "Se suman 7 días al primer día de la FUR, se restan 3 meses y se suma 1 año",
      "Se suman 14 días y se mantiene el mismo mes",
      "Se resta un trimestre completo sin ajustar días",
    ],
    correctIndex: 1,
    explanation:
      "La Regla de Naegele estima la fecha probable de parto agregando 7 días al primer día de la FUR, restando 3 meses y sumando un año, ajustando si el cálculo cruza de mes o año.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 1: Atención prenatal" },
  },
  {
    id: "go-010",
    topicId: "gineco-obstetricia",
    subtopic: "Control prenatal",
    difficulty: "basico",
    stem: "¿En qué momento del embarazo se recomienda tomar el cultivo vaginal y rectal para tamizaje de estreptococo del grupo B?",
    options: ["Entre las 20 y 24 semanas", "Entre las 28 y 32 semanas", "Entre las 35 y 37 semanas", "Entre las 38 y 40 semanas"],
    correctIndex: 2,
    explanation:
      "El CDC recomienda obtener el cultivo vaginal y rectal para estreptococo del grupo B entre las 35 y 37 semanas de gestación, para guiar la profilaxis antibiótica intraparto.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 1: Atención prenatal" },
  },
  {
    id: "go-011",
    topicId: "gineco-obstetricia",
    subtopic: "Fisiología del embarazo",
    difficulty: "intermedio",
    stem: "Una gestante a término refiere sensación de falta de aire al subir gradas. ¿Cuál es el cambio esperado en la capacidad residual funcional pulmonar durante el embarazo normal?",
    options: ["Aumenta 20 a 30%", "Disminuye 20 a 30%", "No presenta cambios significativos", "Se duplica al término"],
    correctIndex: 1,
    explanation:
      "La elevación progresiva del diafragma por el útero grávido reduce la capacidad residual funcional en aproximadamente 20 a 30% (400 a 700 mL), lo que puede generar disnea fisiológica del embarazo.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 2: Fisiología materna" },
  },
  {
    id: "go-012",
    topicId: "gineco-obstetricia",
    subtopic: "Fisiología del embarazo",
    difficulty: "intermedio",
    stem: "Gestante de 34 semanas que refiere mareo y palidez al acostarse boca arriba, con mejoría al girar hacia el lado izquierdo. ¿Cuál es el mecanismo fisiopatológico de este cuadro?",
    options: [
      "Compresión aortocava por el útero grávido en decúbito supino",
      "Vasodilatación esplácnica generalizada",
      "Anemia dilucional grave",
      "Bloqueo simpático farmacológico",
    ],
    correctIndex: 0,
    explanation:
      "En cerca del 10% de las mujeres, la compresión de los grandes vasos por el útero en posición supina causa hipotensión arterial significativa (síndrome hipotensor supino), que mejora con el decúbito lateral izquierdo.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 2: Fisiología materna" },
  },
  {
    id: "go-013",
    topicId: "gineco-obstetricia",
    subtopic: "Fisiología del embarazo",
    difficulty: "intermedio",
    stem: "En una gestante sana de 32 semanas, ¿cuál de los siguientes hallazgos de laboratorio se considera un cambio fisiológico normal del embarazo y NO amerita estudio adicional?",
    options: [
      "Hemoglobina de 9.5 g/dL",
      "Leucocitosis de hasta 15,000/µL",
      "Recuento plaquetario de 90,000/µL",
      "Creatinina sérica de 1.0 mg/dL",
    ],
    correctIndex: 1,
    explanation:
      "Los conteos normales de leucocitos durante el embarazo pueden alcanzar hasta 15,000/µL sin indicar infección; en cambio, hemoglobina <11 g/dL, plaquetas <116,000/µL o creatinina >0.9 mg/dL sí ameritan evaluación.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 2: Fisiología materna" },
  },
  {
    id: "go-014",
    topicId: "gineco-obstetricia",
    subtopic: "Atención del parto",
    difficulty: "basico",
    stem: "Al realizar las maniobras de Leopold en una gestante a término, se palpa una masa dura, redonda y peloteable en el fondo uterino, y en la pelvis una masa irregular y menos definida. ¿Cuál es la presentación fetal más probable?",
    options: ["Cefálica", "Podálica", "Transversa", "Compuesta"],
    correctIndex: 1,
    explanation:
      "La cabeza fetal (dura, redonda, peloteable) ubicada en el fondo uterino, con las nalgas (masa irregular, menos definida) en la pelvis, corresponde a presentación podálica.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 3: Parto normal" },
  },
  {
    id: "go-015",
    topicId: "gineco-obstetricia",
    subtopic: "Atención del parto",
    difficulty: "intermedio",
    stem: "¿Cuál es el orden correcto de los movimientos cardinales del trabajo de parto en presentación cefálica de vértice?",
    options: [
      "Encajamiento, descenso, flexión, rotación interna, extensión, rotación externa, expulsión",
      "Descenso, encajamiento, extensión, flexión, rotación externa, rotación interna, expulsión",
      "Flexión, encajamiento, descenso, rotación externa, extensión, rotación interna, expulsión",
      "Encajamiento, flexión, descenso, extensión, rotación interna, rotación externa, expulsión",
    ],
    correctIndex: 0,
    explanation:
      "Los movimientos cardinales siguen la secuencia encajamiento, descenso, flexión, rotación interna, extensión, rotación externa y expulsión (nemotecnia EDFRERE).",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 3: Parto normal" },
  },
  {
    id: "go-016",
    topicId: "gineco-obstetricia",
    subtopic: "Atención del parto",
    difficulty: "basico",
    stem: "Una gestante a término tiene un índice de Bishop de 9 al examen cervical. ¿Qué implica este resultado?",
    options: [
      "Cuello uterino desfavorable para inducción",
      "Cuello uterino favorable para inducción del trabajo de parto",
      "Necesidad de cesárea inmediata",
      "Trabajo de parto pretérmino inminente",
    ],
    correctIndex: 1,
    explanation:
      "El índice de Bishop evalúa dilatación, borramiento, estación, consistencia y posición cervical; un puntaje alto (≥8) indica un cuello favorable, con mayor probabilidad de éxito en la inducción del parto.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 3: Parto normal" },
  },
  {
    id: "go-017",
    topicId: "gineco-obstetricia",
    subtopic: "Monitoreo fetal",
    difficulty: "intermedio",
    stem: "En el monitoreo electrónico fetal intraparto, una desaceleración de la frecuencia cardíaca que inicia después del pico de la contracción, con nadir posterior al pico y retorno gradual a la basal, se denomina:",
    options: ["Desaceleración temprana", "Desaceleración tardía", "Desaceleración variable", "Desaceleración prolongada"],
    correctIndex: 1,
    explanation:
      "La desaceleración tardía inicia, alcanza su nadir y termina después del pico de la contracción, y refleja insuficiencia uteroplacentaria; requiere vigilancia estrecha del bienestar fetal.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 4: Monitoreo fetal intraparto" },
  },
  {
    id: "go-018",
    topicId: "gineco-obstetricia",
    subtopic: "Monitoreo fetal",
    difficulty: "avanzado",
    stem: "¿Cuál de los siguientes trazados corresponde a la categoría III (ACOG) de frecuencia cardíaca fetal, que exige atención inmediata?",
    options: [
      "Variabilidad moderada sin desaceleraciones",
      "Ausencia de variabilidad de la línea basal con desaceleraciones tardías o variables recurrentes, o bradicardia sostenida",
      "Aceleraciones periódicas con variabilidad normal",
      "Variabilidad mínima aislada sin otros hallazgos",
    ],
    correctIndex: 1,
    explanation:
      "La categoría III de ACOG es predictiva de estado ácido-base fetal anormal e incluye ausencia de variabilidad con desaceleraciones tardías o variables recurrentes, bradicardia, o un patrón sinusoidal; requiere intervención inmediata.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 4: Monitoreo fetal intraparto" },
  },
  {
    id: "go-019",
    topicId: "gineco-obstetricia",
    subtopic: "Monitoreo fetal",
    difficulty: "intermedio",
    stem: "Se observan desaceleraciones variables recurrentes atribuidas a compresión funicular durante el trabajo de parto. ¿Cuál es una medida terapéutica intraparto útil para este hallazgo?",
    options: ["Amnioinfusión", "Aumentar la dosis de oxitocina", "Romper las membranas de inmediato", "Administrar sulfato de magnesio"],
    correctIndex: 0,
    explanation:
      "La amnioinfusión (instilación de solución salina en la cavidad amniótica) puede aliviar la compresión del cordón umbilical y reducir las desaceleraciones variables recurrentes.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 4: Monitoreo fetal intraparto" },
  },
  {
    id: "go-020",
    topicId: "gineco-obstetricia",
    subtopic: "Atención del parto",
    difficulty: "avanzado",
    stem: "Nulípara en fase activa del trabajo de parto (6 cm de dilatación) con velocidad de dilatación cervical <1.2 cm/hora a pesar de actividad uterina adecuada. ¿Cómo se clasifica este patrón de trabajo de parto anómalo?",
    options: [
      "Fase latente prolongada",
      "Trastorno de progresión (retraso de la dilatación en fase activa)",
      "Detención secundaria de la dilatación",
      "Parto precipitado",
    ],
    correctIndex: 1,
    explanation:
      "En nulíparas, una velocidad de dilatación cervical <1.2 cm/hora en fase activa define un trastorno de retraso o progresión lenta; el manejo preferido es expectante con evaluación del progreso, no la cesárea inmediata.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 5: Distocias" },
  },
  {
    id: "go-021",
    topicId: "gineco-obstetricia",
    subtopic: "Atención del parto",
    difficulty: "avanzado",
    stem: "Se detecta un feto en presentación de cara con posición mentoposterior persistente al final del trabajo de parto. ¿Cuál es la conducta obstétrica más adecuada?",
    options: [
      "Esperar el parto vaginal espontáneo",
      "Cesárea, ya que la mentoposterior persistente no puede nacer por vía vaginal salvo prematuridad extrema",
      "Fórceps bajo de forma electiva",
      "Versión cefálica externa intraparto",
    ],
    correctIndex: 1,
    explanation:
      "En la presentación de cara con mentón posterior persistente, la barbilla no puede rotar hacia la sínfisis del pubis, impidiendo el nacimiento vaginal excepto en fetos muy prematuros; se indica cesárea.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 5: Distocias" },
  },
  {
    id: "go-022",
    topicId: "gineco-obstetricia",
    subtopic: "Atención del parto",
    difficulty: "intermedio",
    stem: "¿Cuál es la causa más común de posición fetal transversa?",
    options: ["Placenta previa", "Relajación de la pared abdominal por alta paridad", "Macrosomía fetal", "Embarazo postérmino"],
    correctIndex: 1,
    explanation:
      "La relajación de la pared abdominal por alta paridad es la causa más frecuente de posición transversa; las mujeres con 4 o más partos tienen una incidencia hasta 10 veces mayor que las nulíparas.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 5: Distocias" },
  },
  {
    id: "go-023",
    topicId: "gineco-obstetricia",
    subtopic: "Puerperio",
    difficulty: "basico",
    stem: "A las 2 semanas posparto, una puérpera nota que su descarga vaginal cambió de rojo intenso a un tono pálido rosado-amarronado. ¿Cómo se denomina esta etapa de los loquios?",
    options: ["Loquios rojos", "Loquios serosos", "Loquios alba", "Loquios purulentos (hallazgo anormal)"],
    correctIndex: 1,
    explanation:
      "Después de 3 a 4 días posparto, los loquios se tornan progresivamente pálidos (loquios serosos); hacia el décimo día se vuelven blanco-amarillentos (loquios alba), por la mezcla de leucocitos y menor contenido líquido.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 6: Puerperio" },
  },
  {
    id: "go-024",
    topicId: "gineco-obstetricia",
    subtopic: "Hemorragia obstétrica",
    difficulty: "intermedio",
    stem: "¿Cuál es la causa más frecuente de hemorragia posparto tardía (secundaria), definida como sangrado entre 24 horas y 12 semanas posparto?",
    options: [
      "Atonía uterina inmediata",
      "Involución anormal del sitio placentario, frecuentemente por retención de restos",
      "Laceración cervical del parto",
      "Coagulopatía congénita no diagnosticada",
    ],
    correctIndex: 1,
    explanation:
      "La hemorragia posparto secundaria resulta con mayor frecuencia de una involución anormal del sitio de implantación placentaria, a menudo por retención de fragmentos placentarios que pueden formar un pólipo placentario.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 6: Puerperio" },
  },
  {
    id: "go-025",
    topicId: "gineco-obstetricia",
    subtopic: "Puerperio",
    difficulty: "basico",
    stem: "¿En cuál de las siguientes situaciones está indicada la administración de inmunoglobulina anti-D en el posparto inmediato?",
    options: [
      "Madre Rh negativo no isoinmunizada con recién nacido Rh positivo",
      "Madre Rh positivo con recién nacido Rh negativo",
      "Cualquier puérpera, independientemente del grupo Rh",
      "Únicamente si el parto fue por cesárea",
    ],
    correctIndex: 0,
    explanation:
      "A la mujer con Rh D negativo no isoinmunizada, cuyo recién nacido es Rh D positivo, se le administran 300 µg de inmunoglobulina anti-D poco después del parto para prevenir la aloinmunización.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 6: Puerperio" },
  },
  {
    id: "go-026",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    difficulty: "intermedio",
    stem: "Paciente con embarazo de 9 semanas, sangrado vaginal abundante y cérvix dilatado; la ecografía muestra un saco gestacional incompleto con restos ovulares dentro del canal cervical. ¿Cuál es el diagnóstico?",
    options: ["Amenaza de aborto", "Aborto incompleto", "Aborto diferido", "Aborto séptico"],
    correctIndex: 1,
    explanation:
      "El aborto incompleto se caracteriza por expulsión parcial de los productos de la concepción con cérvix dilatado y persistencia de restos ovulares, que suelen extraerse con pinza de anillo o requerir legrado.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 7: Aborto" },
  },
  {
    id: "go-027",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    difficulty: "avanzado",
    stem: "¿Cuál es la anomalía cromosómica más frecuente encontrada en los abortos espontáneos cromosómicamente anormales del primer trimestre?",
    options: ["Monosomía X (45,X)", "Triploidía", "Trisomía", "Translocación balanceada parental"],
    correctIndex: 2,
    explanation:
      "Entre los abortos cromosómicamente anormales (que ocurren en el 75% a las 8 semanas), la trisomía es la más común (50-60%), seguida de la monosomía (9-13%) y la triploidía (11-12%).",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 7: Aborto" },
  },
  {
    id: "go-028",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    difficulty: "avanzado",
    stem: "Según la definición de la SAMR (2013), ¿cómo se establece la pérdida habitual del embarazo (RPL)?",
    options: [
      "3 o más pérdidas consecutivas de cualquier tipo",
      "2 o más embarazos fallidos confirmados por ecografía o histopatología",
      "Cualquier pérdida ocurrida después de las 20 semanas",
      "Un solo aborto con antecedente familiar de pérdidas",
    ],
    correctIndex: 1,
    explanation:
      "Mientras la definición clásica exige 3 o más pérdidas consecutivas, la SAMR redefinió en 2013 la pérdida habitual del embarazo como 2 o más embarazos fallidos confirmados por examen ecográfico o histopatológico.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 7: Aborto" },
  },
  {
    id: "go-029",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    difficulty: "basico",
    stem: "¿Cuál es el sitio más frecuente de implantación en el embarazo ectópico tubárico?",
    options: ["Segmento ístmico", "Segmento fimbrial", "Segmento ampular", "Segmento intersticial"],
    correctIndex: 2,
    explanation:
      "Cerca del 70% de los embarazos ectópicos tubáricos se implantan en el segmento ampular de la trompa de Falopio, seguido del ístmico (12%), fimbrial (11%) e intersticial (2%).",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 8: Embarazo ectópico" },
  },
  {
    id: "go-030",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    difficulty: "avanzado",
    stem: "Paciente hemodinámicamente estable con embarazo ectópico tubárico íntegro <3.5 cm, sin actividad cardíaca fetal y β-hCG <5,000 mIU/mL. ¿Cuál es el tratamiento de primera línea?",
    options: [
      "Salpingectomía de urgencia",
      "Metotrexato en dosis única",
      "Laparotomía exploratoria",
      "Observación sin ningún tratamiento",
    ],
    correctIndex: 1,
    explanation:
      "En pacientes estables, con embarazo ectópico pequeño, sin actividad cardíaca fetal y β-hCG sérica baja, el metotrexato en dosis única es el tratamiento médico de elección, con tasas de éxito cercanas al 88%.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 8: Embarazo ectópico" },
  },
  {
    id: "go-031",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    difficulty: "avanzado",
    stem: "¿Cuál es el mejor predictor de éxito del tratamiento médico con metotrexato en el embarazo ectópico?",
    options: ["Edad materna", "Nivel inicial bajo de β-hCG sérica", "Tamaño uterino", "Paridad previa"],
    correctIndex: 1,
    explanation:
      "De los predictores de éxito (bajo nivel inicial de β-hCG, tamaño ectópico pequeño y ausencia de actividad cardíaca fetal), el nivel inicial de β-hCG sérica es el único indicador de mejor pronóstico para el tratamiento con dosis única de metotrexato.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 8: Embarazo ectópico" },
  },
  {
    id: "go-032",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    difficulty: "avanzado",
    stem: "Una mola hidatiforme completa se caracteriza cariotípicamente por:",
    options: [
      "Cariotipo 69,XXX triploide",
      "Cariotipo 46,XX diploide, de origen completamente paterno (androgénesis)",
      "Cariotipo 46,XY normal biparental",
      "Cariotipo 45,X (monosomía)",
    ],
    correctIndex: 1,
    explanation:
      "La mola completa suele tener cariotipo diploide 46,XX, resultante de androgénesis (ambos conjuntos cromosómicos de origen paterno), sin tejido embrionario y con vellosidades coriónicas hidrópicas difusas.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 9: Mola hidatiforme" },
  },
  {
    id: "go-033",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    difficulty: "intermedio",
    stem: "¿Cuál es el tratamiento preferido para la terminación del embarazo molar, independientemente del tamaño uterino?",
    options: ["Histerectomía en todas las pacientes", "Legrado por succión (evacuación molar)", "Inducción del parto", "Histerotomía"],
    correctIndex: 1,
    explanation:
      "El legrado por succión es el tratamiento preferido para la evacuación molar en la mayoría de las pacientes; la inducción del parto o la histerotomía rara vez se utilizan porque aumentan el riesgo de enfermedad trofoblástica persistente.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 9: Mola hidatiforme" },
  },
  {
    id: "go-034",
    topicId: "gineco-obstetricia",
    subtopic: "Hemorragia obstétrica",
    difficulty: "intermedio",
    stem: "¿Cuál es la tríada clínica clásica del desprendimiento prematuro de placenta normoinserta?",
    options: [
      "Sangrado indoloro, hipotensión, taquicardia",
      "Dolor abdominal súbito, sangrado vaginal, hipertonía o sensibilidad uterina",
      "Fiebre, sangrado profuso, leucocitosis",
      "Sangrado poscoital, dispareunia, flujo vaginal",
    ],
    correctIndex: 1,
    explanation:
      "La mayoría de las mujeres con desprendimiento de placenta presentan dolor abdominal repentino, sangrado vaginal y sensibilidad/hipertonía uterina, aunque el sangrado externo puede estar ausente si la hemorragia es oculta.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 10: Desprendimiento de placenta" },
  },
  {
    id: "go-035",
    topicId: "gineco-obstetricia",
    subtopic: "Hemorragia obstétrica",
    difficulty: "avanzado",
    stem: "¿Cuál de los siguientes factores confiere el mayor riesgo relativo de desprendimiento de placenta?",
    options: ["Tabaquismo", "Desprendimiento de placenta previo (riesgo relativo 10-188)", "Hidramnios", "Gestación multifetal"],
    correctIndex: 1,
    explanation:
      "El antecedente de un desprendimiento de placenta previo es el factor de riesgo con mayor riesgo relativo (10 a 188 veces) para un nuevo episodio, según el cuadro de factores predisponentes.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 10: Desprendimiento de placenta" },
  },
  {
    id: "go-036",
    topicId: "gineco-obstetricia",
    subtopic: "Hemorragia obstétrica",
    difficulty: "basico",
    stem: "¿Cuál es el signo clínico más característico de la placenta previa?",
    options: [
      "Sangrado doloroso acompañado de contracciones intensas",
      "Sangrado vaginal indoloro, descrito como 'centinela de sangre'",
      "Sangrado exclusivamente poscoital",
      "Ausencia total de sangrado hasta el parto",
    ],
    correctIndex: 1,
    explanation:
      "El evento más característico de la placenta previa es el sangrado indoloro ('centinela de sangre'), que inicia sin previo aviso, sin dolor ni contracciones, y puede cesar para luego reaparecer.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 11: Placenta previa" },
  },
  {
    id: "go-037",
    topicId: "gineco-obstetricia",
    subtopic: "Atención del parto",
    difficulty: "basico",
    stem: "¿Cuál es la vía de finalización del embarazo indicada en todas las pacientes con diagnóstico confirmado de placenta previa?",
    options: [
      "Parto vaginal espontáneo",
      "Cesárea",
      "Parto instrumentado con fórceps",
      "Depende únicamente de la preferencia materna",
    ],
    correctIndex: 1,
    explanation:
      "Todas las mujeres con placenta previa se someten a cesárea, habitualmente con incisión de laparotomía vertical si se anticipa sangrado torrencial o necesidad de histerectomía.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 11: Placenta previa" },
  },
  {
    id: "go-038",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    difficulty: "intermedio",
    stem: "¿Cuáles son los tres antihipertensivos más comúnmente empleados para tratar la hipertensión severa aguda en preeclampsia?",
    options: [
      "Captopril, enalapril y losartán",
      "Hidralazina, labetalol y nifedipino",
      "Furosemida, espironolactona e hidroclorotiazida",
      "Metildopa, amlodipino y atenolol",
    ],
    correctIndex: 1,
    explanation:
      "Hidralazina, labetalol y nifedipino son los tres antihipertensivos más comúnmente empleados para bajar la presión sistólica a ≤160 mmHg y la diastólica a ≤110 mmHg en la hipertensión severa aguda.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 12: Trastornos hipertensivos del embarazo" },
  },
  {
    id: "go-039",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    difficulty: "avanzado",
    stem: "¿Con qué nivel de magnesio en plasma se espera la pérdida de los reflejos patelares, signo temprano de alarma de toxicidad por sulfato de magnesio?",
    options: ["4 a 8 mg/dL (rango terapéutico, asintomático)", "9 a 12 mg/dL", "Mayor a 12 mg/dL", "15 a 17 mg/dL"],
    correctIndex: 1,
    explanation:
      "Los reflejos patelares desaparecen cuando el nivel de magnesio en plasma alcanza aproximadamente 10 mg/dL (rango de 9 a 12), lo que sirve como signo clínico de advertencia antes de la toxicidad respiratoria más grave.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 12: Trastornos hipertensivos del embarazo" },
  },
  {
    id: "go-040",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    difficulty: "intermedio",
    stem: "El síndrome de HELLP, complicación multisistémica del embarazo asociada a preeclampsia grave, se caracteriza por:",
    options: [
      "Hemólisis, elevación de enzimas hepáticas y trombocitopenia",
      "Hiperglucemia, edema, letargo y proteinuria",
      "Hemorragia, edema, lipotimia y letargo",
      "Hipertensión, edema, lipotimia y proteinuria",
    ],
    correctIndex: 0,
    explanation:
      "HELLP corresponde a Hemolysis, Elevated Liver enzymes, Low Platelets: hemólisis microangiopática, elevación de enzimas hepáticas y trombocitopenia, y ocurre en el 10% de los embarazos complicados con preeclampsia grave o eclampsia.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 12: Trastornos hipertensivos del embarazo" },
  },
  {
    id: "go-041",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    difficulty: "avanzado",
    stem: "Paciente con embarazo de 30 semanas y ruptura prematura de membranas confirmada, sin signos de infección ni trabajo de parto activo. ¿Cuál es el manejo más apropiado?",
    options: [
      "Parto inmediato por cesárea",
      "Manejo expectante con vigilancia, corticosteroides para maduración pulmonar y profilaxis para estreptococo del grupo B",
      "Alta domiciliaria sin seguimiento",
      "Tocólisis prolongada indefinida sin otras medidas",
    ],
    correctIndex: 1,
    explanation:
      "Entre las 24 0/7 y 33 6/7 semanas, se recomienda manejo expectante en ausencia de un estatus fetal no seguro, corioamnionitis clínica o abrupción, con corticosteroides, profilaxis antimicrobiana y para estreptococo del grupo B.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 13: Ruptura prematura de membranas ovulares" },
  },
  {
    id: "go-042",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    difficulty: "intermedio",
    stem: "¿Cuál es el único indicador clínico consistente y confiable para el diagnóstico de corioamnionitis clínica, según los criterios de Gibbs?",
    options: ["Leucocitosis materna aislada", "Fiebre materna", "Taquicardia fetal aislada", "Dolor abdominal leve"],
    correctIndex: 1,
    explanation:
      "Debido a que la leucocitosis materna no es un hallazgo consistente por sí sola, la fiebre (temperatura axilar >38°C, o >39°C acompañada de 2 o más criterios adicionales) es el único indicador confiable para el diagnóstico de corioamnionitis clínica.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 13: Ruptura prematura de membranas ovulares" },
  },
  {
    id: "go-043",
    topicId: "gineco-obstetricia",
    subtopic: "Fisiología del ciclo menstrual",
    difficulty: "intermedio",
    stem: "¿Cuál hormona es directamente responsable de desencadenar la ovulación?",
    options: [
      "FSH basal",
      "El valor máximo (pico) de LH a mitad del ciclo",
      "Progesterona de la fase folicular",
      "Estradiol basal de la fase folicular temprana",
    ],
    correctIndex: 1,
    explanation:
      "El valor máximo hipofisario de secreción de LH, generado por retroalimentación positiva tras la estimulación estrogénica sostenida, es la causa directa de que se produzca la ovulación entre 24 y 36 horas después.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 14: Ciclo menstrual" },
  },
  {
    id: "go-044",
    topicId: "gineco-obstetricia",
    subtopic: "Fisiología del ciclo menstrual",
    difficulty: "basico",
    stem: "Durante la fase lútea del ciclo menstrual, ¿cuál es la principal hormona secretada por el cuerpo lúteo?",
    options: ["FSH", "Progesterona", "LH", "Inhibina B"],
    correctIndex: 1,
    explanation:
      "Tras la ovulación, el cuerpo lúteo se convierte en el regulador principal de la fase lútea, secretando progesterona (además de estrógenos e inhibina A) para mantener el endometrio en fase secretora.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 14: Ciclo menstrual" },
  },
  {
    id: "go-045",
    topicId: "gineco-obstetricia",
    subtopic: "Menopausia",
    difficulty: "basico",
    stem: "¿Cómo se define clínicamente la menopausia?",
    options: [
      "El cese de la menstruación por 3 meses consecutivos",
      "El cese permanente de la menstruación, confirmado retrospectivamente por 12 meses de amenorrea",
      "La elevación de FSH sin cambio en el patrón menstrual",
      "Cualquier mujer mayor de 45 años",
    ],
    correctIndex: 1,
    explanation:
      "La menopausia se define como el momento de la última menstruación, confirmado por 12 meses consecutivos de amenorrea; suele aparecer aproximadamente a los 51 años de edad.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 15: Menopausia" },
  },
  {
    id: "go-046",
    topicId: "gineco-obstetricia",
    subtopic: "Menopausia",
    difficulty: "intermedio",
    stem: "¿Cuál es el tratamiento más eficaz para los síntomas vasomotores (sofocos) de la menopausia?",
    options: ["Ejercicio aeróbico exclusivo", "Estrógenos sistémicos", "Complementos con isoflavonas", "Acupuntura"],
    correctIndex: 1,
    explanation:
      "El tratamiento con estrógenos sistémicos es el más efectivo para los síntomas vasomotores y actualmente es el único aprobado por la FDA con esta indicación específica.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 15: Menopausia" },
  },
  {
    id: "go-047",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    difficulty: "basico",
    stem: "Mujer con vaginitis provocada por Trichomonas vaginalis, con secreción profusa, purulenta y maloliente. ¿Cuál es el tratamiento de elección?",
    options: [
      "Fluconazol en dosis única",
      "Metronidazol, tratando también a la pareja sexual",
      "Clindamicina intravaginal exclusiva",
      "Aciclovir oral",
    ],
    correctIndex: 1,
    explanation:
      "El metronidazol es el fármaco de elección para la vaginitis por tricomonas (índice de curación de 95%), y debido a su transmisión sexual, debe tratarse también al compañero sexual.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 16: Infecciones urogenitales y ETS" },
  },
  {
    id: "go-048",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    difficulty: "intermedio",
    stem: "Paciente con úlcera genital indolora, mínimamente sensible, indurada, con borde y base suaves, sin adenopatías inguinales dolorosas. ¿Cuál es el diagnóstico más probable?",
    options: ["Chancroide", "Sífilis primaria", "Herpes genital", "Linfogranuloma venéreo"],
    correctIndex: 1,
    explanation:
      "La úlcera de la sífilis primaria (chancro) es característicamente indolora, indurada, con borde y base suaves, y sin adenopatías inguinales dolorosas, a diferencia del chancroide (úlceras dolorosas con adenopatía dolorosa).",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 16: Infecciones urogenitales y ETS" },
  },
  {
    id: "go-049",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    difficulty: "avanzado",
    stem: "¿Cuál es el esquema recomendado para el tratamiento ambulatorio de la enfermedad inflamatoria pélvica leve a moderada?",
    options: [
      "Penicilina G benzatínica en dosis única",
      "Cefoxitina o ceftriaxona intramuscular más doxiciclina oral",
      "Azitromicina en monodosis exclusivamente",
      "Fluconazol oral",
    ],
    correctIndex: 1,
    explanation:
      "Una pauta ambulatoria con cefoxitina (2 g IM con probenecid) o ceftriaxona (250 mg IM) más doxiciclina oral por 14 días es tan efectiva como el tratamiento parenteral hospitalario para la EIP leve a moderada.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 16: Infecciones urogenitales y ETS" },
  },
  {
    id: "go-050",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    difficulty: "intermedio",
    stem: "Mujer de 45 años con sangrado uterino anormal crónico. ¿Cuál es la causa estructural más frecuente de la expulsión anormal de sangre uterina?",
    options: ["Pólipos endocervicales", "Leiomiomas uterinos", "Adenomiosis", "Malformación arteriovenosa"],
    correctIndex: 1,
    explanation:
      "Las anormalidades estructurales son causas frecuentes de expulsión anormal de sangre, y de ellas, los leiomiomas son las más comunes, con una trascendencia clínica muy importante en ginecología.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 17: Hemorragia uterina anormal" },
  },
  {
    id: "go-051",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    difficulty: "basico",
    stem: "¿Cuál es la definición objetiva de menorragia?",
    options: [
      "Sangrado intermenstrual de cualquier volumen",
      "Menstruación que dura más de 7 días o cuyo volumen supera los 80 mL de sangre expulsada",
      "Cualquier episodio de sangrado poscoital",
      "Intervalos intercíclicos mayores a 35 días",
    ],
    correctIndex: 1,
    explanation:
      "Se conoce como menorragia a la menstruación cíclica duradera o profusa: en el plano objetivo, que dure siete días o más, o que rebase los 80 mL de sangre expulsada.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 17: Hemorragia uterina anormal" },
  },
  {
    id: "go-052",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    difficulty: "avanzado",
    stem: "Según el sistema Bethesda, una citología cervical con lesión intraepitelial escamosa de alto grado (HSIL) requiere:",
    options: [
      "Repetir la citología en 12 meses",
      "Colposcopia con biopsia dirigida",
      "Observación sin estudios adicionales",
      "Tratamiento antibiótico empírico",
    ],
    correctIndex: 1,
    explanation:
      "Cualquier mujer con una citología sugestiva de HSIL debería realizarse una colposcopia con biopsia dirigida y, tras la biopsia, un tratamiento por ablación y destrucción de toda la zona de transformación.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 18: Detección del cáncer de cérvix" },
  },
  {
    id: "go-053",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    difficulty: "basico",
    stem: "¿A qué edad recomienda la American Cancer Society iniciar la detección del cáncer cervicouterino mediante citología?",
    options: [
      "15 años",
      "21 años, o en los primeros 3 años después de iniciadas las relaciones sexuales",
      "30 años",
      "40 años",
    ],
    correctIndex: 1,
    explanation:
      "Las recomendaciones de la ACS establecen que la detección mediante citología debe empezar a los 21 años, o en los primeros 3 años después de iniciadas las relaciones sexuales, y puede acabar a los 65 años con resultados negativos previos.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 18: Detección del cáncer de cérvix" },
  },
  {
    id: "go-054",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    difficulty: "basico",
    stem: "¿Cuál es la localización más frecuente del cáncer de mama?",
    options: ["Cuadrante inferior interno", "Cuadrante superior externo", "Región retroareolar", "Cola axilar exclusivamente"],
    correctIndex: 1,
    explanation:
      "La localización más frecuente del cáncer de mama es el cuadrante superior externo, donde en proporción hay más tejido mamario.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 19: Detección del cáncer de mama" },
  },
  {
    id: "go-055",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    difficulty: "basico",
    stem: "¿A qué edad se recomienda por lo general iniciar la mamografía anual de tamizaje en mujeres de riesgo promedio?",
    options: ["25 años", "30 años", "40 años", "50 años"],
    correctIndex: 2,
    explanation:
      "Por lo general se recomienda que todas las mujeres se realicen una mamografía anual a partir de los 40 años, junto con una exploración clínica de mama al menos cada 3 años.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 19: Detección del cáncer de mama" },
  },
  {
    id: "go-056",
    topicId: "gineco-obstetricia",
    subtopic: "Fisiología del embarazo",
    difficulty: "avanzado",
    stem: "¿Cuál valor de creatinina sérica en una gestante sugiere una enfermedad renal subyacente y amerita mayor evaluación?",
    options: ["0.5 mg/dL", "0.7 mg/dL", "0.9 mg/dL o más", "0.3 mg/dL"],
    correctIndex: 2,
    explanation:
      "La creatinina sérica disminuye durante el embarazo normal (media de 0.5-0.7 mg/dL) por el aumento de la filtración glomerular; valores de 0.9 mg/dL o más sugieren enfermedad renal subyacente.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 2: Fisiología materna" },
  },
  {
    id: "go-057",
    topicId: "gineco-obstetricia",
    subtopic: "Puerperio",
    difficulty: "avanzado",
    stem: "Puérpera con necrosis hipofisaria extensa secundaria a hemorragia obstétrica masiva, que presenta agalactia (incapacidad para lactar). ¿Cómo se denomina este síndrome?",
    options: ["Síndrome de Asherman", "Síndrome de Sheehan", "Síndrome de HELLP", "Síndrome de Turner"],
    correctIndex: 1,
    explanation:
      "El síndrome de Sheehan es la necrosis hipofisaria extensa causada por hipoperfusión posparto grave; la prolactina es esencial para la lactancia, y las mujeres con este síndrome no lactan.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 6: Puerperio" },
  },
  {
    id: "go-058",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    difficulty: "avanzado",
    stem: "Tras la evacuación de una mola hidatiforme completa, ¿cómo se realiza la vigilancia posevacuación?",
    options: [
      "No se requiere seguimiento si la paciente está asintomática",
      "Medición seriada de β-hCG cada 1 a 2 semanas hasta ser indetectable, luego mensual varios meses, con anticoncepción efectiva durante el seguimiento",
      "Una sola medición de β-hCG a las 6 semanas",
      "Histerectomía sistemática en todas las pacientes",
    ],
    correctIndex: 1,
    explanation:
      "Se debe continuar la vigilancia bioquímica mediante medición en serie de β-hCG (cada 1-2 semanas hasta ser indetectable, luego mensual por varios meses) para detectar neoplasia trofoblástica persistente, con anticoncepción efectiva durante ese período.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 9: Mola hidatiforme" },
  },
  {
    id: "go-059",
    topicId: "gineco-obstetricia",
    subtopic: "Hemorragia obstétrica",
    difficulty: "avanzado",
    stem: "Se identifican vasos fetales que atraviesan las membranas y se presentan directamente sobre el orificio cervical interno, sin protección de la placenta o el cordón. ¿Cómo se denomina este hallazgo?",
    options: ["Placenta previa marginal", "Vasa previa", "Placenta acreta", "Inserción velamentosa sin riesgo"],
    correctIndex: 1,
    explanation:
      "La vasa previa describe vasos fetales que atraviesan las membranas y se presentan en el orificio cervical, con alto riesgo de exanguinación fetal si se rompen las membranas o inician el trabajo de parto.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 11: Placenta previa" },
  },
  {
    id: "go-060",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    difficulty: "intermedio",
    stem: "¿Cuáles son las cuatro categorías clínicas en que se clasifica la enfermedad hipertensiva del embarazo?",
    options: [
      "Hipertensión gestacional, hipertensión crónica, preeclampsia sobreagregada a hipertensión crónica, y síndrome de preeclampsia-eclampsia",
      "Hipertensión leve, moderada, grave y crítica",
      "Preeclampsia temprana, tardía, atípica y recurrente",
      "Hipertensión primaria, secundaria, terciaria y refractaria",
    ],
    correctIndex: 0,
    explanation:
      "Se describen cuatro tipos de enfermedad hipertensiva del embarazo: hipertensión gestacional, hipertensión crónica de cualquier etiología, preeclampsia sobreagregada a hipertensión crónica, y síndrome de preeclampsia y eclampsia.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 12: Trastornos hipertensivos del embarazo" },
  },
  {
    id: "go-061",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    difficulty: "avanzado",
    stem: "Gestante de 28 semanas con RPMO pretérmino confirmada, sin trabajo de parto. Según el esquema antimicrobiano recomendado, ¿qué combinación se administra para prolongar la latencia?",
    options: [
      "Amoxicilina/ácido clavulánico exclusivamente",
      "Ampicilina IV más eritromicina IV, seguidas de amoxicilina y eritromicina orales",
      "Ciprofloxacino oral por 5 días",
      "Penicilina G benzatínica en dosis única",
    ],
    correctIndex: 1,
    explanation:
      "El régimen recomendado es ampicilina 2 g IV + eritromicina 250 mg cada 6 horas por 48 horas, seguido de amoxicilina oral + eritromicina oral cada 8 horas por 5 días, en pacientes con RPMO <34 semanas.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 13: Ruptura prematura de membranas ovulares" },
  },
  {
    id: "go-062",
    topicId: "gineco-obstetricia",
    subtopic: "Menopausia",
    difficulty: "intermedio",
    stem: "En la absorciometría dual de rayos X (densitometría ósea), ¿qué grado T se considera diagnóstico de osteoporosis?",
    options: ["Por encima de -1", "Entre -1 y -2.5 (osteopenia)", "Menor de -2.5", "Cualquier valor negativo"],
    correctIndex: 2,
    explanation:
      "Un grado T por encima de -1 se considera normal, entre -1 y -2.5 denota osteopenia, y un grado T menor de -2.5 indica osteoporosis.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 15: Menopausia" },
  },
  {
    id: "go-063",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    difficulty: "intermedio",
    stem: "Mujer con 4 episodios de candidiasis vulvovaginal en el último año. ¿Cómo se clasifica esta condición y cuál es su manejo de mantenimiento?",
    options: [
      "Candidiasis vulvovaginal no complicada; azol tópico de 3 días",
      "Candidiasis vulvovaginal recurrente; remisión con fluconazol y dosis supresora semanal por 6 meses",
      "Vaginitis atrófica; estrógenos tópicos",
      "Vaginosis bacteriana; metronidazol oral",
    ],
    correctIndex: 1,
    explanation:
      "La candidiasis vulvovaginal recurrente se define como 4 o más episodios en 1 año; se trata con fluconazol (150 mg cada 3 días, 3 dosis) seguido de una dosis supresora de mantenimiento (150 mg semanales por 6 meses).",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 16: Infecciones urogenitales y ETS" },
  },
  {
    id: "go-064",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    difficulty: "intermedio",
    stem: "El American College of Obstetricians and Gynecologists recomienda la valoración endometrial (biopsia) en toda mujer con expulsión anormal de sangre uterina cuando:",
    options: [
      "Tiene menos de 25 años",
      "Tiene más de 35 años, o es más joven con sospecha de hemorragia anovulatoria refractaria al tratamiento médico",
      "Solo si presenta dolor pélvico intenso",
      "Únicamente si desea un método anticonceptivo hormonal",
    ],
    correctIndex: 1,
    explanation:
      "El ACOG (2000) recomienda la valoración endometrial en toda mujer mayor de 35 años con expulsión anormal de sangre, o en mujeres más jóvenes en quienes se sospecha hemorragia uterina anovulatoria refractaria al tratamiento médico.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 17: Hemorragia uterina anormal" },
  },
  {
    id: "go-065",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    difficulty: "avanzado",
    stem: "¿Cuáles son las mutaciones genéticas hereditarias más frecuentemente asociadas al cáncer de mama?",
    options: ["TP53 y RB1", "BRCA1 (17q21) y BRCA2 (13q12-13)", "APC y MLH1", "RET y VHL"],
    correctIndex: 1,
    explanation:
      "Las mutaciones más frecuentes en el cáncer de mama hereditario son las deleciones genéticas BRCA1 (cromosoma 17q21) y BRCA2 (cromosoma 13q12-13), con un riesgo a lo largo de la vida que oscila entre 35% y 85%.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 19: Detección del cáncer de mama" },
  },
  {
    id: "go-066",
    topicId: "gineco-obstetricia",
    subtopic: "Atención del parto",
    difficulty: "avanzado",
    stem: "En una nulípara, la mayoría de los comités de consenso recomiendan permitir el pujo activo hasta un límite antes de diagnosticar detención del parto en la segunda etapa. ¿Cuál es ese límite mínimo recomendado?",
    options: ["Al menos 1 hora de pujo", "Al menos 3 horas de pujo (2 horas si no hay analgesia regional)", "10 minutos de pujo", "Sin límite, siempre que la madre lo tolere"],
    correctIndex: 1,
    explanation:
      "El Comité de consenso recomienda permitir que una nulípara empuje durante al menos 3 horas (2 horas sin analgesia regional) antes de diagnosticar detención del parto en la segunda etapa, siempre que el estado materno y fetal sean tranquilizadores.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 5: Distocias" },
  },
];
