import type { QuizQuestion } from "@/types/content";

export const medicinaInternaQuestions: QuizQuestion[] = [
  {
    id: "mi-001",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "intermedio",
    stem: "Hombre de 58 años llega a emergencias con dolor torácico opresivo de 40 minutos, diaforesis y náuseas. El ECG muestra elevación del ST de 3 mm en DII, DIII y aVF. ¿Cuál es la conducta inmediata más apropiada?",
    options: [
      "Iniciar aspirina, doble antiagregación y trasladar para angioplastia primaria (o fibrinólisis si no hay PCI disponible en <120 min)",
      "Solicitar troponina seriada cada 6 horas antes de decidir tratamiento",
      "Iniciar betabloqueador intravenoso en bolo y dar de alta si el dolor cede",
      "Realizar prueba de esfuerzo para confirmar isquemia antes de tratar",
    ],
    correctIndex: 0,
    explanation:
      "Un IAMCEST inferior (elevación de ST en DII, DIII, aVF) es una emergencia tiempo-dependiente: requiere reperfusión inmediata (ICP primaria idealmente <120 min desde el primer contacto médico, o fibrinólisis si no es posible) junto con doble antiagregación plaquetaria y anticoagulación. No se espera la troponina para decidir reperfusión.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Capítulo de Síndrome Coronario Agudo" },
  },
  {
    id: "mi-002",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    difficulty: "intermedio",
    stem: "Paciente de 70 años con neumonía adquirida en la comunidad. Se encuentra confuso, FR 32/min, PA 88/58 mmHg y BUN elevado. Según CURB-65, ¿cuál es la conducta más adecuada?",
    options: [
      "Manejo ambulatorio con amoxicilina oral",
      "Hospitalización, con consideración de manejo en UCI por alto riesgo (CURB-65 alto)",
      "Alta con control ambulatorio en 48 horas",
      "Observación en urgencias por 6 horas y alta si mejora el dolor pleurítico",
    ],
    correctIndex: 1,
    explanation:
      "Con confusión, FR ≥30, presión sistólica <90 y BUN elevado, el paciente acumula ≥3 puntos en CURB-65, lo que indica alto riesgo de mortalidad y necesidad de hospitalización, valorando ingreso a UCI.",
    source: { label: "BTS/ATS Guidelines — Escala CURB-65 para neumonía adquirida en la comunidad" },
  },
  {
    id: "mi-003",
    topicId: "medicina-interna",
    subtopic: "Endocrinología",
    difficulty: "basico",
    stem: "¿Cuál de los siguientes valores confirma el diagnóstico de diabetes mellitus tipo 2 en un paciente asintomático?",
    options: [
      "Glucemia en ayunas de 110 mg/dL en una sola determinación",
      "Glucemia en ayunas ≥126 mg/dL confirmada en dos ocasiones",
      "Glucemia posprandial de 130 mg/dL",
      "HbA1c de 5.8%",
    ],
    correctIndex: 1,
    explanation:
      "El diagnóstico de diabetes en un paciente asintomático requiere confirmar con una segunda prueba: glucemia en ayunas ≥126 mg/dL, glucemia a las 2h en PTOG ≥200 mg/dL, HbA1c ≥6.5%, o glucemia al azar ≥200 mg/dL con síntomas clásicos.",
    source: { label: "American Diabetes Association — Standards of Care in Diabetes 2024" },
  },
  {
    id: "mi-004",
    topicId: "medicina-interna",
    subtopic: "Nefrología",
    difficulty: "intermedio",
    stem: "Paciente con TFG estimada de 38 mL/min/1.73m² sostenida por más de 3 meses, sin albuminuria significativa. ¿En qué estadio de enfermedad renal crónica (KDIGO) se clasifica?",
    options: ["G2", "G3a", "G3b", "G4"],
    correctIndex: 2,
    explanation:
      "KDIGO clasifica la TFG en: G1 ≥90, G2 60-89, G3a 45-59, G3b 30-44, G4 15-29, G5 <15 mL/min/1.73m². Una TFG de 38 corresponde a G3b.",
    source: { label: "KDIGO Clinical Practice Guideline for CKD Evaluation and Management, 2024" },
  },
  {
    id: "mi-005",
    topicId: "medicina-interna",
    subtopic: "Infectología",
    difficulty: "intermedio",
    stem: "Paciente con foco infeccioso claro que presenta alteración del estado mental, frecuencia respiratoria de 24/min y presión arterial sistólica de 95 mmHg. ¿Qué puntaje qSOFA tiene y qué implica?",
    options: [
      "qSOFA 1, bajo riesgo",
      "qSOFA 2, riesgo aumentado de mala evolución por sepsis",
      "qSOFA 3, requiere solo observación ambulatoria",
      "El qSOFA no aplica hasta tener lactato sérico",
    ],
    correctIndex: 1,
    explanation:
      "qSOFA asigna 1 punto por: alteración del estado mental (Glasgow <15), FR ≥22/min y PAS ≤100 mmHg. Con alteración mental y taquipnea el paciente suma 2 puntos, lo que identifica riesgo aumentado de mortalidad hospitalaria por sepsis y obliga a buscar disfunción orgánica (SOFA completo, lactato).",
    source: { label: "Surviving Sepsis Campaign — International Guidelines 2021" },
  },
  {
    id: "mi-006",
    topicId: "medicina-interna",
    subtopic: "Hematología",
    difficulty: "basico",
    stem: "Mujer de 34 años con fatiga, palidez, VCM bajo, ferritina baja y aumento de la capacidad de fijación de hierro (TIBC). ¿Cuál es el diagnóstico más probable?",
    options: [
      "Anemia de enfermedad crónica",
      "Anemia ferropénica",
      "Anemia megaloblástica por déficit de B12",
      "Talasemia menor",
    ],
    correctIndex: 1,
    explanation:
      "Anemia microcítica con ferritina baja y TIBC/transferrina elevada es característica de anemia ferropénica (en enfermedad crónica la ferritina suele estar normal o alta y la TIBC baja).",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Anemias microcíticas" },
  },
  {
    id: "mi-007",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "intermedio",
    stem: "Paciente con disnea de esfuerzo, ortopnea, edema de miembros inferiores y NT-proBNP muy elevado. ¿Qué clase funcional NYHA corresponde a un paciente con disnea ante actividad física ordinaria (caminar en llano) pero sin síntomas en reposo?",
    options: ["NYHA I", "NYHA II", "NYHA III", "NYHA IV"],
    correctIndex: 1,
    explanation:
      "NYHA I: sin limitación. NYHA II: limitación leve, síntomas con actividad ordinaria. NYHA III: limitación marcada, síntomas con actividad menor a la ordinaria. NYHA IV: síntomas en reposo.",
    source: { label: "New York Heart Association — Clasificación funcional de insuficiencia cardíaca" },
  },
  {
    id: "mi-008",
    topicId: "medicina-interna",
    subtopic: "Endocrinología",
    difficulty: "basico",
    stem: "Mujer de 45 años con fatiga, intolerancia al frío, piel seca y estreñimiento. TSH 12 mUI/L (elevada) y T4 libre baja. ¿Cuál es el diagnóstico?",
    options: [
      "Hipertiroidismo primario",
      "Hipotiroidismo primario",
      "Hipotiroidismo central (hipofisario)",
      "Síndrome del eutiroideo enfermo",
    ],
    correctIndex: 1,
    explanation:
      "TSH elevada con T4 libre baja confirma hipotiroidismo primario (falla tiroidea); en el hipotiroidismo central la TSH típicamente está baja o inapropiadamente normal.",
    source: { label: "American Thyroid Association — Guidelines for Hypothyroidism" },
  },
  {
    id: "mi-009",
    topicId: "medicina-interna",
    subtopic: "Gastroenterología",
    difficulty: "avanzado",
    stem: "Paciente cirrótico con hematemesis masiva. Además de la reanimación con líquidos y hemoderivados, ¿cuál es el manejo farmacológico inicial más apropiado mientras se organiza la endoscopía?",
    options: [
      "Omeprazol intravenoso únicamente",
      "Octreótide (o terlipresina) intravenoso más antibiótico profiláctico",
      "Propranolol intravenoso en bolo",
      "Ácido tranexámico intravenoso como única medida",
    ],
    correctIndex: 1,
    explanation:
      "En sangrado variceal se recomienda iniciar un vasoconstrictor esplácnico (octreótide o terlipresina) y profilaxis antibiótica (ej. ceftriaxona) desde el ingreso, además de la endoscopía terapéutica temprana (idealmente <12h).",
    source: { label: "AASLD Practice Guidance — Portal Hypertensive Bleeding in Cirrhosis, 2023" },
  },
  {
    id: "mi-010",
    topicId: "medicina-interna",
    subtopic: "Reumatología",
    difficulty: "intermedio",
    stem: "Mujer de 28 años con artralgias simétricas de manos, eritema malar que respeta surcos nasogenianos, fotosensibilidad y ANA positivo a título alto. ¿Cuál es el diagnóstico más probable?",
    options: [
      "Artritis reumatoide",
      "Lupus eritematoso sistémico",
      "Dermatomiositis",
      "Fibromialgia",
    ],
    correctIndex: 1,
    explanation:
      "El eritema malar que respeta pliegues nasolabiales, fotosensibilidad, artralgias y ANA positivo son criterios clásicos sugestivos de lupus eritematoso sistémico.",
    source: { label: "EULAR/ACR Classification Criteria for Systemic Lupus Erythematosus, 2019" },
  },
  {
    id: "mi-011",
    topicId: "medicina-interna",
    subtopic: "Infectología",
    difficulty: "basico",
    stem: "¿Cuál es la estrategia diagnóstica actual recomendada para confirmar la infección por VIH en un paciente con una prueba de tamizaje inicial positiva?",
    options: [
      "Repetir únicamente el mismo inmunoensayo de tamizaje",
      "Inmunoensayo de 4.ª generación (antígeno p24 + anticuerpos) seguido de un inmunoensayo diferencial de confirmación",
      "Cultivo viral directo",
      "Biopsia de ganglio linfático",
    ],
    correctIndex: 1,
    explanation:
      "El algoritmo actual inicia con un inmunoensayo combinado de 4.ª generación (detecta antígeno p24 y anticuerpos), y ante un resultado positivo se confirma con un inmunoensayo diferencial VIH-1/VIH-2; el Western blot ya no es el estándar de confirmación.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 1: VIH" },
  },
  {
    id: "mi-012",
    topicId: "medicina-interna",
    subtopic: "Infectología",
    difficulty: "intermedio",
    stem: "Paciente recién diagnosticado con VIH y CD4 de 550 células/µL, asintomático. ¿Cuándo debe iniciarse la terapia antirretroviral (TARV)?",
    options: [
      "Solo cuando el CD4 caiga por debajo de 350",
      "De inmediato, independientemente del conteo de CD4",
      "Únicamente si desarrolla una infección oportunista",
      "Se debe esperar a que el paciente presente síntomas",
    ],
    correctIndex: 1,
    explanation:
      "Las guías actuales recomiendan iniciar TARV en todas las personas con VIH tan pronto como sea posible tras el diagnóstico, independientemente del conteo de CD4, para reducir la morbimortalidad y la transmisión.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 1: VIH" },
  },
  {
    id: "mi-013",
    topicId: "medicina-interna",
    subtopic: "Infectología",
    difficulty: "avanzado",
    stem: "Paciente con VIH y conteo de CD4 de 80 células/µL. ¿Contra qué infección oportunista está indicada la profilaxis primaria a este nivel de CD4, además de la profilaxis para Pneumocystis jirovecii?",
    options: [
      "Toxoplasma gondii (con TMP-SMX)",
      "Complejo Mycobacterium avium (MAC), que se inicia por debajo de 50 células/µL",
      "Histoplasma capsulatum en todos los pacientes",
      "Ninguna profilaxis adicional está indicada",
    ],
    correctIndex: 0,
    explanation:
      "La profilaxis para P. jirovecii se inicia con CD4 <200 y la de toxoplasmosis (también con TMP-SMX) con CD4 <100; con CD4 de 80 ambas están indicadas. La profilaxis para MAC se reserva para CD4 <50 células/µL.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 1: VIH" },
  },
  {
    id: "mi-014",
    topicId: "medicina-interna",
    subtopic: "Infectología",
    difficulty: "avanzado",
    stem: "Paciente con VIH avanzado que, semanas después de iniciar TARV, presenta empeoramiento paradójico de una infección oportunista preexistente pese a la mejoría inmunológica (CD4 en ascenso, carga viral en descenso). ¿Cómo se denomina este cuadro?",
    options: [
      "Fracaso virológico",
      "Síndrome inflamatorio de reconstitución inmune (IRIS)",
      "Resistencia primaria a antirretrovirales",
      "Toxicidad medicamentosa directa",
    ],
    correctIndex: 1,
    explanation:
      "El IRIS ocurre cuando la recuperación inmune tras iniciar TARV desencadena una respuesta inflamatoria exagerada contra antígenos de infecciones oportunistas preexistentes (tratadas o subclínicas), empeorando paradójicamente el cuadro clínico.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 1: VIH" },
  },
  {
    id: "mi-015",
    topicId: "medicina-interna",
    subtopic: "Infectología",
    difficulty: "intermedio",
    stem: "¿Cuál neoplasia definitoria de sida está causada por el virus del herpes humano tipo 8 (HHV-8) y se manifiesta típicamente con lesiones cutáneas violáceas?",
    options: ["Linfoma no Hodgkin", "Sarcoma de Kaposi", "Cáncer cervical invasivo", "Carcinoma hepatocelular"],
    correctIndex: 1,
    explanation:
      "El sarcoma de Kaposi es una neoplasia vascular causada por HHV-8, considerada definitoria de sida, que se presenta característicamente con placas o nódulos cutáneos violáceos, aunque también puede afectar mucosas y vísceras.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 1: VIH" },
  },
  {
    id: "mi-016",
    topicId: "medicina-interna",
    subtopic: "Endocrinología",
    difficulty: "avanzado",
    stem: "Paciente con cetoacidosis diabética. Además de la reposición de líquidos y potasio, ¿cuál es el esquema inicial de insulina recomendado?",
    options: [
      "Insulina subcutánea de acción prolongada únicamente",
      "Bolo IV de 0.1 U/kg seguido de infusión continua a 0.1 U/kg/h",
      "Insulina oral en combinación con metformina",
      "Suspender toda insulina hasta corregir la acidosis",
    ],
    correctIndex: 1,
    explanation:
      "El tratamiento estándar de la CAD incluye insulina IV en bolo de 0.1 U/kg seguida de goteo continuo a 0.1 U/kg/h; si la glucemia no disminuye, se duplica la velocidad de infusión, y se agrega glucosa a la solución cuando la glucemia baja a 250 mg/dL.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 3: Diabetes mellitus — control y tratamiento" },
  },
  {
    id: "mi-017",
    topicId: "medicina-interna",
    subtopic: "Endocrinología",
    difficulty: "intermedio",
    stem: "¿Cuáles son las metas glucémicas recomendadas para un paciente diabético hospitalizado y clínicamente grave?",
    options: [
      "Glucemia de 140 a 180 mg/100 mL",
      "Glucemia estrictamente normal, <100 mg/100 mL",
      "Glucemia libre, sin meta específica",
      "Glucemia >250 mg/100 mL para evitar hipoglucemia",
    ],
    correctIndex: 0,
    explanation:
      "En pacientes hospitalizados graves se recomienda una meta de glucemia de 140-180 mg/100 mL, ya que el control muy estricto de la glucemia en enfermedades agudas parece agravar los resultados y aumentar la hipoglucemia.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 3: Diabetes mellitus — control y tratamiento" },
  },
  {
    id: "mi-018",
    topicId: "medicina-interna",
    subtopic: "Endocrinología",
    difficulty: "avanzado",
    stem: "¿Cuál es la principal diferencia en el manejo con líquidos IV entre la cetoacidosis diabética (CAD) y el estado hiperosmolar hiperglucémico (HHS)?",
    options: [
      "En HHS no se administran líquidos IV",
      "Las pérdidas de líquidos y la deshidratación son más intensas en HHS, por la duración más prolongada del cuadro",
      "En CAD nunca se repone potasio",
      "El HHS siempre requiere diálisis de urgencia",
    ],
    correctIndex: 1,
    explanation:
      "Aunque el tratamiento de CAD y HHS comparte elementos, en el HHS las pérdidas de líquidos y la deshidratación son más intensas debido a la duración más prolongada del cuadro clínico, e incluso con tratamiento adecuado la mortalidad es más elevada que en la CAD.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 3: Diabetes mellitus — control y tratamiento" },
  },
  {
    id: "mi-019",
    topicId: "medicina-interna",
    subtopic: "Endocrinología",
    difficulty: "intermedio",
    stem: "Paciente con diabetes mellitus tipo 2 y neuropatía diabética distal simétrica dolorosa, refractaria a medidas generales. ¿Cuáles son opciones farmacológicas de primera línea?",
    options: [
      "Ibuprofeno en dosis altas",
      "Duloxetina, gabapentina o pregabalina",
      "Insulina intravenosa en bolo",
      "Antibióticos de amplio espectro",
    ],
    correctIndex: 1,
    explanation:
      "Para la neuropatía diabética dolorosa crónica y de difícil manejo, las opciones incluyen duloxetina, amitriptilina, gabapentina, valproato, pregabalina u opioides, según respuesta y tolerancia.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 4: Diabetes mellitus — complicaciones" },
  },
  {
    id: "mi-020",
    topicId: "medicina-interna",
    subtopic: "Endocrinología",
    difficulty: "avanzado",
    stem: "¿Cuál es el umbral de excreción urinaria de albúmina que define la macroalbuminuria en la nefropatía diabética?",
    options: ["30 mg/24 h", "100 mg/24 h", ">300 mg/24 h", ">1,000 mg/24 h"],
    correctIndex: 2,
    explanation:
      "La albuminuria persistente se define entre 30 y 299 mg/24 h, y la macroalbuminuria cuando supera 300 mg/24 h; la monitorización con cociente albúmina/creatinina debe iniciarse desde el momento del diagnóstico en DM tipo 2.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 4: Diabetes mellitus — complicaciones" },
  },
  {
    id: "mi-021",
    topicId: "medicina-interna",
    subtopic: "Endocrinología",
    difficulty: "basico",
    stem: "¿Cuál es la causa más frecuente de amputación no traumática de miembros inferiores?",
    options: ["Enfermedad arterial periférica aislada", "Diabetes mellitus", "Traumatismo laboral", "Enfermedad venosa crónica"],
    correctIndex: 1,
    explanation:
      "La diabetes mellitus es la principal causa de amputación de miembros inferiores; entre los factores que incrementan la incidencia de úlceras e infecciones están la neuropatía, la enfermedad arterial periférica y las deformidades óseas.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 4: Diabetes mellitus — complicaciones" },
  },
  {
    id: "mi-022",
    topicId: "medicina-interna",
    subtopic: "Endocrinología",
    difficulty: "intermedio",
    stem: "Paciente diabético con retinopatía proliferativa confirmada en el examen oftalmológico. ¿Cuál es el tratamiento indicado?",
    options: [
      "Observación sin tratamiento",
      "Fotocoagulación panretiniana con láser",
      "Corticosteroides orales en dosis altas",
      "Insulina intravenosa exclusivamente",
    ],
    correctIndex: 1,
    explanation:
      "La retinopatía no proliferativa se trata con fotocoagulación profiláctica; la retinopatía proliferativa requiere fotocoagulación panretiniana con láser, y el edema macular se trata con fotocoagulación focal o terapia anti-VEGF intraocular.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 4: Diabetes mellitus — complicaciones" },
  },
  {
    id: "mi-023",
    topicId: "medicina-interna",
    subtopic: "Metabolismo",
    difficulty: "intermedio",
    stem: "Según los criterios NCEP:ATPIII (2001), ¿cuántos de los cinco componentes se requieren para diagnosticar síndrome metabólico?",
    options: ["Uno", "Dos", "Tres o más", "Los cinco simultáneamente"],
    correctIndex: 2,
    explanation:
      "Se requieren 3 o más de los siguientes: obesidad central (perímetro abdominal aumentado), hipertrigliceridemia ≥150 mg/dL, HDL bajo, presión arterial elevada, y glucosa plasmática en ayuno ≥100 mg/dL o diabetes tipo 2 diagnosticada.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 5: Síndrome metabólico" },
  },
  {
    id: "mi-024",
    topicId: "medicina-interna",
    subtopic: "Metabolismo",
    difficulty: "basico",
    stem: "En un paciente con síndrome metabólico y colesterol LDL persistentemente elevado, ¿cuál es el fármaco de primera línea?",
    options: ["Fibratos", "Estatinas", "Ácido nicotínico", "Captadores de ácidos biliares"],
    correctIndex: 1,
    explanation:
      "Las estatinas (inhibidores de la reductasa de HMG-CoA) son los fármacos de primera línea para reducir el colesterol LDL; la ezetimiba es de segunda línea y los captadores de ácidos biliares se usan con cautela por elevar los triglicéridos.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 5: Síndrome metabólico" },
  },
  {
    id: "mi-025",
    topicId: "medicina-interna",
    subtopic: "Metabolismo",
    difficulty: "intermedio",
    stem: "¿Cuál es el fármaco de elección para reducir los triglicéridos en ayuno cuando están significativamente elevados?",
    options: ["Estatinas en monoterapia", "Fibratos", "Captadores de ácidos biliares", "Orlistat"],
    correctIndex: 1,
    explanation:
      "Los fibratos son los fármacos de elección para reducir triglicéridos en ayuno, con descensos de 30-45%; su combinación con estatinas es eficaz pero eleva el riesgo de miopatía.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 5: Síndrome metabólico" },
  },
  {
    id: "mi-026",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    difficulty: "intermedio",
    stem: "Paciente con EPOC en quien la espirometría muestra FEV1/FVC <0.7 y FEV1 entre 50 y 79% del valor de referencia. Según la clasificación GOLD, ¿qué etapa corresponde?",
    options: ["I — Leve", "II — Moderada", "III — Intensa", "IV — Muy intensa"],
    correctIndex: 1,
    explanation:
      "La clasificación GOLD de intensidad de obstrucción del flujo de aire en EPOC define: I Leve (FEV1 ≥80%), II Moderada (50-79%), III Intensa (30-49%), IV Muy intensa (<30%), siempre con FEV1/FVC <0.7.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 6: Enfermedad pulmonar obstructiva crónica" },
  },
  {
    id: "mi-027",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    difficulty: "avanzado",
    stem: "¿Cuál es el único elemento terapéutico que ha demostrado reducir la mortalidad en pacientes con EPOC?",
    options: ["Broncodilatadores inhalados", "Corticosteroides sistémicos", "Oxígeno complementario", "Teofilina oral"],
    correctIndex: 2,
    explanation:
      "El oxígeno complementario, administrado en pacientes con hipoxemia crónica, es el único elemento terapéutico que ha reducido la mortalidad en pacientes con EPOC.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 6: Enfermedad pulmonar obstructiva crónica" },
  },
  {
    id: "mi-028",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    difficulty: "intermedio",
    stem: "¿Cuál es la deficiencia genética asociada al desarrollo de EPOC de tipo panacinar, incluso en personas no fumadoras?",
    options: ["Deficiencia de factor VIII", "Deficiencia de antitripsina A1", "Deficiencia de G6PD", "Deficiencia de vitamina D"],
    correctIndex: 1,
    explanation:
      "El fenotipo homocigoto PiZ de deficiencia de antitripsina A1 es la forma más frecuente de deficiencia grave y predispone al enfisema panacinar con predilección por los lóbulos inferiores, incluso en no fumadores.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 6: Enfermedad pulmonar obstructiva crónica" },
  },
  {
    id: "mi-029",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    difficulty: "basico",
    stem: "¿Cuáles son los tres síntomas más frecuentes de presentación de la EPOC?",
    options: [
      "Fiebre, escalofríos y mialgias",
      "Tos, producción de esputo y disnea con el ejercicio",
      "Dolor torácico pleurítico, hemoptisis y pérdida de peso",
      "Cianosis, síncope y palpitaciones",
    ],
    correctIndex: 1,
    explanation:
      "Los tres síntomas más frecuentes de la EPOC son tos, producción de esputo y disnea con el ejercicio, de aparición y evolución gradual, aunque muchos pacientes lo notan solo hasta una exacerbación aguda.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 6: Enfermedad pulmonar obstructiva crónica" },
  },
  {
    id: "mi-030",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    difficulty: "basico",
    stem: "¿Cuáles son los medicamentos controladores de primera línea en pacientes con asma persistente?",
    options: [
      "Antibióticos macrólidos",
      "Corticosteroides inhalados (ICS)",
      "Antihistamínicos orales",
      "Broncodilatadores de acción corta como monoterapia diaria",
    ],
    correctIndex: 1,
    explanation:
      "Los corticosteroides inhalados son de primera línea en el asma persistente: disminuyen las células inflamatorias, la hiperreactividad de las vías respiratorias y mejoran la función pulmonar, aunque requieren varios meses para la mejoría máxima.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 7: Asma bronquial" },
  },
  {
    id: "mi-031",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    difficulty: "avanzado",
    stem: "Paciente con asma grave, IgE elevada y mal control pese a corticosteroides inhalados en dosis altas más un agonista β2 de acción prolongada. ¿Qué fármaco biológico está indicado?",
    options: ["Omalizumab (anti-IgE)", "Vancomicina", "Amiodarona", "Warfarina"],
    correctIndex: 0,
    explanation:
      "El omalizumab es un anticuerpo que neutraliza la IgE circulante, reduce las exacerbaciones y mejora el control en el asma grave alérgica no controlada con tratamiento convencional, aunque tiene un costo elevado.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 7: Asma bronquial" },
  },
  {
    id: "mi-032",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    difficulty: "intermedio",
    stem: "¿Cuál es la anomalía funcional característica del asma que explica la broncoconstricción excesiva ante múltiples estímulos inhalados?",
    options: [
      "Hiperreactividad de las vías respiratorias (AHR)",
      "Fibrosis pulmonar irreversible",
      "Hipertensión pulmonar primaria",
      "Deficiencia de surfactante",
    ],
    correctIndex: 0,
    explanation:
      "La hiperreactividad de las vías respiratorias (AHR) es la anomalía funcional característica del asma: la respuesta broncoconstrictora excesiva frente a estímulos directos (histamina, metacolina) e indirectos.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 7: Asma bronquial" },
  },
  {
    id: "mi-033",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "basico",
    stem: "¿Cuáles son los dos factores determinantes principales de la presión arterial?",
    options: [
      "Volumen sanguíneo total y viscosidad",
      "Gasto cardíaco y resistencia periférica",
      "Frecuencia cardíaca y saturación de oxígeno",
      "Presión venosa central y gasto urinario",
    ],
    correctIndex: 1,
    explanation:
      "La presión arterial depende del gasto cardíaco (determinado por volumen sistólico y frecuencia cardíaca) y de la resistencia periférica (regida por cambios funcionales y anatómicos en arterias de fino calibre y arteriolas).",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 8: Hipertensión arterial" },
  },
  {
    id: "mi-034",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "intermedio",
    stem: "Un paciente tiene presión arterial de 145/95 mmHg de forma persistente. Según la clasificación clásica de presión arterial, ¿cómo se categoriza?",
    options: ["Prehipertensión", "Hipertensión en etapa 1", "Hipertensión en etapa 2", "Hipertensión sistólica aislada"],
    correctIndex: 1,
    explanation:
      "La hipertensión en etapa 1 se define por presión sistólica de 140-159 mmHg o diastólica de 90-99 mmHg; la etapa 2 corresponde a valores ≥160/≥100 mmHg.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 8: Hipertensión arterial" },
  },
  {
    id: "mi-035",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "avanzado",
    stem: "¿Qué se entiende por hipertensión resistente al tratamiento?",
    options: [
      "PA que no responde a un solo fármaco antihipertensivo",
      "PA persistentemente >140/90 mmHg pese a recibir tres o más antihipertensivos que incluyen un diurético",
      "Cualquier hipertensión en pacientes mayores de 60 años",
      "Hipertensión que solo aparece en el consultorio (bata blanca)",
    ],
    correctIndex: 1,
    explanation:
      "La hipertensión resistente al tratamiento se define como tensión persistentemente >140/90 mmHg pese a recibir tres o más antihipertensivos que incluyan un diurético; es más frecuente en mayores de 60 años.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 8: Hipertensión arterial" },
  },
  {
    id: "mi-036",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "avanzado",
    stem: "Paciente hipertenso con hipopotasemia no provocada (sin uso de diuréticos) y PA resistente al tratamiento. ¿Cuál es la causa secundaria de hipertensión más probable?",
    options: ["Feocromocitoma", "Aldosteronismo primario", "Síndrome de Cushing", "Coartación de la aorta"],
    correctIndex: 1,
    explanation:
      "En un hipertenso con hipopotasemia no provocada, la prevalencia de aldosteronismo primario fluctúa entre 40 y 50%; se evalúa con la proporción aldosterona/renina en plasma (>30:1 sugiere el diagnóstico).",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 8: Hipertensión arterial" },
  },
  {
    id: "mi-037",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "avanzado",
    stem: "Paciente con hipertensión maligna y encefalopatía hipertensiva. ¿Cuál es el objetivo inicial de reducción de la presión arterial media?",
    options: [
      "Normalizar la PA de inmediato (<120/80)",
      "Disminuir la PA media en no más de 25%, en minutos a 2 horas",
      "Esperar sin tratamiento hasta ingreso a UCI",
      "Reducir la PA sistólica a menos de 90 mmHg en la primera hora",
    ],
    correctIndex: 1,
    explanation:
      "En las urgencias hipertensivas el objetivo inicial es disminuir la PA media en no más de 25% en minutos a 2 horas, o a una presión de 160/100 a 110 mmHg, para evitar isquemia por caída brusca por debajo del límite de autorregulación cerebral.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 8: Hipertensión arterial" },
  },
  {
    id: "mi-038",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "avanzado",
    stem: "¿Cuál es la ventana de tiempo recomendada para administrar fibrinolíticos desde la presentación de un IAMCEST, en circunstancias óptimas?",
    options: ["Dentro de 30 minutos", "Dentro de 6 horas", "Dentro de 12 horas", "Dentro de 24 horas"],
    correctIndex: 0,
    explanation:
      "En circunstancias óptimas se deben administrar fibrinolíticos dentro de los 30 minutos de la presentación; la PCI primaria, si está disponible, debe iniciarse en un plazo de 120 minutos desde el primer contacto médico.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 9: Infarto agudo de miocardio con elevación del ST" },
  },
  {
    id: "mi-039",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "avanzado",
    stem: "¿Cuál de los siguientes es una contraindicación absoluta para el uso de fibrinolíticos en IAMCEST?",
    options: [
      "Uso de anticoagulantes con INR >2",
      "Antecedente de accidente cerebrovascular hemorrágico previo",
      "Cirugía menor hace 5 días",
      "Úlcera péptica activa",
    ],
    correctIndex: 1,
    explanation:
      "El antecedente de ECV hemorrágico previo, el ECV isquémico en los últimos 12 meses, la neoplasia intracraneal, la disección aórtica sospechada y la hemorragia activa interna son contraindicaciones absolutas; las otras opciones listadas son contraindicaciones relativas.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 9: Infarto agudo de miocardio con elevación del ST" },
  },
  {
    id: "mi-040",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "intermedio",
    stem: "Paciente con IAMCEST que en la exploración presenta edema agudo de pulmón. Según la clasificación de Killip, ¿en qué clase se ubica?",
    options: ["Killip I", "Killip II", "Killip III", "Killip IV"],
    correctIndex: 2,
    explanation:
      "La clasificación de Killip estima el riesgo de muerte hospitalaria: I sin signos de IC izquierda, II estertores/S3/taquipnea/ingurgitación yugular, III edema agudo de pulmón, IV choque cardiogénico con vasoconstricción periférica.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 9: Infarto agudo de miocardio con elevación del ST" },
  },
  {
    id: "mi-041",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "basico",
    stem: "¿Cuál es la principal diferencia bioquímica entre la angina inestable y el infarto de miocardio sin elevación del ST (IAMSEST)?",
    options: [
      "La angina inestable siempre eleva el segmento ST",
      "En el IAMSEST se elevan significativamente los biomarcadores cardíacos (troponinas), lo que no ocurre en la angina inestable",
      "Solo el IAMSEST causa dolor torácico",
      "La angina inestable solo ocurre en mujeres",
    ],
    correctIndex: 1,
    explanation:
      "Ambos comparten fisiopatología de síndrome coronario agudo sin elevación del ST, pero la elevación significativa de biomarcadores cardíacos (troponinas) es lo que permite diferenciar el IAMSEST de la angina inestable, donde no hay necrosis miocárdica significativa.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 10: Infarto agudo de miocardio sin elevación del ST" },
  },
  {
    id: "mi-042",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "avanzado",
    stem: "¿Para qué se utiliza el puntaje de riesgo TIMI en un paciente con síndrome coronario agudo sin elevación del ST?",
    options: [
      "Para decidir el tipo de anestesia en cirugía",
      "Para predecir la mortalidad a 14 días, el infarto nuevo o recurrente, y la necesidad urgente de revascularización",
      "Para diagnosticar hipertensión arterial",
      "Para clasificar el tipo de diabetes",
    ],
    correctIndex: 1,
    explanation:
      "El puntaje TIMI (edad >65, ≥3 factores de riesgo coronario, estenosis conocida >50%, uso de aspirina en 7 días previos, angina severa reciente, desviación del ST >0.5 mm, biomarcadores elevados) predice la mortalidad a 14 días y la necesidad de revascularización urgente.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 10: Infarto agudo de miocardio sin elevación del ST" },
  },
  {
    id: "mi-043",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "basico",
    stem: "Según la clasificación funcional de la Canadian Cardiovascular Society (CCS), un paciente cuya angina aparece al caminar dos cuadras en terreno plano o al subir más de un tramo de escaleras en circunstancias normales se clasifica como:",
    options: ["Clase I", "Clase II", "Clase III", "Clase IV"],
    correctIndex: 1,
    explanation:
      "La clase II de la CCS corresponde a una limitación leve de la actividad física habitual: angina al caminar rápido, subir escaleras después de comer, con frío, viento, estrés emocional, o en las horas después de despertar.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 11: Angina de pecho estable" },
  },
  {
    id: "mi-044",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "basico",
    stem: "¿Cuál es el tratamiento de elección para el alivio agudo de un episodio de angina de pecho?",
    options: ["Nitroglicerina sublingual", "Warfarina oral", "Furosemida IV", "Amiodarona oral"],
    correctIndex: 0,
    explanation:
      "La nitroglicerina sublingual (0.3-0.6 mg) alivia rápidamente la angina mediante venodilatación sistémica, dilatación de vasos epicárdicos y mayor flujo colateral; el paciente puede repetir la dosis y tomarla profilácticamente antes de esfuerzos.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 11: Angina de pecho estable" },
  },
  {
    id: "mi-045",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "intermedio",
    stem: "¿Qué clase de fármacos ha demostrado prolongar la esperanza de vida después de un infarto de miocardio en pacientes con angina y daño del ventrículo izquierdo?",
    options: ["Bloqueadores β", "Antileucotrienos", "Antihistamínicos", "Broncodilatadores anticolinérgicos"],
    correctIndex: 0,
    explanation:
      "Los bloqueadores β prolongan la esperanza de vida después del infarto de miocardio y son preferidos en pacientes con angina y daño del ventrículo izquierdo, aunque están relativamente contraindicados en asma, EPOC grave y trastornos de la conducción AV.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 11: Angina de pecho estable" },
  },
  {
    id: "mi-046",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "avanzado",
    stem: "¿Cuáles son los dos pilares farmacológicos base del tratamiento de la insuficiencia cardíaca con reducción de la fracción de expulsión?",
    options: [
      "Antibióticos y antipiréticos",
      "Inhibidores de la ECA (o ARA) y bloqueadores β",
      "Anticonvulsivantes y ansiolíticos",
      "Insulina y metformina",
    ],
    correctIndex: 1,
    explanation:
      "La base del tratamiento de la IC con FE reducida son los IECA (o ARA) y los bloqueadores β, ya que ocasionan atenuación en la reducción y mejoría en la estructura y función cardíacas, con reducción de mortalidad y hospitalizaciones.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 12: Insuficiencia cardíaca" },
  },
  {
    id: "mi-047",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "intermedio",
    stem: "¿Qué biomarcadores se utilizan para apoyar el diagnóstico de insuficiencia cardíaca con disminución de la fracción de expulsión?",
    options: ["Troponina I exclusivamente", "BNP y pro-BNP", "Dímero D", "Procalcitonina"],
    correctIndex: 1,
    explanation:
      "El BNP y el pro-BNP se liberan en el corazón con insuficiencia y son marcadores sensibles a la IC con disminución de la FE; sus concentraciones aumentan con la edad y con el daño renal, lo cual debe considerarse en su interpretación.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 12: Insuficiencia cardíaca" },
  },
  {
    id: "mi-048",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "avanzado",
    stem: "¿Cuál es el principal riesgo a vigilar al usar antagonistas de los mineralocorticoides (espironolactona/eplerenona) en pacientes con IC y nefropatía crónica?",
    options: ["Hipoglucemia", "Hiperpotasemia y deterioro de la función renal", "Hipernatremia severa", "Anemia hemolítica"],
    correctIndex: 1,
    explanation:
      "Aunque el antagonismo de la aldosterona se asocia con reducción de la mortalidad en todas las etapas sintomáticas de la IC (clases NYHA II-IV), debe vigilarse el potasio y la función renal, especialmente en nefropatía crónica, por el riesgo de hiperpotasemia y disfunción renal.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 12: Insuficiencia cardíaca" },
  },
  {
    id: "mi-049",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    difficulty: "avanzado",
    stem: "¿Cómo se define el síndrome de distrés respiratorio agudo (SDRA)?",
    options: [
      "Fiebre y tos con radiografía normal",
      "Inicio agudo de infiltrados bilaterales, hipoxemia severa y edema pulmonar no explicado por falla cardíaca o sobrecarga de volumen",
      "Cualquier disnea de esfuerzo crónica",
      "Derrame pleural unilateral aislado",
    ],
    correctIndex: 1,
    explanation:
      "El SDRA se define por el inicio agudo de infiltrados bilaterales, hipoxemia severa y edema pulmonar no explicado por falla cardíaca ni sobrecarga de volumen; es una complicación frecuente en la COVID-19 severa.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 13: SARS-CoV-2 / COVID-19" },
  },
  {
    id: "mi-050",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    difficulty: "intermedio",
    stem: "¿En qué pacientes con COVID-19 severo/crítico ha demostrado la dexametasona reducir la mortalidad?",
    options: [
      "En todos los pacientes con COVID-19, incluso leve, sin oxígeno suplementario",
      "En pacientes que reciben oxígeno suplementario o ventilación mecánica, con mayor beneficio en ventilación mecánica",
      "Solo en pacientes ambulatorios asintomáticos",
      "Nunca ha demostrado beneficio",
    ],
    correctIndex: 1,
    explanation:
      "La dexametasona reduce la mortalidad en pacientes hospitalizados con COVID-19 que reciben oxígeno suplementario, con un beneficio mayor en quienes están bajo ventilación mecánica; no está recomendada en enfermedad leve a moderada sin necesidad de oxígeno.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 13: SARS-CoV-2 / COVID-19" },
  },
  {
    id: "mi-051",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    difficulty: "avanzado",
    stem: "En el manejo ventilatorio del SDRA (incluido el asociado a COVID-19), ¿cuál es el volumen tidal objetivo recomendado como parte de la 'ventilación protectora pulmonar'?",
    options: ["12-15 mL/kg de peso predicho", "6 mL/kg de peso predicho", "20 mL/kg de peso predicho", "No hay un volumen objetivo definido"],
    correctIndex: 1,
    explanation:
      "La ventilación protectora pulmonar busca prevenir la sobredistensión alveolar programando un volumen tidal de 6 mL/kg de peso predicho (se puede permitir hasta 8 mL/kg si el paciente está agitado), manteniendo la presión meseta ≤30 cm de agua.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 13: SARS-CoV-2 / COVID-19" },
  },
  {
    id: "mi-052",
    topicId: "medicina-interna",
    subtopic: "Endocrinología",
    difficulty: "avanzado",
    stem: "Paciente con hipertensión episódica intensa, cefalea, palpitaciones y diaforesis. Se sospecha feocromocitoma. ¿Cuál es el estudio diagnóstico inicial más adecuado?",
    options: [
      "Catecolaminas en orina de 24 h o metanefrinas plasmáticas libres fraccionadas",
      "Biopsia suprarrenal percutánea de entrada",
      "Prueba de supresión con dexametasona únicamente",
      "Cortisol libre urinario",
    ],
    correctIndex: 0,
    explanation:
      "Para el diagnóstico de feocromocitoma se miden catecolaminas en orina de 24 h o metanefrinas plasmáticas libres fraccionadas; la extirpación quirúrgica es el tratamiento definitivo y cura al 90% de los pacientes.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 8: Hipertensión arterial" },
  },
  {
    id: "mi-053",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    difficulty: "intermedio",
    stem: "¿Cuál es una diferencia clave entre el asma y la EPOC en cuanto a la reversibilidad de la obstrucción del flujo aéreo tras broncodilatadores inhalados?",
    options: [
      "En la EPOC la FEV1 rara vez muestra respuesta significativa a broncodilatadores, a diferencia del asma",
      "En el asma nunca hay respuesta a broncodilatadores",
      "Ambas enfermedades son siempre completamente reversibles",
      "Ambas enfermedades son siempre completamente irreversibles",
    ],
    correctIndex: 0,
    explanation:
      "A diferencia del asma, en la EPOC la FEV1 pocas veces muestra una respuesta significativa a los broncodilatadores inhalados (solo se detecta en el 15% de los casos), reflejando el componente fijo de la obstrucción.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 6: Enfermedad pulmonar obstructiva crónica" },
  },
  {
    id: "mi-054",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    difficulty: "basico",
    stem: "¿Cuál es la causa predominante de insuficiencia cardíaca en países industrializados, atribuible al 60-75% de los casos?",
    options: ["Enfermedad de Chagas", "Cardiopatía reumática", "Coronariopatía", "Anemia crónica"],
    correctIndex: 2,
    explanation:
      "En países industrializados, la coronariopatía es la causa predominante de insuficiencia cardíaca en ambos sexos, atribuible al 60-75% de los casos; la hipertensión contribuye en el 75% de los pacientes.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 12: Insuficiencia cardíaca" },
  },
  {
    id: "mi-055",
    topicId: "medicina-interna",
    subtopic: "Infectología",
    difficulty: "basico",
    stem: "¿Cuál es el estudio de elección para identificar a las personas con infección activa por SARS-CoV-2?",
    options: [
      "Anticuerpos IgG anti-SARS-CoV-2",
      "Reacción en cadena de la polimerasa (PCR)",
      "Radiografía de tórax aislada",
      "Hemocultivo",
    ],
    correctIndex: 1,
    explanation:
      "La PCR (reacción en cadena de la polimerasa) detecta el material genético del virus y es el estudio de elección para identificar infección activa, con sensibilidad mayor cuando se realiza cerca del inicio de los síntomas y especificidad cercana al 100%.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 13: SARS-CoV-2 / COVID-19" },
  },
  {
    id: "mi-056",
    topicId: "medicina-interna",
    subtopic: "Nefrología",
    difficulty: "intermedio",
    stem: "Paciente hospitalizado cuya creatinina sérica aumenta de 0.8 a 1.5 mg/dL en 48 horas. ¿Qué estadio de lesión renal aguda (KDIGO) corresponde?",
    options: [
      "Estadio 1 (aumento ≥0.3 mg/dL o 1.5-1.9 veces el valor basal)",
      "Estadio 2 (2-2.9 veces el valor basal)",
      "Estadio 3 (≥3 veces el valor basal o creatinina ≥4 mg/dL)",
      "No cumple criterios de lesión renal aguda",
    ],
    correctIndex: 0,
    explanation:
      "El estadio 1 de lesión renal aguda (KDIGO) se define por un aumento de creatinina ≥0.3 mg/dL en 48 horas o 1.5-1.9 veces el valor basal; en este caso, el aumento de 0.7 mg/dL en 48h (1.87 veces el basal) cumple criterio de estadio 1.",
    source: { label: "KDIGO Clinical Practice Guideline for Acute Kidney Injury" },
  },
  {
    id: "mi-057",
    topicId: "medicina-interna",
    subtopic: "Nefrología",
    difficulty: "intermedio",
    stem: "Paciente con potasio sérico de 7.2 mEq/L y ondas T picudas en el electrocardiograma. ¿Cuál es la primera medida a administrar para estabilizar la membrana miocárdica?",
    options: [
      "Gluconato de calcio intravenoso",
      "Insulina con glucosa intravenosa",
      "Resina de intercambio catiónico por vía oral",
      "Furosemida intravenosa",
    ],
    correctIndex: 0,
    explanation:
      "Ante hiperkalemia con cambios electrocardiográficos, el gluconato de calcio IV es la primera medida: no reduce el potasio sérico, pero estabiliza la membrana miocárdica de forma inmediata mientras se inician medidas (insulina/glucosa, salbutamol) para desplazar el potasio hacia el intracelular.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Trastornos del potasio" },
  },
  {
    id: "mi-058",
    topicId: "medicina-interna",
    subtopic: "Nefrología",
    difficulty: "basico",
    stem: "¿Cuál de los siguientes hallazgos es característico del síndrome nefrótico y lo distingue del síndrome nefrítico?",
    options: [
      "Hematuria macroscópica con cilindros hemáticos",
      "Proteinuria masiva (>3.5 g/día), edema e hipoalbuminemia, con hematuria mínima",
      "Hipertensión arterial severa como hallazgo predominante",
      "Oliguria progresiva con insuficiencia renal rápidamente progresiva",
    ],
    correctIndex: 1,
    explanation:
      "El síndrome nefrótico se caracteriza por proteinuria masiva, edema e hipoalbuminemia (con hematuria mínima o ausente), mientras que el síndrome nefrítico se caracteriza por hematuria con cilindros hemáticos, hipertensión y grados variables de deterioro de la función renal.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Enfermedad glomerular" },
  },
  {
    id: "mi-059",
    topicId: "medicina-interna",
    subtopic: "Nefrología",
    difficulty: "avanzado",
    stem: "Paciente con acidosis metabólica y anión gap elevado. ¿Cuál de las siguientes causas es consistente con este hallazgo?",
    options: ["Diarrea profusa", "Acidosis tubular renal tipo 2", "Cetoacidosis diabética", "Uso de acetazolamida"],
    correctIndex: 2,
    explanation:
      "La cetoacidosis diabética genera acidosis metabólica con anión gap elevado por acumulación de cetoácidos; la diarrea, la acidosis tubular renal y la acetazolamida producen típicamente acidosis metabólica con anión gap normal (hiperclorémica) por pérdida de bicarbonato.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Trastornos acidobásicos" },
  },
  {
    id: "mi-060",
    topicId: "medicina-interna",
    subtopic: "Nefrología",
    difficulty: "intermedio",
    stem: "Paciente con hiponatremia, osmolalidad urinaria inapropiadamente elevada, sodio urinario >40 mEq/L y euvolemia clínica, sin insuficiencia renal, tiroidea ni suprarrenal. ¿Cuál es el diagnóstico más probable?",
    options: [
      "Diabetes insípida central",
      "Síndrome de secreción inadecuada de hormona antidiurética (SIADH)",
      "Insuficiencia suprarrenal primaria",
      "Polidipsia psicógena",
    ],
    correctIndex: 1,
    explanation:
      "El SIADH se caracteriza por hiponatremia euvolémica con orina inapropiadamente concentrada (osmolalidad urinaria elevada) y natriuresis elevada, en ausencia de causas renales, tiroideas o suprarrenales de hiponatremia.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Trastornos del sodio" },
  },
  {
    id: "mi-061",
    topicId: "medicina-interna",
    subtopic: "Nefrología",
    difficulty: "intermedio",
    stem: "¿Cuál de las siguientes es una indicación de terapia de reemplazo renal urgente en un paciente con lesión renal aguda?",
    options: [
      "Hiperkalemia refractaria al tratamiento médico con cambios electrocardiográficos",
      "Creatinina sérica de 1.3 mg/dL de forma aislada",
      "Proteinuria leve asintomática",
      "Hipertensión arterial leve bien controlada",
    ],
    correctIndex: 0,
    explanation:
      "Las indicaciones clásicas de diálisis urgente se resumen en el mnemónico AEIOU: Acidosis refractaria, alteraciones Electrolíticas (hiperkalemia refractaria), Intoxicaciones dializables, sObrecarga de volumen refractaria y Uremia sintomática.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Lesión renal aguda" },
  },
  {
    id: "mi-062",
    topicId: "medicina-interna",
    subtopic: "Nefrología",
    difficulty: "avanzado",
    stem: "Paciente con oliguria y elevación de creatinina, fracción excretada de sodio (FeNa) <1%. ¿Qué mecanismo es más probable?",
    options: [
      "Necrosis tubular aguda ya establecida",
      "Azoemia prerrenal por hipoperfusión renal, con función tubular conservada",
      "Glomerulonefritis rápidamente progresiva",
      "Obstrucción del tracto urinario bajo",
    ],
    correctIndex: 1,
    explanation:
      "Una FeNa <1% sugiere que los túbulos renales conservan su capacidad de reabsorber sodio de forma ávida, típico de la azoemia prerrenal por hipoperfusión; en la necrosis tubular aguda establecida, la FeNa suele ser >2% por pérdida de esa capacidad de reabsorción.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Lesión renal aguda" },
  },
  {
    id: "mi-063",
    topicId: "medicina-interna",
    subtopic: "Hematología",
    difficulty: "intermedio",
    stem: "Paciente con anemia macrocítica, glositis, parestesias simétricas en manos y pies, y alteración de la propiocepción. ¿Cuál es la causa más probable?",
    options: ["Déficit de folato", "Déficit de vitamina B12", "Anemia ferropénica", "Anemia de enfermedad crónica"],
    correctIndex: 1,
    explanation:
      "El déficit de vitamina B12 causa anemia megaloblástica (macrocítica) asociada a manifestaciones neurológicas (degeneración combinada subaguda de la médula: parestesias, alteración de la propiocepción y vibración), a diferencia del déficit de folato, que no suele causar afectación neurológica.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Anemias megaloblásticas" },
  },
  {
    id: "mi-064",
    topicId: "medicina-interna",
    subtopic: "Hematología",
    difficulty: "avanzado",
    stem: "Paciente séptico con sangrado difuso, trombocitopenia, tiempo de protrombina prolongado, fibrinógeno bajo y dímero D marcadamente elevado. ¿Cuál es el diagnóstico más probable?",
    options: [
      "Púrpura trombocitopénica trombótica",
      "Coagulación intravascular diseminada",
      "Hemofilia A adquirida",
      "Deficiencia aislada de vitamina K",
    ],
    correctIndex: 1,
    explanation:
      "La combinación de trombocitopenia, prolongación de los tiempos de coagulación, fibrinógeno consumido (bajo) y dímero D marcadamente elevado, en un contexto de sepsis, es característica de coagulación intravascular diseminada.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Coagulación intravascular diseminada" },
  },
  {
    id: "mi-065",
    topicId: "medicina-interna",
    subtopic: "Hematología",
    difficulty: "avanzado",
    stem: "Paciente con anemia hemolítica microangiopática (esquistocitos en frotis), trombocitopenia, fiebre, alteración neurológica y disfunción renal. ¿Cuál es el diagnóstico más probable?",
    options: ["Púrpura trombocitopénica trombótica (PTT)", "Anemia ferropénica", "Leucemia mieloide crónica", "Enfermedad de von Willebrand"],
    correctIndex: 0,
    explanation:
      "La péntada clásica de la PTT incluye anemia hemolítica microangiopática, trombocitopenia, fiebre, alteración neurológica y disfunción renal, aunque no siempre están presentes los 5 elementos; requiere plasmaféresis urgente.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Microangiopatías trombóticas" },
  },
  {
    id: "mi-066",
    topicId: "medicina-interna",
    subtopic: "Hematología",
    difficulty: "intermedio",
    stem: "Paciente con anemia de células falciformes que presenta una crisis vasooclusiva dolorosa aguda. ¿Cuál es el pilar del manejo inicial?",
    options: [
      "Antibióticos de amplio espectro exclusivamente",
      "Hidratación, analgesia (incluyendo opioides si es necesario) y oxígeno suplementario si hay hipoxemia",
      "Transfusión de intercambio inmediata en todos los casos",
      "Esplenectomía urgente",
    ],
    correctIndex: 1,
    explanation:
      "El manejo inicial de la crisis vasooclusiva dolorosa se basa en hidratación, analgesia adecuada (frecuentemente opioides) y oxígeno suplementario si hay hipoxemia; la transfusión de intercambio se reserva para complicaciones graves específicas (ej. síndrome torácico agudo, ictus).",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Enfermedad de células falciformes" },
  },
  {
    id: "mi-067",
    topicId: "medicina-interna",
    subtopic: "Hematología",
    difficulty: "intermedio",
    stem: "Paciente anticoagulado con warfarina que presenta hemorragia intracraneal activa e INR de 4.5. ¿Cuál es la conducta más apropiada para revertir rápidamente el efecto anticoagulante?",
    options: [
      "Suspender la warfarina y esperar su eliminación espontánea",
      "Concentrado de complejo protrombínico (CCP) más vitamina K intravenosa",
      "Plasma fresco congelado como única medida, sin vitamina K",
      "Protamina intravenosa",
    ],
    correctIndex: 1,
    explanation:
      "Ante hemorragia grave (ej. intracraneal) en un paciente anticoagulado con warfarina, se recomienda reversión rápida con concentrado de complejo protrombínico (más rápido que el plasma fresco congelado) más vitamina K intravenosa para mantener la reversión.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Anticoagulación y reversión" },
  },
  {
    id: "mi-068",
    topicId: "medicina-interna",
    subtopic: "Hematología",
    difficulty: "intermedio",
    stem: "Minutos después de iniciar una transfusión de concentrado eritrocitario, el paciente presenta fiebre, dolor lumbar, hipotensión y hemoglobinuria. ¿Cuál es la causa más probable?",
    options: [
      "Reacción febril no hemolítica simple",
      "Reacción hemolítica aguda por incompatibilidad ABO",
      "Sobrecarga circulatoria asociada a la transfusión",
      "Contaminación bacteriana leve sin relevancia clínica",
    ],
    correctIndex: 1,
    explanation:
      "La aparición temprana de fiebre, dolor lumbar, hipotensión y hemoglobinuria tras iniciar una transfusión es característica de una reacción hemolítica aguda por incompatibilidad ABO, una emergencia que obliga a detener la transfusión de inmediato.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Reacciones transfusionales" },
  },
  {
    id: "mi-069",
    topicId: "medicina-interna",
    subtopic: "Hematología",
    difficulty: "avanzado",
    stem: "Paciente con leucemia de alto recuento celular que, tras iniciar quimioterapia, desarrolla hiperkalemia, hiperfosfatemia, hipocalcemia e hiperuricemia. ¿Qué complicación describe este cuadro?",
    options: ["Neutropenia febril", "Síndrome de lisis tumoral", "Coagulación intravascular diseminada", "Síndrome de vena cava superior"],
    correctIndex: 1,
    explanation:
      "El síndrome de lisis tumoral ocurre por la destrucción masiva de células tumorales (espontánea o inducida por quimioterapia), liberando potasio, fosfato y ácido úrico intracelulares, con hipocalcemia secundaria a la hiperfosfatemia.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Urgencias oncológicas" },
  },
  {
    id: "mi-070",
    topicId: "medicina-interna",
    subtopic: "Gastroenterología",
    difficulty: "basico",
    stem: "¿Qué criterios se requieren para establecer el diagnóstico de pancreatitis aguda (al menos 2 de 3)?",
    options: [
      "Dolor abdominal característico, amilasa o lipasa ≥3 veces el límite superior normal, y/o hallazgos imagenológicos compatibles",
      "Fiebre aislada más leucocitosis",
      "Solo la elevación de bilirrubina directa",
      "Únicamente hallazgos ecográficos, sin necesidad de clínica ni laboratorio",
    ],
    correctIndex: 0,
    explanation:
      "Según la clasificación revisada de Atlanta, el diagnóstico de pancreatitis aguda requiere al menos 2 de 3 criterios: dolor abdominal característico, lipasa o amilasa ≥3 veces el límite superior normal, y/o hallazgos imagenológicos compatibles.",
    source: { label: "Revised Atlanta Classification of Acute Pancreatitis" },
  },
  {
    id: "mi-071",
    topicId: "medicina-interna",
    subtopic: "Gastroenterología",
    difficulty: "intermedio",
    stem: "Paciente con úlcera péptica confirmada e infección por Helicobacter pylori. ¿Cuál es un esquema de primera línea recomendado para su erradicación?",
    options: [
      "Monoterapia con inhibidor de bomba de protones",
      "Terapia cuádruple o triple con inhibidor de bomba de protones más antibióticos (ej. claritromicina y amoxicilina)",
      "Antiácidos únicamente, sin antibióticos",
      "Corticosteroides sistémicos",
    ],
    correctIndex: 1,
    explanation:
      "La erradicación de H. pylori requiere un inhibidor de bomba de protones combinado con al menos dos antibióticos (terapia triple) o un esquema cuádruple (con bismuto), según los patrones locales de resistencia a claritromicina.",
    source: { label: "American College of Gastroenterology — Guideline for the Treatment of Helicobacter pylori" },
  },
  {
    id: "mi-072",
    topicId: "medicina-interna",
    subtopic: "Gastroenterología",
    difficulty: "intermedio",
    stem: "¿Cuál de los siguientes hallazgos es más característico de la colitis ulcerosa en comparación con la enfermedad de Crohn?",
    options: [
      "Afectación transmural con lesiones salteadas (\"skip lesions\") en cualquier segmento del tubo digestivo",
      "Afectación continua limitada a la mucosa, que inicia en el recto y se extiende proximalmente en el colon",
      "Formación frecuente de fístulas y granulomas no caseificantes",
      "Afectación predominante del intestino delgado",
    ],
    correctIndex: 1,
    explanation:
      "La colitis ulcerosa afecta de forma continua la mucosa del colon, iniciando siempre en el recto y extendiéndose proximalmente, mientras que la enfermedad de Crohn se caracteriza por afectación transmural, lesiones salteadas y puede afectar cualquier segmento del tubo digestivo, con fístulas y granulomas.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Enfermedad inflamatoria intestinal" },
  },
  {
    id: "mi-073",
    topicId: "medicina-interna",
    subtopic: "Gastroenterología",
    difficulty: "basico",
    stem: "Paciente con fiebre, ictericia y dolor en hipocondrio derecho (tríada de Charcot). ¿Qué diagnóstico sugiere este cuadro?",
    options: ["Colecistitis aguda no complicada", "Colangitis aguda", "Hepatitis viral aguda", "Pancreatitis biliar leve"],
    correctIndex: 1,
    explanation:
      "La tríada de Charcot (fiebre, ictericia y dolor en hipocondrio derecho) es clásica de la colangitis aguda, una infección de la vía biliar que requiere descompresión biliar urgente además de antibióticos.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Colangitis aguda" },
  },
  {
    id: "mi-074",
    topicId: "medicina-interna",
    subtopic: "Gastroenterología",
    difficulty: "intermedio",
    stem: "Paciente cirrótico que desarrolla confusión y asterixis después de un episodio de estreñimiento y una infección urinaria no tratada. ¿Cuál es el diagnóstico más probable y qué lo precipitó?",
    options: [
      "Encefalopatía hepática, precipitada por el estreñimiento y la infección (aumento de producción/absorción de amonio)",
      "Ictus isquémico agudo, sin relación con la cirrosis",
      "Intoxicación alcohólica aguda exclusivamente",
      "Hipoglucemia aislada sin relación hepática",
    ],
    correctIndex: 0,
    explanation:
      "El estreñimiento y las infecciones son factores precipitantes clásicos de encefalopatía hepática en el paciente cirrótico, al aumentar la producción y absorción intestinal de amonio y otras toxinas que el hígado ya no puede depurar eficientemente.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Encefalopatía hepática" },
  },
  {
    id: "mi-075",
    topicId: "medicina-interna",
    subtopic: "Gastroenterología",
    difficulty: "avanzado",
    stem: "Paciente con ascitis en quien el gradiente de albúmina suero-ascitis (SAAG) es ≥1.1 g/dL. ¿Qué implica este resultado?",
    options: [
      "Sugiere una causa no relacionada con hipertensión portal (ej. carcinomatosis peritoneal)",
      "Sugiere hipertensión portal como causa de la ascitis (ej. cirrosis, insuficiencia cardíaca)",
      "Descarta cualquier enfermedad hepática",
      "Indica siempre infección bacteriana del líquido ascítico",
    ],
    correctIndex: 1,
    explanation:
      "Un SAAG ≥1.1 g/dL tiene aproximadamente 97% de exactitud para identificar hipertensión portal como causa de la ascitis (cirrosis, insuficiencia cardíaca); un SAAG <1.1 g/dL sugiere causas no relacionadas con hipertensión portal, como carcinomatosis peritoneal o tuberculosis peritoneal.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Ascitis" },
  },
  {
    id: "mi-076",
    topicId: "medicina-interna",
    subtopic: "Gastroenterología",
    difficulty: "intermedio",
    stem: "Paciente con reflujo gastroesofágico crónico de larga evolución en quien la endoscopía muestra metaplasia intestinal en la mucosa esofágica distal. ¿Cómo se denomina esta condición y por qué es clínicamente relevante?",
    options: [
      "Esófago de Barrett; es un factor de riesgo para adenocarcinoma esofágico",
      "Acalasia; sin relación con el reflujo",
      "Anillo de Schatzki; variante anatómica sin relevancia oncológica",
      "Esofagitis eosinofílica; se asocia siempre a alergias alimentarias",
    ],
    correctIndex: 0,
    explanation:
      "El esófago de Barrett es la sustitución del epitelio escamoso esofágico distal por epitelio columnar con metaplasia intestinal, secundaria al reflujo crónico, y constituye un factor de riesgo reconocido para el desarrollo de adenocarcinoma esofágico, por lo que amerita vigilancia endoscópica.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Enfermedad por reflujo gastroesofágico" },
  },
  {
    id: "mi-077",
    topicId: "medicina-interna",
    subtopic: "Reumatología",
    difficulty: "basico",
    stem: "Mujer de 45 años con poliartritis simétrica de pequeñas articulaciones de las manos, rigidez matutina de más de 1 hora que mejora con la actividad, y factor reumatoide y anti-CCP positivos. ¿Cuál es el diagnóstico más probable?",
    options: ["Osteoartritis", "Artritis reumatoide", "Gota poliarticular", "Lupus eritematoso sistémico"],
    correctIndex: 1,
    explanation:
      "La poliartritis simétrica de pequeñas articulaciones con rigidez matutina prolongada que mejora con la actividad, junto con factor reumatoide y anti-CCP positivos (este último más específico), es característica de la artritis reumatoide.",
    source: { label: "ACR/EULAR Rheumatoid Arthritis Classification Criteria" },
  },
  {
    id: "mi-078",
    topicId: "medicina-interna",
    subtopic: "Reumatología",
    difficulty: "intermedio",
    stem: "Paciente con monoartritis aguda de la primera articulación metatarsofalángica. El análisis del líquido sinovial muestra cristales en forma de aguja con birrefringencia negativa. ¿Cuál es el diagnóstico?",
    options: [
      "Pseudogota (depósito de pirofosfato de calcio)",
      "Gota (depósito de urato monosódico)",
      "Artritis séptica",
      "Artritis reactiva",
    ],
    correctIndex: 1,
    explanation:
      "Los cristales de urato monosódico son alargados, en forma de aguja, con birrefringencia negativa fuerte bajo luz polarizada, característicos de la gota; los cristales de pirofosfato de calcio (pseudogota) son romboidales, con birrefringencia positiva débil.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Gota y enfermedad por depósito de cristales" },
  },
  {
    id: "mi-079",
    topicId: "medicina-interna",
    subtopic: "Reumatología",
    difficulty: "intermedio",
    stem: "Varón joven con dolor lumbar inflamatorio crónico (mejora con el ejercicio, empeora con el reposo), rigidez matutina prolongada y sacroileítis en imágenes. ¿Cuál es el diagnóstico más probable?",
    options: ["Espondilitis anquilosante", "Hernia discal lumbar mecánica", "Fibromialgia", "Osteoartritis lumbar"],
    correctIndex: 0,
    explanation:
      "El dolor lumbar de tipo inflamatorio (mejora con el ejercicio, empeora con el reposo, rigidez matutina prolongada) asociado a sacroileítis es característico de la espondilitis anquilosante, a diferencia del dolor lumbar mecánico, que empeora con la actividad.",
    source: { label: "Assessment of SpondyloArthritis International Society (ASAS) — Criterios de clasificación" },
  },
  {
    id: "mi-080",
    topicId: "medicina-interna",
    subtopic: "Reumatología",
    difficulty: "avanzado",
    stem: "Mujer de 70 años con dolor y rigidez matutina en cinturas escapular y pelviana, VES muy elevada, que además refiere cefalea temporal nueva y claudicación mandibular. ¿Qué complicación debe descartarse de forma urgente?",
    options: [
      "Arteritis de células gigantes (riesgo de pérdida visual irreversible)",
      "Fibromialgia asociada",
      "Osteoartritis de cadera",
      "Gota poliarticular",
    ],
    correctIndex: 0,
    explanation:
      "La polimialgia reumática se asocia frecuentemente con arteritis de células gigantes; la cefalea temporal nueva y la claudicación mandibular son datos de alarma que obligan a descartarla de forma urgente, por el riesgo de pérdida visual irreversible por afectación de la arteria oftálmica.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Polimialgia reumática y arteritis de células gigantes" },
  },
  {
    id: "mi-081",
    topicId: "medicina-interna",
    subtopic: "Reumatología",
    difficulty: "intermedio",
    stem: "Mujer de 50 años con xerostomía, xeroftalmia (queratoconjuntivitis seca) y anticuerpos anti-Ro/SSA positivos. ¿Cuál es el diagnóstico más probable?",
    options: ["Síndrome de Sjögren", "Lupus eritematoso sistémico aislado", "Esclerosis sistémica", "Artritis reumatoide aislada"],
    correctIndex: 0,
    explanation:
      "La combinación de xerostomía, xeroftalmia y anticuerpos anti-Ro/SSA (o anti-La/SSB) positivos es característica del síndrome de Sjögren, que puede presentarse de forma primaria o asociado a otras enfermedades autoinmunes.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Síndrome de Sjögren" },
  },
  {
    id: "mi-082",
    topicId: "medicina-interna",
    subtopic: "Reumatología",
    difficulty: "avanzado",
    stem: "Paciente con sinusitis crónica, hemoptisis, glomerulonefritis rápidamente progresiva y c-ANCA (anti-proteinasa 3) positivo. ¿Cuál es el diagnóstico más probable?",
    options: [
      "Granulomatosis con poliangeítis (antes Wegener)",
      "Poliarteritis nodosa clásica",
      "Arteritis de Takayasu",
      "Púrpura de Henoch-Schönlein",
    ],
    correctIndex: 0,
    explanation:
      "La tríada de afectación de vías respiratorias superiores (sinusitis), pulmón (hemoptisis) y riñón (glomerulonefritis rápidamente progresiva), junto con c-ANCA/anti-proteinasa 3 positivo, es característica de la granulomatosis con poliangeítis.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed. — Vasculitis asociadas a ANCA" },
  },
  {
    id: "mi-083",
    topicId: "medicina-interna",
    subtopic: "Reumatología",
    difficulty: "basico",
    stem: "Paciente con dolor musculoesquelético generalizado y crónico (>3 meses), fatiga, sueño no reparador y múltiples puntos dolorosos a la palpación, sin evidencia de inflamación articular ni alteraciones en marcadores inflamatorios. ¿Cuál es el diagnóstico más probable?",
    options: ["Artritis reumatoide temprana", "Fibromialgia", "Polimialgia reumática", "Lupus eritematoso sistémico"],
    correctIndex: 1,
    explanation:
      "El dolor musculoesquelético generalizado crónico con fatiga, sueño no reparador y puntos dolorosos, sin evidencia objetiva de inflamación articular ni alteración de marcadores inflamatorios, es característico de la fibromialgia.",
    source: { label: "American College of Rheumatology — Criterios de fibromialgia" },
  },
];
