import type { QuizQuestion } from "@/types/content";

export const pediatriaQuestions: QuizQuestion[] = [
  {
    id: "ped-001",
    topicId: "pediatria",
    subtopic: "Neonatología",
    difficulty: "basico",
    stem: "Recién nacido a 1 minuto de vida: frecuencia cardíaca 105 lpm, llanto vigoroso, algo de flexión de extremidades, hace muecas al estímulo y cuerpo rosado con extremidades cianóticas. ¿Cuál es su puntaje de APGAR?",
    options: ["6", "7", "8", "10"],
    correctIndex: 2,
    explanation:
      "FC >100 = 2, esfuerzo respiratorio bueno/llanto = 2, tono con algo de flexión = 1, irritabilidad refleja (muecas) = 1, color acrocianótico = 1. Total = 8.",
    source: { label: "American Academy of Pediatrics — Escala de APGAR" },
  },
  {
    id: "ped-002",
    topicId: "pediatria",
    subtopic: "Infecciones respiratorias",
    difficulty: "intermedio",
    stem: "Lactante de 8 meses con tos, sibilancias espiratorias, tiraje subcostal leve y saturación de 94% al aire ambiente, alimentándose adecuadamente. Según los criterios de gravedad de bronquiolitis, ¿cuál es la conducta más apropiada?",
    options: [
      "Hospitalizar de forma inmediata en UCI",
      "Manejo ambulatorio con medidas de soporte, hidratación y signos de alarma",
      "Indicar salbutamol nebulizado de forma sistemática",
      "Iniciar antibióticos de amplio espectro",
    ],
    correctIndex: 1,
    explanation:
      "La bronquiolitis leve-moderada con buena tolerancia oral y saturación >92-94% se maneja de forma ambulatoria con medidas de soporte (hidratación, lavados nasales, antipiréticos si hay fiebre) y educación sobre signos de alarma; los broncodilatadores y antibióticos no están indicados de rutina.",
    source: { label: "American Academy of Pediatrics — Clinical Practice Guideline: Bronchiolitis" },
  },
  {
    id: "ped-003",
    topicId: "pediatria",
    subtopic: "Nutrición",
    difficulty: "intermedio",
    stem: "Niño de 2 años con peso muy bajo para la talla, edema bilateral en miembros inferiores, piel con lesiones descamativas y cabello despigmentado. ¿Cuál es el diagnóstico más probable?",
    options: ["Marasmo", "Kwashiorkor", "Raquitismo", "Deficiencia de vitamina A"],
    correctIndex: 1,
    explanation:
      "El kwashiorkor se caracteriza por edema (por hipoalbuminemia), lesiones cutáneas descamativas, cambios en cabello y hepatomegalia, a diferencia del marasmo que cursa con emaciación severa sin edema.",
    source: { label: "OMS — Manejo de la desnutrición aguda severa en niños" },
  },
  {
    id: "ped-004",
    topicId: "pediatria",
    subtopic: "Enfermedad diarreica",
    difficulty: "basico",
    stem: "Niño de 3 años con diarrea acuosa, ojos hundidos, sed intensa, pliegue cutáneo que se deshace lentamente. Según AIEPI, ¿cómo se clasifica la deshidratación?",
    options: ["Sin deshidratación", "Algún grado de deshidratación", "Deshidratación grave", "Choque hipovolémico establecido"],
    correctIndex: 1,
    explanation:
      "Dos o más signos como ojos hundidos, sed intensa/bebe con avidez y pliegue cutáneo que se deshace lentamente clasifican como 'algún grado de deshidratación' según AIEPI, que requiere plan B de rehidratación oral.",
    source: { label: "OPS/OMS — AIEPI: Atención Integrada a las Enfermedades Prevalentes de la Infancia" },
  },
  {
    id: "ped-005",
    topicId: "pediatria",
    subtopic: "Inmunizaciones",
    difficulty: "basico",
    stem: "Según el esquema nacional de vacunación de Guatemala, ¿a qué edad se aplica típicamente la primera dosis de la vacuna pentavalente (DPT-HB-Hib)?",
    options: ["Al nacer", "2 meses", "6 meses", "12 meses"],
    correctIndex: 1,
    explanation:
      "El esquema nacional de Guatemala (MSPAS) inicia la serie de pentavalente a los 2 meses de edad, con dosis subsecuentes a los 4 y 6 meses.",
    source: { label: "MSPAS Guatemala — Esquema Nacional de Vacunación vigente" },
  },
  {
    id: "ped-006",
    topicId: "pediatria",
    subtopic: "Neonatología",
    difficulty: "intermedio",
    stem: "Recién nacido a término con ictericia que aparece en las primeras 24 horas de vida. ¿Cómo se interpreta este hallazgo?",
    options: [
      "Es fisiológica y no requiere estudio",
      "Es patológica y requiere evaluación urgente de bilirrubinas",
      "Solo se debe observar sin intervención hasta el alta",
      "Indica siempre incompatibilidad Rh sin necesidad de más pruebas",
    ],
    correctIndex: 1,
    explanation:
      "La ictericia neonatal que aparece en las primeras 24 horas de vida siempre se considera patológica (a diferencia de la ictericia fisiológica que aparece después del segundo día) y obliga a descartar causas como incompatibilidad de grupo/Rh, sepsis o hemólisis.",
    source: { label: "American Academy of Pediatrics — Clinical Practice Guideline: Hyperbilirubinemia in the Newborn" },
  },
  {
    id: "ped-007",
    topicId: "pediatria",
    subtopic: "Urgencias pediátricas",
    difficulty: "avanzado",
    stem: "Niño de 4 años con estridor inspiratorio, tos 'perruna', voz ronca y fiebre baja de inicio gradual. ¿Cuál es el diagnóstico más probable y su primera línea de tratamiento?",
    options: [
      "Epiglotitis; requiere intubación inmediata",
      "Laringotraqueítis (crup); dexametasona oral/IM y considerar epinefrina nebulizada si es moderado-grave",
      "Cuerpo extraño en vía aérea; maniobra de Heimlich",
      "Asma; salbutamol inhalado",
    ],
    correctIndex: 1,
    explanation:
      "El cuadro de tos perruna, estridor y disfonía de inicio gradual es característico del crup viral. El tratamiento de elección es dexametasona (oral, IM o IV) en todos los casos, agregando epinefrina nebulizada en casos moderados-graves.",
    source: { label: "American Academy of Pediatrics — Croup: Diagnosis and Management" },
  },
  {
    id: "ped-008",
    topicId: "pediatria",
    subtopic: "Crecimiento y desarrollo",
    difficulty: "basico",
    stem: "¿A qué edad aproximada se espera que un lactante logre sostener la cabeza de forma estable en decúbito prono y comience a rodar?",
    options: ["1 mes", "3-4 meses", "9 meses", "12 meses"],
    correctIndex: 1,
    explanation:
      "El control cefálico completo y el inicio de la capacidad de rodar se espera aproximadamente entre los 3 y 4 meses de edad, como hito del desarrollo motor grueso.",
    source: { label: "OMS — Indicadores de hitos del desarrollo infantil temprano" },
  },
  {
    id: "ped-009",
    topicId: "pediatria",
    subtopic: "Enfermedades exantemáticas",
    difficulty: "basico",
    stem: "Niño de 5 años con fiebre, tos, conjuntivitis y pequeñas manchas blanco-grisáceas sobre una base eritematosa en la mucosa bucal, un día antes de la aparición del exantema. ¿Cómo se denomina este hallazgo y qué enfermedad indica?",
    options: [
      "Líneas de Pastia; escarlatina",
      "Manchas de Koplik; sarampión",
      "Enantema petequial; rubéola",
      "Úlceras aftosas; herpangina",
    ],
    correctIndex: 1,
    explanation:
      "Las manchas de Koplik (lesiones blanco-grisáceas sobre base eritematosa en la mucosa yugal) son patognomónicas del sarampión y aparecen típicamente 1-2 días antes del exantema.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 1: Enfermedades exantemáticas" },
  },
  {
    id: "ped-010",
    topicId: "pediatria",
    subtopic: "Enfermedades exantemáticas",
    difficulty: "intermedio",
    stem: "¿Cuál es la principal medida de tratamiento recomendada por la OMS en niños con sarampión, además del manejo de soporte?",
    options: ["Antibióticos profilácticos sistemáticos", "Suplementación con vitamina A", "Aciclovir oral", "Inmunoglobulina IV en todos los casos"],
    correctIndex: 1,
    explanation:
      "La OMS recomienda administrar vitamina A a todos los niños con sarampión, ya que reduce la gravedad de la enfermedad y el riesgo de complicaciones oculares y de mortalidad, especialmente en niños con deficiencia subyacente.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 1: Enfermedades exantemáticas" },
  },
  {
    id: "ped-011",
    topicId: "pediatria",
    subtopic: "Enfermedades exantemáticas",
    difficulty: "intermedio",
    stem: "Niño con exantema vesicular pruriginoso en el que coexisten simultáneamente máculas, pápulas, vesículas y costras en distintas áreas del cuerpo. ¿Cuál es el diagnóstico más probable y qué característica confirma el diagnóstico?",
    options: [
      "Varicela; lesiones en diferentes estadios evolutivos de forma simultánea",
      "Escarlatina; exantema papular uniforme",
      "Roséola; exantema tras la resolución de la fiebre",
      "Eritema infeccioso; exantema en 'mejillas abofeteadas'",
    ],
    correctIndex: 0,
    explanation:
      "La presencia simultánea de lesiones en distintos estadios evolutivos (máculas, pápulas, vesículas, costras) es la característica diagnóstica clave de la varicela, a diferencia de otras enfermedades exantemáticas con lesiones más uniformes.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 1: Enfermedades exantemáticas" },
  },
  {
    id: "ped-012",
    topicId: "pediatria",
    subtopic: "Enfermedades exantemáticas",
    difficulty: "avanzado",
    stem: "¿Cómo se denomina la complicación tardía y crónica del sarampión, causada por persistencia viral en el sistema nervioso central años después de la infección aguda?",
    options: [
      "Encefalitis aguda posinfecciosa",
      "Panencefalitis esclerosante subaguda (PEES)",
      "Síndrome de Guillain-Barré",
      "Meningitis aséptica",
    ],
    correctIndex: 1,
    explanation:
      "La panencefalitis esclerosante subaguda (PEES) es una complicación neurodegenerativa tardía y casi siempre mortal del sarampión, que se manifiesta años después de la infección aguda por persistencia del virus en el SNC.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 1: Enfermedades exantemáticas" },
  },
  {
    id: "ped-013",
    topicId: "pediatria",
    subtopic: "Enfermedades exantemáticas",
    difficulty: "intermedio",
    stem: "Niño con fiebre, faringitis, exantema papular áspero como 'papel de lija', lengua aframbuesada y líneas de Pastia en los pliegues cutáneos. ¿Cuál es el diagnóstico más probable?",
    options: ["Sarampión", "Escarlatina", "Rubéola", "Roséola infantil"],
    correctIndex: 1,
    explanation:
      "La escarlatina, causada por Streptococcus pyogenes productor de exotoxina pirogénica, se caracteriza por exantema áspero tipo 'papel de lija', lengua aframbuesada y líneas de Pastia (acentuación del exantema en los pliegues cutáneos).",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 1: Enfermedades exantemáticas" },
  },
  {
    id: "ped-014",
    topicId: "pediatria",
    subtopic: "Neonatología",
    difficulty: "intermedio",
    stem: "¿Cuáles son los cuatro mecanismos por los que un recién nacido puede perder calor corporal?",
    options: [
      "Conducción, convección, radiación y evaporación",
      "Sudoración, escalofríos, vasodilatación y taquicardia",
      "Fiebre, hipotermia, taquipnea y bradicardia",
      "Solo la evaporación es relevante en el recién nacido",
    ],
    correctIndex: 0,
    explanation:
      "El recién nacido pierde calor por conducción (contacto con superficies frías), convección (corrientes de aire), radiación (hacia objetos fríos cercanos sin contacto directo) y evaporación (piel húmeda, especialmente justo después del nacimiento).",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 2: El recién nacido" },
  },
  {
    id: "ped-015",
    topicId: "pediatria",
    subtopic: "Neonatología",
    difficulty: "basico",
    stem: "¿Qué medida rutinaria de cuidados del recién nacido previene la enfermedad hemorrágica del recién nacido?",
    options: [
      "Administración de vitamina K al nacer",
      "Profilaxis ocular con nitrato de plata",
      "Baño inmediato después del parto",
      "Aspiración rutinaria de secreciones",
    ],
    correctIndex: 0,
    explanation:
      "La administración de vitamina K al nacer es una medida de cuidado general estándar (junto con el cuidado del cordón umbilical, cuidado de los ojos y establecimiento de la respiración) que previene la enfermedad hemorrágica del recién nacido.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 5: Prematuridad y crecimiento intrauterino retardado" },
  },
  {
    id: "ped-016",
    topicId: "pediatria",
    subtopic: "Neonatología",
    difficulty: "avanzado",
    stem: "¿Cuál fracción de bilirrubina es la responsable del riesgo de neurotoxicidad (kernícterus) en el recién nacido con hiperbilirrubinemia grave?",
    options: ["Bilirrubina directa (conjugada)", "Bilirrubina indirecta (no conjugada)", "Ambas por igual", "Ninguna, el riesgo depende solo de la edad gestacional"],
    correctIndex: 1,
    explanation:
      "La bilirrubina indirecta (no conjugada), al ser liposoluble, puede atravesar la barrera hematoencefálica y depositarse en los ganglios basales, causando kernícterus cuando alcanza niveles críticos.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 3: Ictericia fisiológica" },
  },
  {
    id: "ped-017",
    topicId: "pediatria",
    subtopic: "Neonatología",
    difficulty: "avanzado",
    stem: "Recién nacido Rh negativo, hijo de madre Rh negativo previamente sensibilizada. ¿Cuál es el mecanismo fisiopatológico de la enfermedad hemolítica del recién nacido por incompatibilidad Rh?",
    options: [
      "Paso de anticuerpos maternos IgG anti-D a través de la placenta hacia el feto Rh positivo, causando hemólisis",
      "Infección directa del feto por el virus de la hepatitis materna",
      "Deficiencia de glucosa-6-fosfato deshidrogenasa fetal",
      "Producción de anticuerpos fetales contra sus propios eritrocitos",
    ],
    correctIndex: 0,
    explanation:
      "En la incompatibilidad Rh, una madre Rh negativa sensibilizada (por embarazo o transfusión previa) produce anticuerpos IgG anti-D que atraviesan la placenta y hemolizan los eritrocitos de un feto Rh positivo.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 4: Enfermedad hemolítica del recién nacido" },
  },
  {
    id: "ped-018",
    topicId: "pediatria",
    subtopic: "Neonatología",
    difficulty: "intermedio",
    stem: "¿En qué momento se administra la inmunoglobulina anti-D (RhoGAM) a una embarazada Rh negativa no sensibilizada como profilaxis de rutina?",
    options: [
      "Solo después de un aborto",
      "Alrededor de las 28 semanas de gestación y nuevamente después del parto si el recién nacido es Rh positivo",
      "Únicamente si el padre es Rh negativo",
      "Nunca antes del parto, solo después",
    ],
    correctIndex: 1,
    explanation:
      "La inmunoglobulina anti-D se administra de rutina alrededor de las 28 semanas de gestación y nuevamente dentro de las 72 horas posparto si el recién nacido resulta Rh positivo, para prevenir la sensibilización materna.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 4: Enfermedad hemolítica del recién nacido" },
  },
  {
    id: "ped-019",
    topicId: "pediatria",
    subtopic: "Neonatología",
    difficulty: "intermedio",
    stem: "¿Cuál es el riesgo neonatal que es inversamente proporcional al peso al nacer en los niños con muy bajo peso al nacer (MBPN)?",
    options: [
      "El riesgo de macrosomía",
      "La morbilidad (sepsis tardía, displasia broncopulmonar, hemorragia intraventricular grave, enterocolitis necrosante)",
      "El riesgo de sobrepeso en la adolescencia",
      "El riesgo de anomalías cromosómicas",
    ],
    correctIndex: 1,
    explanation:
      "En los niños con muy bajo peso al nacer (MBPN), la morbilidad es inversamente proporcional al peso al nacer: a menor peso, mayor riesgo de sepsis tardía, displasia broncopulmonar, hemorragia intraventricular grave y enterocolitis necrosante.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 5: Prematuridad y crecimiento intrauterino retardado" },
  },
  {
    id: "ped-020",
    topicId: "pediatria",
    subtopic: "Neonatología",
    difficulty: "basico",
    stem: "¿Qué es la 'alimentación trófica' en el manejo nutricional de los recién nacidos pretérmino con muy bajo peso al nacer?",
    options: [
      "La nutrición parenteral total exclusiva",
      "La administración de cantidades muy pequeñas de alimento por vía enteral para estimular el desarrollo del aparato gastrointestinal inmaduro",
      "El uso exclusivo de fórmulas hipercalóricas",
      "La suspensión de toda alimentación hasta el alta",
    ],
    correctIndex: 1,
    explanation:
      "La alimentación trófica consiste en administrar cantidades muy pequeñas de alimento por vía enteral, con beneficios como mejoría de la motilidad digestiva, menor necesidad de nutrición parenteral y menor riesgo de sepsis y enterocolitis necrosante.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 5: Prematuridad y crecimiento intrauterino retardado" },
  },
  {
    id: "ped-021",
    topicId: "pediatria",
    subtopic: "Neonatología",
    difficulty: "intermedio",
    stem: "¿Cuál es la causa más frecuente del síndrome de dificultad respiratoria (SDR) neonatal, también llamado enfermedad de membrana hialina?",
    options: [
      "Aspiración de meconio",
      "Disminución de la producción y secreción del agente tensioactivo (surfactante)",
      "Neumotórax espontáneo",
      "Cardiopatía congénita cianótica",
    ],
    correctIndex: 1,
    explanation:
      "La causa principal del SDR es la disminución de la producción y secreción de surfactante pulmonar, cuya incidencia es inversamente proporcional a la edad gestacional (afecta al 60-80% de los prematuros menores de 28 semanas).",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 6: Síndrome de dificultad respiratoria" },
  },
  {
    id: "ped-022",
    topicId: "pediatria",
    subtopic: "Neonatología",
    difficulty: "intermedio",
    stem: "¿Qué beneficio tiene la administración de corticoides prenatales a mujeres con trabajo de parto pretérmino en riesgo de dar a luz en el plazo de una semana?",
    options: [
      "Aumenta el riesgo de hemorragia intraventricular",
      "Disminuye la mortalidad global, la necesidad de soporte ventilatorio y la incidencia de hemorragia intraventricular grave y enterocolitis necrosante",
      "No tiene ningún beneficio comprobado",
      "Solo beneficia el desarrollo neurológico a largo plazo, sin efecto respiratorio",
    ],
    correctIndex: 1,
    explanation:
      "Los corticoides prenatales (betametasona o dexametasona) reducen la mortalidad global, la duración del soporte ventilatorio, el ingreso a UCIN, y la incidencia de hemorragia intraventricular grave, enterocolitis necrosante y sepsis de comienzo precoz.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 6: Síndrome de dificultad respiratoria" },
  },
  {
    id: "ped-023",
    topicId: "pediatria",
    subtopic: "Neonatología",
    difficulty: "avanzado",
    stem: "Neonato de 34 semanas con dependencia de oxígeno >21% durante al menos 28 días, respirando aire ambiente para su edad gestacional postconcepcional de 36 semanas. Según el criterio diagnóstico, ¿qué diagnóstico corresponde?",
    options: ["Neumonía congénita", "Displasia broncopulmonar leve", "Taquipnea transitoria del recién nacido", "Hipertensión pulmonar persistente"],
    correctIndex: 1,
    explanation:
      "La displasia broncopulmonar (DBP) se define por la necesidad de oxígeno >21% durante al menos 28 días; en <32 semanas de edad gestacional, la DBP leve corresponde a respirar aire ambiente en la semana 36 desde la última regla o al dar el alta.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 6: Síndrome de dificultad respiratoria" },
  },
  {
    id: "ped-024",
    topicId: "pediatria",
    subtopic: "Crecimiento y desarrollo",
    difficulty: "intermedio",
    stem: "¿Alrededor de qué edad se establece firmemente la 'permanencia (constancia) del objeto', la comprensión de que los objetos siguen existiendo aunque no se vean?",
    options: ["2 meses", "9 meses", "24 meses", "48 meses"],
    correctIndex: 1,
    explanation:
      "Un hito fundamental del desarrollo cognitivo es la percepción de la permanencia del objeto hacia los 9 meses de edad; una vez comprendida, el lactante persiste en la búsqueda del objeto oculto.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 7: Patrones de crecimiento infantil" },
  },
  {
    id: "ped-025",
    topicId: "pediatria",
    subtopic: "Crecimiento y desarrollo",
    difficulty: "basico",
    stem: "Lactante de 9 meses que llora y se aferra a sus padres cuando una persona desconocida se le aproxima. ¿Cómo se denomina este comportamiento del desarrollo emocional?",
    options: ["Apego desorganizado", "Ansiedad ante extraños", "Trastorno de vinculación", "Regresión del desarrollo"],
    correctIndex: 1,
    explanation:
      "La ansiedad ante extraños es un comportamiento esperado del desarrollo emocional normal, que aparece cuando los lactantes miran alternativamente a la persona extraña que se aproxima y a sus padres, aferrándose o llorando con angustia.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 7: Patrones de crecimiento infantil" },
  },
  {
    id: "ped-026",
    topicId: "pediatria",
    subtopic: "Nutrición",
    difficulty: "intermedio",
    stem: "¿Cuál es la diferencia entre el indicador 'peso para la talla' y 'longitud/talla para la edad' en la valoración antropométrica infantil?",
    options: [
      "Ambos miden exactamente lo mismo",
      "Peso para la talla bajo refleja desnutrición aguda (emaciación); talla/longitud para la edad baja refleja desnutrición crónica (retraso del crecimiento)",
      "Peso para la talla mide únicamente sobrepeso; talla para la edad mide únicamente obesidad",
      "Ninguno de los dos tiene utilidad clínica",
    ],
    correctIndex: 1,
    explanation:
      "Un peso para la talla bajo (emaciación) generalmente indica desnutrición aguda, mientras que una talla/longitud para la edad baja refleja el impacto acumulado de un déficit crónico y se asocia a desnutrición crónica (retraso del crecimiento).",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 8: Índices e indicadores antropométricos" },
  },
  {
    id: "ped-027",
    topicId: "pediatria",
    subtopic: "Inmunizaciones",
    difficulty: "intermedio",
    stem: "¿En qué recién nacidos está contraindicada la aplicación de la vacuna BCG?",
    options: [
      "En todos los recién nacidos a término sanos",
      "En recién nacidos con peso al nacer menor a 2,000 gramos, historia familiar de inmunodeficiencia, o hijos de madres con VIH",
      "Únicamente en recién nacidos por cesárea",
      "En recién nacidos mayores de 2,500 gramos",
    ],
    correctIndex: 1,
    explanation:
      "La BCG (vacuna con bacteria viva atenuada) no se aplica en recién nacidos con peso al nacer menor a 2,000 gramos, historia familiar de inmunodeficiencia, o en hijos de madres infectadas por el VIH.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 9: Inmunizaciones" },
  },
  {
    id: "ped-028",
    topicId: "pediatria",
    subtopic: "Inmunizaciones",
    difficulty: "avanzado",
    stem: "¿Cuál es la ventana de edad estricta para iniciar y completar la vacunación contra rotavirus?",
    options: [
      "Cualquier edad, sin restricción",
      "Primera dosis antes de las 14 semanas y 6 días, sin iniciar después de las 15 semanas, con dosis final no después de los 8 meses de edad",
      "Solo se aplica después del año de edad",
      "Debe completarse antes del mes de vida",
    ],
    correctIndex: 1,
    explanation:
      "La vacuna contra rotavirus tiene una ventana de edad estricta: la primera dosis debe administrarse antes de las 14 semanas y 6 días (edad mínima 6 semanas), no debe iniciarse después de las 15 semanas, y la dosis final no debe aplicarse después de los 8 meses.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 9: Inmunizaciones" },
  },
  {
    id: "ped-029",
    topicId: "pediatria",
    subtopic: "Enfermedad diarreica",
    difficulty: "basico",
    stem: "¿Cuál es la causa vírica identificable más frecuente de gastroenteritis grave en niños menores de 5 años a nivel mundial?",
    options: ["Adenovirus", "Rotavirus", "Norovirus", "Astrovirus"],
    correctIndex: 1,
    explanation:
      "Las infecciones por rotavirus son la causa vírica identificable más frecuente de gastroenteritis en niños, responsables de aproximadamente 197,000 muertes al año (28% de todos los fallecimientos por diarrea en menores de 5 años).",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 10: Gastroenteritis aguda en niños" },
  },
  {
    id: "ped-030",
    topicId: "pediatria",
    subtopic: "Enfermedad diarreica",
    difficulty: "intermedio",
    stem: "¿Cuál es la composición aproximada de la solución de rehidratación oral (SRO) de baja osmolalidad de la OMS?",
    options: [
      "75 mEq/L de sodio, 64 mEq/L de cloro, 20 mEq/L de potasio y 75 mmol/L de glucosa, con osmolaridad total de 245 mOsm/L",
      "Solo agua con azúcar sin electrólitos",
      "500 mEq/L de sodio",
      "Solución exclusivamente de glucosa al 50%",
    ],
    correctIndex: 0,
    explanation:
      "La SRO de baja osmolalidad de la OMS contiene 75 mEq/L de sodio, 64 mEq/L de cloro, 20 mEq/L de potasio y 75 mmol/L de glucosa, con una osmolaridad total de 245 mOsm/L, y es el estándar global para el tratamiento de la deshidratación por diarrea.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 10: Gastroenteritis aguda en niños" },
  },
  {
    id: "ped-031",
    topicId: "pediatria",
    subtopic: "Enfermedad diarreica",
    difficulty: "intermedio",
    stem: "¿Qué beneficio tiene la suplementación con zinc oral en niños mayores de 6 meses con diarrea aguda?",
    options: [
      "No tiene ningún beneficio comprobado",
      "Disminuye la duración y gravedad de la diarrea y podría evitar la recidiva",
      "Aumenta el riesgo de deshidratación",
      "Solo es útil en diarrea crónica, no en aguda",
    ],
    correctIndex: 1,
    explanation:
      "La suplementación con zinc disminuye la duración y gravedad de la diarrea, podría evitar la recidiva y reduce la mortalidad y los ingresos hospitalarios; se recomienda zinc oral (20 mg/día) por 10-14 días en todos los niños mayores de 6 meses con diarrea aguda.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 10: Gastroenteritis aguda en niños" },
  },
  {
    id: "ped-032",
    topicId: "pediatria",
    subtopic: "Enfermedad diarreica",
    difficulty: "avanzado",
    stem: "¿Cuál es el fármaco de elección para tratar la disentería bacilar grave por Shigella en niños?",
    options: [
      "Loperamida",
      "Ciprofloxacino, ceftriaxona, ampicilina o azitromicina, según disponibilidad y resistencia local",
      "Metronidazol exclusivamente",
      "No requiere tratamiento antibiótico en ningún caso",
    ],
    correctIndex: 1,
    explanation:
      "El tratamiento antibiótico de la disentería grave por Shigella incluye ciprofloxacino, ceftriaxona, ampicilina o azitromicina, según el patrón de resistencia local, ya que muchas cepas son resistentes a los antibióticos tradicionales.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 10: Gastroenteritis aguda en niños" },
  },
  {
    id: "ped-033",
    topicId: "pediatria",
    subtopic: "Enfermedad diarreica",
    difficulty: "intermedio",
    stem: "¿Cómo se define la 'diarrea persistente' en niños?",
    options: [
      "Episodios que comenzaron de forma aguda pero con una duración de al menos 14 días",
      "Cualquier diarrea que dure más de 3 días",
      "Diarrea con sangre visible, independientemente de la duración",
      "Diarrea que ocurre exclusivamente en lactantes menores de 6 meses",
    ],
    correctIndex: 0,
    explanation:
      "La diarrea persistente se define como episodios que comenzaron de forma aguda pero con una duración de al menos 14 días; puede predisponer a deterioro nutricional, malnutrición caloricoproteica e infecciones secundarias.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 10: Gastroenteritis aguda en niños" },
  },
  {
    id: "ped-034",
    topicId: "pediatria",
    subtopic: "Infecciones respiratorias",
    difficulty: "avanzado",
    stem: "Niño de 8 años con asma que en el último año ha tenido síntomas diurnos diarios, despertares nocturnos más de una vez por semana, y uso diario de agonista β2 de acción corta. Según la clasificación de gravedad, ¿cómo se clasifica su asma?",
    options: ["Intermitente", "Persistente leve", "Persistente moderada", "Persistente grave"],
    correctIndex: 3,
    explanation:
      "Síntomas diurnos presentes a lo largo de todo el día, despertares nocturnos frecuentes (>1 vez/semana en niños ≥5 años) y uso diario de β2-agonista de acción corta corresponden a la clasificación de asma persistente grave.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 11: Asma" },
  },
  {
    id: "ped-035",
    topicId: "pediatria",
    subtopic: "Infecciones respiratorias",
    difficulty: "avanzado",
    stem: "Niño con exacerbación asmática que, tras recibir β2-agonista de acción corta y corticosteroides sistémicos, no mejora. Según el manejo escalonado de exacerbaciones agudas, ¿cuál es el siguiente paso recomendado?",
    options: [
      "Añadir ipratropio; si no mejora, considerar epinefrina IM; luego sulfato de magnesio parenteral; y como último recurso, intubar",
      "Duplicar de inmediato la dosis de corticosteroides orales sin otras medidas",
      "Suspender todo tratamiento y observar",
      "Administrar antibióticos de amplio espectro",
    ],
    correctIndex: 0,
    explanation:
      "Si el paciente no mejora con SABA y corticosteroides sistémicos, se debe añadir ipratropio; si continúa sin mejorar, considerar epinefrina IM; el siguiente paso es sulfato de magnesio parenteral (25-75 mg/kg); y el último recurso es la intubación.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 11: Asma" },
  },
  {
    id: "ped-036",
    topicId: "pediatria",
    subtopic: "Nutrición",
    difficulty: "intermedio",
    stem: "¿Cómo se define la desnutrición aguda grave en un niño?",
    options: [
      "Talla baja para la edad exclusivamente",
      "Emaciación grave (peso para la talla/longitud <-3 DE) y/o edema bilateral",
      "Cualquier pérdida de peso reciente sin importar la magnitud",
      "Perímetro braquial normal con peso bajo",
    ],
    correctIndex: 1,
    explanation:
      "La desnutrición aguda grave se define como una emaciación grave (peso para la longitud/talla por debajo de -3 DE, o perímetro del brazo <115 mm en niños de 6-59 meses) y/o edema bilateral.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 12: Nutrición, seguridad alimentaria y salud" },
  },
  {
    id: "ped-037",
    topicId: "pediatria",
    subtopic: "Nutrición",
    difficulty: "avanzado",
    stem: "Niño con desnutrición grave que, al iniciar la realimentación agresiva, desarrolla debilidad, arritmias e insuficiencia cardiorrespiratoria. ¿Cuál es la alteración electrolítica central del síndrome de realimentación?",
    options: ["Hipernatremia severa", "Hipofosfatemia grave", "Hipercalcemia", "Hiperpotasemia"],
    correctIndex: 1,
    explanation:
      "La piedra angular del síndrome de realimentación es el desarrollo de hipofosfatemia grave por captación celular de fosfato al administrar un exceso de hidratos de carbono, lo que puede causar debilidad, rabdomiólisis, arritmias e insuficiencia cardiorrespiratoria.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 12: Nutrición, seguridad alimentaria y salud" },
  },
  {
    id: "ped-038",
    topicId: "pediatria",
    subtopic: "Nutrición",
    difficulty: "intermedio",
    stem: "Niño con desnutrición grave que presenta cara de 'luna llena', edema, piel flácida con dermatosis en 'pintura desconchada' y cabello despigmentado con signo de bandera. ¿Cuál es el diagnóstico?",
    options: ["Marasmo puro", "Kwashiorkor", "Deficiencia aislada de vitamina D", "Desnutrición crónica leve"],
    correctIndex: 1,
    explanation:
      "El Kwashiorkor se caracteriza por edema, cara de 'luna llena', piel flácida y edematosa con dermatosis en 'pintura desconchada', y cabello con signo de bandera (bandas alternantes de color claro y normal), a diferencia del marasmo (emaciación grave sin edema, cara 'simiesca').",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 12: Nutrición, seguridad alimentaria y salud" },
  },
  {
    id: "ped-039",
    topicId: "pediatria",
    subtopic: "Infecciones respiratorias",
    difficulty: "intermedio",
    stem: "¿Cuál es el patógeno bacteriano más frecuente de neumonía adquirida en la comunidad en niños de 3 semanas a 4 años de edad?",
    options: ["Mycoplasma pneumoniae", "Streptococcus pneumoniae", "Staphylococcus aureus", "Chlamydia trachomatis"],
    correctIndex: 1,
    explanation:
      "Streptococcus pneumoniae es el patógeno bacteriano más común de neumonía adquirida en la comunidad en niños de 3 semanas a 4 años; Mycoplasma pneumoniae y Chlamydophila pneumoniae predominan en niños de 5 años o más.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 13: Neumonía adquirida en la comunidad" },
  },
  {
    id: "ped-040",
    topicId: "pediatria",
    subtopic: "Infecciones respiratorias",
    difficulty: "intermedio",
    stem: "¿Cuál es el tratamiento antibiótico de primera línea para la neumonía bacteriana adquirida en la comunidad en un niño con cuadro leve que no requiere ingreso hospitalario?",
    options: ["Vancomicina IV", "Amoxicilina oral (80-90 mg/kg/24h)", "Ciprofloxacino oral", "Meropenem IV"],
    correctIndex: 1,
    explanation:
      "En niños con cuadros leves de neumonía bacteriana que no precisan ingreso, se recomienda amoxicilina oral (80-90 mg/kg/24h); las alternativas incluyen cefuroxima axetilo o amoxicilina/clavulánico.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 13: Neumonía adquirida en la comunidad" },
  },
  {
    id: "ped-041",
    topicId: "pediatria",
    subtopic: "Infecciones respiratorias",
    difficulty: "avanzado",
    stem: "¿Cuáles de los siguientes hallazgos definen una 'neumonía complicada'?",
    options: [
      "Fiebre de menos de 24 horas de evolución",
      "Derrame pleural, empiema, absceso, fístula broncopleural, neumonía necrosante o síndrome de dificultad respiratoria aguda",
      "Tos productiva sin otros síntomas",
      "Cualquier neumonía tratada de forma ambulatoria",
    ],
    correctIndex: 1,
    explanation:
      "La neumonía complicada se define por la presencia de uno de los siguientes hallazgos: derrame pleural, empiema, absceso, fístula broncopleural, neumonía necrosante o síndrome de dificultad respiratoria aguda.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 13: Neumonía adquirida en la comunidad" },
  },
  {
    id: "ped-042",
    topicId: "pediatria",
    subtopic: "Urgencias pediátricas",
    difficulty: "intermedio",
    stem: "¿Cuáles son los cinco tipos principales de choque (shock) según los sistemas de clasificación habituales?",
    options: [
      "Hipovolémico, cardiogénico, distributivo, obstructivo y séptico",
      "Compensado, descompensado, reversible, irreversible y terminal",
      "Neurogénico, alérgico, tóxico, metabólico y traumático",
      "Leve, moderado, grave, crítico y terminal",
    ],
    correctIndex: 0,
    explanation:
      "Los sistemas de clasificación del shock definen 5 tipos principales: hipovolémico, cardiogénico, distributivo (incluye neurogénico y anafiláctico), obstructivo y séptico.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 14: Estado de choque" },
  },
  {
    id: "ped-043",
    topicId: "pediatria",
    subtopic: "Urgencias pediátricas",
    difficulty: "basico",
    stem: "¿Cuál es la causa más frecuente de choque hipovolémico en niños en todo el mundo?",
    options: ["Quemaduras extensas", "Diarrea y vómitos", "Traumatismo con hemorragia", "Anafilaxia"],
    correctIndex: 1,
    explanation:
      "El choque hipovolémico es la causa más frecuente de choque en niños en todo el mundo, debido en la mayoría de los casos a diarreas, vómitos, quemaduras o hemorragias, con pérdida de líquido y disminución de la precarga.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 14: Estado de choque" },
  },
  {
    id: "ped-044",
    topicId: "pediatria",
    subtopic: "Urgencias pediátricas",
    difficulty: "basico",
    stem: "Niño en estado de choque hipovolémico. ¿Cuál es el manejo inicial estándar de reposición de líquidos?",
    options: [
      "Bolos IV de 20 mL/kg de suero salino isotónico, repetidos según respuesta",
      "Restricción hídrica estricta",
      "Solo transfusión de plaquetas",
      "Diuréticos de asa en dosis altas",
    ],
    correctIndex: 0,
    explanation:
      "El tratamiento inicial del shock consiste en la administración rápida por vía IV de bolos de 20 mL/kg de suero salino isotónico, que puede repetirse hasta 60-80 mL/kg, ajustando según la frecuencia cardíaca, diuresis, relleno capilar y nivel de consciencia.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 14: Estado de choque" },
  },
  {
    id: "ped-045",
    topicId: "pediatria",
    subtopic: "Urgencias pediátricas",
    difficulty: "avanzado",
    stem: "¿Cómo se define el síndrome de respuesta inflamatoria sistémica (SRIS) en niños?",
    options: [
      "Cualquier fiebre aislada sin otros criterios",
      "2 de 4 criterios, de los cuales 1 debe ser temperatura anormal o recuento de leucocitos anormal (además de taquicardia y/o taquipnea)",
      "Únicamente hipotensión sostenida",
      "Presencia obligatoria de bacteriemia confirmada por hemocultivo",
    ],
    correctIndex: 1,
    explanation:
      "El SRIS se define por 2 de 4 criterios, de los cuales 1 debe ser temperatura anormal (>38.5°C o <36°C) o recuento de leucocitos anormal para la edad; los otros dos criterios son taquicardia y frecuencia respiratoria elevada o necesidad de ventilación mecánica.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 14: Estado de choque" },
  },
  {
    id: "ped-046",
    topicId: "pediatria",
    subtopic: "Urgencias pediátricas",
    difficulty: "avanzado",
    stem: "En un niño con sospecha de choque séptico, ¿por qué no debe retrasarse el inicio de antibióticos de amplio espectro?",
    options: [
      "Porque la administración precoz de antibióticos de amplio espectro se asocia a una disminución de la mortalidad",
      "Porque los antibióticos reemplazan la necesidad de reposición de líquidos",
      "Los antibióticos deben esperar el resultado del hemocultivo antes de iniciarse",
      "No hay evidencia de que el momento de inicio de antibióticos importe",
    ],
    correctIndex: 0,
    explanation:
      "La administración precoz de antibióticos de amplio espectro se asocia con una disminución de la mortalidad en el choque séptico; se deben obtener hemocultivos antes de iniciar antibióticos, pero esto no debe retrasar su administración.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 14: Estado de choque" },
  },
  {
    id: "ped-047",
    topicId: "pediatria",
    subtopic: "Neonatología",
    difficulty: "basico",
    stem: "¿En qué consiste la 'técnica de la madre canguro' para mantener la temperatura corporal de un recién nacido de peso extremadamente bajo?",
    options: [
      "Contacto cutáneo directo piel con piel entre la madre y el neonato, cubriendo con un gorrito y una manta",
      "Baño inmediato en agua tibia cada hora",
      "Uso exclusivo de incubadora sin contacto humano",
      "Administración de líquidos calientes por vía oral",
    ],
    correctIndex: 0,
    explanation:
      "La técnica de la madre canguro, con contacto cutáneo directo entre la madre y el neonato, cubriéndolo con un gorrito y una manta, es una alternativa segura y eficaz para mantener la temperatura corporal en recién nacidos de peso extremadamente bajo.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 5: Prematuridad y crecimiento intrauterino retardado" },
  },
  {
    id: "ped-048",
    topicId: "pediatria",
    subtopic: "Infecciones respiratorias",
    difficulty: "avanzado",
    stem: "Adolescente con neumonía atípica en quien se sospecha infección por Mycoplasma pneumoniae. ¿Qué hallazgo de laboratorio apoya este diagnóstico?",
    options: [
      "Crioaglutininas a títulos >1:64, presentes en aproximadamente el 50% de los pacientes",
      "Hemocultivo positivo en el 90% de los casos",
      "Neutrofilia extrema >40,000/mm³",
      "Eosinofilia marcada aislada",
    ],
    correctIndex: 0,
    explanation:
      "Las crioaglutininas a títulos mayores de 1:64 se encuentran en la sangre de aproximadamente el 50% de los pacientes con infecciones por M. pneumoniae; el diagnóstico definitivo también puede hacerse por PCR o seroconversión de IgG.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 13: Neumonía adquirida en la comunidad" },
  },
];
