import type { QuizQuestion } from "@/types/content";

export const saludPublicaQuestions: QuizQuestion[] = [
  {
    id: "sp-001",
    topicId: "salud-publica",
    subtopic: "Epidemiología",
    difficulty: "intermedio",
    stem: "Un estudio compara la exposición a un factor de riesgo entre casos y controles de una enfermedad rara. ¿Qué medida de asociación es la más apropiada de calcular en este diseño?",
    options: ["Riesgo relativo", "Razón de momios (odds ratio)", "Incidencia acumulada", "Tasa de mortalidad"],
    correctIndex: 1,
    explanation:
      "En estudios de casos y controles no se puede calcular incidencia directamente, por lo que la medida de asociación apropiada es la razón de momios (odds ratio), que aproxima al riesgo relativo cuando la enfermedad es rara.",
    source: { label: "Gordis — Epidemiology, 6.ª ed." },
  },
  {
    id: "sp-002",
    topicId: "salud-publica",
    subtopic: "Sistema de salud de Guatemala",
    difficulty: "basico",
    stem: "¿Cuál es el ente rector del sistema de salud pública en Guatemala?",
    options: [
      "Instituto Guatemalteco de Seguridad Social (IGSS)",
      "Ministerio de Salud Pública y Asistencia Social (MSPAS)",
      "Colegio de Médicos y Cirujanos de Guatemala",
      "Organización Panamericana de la Salud (OPS)",
    ],
    correctIndex: 1,
    explanation:
      "El MSPAS es la entidad rectora del sector salud en Guatemala, responsable de las políticas de salud pública a nivel nacional; el IGSS es el ente de seguridad social para trabajadores afiliados.",
    source: { label: "Ministerio de Salud Pública y Asistencia Social de Guatemala — Marco institucional" },
  },
  {
    id: "sp-003",
    topicId: "salud-publica",
    subtopic: "Bioestadística",
    difficulty: "intermedio",
    stem: "Una prueba diagnóstica tiene alta sensibilidad pero baja especificidad. ¿Para qué es más útil clínicamente este tipo de prueba?",
    options: [
      "Confirmar la enfermedad en pacientes con resultado positivo",
      "Descartar la enfermedad cuando el resultado es negativo (tamizaje)",
      "Determinar el pronóstico de la enfermedad",
      "Reemplazar completamente a las pruebas confirmatorias",
    ],
    correctIndex: 1,
    explanation:
      "Una prueba muy sensible tiene pocos falsos negativos, por lo que un resultado negativo prácticamente descarta la enfermedad (regla mnemotécnica SnNout), siendo ideal para tamizaje poblacional.",
    source: { label: "Gordis — Epidemiology, 6.ª ed. — Validez de pruebas diagnósticas" },
  },
  {
    id: "sp-004",
    topicId: "salud-publica",
    subtopic: "Ética médica",
    difficulty: "basico",
    stem: "Un paciente competente rechaza una transfusión sanguínea después de recibir información completa sobre riesgos y beneficios. ¿Qué principio bioético prevalece en esta decisión?",
    options: ["Beneficencia", "No maleficencia", "Autonomía", "Justicia"],
    correctIndex: 2,
    explanation:
      "El principio de autonomía respalda el derecho del paciente competente e informado a aceptar o rechazar un tratamiento, incluso si el equipo médico considera que no es la mejor opción clínica.",
    source: { label: "Beauchamp & Childress — Principles of Biomedical Ethics" },
  },
  {
    id: "sp-005",
    topicId: "salud-publica",
    subtopic: "Epidemiología",
    difficulty: "intermedio",
    stem: "Durante un brote de enfermedad transmitida por alimentos en una comunidad, ¿cuál es el primer paso en la investigación epidemiológica de campo?",
    options: [
      "Implementar cuarentena general inmediata",
      "Confirmar la existencia del brote y verificar el diagnóstico",
      "Publicar los resultados en medios de comunicación",
      "Calcular directamente la razón de momios sin más pasos previos",
    ],
    correctIndex: 1,
    explanation:
      "Los pasos clásicos de investigación de un brote inician con confirmar el diagnóstico y la existencia real del brote, antes de definir caso, contar casos, caracterizar por tiempo-lugar-persona y generar hipótesis.",
    source: { label: "CDC — Steps of an Outbreak Investigation" },
  },
  {
    id: "sp-006",
    topicId: "salud-publica",
    subtopic: "Niveles de atención",
    difficulty: "basico",
    stem: "Una campaña de vacunación infantil dirigida a prevenir la aparición de enfermedades en niños sanos corresponde a:",
    options: ["Prevención primaria", "Prevención secundaria", "Prevención terciaria", "Prevención cuaternaria"],
    correctIndex: 0,
    explanation:
      "La prevención primaria busca evitar la aparición de la enfermedad antes de que ocurra (vacunación, promoción de estilos de vida saludables); la secundaria detecta enfermedad temprana (tamizajes) y la terciaria limita el daño/discapacidad ya establecida.",
    source: { label: "OPS/OMS — Niveles de prevención en salud pública" },
  },
  {
    id: "sp-007",
    topicId: "salud-publica",
    subtopic: "Epidemiología",
    difficulty: "intermedio",
    stem: "En un estudio de cohorte prospectivo se sigue a 500 fumadores y 500 no fumadores durante 10 años para determinar la incidencia de cáncer pulmonar. ¿Qué medida de asociación puede calcularse directamente en este diseño, a diferencia de un estudio de casos y controles?",
    options: ["Razón de momios (odds ratio)", "Riesgo relativo (cociente de incidencias en cada grupo)", "Prevalencia puntual", "Razón de prevalencia únicamente"],
    correctIndex: 1,
    explanation:
      "A diferencia del diseño de casos y controles, el estudio de cohorte sigue a los grupos en el tiempo y permite calcular la incidencia en cada grupo de exposición, por lo que el riesgo relativo (cociente de incidencias) puede obtenerse directamente.",
    source: { label: "Gordis — Epidemiology, 6.ª ed." },
  },
  {
    id: "sp-008",
    topicId: "salud-publica",
    subtopic: "Epidemiología",
    difficulty: "intermedio",
    stem: "En un estudio se observa asociación entre consumo de café y cáncer de pulmón, pero al ajustar por tabaquismo la asociación desaparece. ¿Qué fenómeno explica mejor este hallazgo?",
    options: ["Sesgo de selección", "Variable de confusión (confusor)", "Sesgo de memoria", "Modificación del efecto (interacción)"],
    correctIndex: 1,
    explanation:
      "El tabaquismo actúa como variable de confusión: se asocia de forma independiente tanto con el consumo de café como con el cáncer de pulmón, generando una asociación espuria que desaparece al ajustar estadísticamente por él.",
    source: { label: "Gordis — Epidemiology, 6.ª ed." },
  },
  {
    id: "sp-009",
    topicId: "salud-publica",
    subtopic: "Epidemiología",
    difficulty: "avanzado",
    stem: "Una prueba de tamizaje tiene alta sensibilidad y alta especificidad, pero un valor predictivo positivo bajo cuando se aplica en cierta población. ¿Cuál es la explicación más probable?",
    options: [
      "La prueba es de mala calidad técnica",
      "La prevalencia de la enfermedad en esa población es baja",
      "La sensibilidad fue calculada incorrectamente",
      "El valor predictivo positivo no depende de la prevalencia",
    ],
    correctIndex: 1,
    explanation:
      "El valor predictivo positivo depende fuertemente de la prevalencia de la enfermedad en la población estudiada: incluso con pruebas muy sensibles y específicas, si la prevalencia es baja, la mayoría de los resultados positivos serán falsos positivos.",
    source: { label: "Gordis — Epidemiology, 6.ª ed. — Validez de pruebas diagnósticas" },
  },
  {
    id: "sp-010",
    topicId: "salud-publica",
    subtopic: "Epidemiología",
    difficulty: "basico",
    stem: "¿Cuál de las siguientes describe mejor la diferencia entre incidencia y prevalencia?",
    options: [
      "La incidencia mide los casos nuevos en un periodo; la prevalencia mide todos los casos existentes en un momento dado",
      "Ambas miden exactamente lo mismo, solo cambia el nombre según el país",
      "La prevalencia siempre es mayor que la incidencia en enfermedades agudas",
      "La incidencia solo puede medirse en estudios de corte transversal",
    ],
    correctIndex: 0,
    explanation:
      "La incidencia cuantifica los casos nuevos que aparecen durante un periodo definido, mientras que la prevalencia cuantifica todos los casos (nuevos y antiguos) existentes en un momento o periodo dado, reflejando tanto la incidencia como la duración de la enfermedad.",
    source: { label: "Gordis — Epidemiology, 6.ª ed." },
  },
  {
    id: "sp-011",
    topicId: "salud-publica",
    subtopic: "Epidemiología",
    difficulty: "intermedio",
    stem: "En un estudio de casos y controles sobre malformaciones congénitas, las madres de niños afectados recuerdan con mayor detalle su exposición a medicamentos durante el embarazo que las madres de niños sanos. ¿Qué tipo de sesgo describe esta situación?",
    options: ["Sesgo de selección", "Sesgo de memoria (recall bias)", "Sesgo del observador", "Confusión residual"],
    correctIndex: 1,
    explanation:
      "El sesgo de memoria ocurre cuando los casos (afectados) recuerdan o reportan la exposición de forma distinta a los controles, típicamente porque buscan una explicación a su enfermedad, lo que distorsiona la asociación estimada.",
    source: { label: "Gordis — Epidemiology, 6.ª ed." },
  },
  {
    id: "sp-012",
    topicId: "salud-publica",
    subtopic: "Epidemiología",
    difficulty: "intermedio",
    stem: "Si la incidencia de una enfermedad es de 20 por 1000 en expuestos y de 5 por 1000 en no expuestos, ¿cuál es el riesgo atribuible (diferencia de riesgos) asociado a la exposición?",
    options: ["4 por 1000", "15 por 1000", "25 por 1000", "0.25 por 1000"],
    correctIndex: 1,
    explanation:
      "El riesgo atribuible es la diferencia entre la incidencia en expuestos y no expuestos (20 − 5 = 15 por 1000) y representa el exceso de riesgo directamente atribuible a la exposición.",
    source: { label: "Gordis — Epidemiology, 6.ª ed." },
  },
  {
    id: "sp-013",
    topicId: "salud-publica",
    subtopic: "Bioestadística",
    difficulty: "intermedio",
    stem: "Un estudio reporta un valor de p = 0.03 al comparar dos tratamientos, con un nivel de significancia preestablecido de 0.05. ¿Cuál es la interpretación correcta?",
    options: [
      "Existe un 3% de probabilidad de que el tratamiento funcione",
      "Si la hipótesis nula fuera cierta, la probabilidad de observar una diferencia igual o más extrema que la encontrada es del 3%",
      "El tratamiento es 97% efectivo",
      "El resultado no tiene significancia estadística",
    ],
    correctIndex: 1,
    explanation:
      "El valor de p es la probabilidad de obtener un resultado igual o más extremo que el observado, asumiendo que la hipótesis nula es verdadera; con p = 0.03 (menor que 0.05), el resultado se considera estadísticamente significativo.",
    source: { label: "Dawson & Trapp — Basic & Clinical Biostatistics" },
  },
  {
    id: "sp-014",
    topicId: "salud-publica",
    subtopic: "Bioestadística",
    difficulty: "intermedio",
    stem: "Un intervalo de confianza del 95% para una razón de momios es 0.8–1.5. ¿Qué se puede concluir?",
    options: [
      "La asociación es estadísticamente significativa",
      "El intervalo incluye el valor nulo (1), por lo que no hay evidencia de asociación estadísticamente significativa",
      "El riesgo se reduce en un 80%",
      "El estudio no es válido",
    ],
    correctIndex: 1,
    explanation:
      "Cuando el intervalo de confianza de una razón de momios o riesgo relativo incluye el valor 1 (el valor nulo, sin asociación), el resultado no es estadísticamente significativo al nivel de confianza usado.",
    source: { label: "Dawson & Trapp — Basic & Clinical Biostatistics" },
  },
  {
    id: "sp-015",
    topicId: "salud-publica",
    subtopic: "Bioestadística",
    difficulty: "basico",
    stem: "En una distribución de ingresos con fuerte asimetría hacia valores altos (algunos ingresos extremadamente elevados), ¿qué medida de tendencia central es menos sensible a esos valores extremos?",
    options: ["Media aritmética", "Mediana", "Desviación estándar", "Rango"],
    correctIndex: 1,
    explanation:
      "La mediana (el valor central de los datos ordenados) es resistente a valores extremos, mientras que la media aritmética se ve fuertemente desplazada por ellos en distribuciones asimétricas.",
    source: { label: "Dawson & Trapp — Basic & Clinical Biostatistics" },
  },
  {
    id: "sp-016",
    topicId: "salud-publica",
    subtopic: "Bioestadística",
    difficulty: "basico",
    stem: "¿Qué prueba estadística es apropiada para comparar la frecuencia de un desenlace categórico (sí/no) entre dos grupos independientes?",
    options: ["Prueba t de Student", "Correlación de Pearson", "Prueba de chi cuadrado", "Análisis de varianza (ANOVA)"],
    correctIndex: 2,
    explanation:
      "La prueba de chi cuadrado (χ²) se usa para comparar proporciones o frecuencias de variables categóricas entre grupos independientes; la t de Student compara medias, y el ANOVA compara medias entre 3 o más grupos.",
    source: { label: "Dawson & Trapp — Basic & Clinical Biostatistics" },
  },
  {
    id: "sp-017",
    topicId: "salud-publica",
    subtopic: "Bioestadística",
    difficulty: "avanzado",
    stem: "Un estudio no detecta diferencia estadísticamente significativa entre dos grupos, pero el tamaño de muestra fue muy pequeño. Si en realidad sí existía una diferencia real, ¿qué tipo de error es más probable que se haya cometido?",
    options: [
      "Error tipo I (falso positivo)",
      "Error tipo II (falso negativo), por baja potencia estadística",
      "Sesgo de selección",
      "Sesgo de confusión",
    ],
    correctIndex: 1,
    explanation:
      "Un tamaño de muestra insuficiente reduce la potencia estadística del estudio, aumentando el riesgo de error tipo II: no detectar una diferencia real que sí existe (falso negativo).",
    source: { label: "Dawson & Trapp — Basic & Clinical Biostatistics" },
  },
  {
    id: "sp-018",
    topicId: "salud-publica",
    subtopic: "Bioestadística",
    difficulty: "intermedio",
    stem: "Un estudio ecológico encuentra que los países con mayor consumo de cierto alimento tienen mejores indicadores de salud. ¿Qué principio advierte contra interpretar directamente esto como una relación causal a nivel individual?",
    options: [
      "La correlación no implica causalidad; podría deberse a un factor de confusión (ej. nivel de desarrollo económico) o a la falacia ecológica",
      "Este tipo de estudio siempre demuestra causalidad directa",
      "Los estudios ecológicos son el diseño de mayor jerarquía causal",
      "No aplica ningún criterio de causalidad a estudios poblacionales",
    ],
    correctIndex: 0,
    explanation:
      "Los estudios ecológicos comparan grupos poblacionales, no individuos, por lo que una asociación a nivel poblacional puede no reflejar la relación real a nivel individual (falacia ecológica), y siempre debe considerarse la posibilidad de confusión.",
    source: { label: "Gordis — Epidemiology, 6.ª ed." },
  },
  {
    id: "sp-019",
    topicId: "salud-publica",
    subtopic: "Sistema de salud de Guatemala",
    difficulty: "basico",
    stem: "En la red de servicios del Ministerio de Salud Pública y Asistencia Social (MSPAS) de Guatemala, ¿qué caracteriza al primer nivel de atención?",
    options: [
      "Hospitales nacionales de referencia con subespecialidades",
      "Puestos de salud y centros de convergencia orientados a promoción, prevención y atención ambulatoria básica",
      "Hospitales regionales con quirófano y encamamiento especializado",
      "Exclusivamente atención privada",
    ],
    correctIndex: 1,
    explanation:
      "El primer nivel de atención es la puerta de entrada al sistema: puestos de salud y centros comunitarios enfocados en promoción de la salud, prevención y atención ambulatoria de baja complejidad, más cercanos a la comunidad.",
    source: { label: "Ministerio de Salud Pública y Asistencia Social de Guatemala — Marco institucional" },
  },
  {
    id: "sp-020",
    topicId: "salud-publica",
    subtopic: "Sistema de salud de Guatemala",
    difficulty: "basico",
    stem: "¿Qué tipo de establecimiento corresponde típicamente al segundo nivel de atención en la red del MSPAS?",
    options: [
      "Puesto de salud rural",
      "Centros de Atención Permanente (CAP) / centros de salud con camas y hospitales distritales",
      "Hospital nacional de tercer nivel con subespecialidades",
      "Clínica privada de especialidad",
    ],
    correctIndex: 1,
    explanation:
      "El segundo nivel agrega mayor capacidad resolutiva que el primer nivel (partos, cirugías menores, encamamiento básico) sin llegar a la complejidad de los hospitales nacionales de referencia del tercer nivel.",
    source: { label: "Ministerio de Salud Pública y Asistencia Social de Guatemala — Marco institucional" },
  },
  {
    id: "sp-021",
    topicId: "salud-publica",
    subtopic: "Sistema de salud de Guatemala",
    difficulty: "basico",
    stem: "¿A qué población atiende primariamente el Instituto Guatemalteco de Seguridad Social (IGSS)?",
    options: [
      "A toda la población guatemalteca sin excepción",
      "A los trabajadores afiliados (sector formal) y sus beneficiarios, mediante el régimen de seguridad social",
      "Únicamente a la población rural sin acceso a otros servicios",
      "Solo a pacientes con enfermedades crónicas",
    ],
    correctIndex: 1,
    explanation:
      "El IGSS opera un régimen de seguridad social contributivo dirigido a trabajadores del sector formal afiliados y sus beneficiarios, distinto de la cobertura universal que en teoría corresponde al MSPAS.",
    source: { label: "Ministerio de Salud Pública y Asistencia Social de Guatemala — Marco institucional" },
  },
  {
    id: "sp-022",
    topicId: "salud-publica",
    subtopic: "Sistema de salud de Guatemala",
    difficulty: "intermedio",
    stem: "El sistema de salud de Guatemala se describe frecuentemente como \"segmentado\". ¿A qué se refiere este término?",
    options: [
      "A que existe un único pagador público universal",
      "A la coexistencia de subsistemas separados (MSPAS, IGSS, sector privado, ONG) con poca integración entre sí, cada uno atendiendo a distintos grupos poblacionales",
      "A que el país está dividido geográficamente en zonas sin comunicación entre sí",
      "A la clasificación administrativa de enfermedades por gravedad",
    ],
    correctIndex: 1,
    explanation:
      "La segmentación describe la fragmentación del sistema en subsistemas paralelos (público, seguridad social, privado, ONG) con distinta población cubierta, financiamiento y capacidad resolutiva, con escasa coordinación entre ellos — un rasgo común en los sistemas de salud centroamericanos.",
    source: { label: "OPS/OMS — Perfil de sistemas de salud de Centroamérica" },
  },
  {
    id: "sp-023",
    topicId: "salud-publica",
    subtopic: "Sistema de salud de Guatemala",
    difficulty: "intermedio",
    stem: "El Programa de Extensión de Cobertura (PEC) en Guatemala fue una estrategia orientada principalmente a:",
    options: [
      "Construir hospitales de tercer nivel en la capital",
      "Llevar un paquete básico de servicios de salud a población rural dispersa sin acceso regular a servicios del MSPAS",
      "Financiar exclusivamente medicina privada",
      "Reemplazar por completo al IGSS",
    ],
    correctIndex: 1,
    explanation:
      "El PEC surgió como estrategia para ampliar el acceso a un paquete básico de servicios (principalmente materno-infantiles y de inmunización) en áreas rurales donde la red fija del MSPAS tenía baja cobertura.",
    source: { label: "Ministerio de Salud Pública y Asistencia Social de Guatemala — Marco institucional" },
  },
  {
    id: "sp-024",
    topicId: "salud-publica",
    subtopic: "Sistema de salud de Guatemala",
    difficulty: "basico",
    stem: "En Guatemala, ¿qué sistema utiliza el personal de salud para el registro y reporte de información de vigilancia y gestión sanitaria del MSPAS?",
    options: [
      "SIGSA (Sistema de Información Gerencial de Salud)",
      "Una llamada telefónica informal sin registro",
      "Únicamente el expediente clínico privado, sin reporte al MSPAS",
      "No existe ningún sistema de información en salud en Guatemala",
    ],
    correctIndex: 0,
    explanation:
      "El SIGSA es el sistema oficial del MSPAS para el registro, reporte y gestión de información de los servicios de salud, incluida la notificación de eventos de vigilancia epidemiológica.",
    source: { label: "Ministerio de Salud Pública y Asistencia Social de Guatemala — Marco institucional" },
  },
  {
    id: "sp-025",
    topicId: "salud-publica",
    subtopic: "Sistema de salud de Guatemala",
    difficulty: "intermedio",
    stem: "La función de \"rectoría\" del MSPAS sobre el sector salud en Guatemala implica principalmente:",
    options: [
      "Prestar directamente todos los servicios médicos del país sin excepción",
      "Definir políticas, normar, regular y vigilar a todos los actores del sector salud, tanto públicos como privados",
      "Administrar únicamente los hospitales privados",
      "Sustituir la función del Congreso de la República en materia de salud",
    ],
    correctIndex: 1,
    explanation:
      "Como ente rector, el MSPAS tiene la responsabilidad de conducción, regulación y vigilancia de todo el sector salud del país, más allá de los servicios que presta directamente.",
    source: { label: "Ministerio de Salud Pública y Asistencia Social de Guatemala — Marco institucional" },
  },
  {
    id: "sp-026",
    topicId: "salud-publica",
    subtopic: "Niveles de atención",
    difficulty: "basico",
    stem: "La realización de una mamografía de tamizaje en una mujer asintomática de 50 años corresponde a:",
    options: ["Prevención primaria", "Prevención secundaria (detección temprana)", "Prevención terciaria", "Prevención primordial"],
    correctIndex: 1,
    explanation:
      "El tamizaje busca detectar la enfermedad en una etapa temprana asintomática, lo que corresponde a prevención secundaria, a diferencia de la prevención primaria que evita que la enfermedad aparezca.",
    source: { label: "OPS/OMS — Niveles de prevención en salud pública" },
  },
  {
    id: "sp-027",
    topicId: "salud-publica",
    subtopic: "Niveles de atención",
    difficulty: "basico",
    stem: "La rehabilitación física de un paciente tras un evento cerebrovascular, orientada a reducir la discapacidad residual, corresponde a:",
    options: ["Prevención primaria", "Prevención secundaria", "Prevención terciaria", "Prevención primordial"],
    correctIndex: 2,
    explanation:
      "La prevención terciaria actúa una vez establecida la enfermedad, buscando limitar el daño, evitar complicaciones y rehabilitar al paciente para reducir la discapacidad resultante.",
    source: { label: "OPS/OMS — Niveles de prevención en salud pública" },
  },
  {
    id: "sp-028",
    topicId: "salud-publica",
    subtopic: "Niveles de atención",
    difficulty: "avanzado",
    stem: "Una política pública que grava los productos ultraprocesados para reducir la exposición poblacional a factores de riesgo cardiometabólico, antes de que estos factores se establezcan en los individuos, es un ejemplo de:",
    options: ["Prevención terciaria", "Prevención cuaternaria", "Prevención primordial", "Prevención secundaria"],
    correctIndex: 2,
    explanation:
      "La prevención primordial actúa sobre las condiciones sociales, económicas y ambientales que dan origen a los factores de riesgo, antes de que estos aparezcan en la población, a diferencia de la prevención primaria que actúa una vez el factor de riesgo ya está presente en el individuo.",
    source: { label: "OPS/OMS — Niveles de prevención en salud pública" },
  },
  {
    id: "sp-029",
    topicId: "salud-publica",
    subtopic: "Niveles de atención",
    difficulty: "intermedio",
    stem: "Evitar solicitar estudios o tratamientos innecesarios a un paciente de bajo riesgo, para prevenir el daño derivado del sobrediagnóstico o la sobremedicalización, corresponde al concepto de:",
    options: ["Prevención primaria", "Prevención secundaria", "Prevención terciaria", "Prevención cuaternaria"],
    correctIndex: 3,
    explanation:
      "La prevención cuaternaria busca proteger al paciente de intervenciones médicas innecesarias o excesivas, evitando el daño iatrogénico derivado del sobrediagnóstico y el sobretratamiento.",
    source: { label: "WONCA — Conceptos de prevención cuaternaria" },
  },
  {
    id: "sp-030",
    topicId: "salud-publica",
    subtopic: "Ética médica",
    difficulty: "avanzado",
    stem: "Un paciente con tuberculosis pulmonar bacilífera se niega a informar a su familia conviviente sobre su diagnóstico, pese a que esto los expone a contagio. ¿Qué consideración puede justificar limitar la confidencialidad estricta en este caso?",
    options: [
      "El principio de autonomía absoluta del paciente prevalece siempre",
      "El deber de proteger a terceros en riesgo real de daño puede justificar romper la confidencialidad en situaciones excepcionales",
      "La confidencialidad nunca puede limitarse bajo ninguna circunstancia",
      "El paciente pierde todos sus derechos al ser diagnosticado",
    ],
    correctIndex: 1,
    explanation:
      "Aunque la confidencialidad es un deber fundamental, existen excepciones reconocidas cuando hay un riesgo real e identificable de daño grave a terceros (como el contagio de una enfermedad transmisible), situación en la que puede justificarse informar a los contactos en riesgo.",
    source: { label: "Beauchamp & Childress — Principles of Biomedical Ethics" },
  },
  {
    id: "sp-031",
    topicId: "salud-publica",
    subtopic: "Ética médica",
    difficulty: "basico",
    stem: "¿Cuál de los siguientes es un elemento indispensable para que un consentimiento informado sea válido?",
    options: [
      "Que el paciente firme cualquier documento, sin importar si comprendió la información",
      "Que el paciente reciba información comprensible sobre riesgos, beneficios y alternativas, y decida voluntariamente sin coacción",
      "Que el médico decida por el paciente lo que es mejor, sin explicarle las opciones",
      "Que solo se informe si el paciente pregunta explícitamente",
    ],
    correctIndex: 1,
    explanation:
      "El consentimiento informado requiere tres elementos esenciales: información adecuada y comprensible, capacidad del paciente para decidir, y voluntariedad (ausencia de coacción); la sola firma de un documento sin comprensión no lo hace válido.",
    source: { label: "Beauchamp & Childress — Principles of Biomedical Ethics" },
  },
  {
    id: "sp-032",
    topicId: "salud-publica",
    subtopic: "Ética médica",
    difficulty: "basico",
    stem: "¿Cuál es la diferencia principal entre los principios de beneficencia y no maleficencia en bioética?",
    options: [
      "Son sinónimos, no existe diferencia práctica",
      "La beneficencia implica actuar activamente a favor del bienestar del paciente; la no maleficencia implica el deber de no causar daño (\"primum non nocere\")",
      "La no maleficencia solo aplica en el ámbito quirúrgico",
      "La beneficencia se limita exclusivamente al ámbito de la investigación",
    ],
    correctIndex: 1,
    explanation:
      "La beneficencia es un deber activo de promover el bienestar del paciente, mientras que la no maleficencia es el deber, más básico, de abstenerse de causar daño — el clásico \"primum non nocere\".",
    source: { label: "Beauchamp & Childress — Principles of Biomedical Ethics" },
  },
  {
    id: "sp-033",
    topicId: "salud-publica",
    subtopic: "Ética médica",
    difficulty: "intermedio",
    stem: "Durante una emergencia con recursos limitados (por ejemplo, camas de cuidados intensivos insuficientes), priorizar su asignación según criterios clínicos objetivos y equitativos, y no por capacidad de pago o estatus social, refleja el principio bioético de:",
    options: ["Autonomía", "Beneficencia", "Justicia", "No maleficencia"],
    correctIndex: 2,
    explanation:
      "El principio de justicia exige una distribución equitativa de los recursos sanitarios, especialmente relevante en contextos de escasez, donde deben usarse criterios objetivos y no discriminatorios.",
    source: { label: "Beauchamp & Childress — Principles of Biomedical Ethics" },
  },
  {
    id: "sp-034",
    topicId: "salud-publica",
    subtopic: "Ética médica",
    difficulty: "intermedio",
    stem: "¿Qué documento internacional establece los principios éticos fundamentales vigentes para la investigación médica en seres humanos, incluida la necesidad de consentimiento informado y aprobación por un comité de ética?",
    options: [
      "Únicamente el Código de Núremberg",
      "La Declaración de Helsinki de la Asociación Médica Mundial",
      "El Juramento Hipocrático original",
      "La Constitución Política de la República de Guatemala",
    ],
    correctIndex: 1,
    explanation:
      "Aunque el Código de Núremberg (1947) fue el primer antecedente tras los juicios de Núremberg, la Declaración de Helsinki de la Asociación Médica Mundial (1964, con revisiones posteriores) es el documento de referencia vigente que rige la ética de la investigación médica en humanos.",
    source: { label: "Asociación Médica Mundial — Declaración de Helsinki" },
  },
  {
    id: "sp-035",
    topicId: "salud-publica",
    subtopic: "Vigilancia epidemiológica",
    difficulty: "basico",
    stem: "En vigilancia epidemiológica, ¿para qué sirve establecer una \"definición de caso\" estandarizada al inicio de la investigación de un brote?",
    options: [
      "Para inculpar legalmente a un responsable del brote",
      "Para clasificar de manera uniforme y reproducible quién se considera un caso, permitiendo contar y comparar casos de forma consistente",
      "Es un paso opcional, sin utilidad práctica real",
      "Únicamente para fines de facturación hospitalaria",
    ],
    correctIndex: 1,
    explanation:
      "Una definición de caso estandarizada (criterios clínicos, de laboratorio, tiempo y lugar) permite que distintos investigadores clasifiquen de forma consistente quién cuenta como caso, esencial para contar, comparar y analizar el brote.",
    source: { label: "CDC — Principles of Epidemiology in Public Health Practice" },
  },
  {
    id: "sp-036",
    topicId: "salud-publica",
    subtopic: "Vigilancia epidemiológica",
    difficulty: "intermedio",
    stem: "Una curva epidémica muestra un ascenso abrupto de casos que alcanza un pico único y luego desciende, todo dentro de un periodo compatible con un solo periodo de incubación. ¿Qué patrón de brote sugiere esta curva?",
    options: [
      "Brote de fuente común puntual (exposición única compartida)",
      "Brote de transmisión persona a persona sostenida (propagado)",
      "Brote de fuente continua",
      "Enfermedad endémica estable, sin brote",
    ],
    correctIndex: 0,
    explanation:
      "Un pico único y abrupto dentro de un solo periodo de incubación es característico de un brote de fuente común puntual, donde todos los casos comparten una exposición breve y compartida (ej. un alimento contaminado en un evento).",
    source: { label: "CDC — Principles of Epidemiology in Public Health Practice" },
  },
  {
    id: "sp-037",
    topicId: "salud-publica",
    subtopic: "Vigilancia epidemiológica",
    difficulty: "basico",
    stem: "¿Cuál de las siguientes es una enfermedad de notificación obligatoria e inmediata en el sistema de vigilancia epidemiológica de Guatemala, dado su potencial epidémico?",
    options: ["Resfriado común", "Sarampión", "Cefalea tensional crónica", "Dermatitis de contacto leve"],
    correctIndex: 1,
    explanation:
      "El sarampión, por su alto potencial de transmisión y de generar brotes, es una enfermedad de notificación obligatoria e inmediata dentro del sistema de vigilancia epidemiológica del MSPAS.",
    source: { label: "Ministerio de Salud Pública y Asistencia Social de Guatemala — Marco institucional" },
  },
  {
    id: "sp-038",
    topicId: "salud-publica",
    subtopic: "Vigilancia epidemiológica",
    difficulty: "intermedio",
    stem: "¿Cuál de los siguientes es un atributo deseable de un sistema de vigilancia epidemiológica, según los criterios estándar de evaluación de estos sistemas?",
    options: [
      "Que sea lento y burocrático, para evitar falsas alarmas",
      "Oportunidad (rapidez para detectar y reportar eventos) y sensibilidad para detectar la mayoría de los casos reales",
      "Que dependa exclusivamente de reportes voluntarios anónimos, sin verificación",
      "Que solo reporte los casos que terminan en fallecimiento",
    ],
    correctIndex: 1,
    explanation:
      "Los atributos clave de un buen sistema de vigilancia incluyen sensibilidad, oportunidad, simplicidad, flexibilidad y representatividad, permitiendo detectar y actuar sobre eventos de salud pública a tiempo.",
    source: { label: "CDC — Updated Guidelines for Evaluating Public Health Surveillance Systems" },
  },
  {
    id: "sp-039",
    topicId: "salud-publica",
    subtopic: "Vigilancia epidemiológica",
    difficulty: "intermedio",
    stem: "La vigilancia centinela consiste en:",
    options: [
      "Reportar el 100% de los casos de todas las enfermedades en todo el territorio nacional",
      "Monitorear una enfermedad o evento a través de una red seleccionada de sitios representativos, en vez de la totalidad del sistema de salud",
      "Una modalidad exclusiva para enfermedades no transmisibles",
      "Un sistema que reemplaza por completo la notificación obligatoria",
    ],
    correctIndex: 1,
    explanation:
      "La vigilancia centinela usa una red limitada pero representativa de establecimientos o laboratorios para monitorear tendencias de una enfermedad, siendo más ágil y económica que la vigilancia universal, aunque no reemplaza la notificación obligatoria de eventos de alto impacto.",
    source: { label: "CDC — Principles of Epidemiology in Public Health Practice" },
  },
  {
    id: "sp-040",
    topicId: "salud-publica",
    subtopic: "Promoción de la salud",
    difficulty: "basico",
    stem: "La Carta de Ottawa (1986) es un documento fundacional de:",
    options: [
      "La medicina basada en evidencia",
      "La promoción de la salud, que define áreas de acción como políticas públicas saludables y entornos favorables",
      "La bioética contemporánea",
      "La Clasificación Internacional de Enfermedades",
    ],
    correctIndex: 1,
    explanation:
      "La Carta de Ottawa, adoptada en la Primera Conferencia Internacional sobre la Promoción de la Salud (OMS, 1986), estableció las bases conceptuales y las áreas de acción prioritarias de la promoción de la salud moderna.",
    source: { label: "OMS — Carta de Ottawa para la Promoción de la Salud" },
  },
  {
    id: "sp-041",
    topicId: "salud-publica",
    subtopic: "Promoción de la salud",
    difficulty: "intermedio",
    stem: "¿Cuál es la diferencia principal entre educación para la salud y promoción de la salud?",
    options: [
      "Son términos idénticos, sin diferencia conceptual",
      "La educación para la salud se centra en transmitir conocimientos individuales, mientras que la promoción de la salud aborda también los determinantes sociales, políticos y ambientales",
      "La promoción de la salud solo puede aplicarse dentro de hospitales",
      "La educación para la salud reemplaza a la vacunación",
    ],
    correctIndex: 1,
    explanation:
      "La educación para la salud es un componente (transmisión de conocimientos y habilidades individuales), mientras que la promoción de la salud es un enfoque más amplio que incluye políticas públicas, entornos favorables y participación comunitaria.",
    source: { label: "OMS — Carta de Ottawa para la Promoción de la Salud" },
  },
  {
    id: "sp-042",
    topicId: "salud-publica",
    subtopic: "Promoción de la salud",
    difficulty: "intermedio",
    stem: "El enfoque de \"entornos saludables\" (ej. escuelas saludables, municipios saludables) en promoción de la salud busca principalmente:",
    options: [
      "Enfocarse únicamente en el tratamiento médico individual",
      "Modificar el entorno físico y social donde las personas viven, estudian y trabajan, para facilitar decisiones saludables",
      "Sustituir por completo la atención primaria de salud",
      "Aplicarse exclusivamente a nivel hospitalario",
    ],
    correctIndex: 1,
    explanation:
      "El enfoque de entornos saludables busca que los espacios cotidianos (escuela, trabajo, municipio) faciliten y apoyen decisiones saludables, en línea con las áreas de acción de la Carta de Ottawa.",
    source: { label: "OMS — Carta de Ottawa para la Promoción de la Salud" },
  },
  {
    id: "sp-043",
    topicId: "salud-publica",
    subtopic: "Promoción de la salud",
    difficulty: "basico",
    stem: "La capacidad de una persona para obtener, procesar y comprender información básica de salud necesaria para tomar decisiones adecuadas se conoce como:",
    options: ["Adherencia terapéutica", "Alfabetización en salud (health literacy)", "Consentimiento informado", "Autoeficacia"],
    correctIndex: 1,
    explanation:
      "La alfabetización en salud describe la capacidad individual de acceder, entender y usar información de salud para tomar decisiones apropiadas, y es un determinante importante de los resultados en salud.",
    source: { label: "OMS — Promoción de la salud" },
  },
  {
    id: "sp-044",
    topicId: "salud-publica",
    subtopic: "Programas nacionales de salud",
    difficulty: "basico",
    stem: "El Programa Ampliado de Inmunizaciones (PAI) tiene como objetivo principal:",
    options: [
      "Reducir la morbimortalidad por enfermedades prevenibles por vacunación, mediante esquemas nacionales de inmunización",
      "Tratar enfermedades crónicas del adulto",
      "Reemplazar la atención prenatal",
      "Vigilar exclusivamente enfermedades no transmisibles",
    ],
    correctIndex: 0,
    explanation:
      "El PAI, impulsado regionalmente por la OPS/OMS, busca garantizar el acceso universal a vacunas para reducir la morbimortalidad por enfermedades prevenibles mediante inmunización en la niñez y otros grupos.",
    source: { label: "OPS/OMS — Programa Ampliado de Inmunizaciones" },
  },
  {
    id: "sp-045",
    topicId: "salud-publica",
    subtopic: "Programas nacionales de salud",
    difficulty: "basico",
    stem: "La \"cadena de frío\" en un programa de vacunación se refiere a:",
    options: [
      "El transporte de pacientes en ambulancias refrigeradas",
      "El conjunto de procesos y equipos que mantienen la temperatura adecuada de las vacunas desde su fabricación hasta su aplicación",
      "Un protocolo de aislamiento hospitalario",
      "El almacenamiento de medicamentos vencidos",
    ],
    correctIndex: 1,
    explanation:
      "La cadena de frío garantiza que las vacunas se mantengan dentro del rango de temperatura adecuado en todas las etapas (fabricación, transporte, almacenamiento, aplicación), preservando su eficacia.",
    source: { label: "OPS/OMS — Programa Ampliado de Inmunizaciones" },
  },
  {
    id: "sp-046",
    topicId: "salud-publica",
    subtopic: "Programas nacionales de salud",
    difficulty: "intermedio",
    stem: "Guatemala presenta una de las prevalencias más altas de desnutrición crónica infantil de América Latina. ¿Qué indicador antropométrico se utiliza principalmente para diagnosticarla?",
    options: [
      "Peso para la talla",
      "Talla para la edad (retraso en el crecimiento lineal, \"stunting\")",
      "Circunferencia braquial únicamente",
      "Índice de masa corporal en menores de 1 año",
    ],
    correctIndex: 1,
    explanation:
      "La desnutrición crónica (retraso en talla o \"stunting\") se evalúa mediante el indicador talla/longitud para la edad, a diferencia de la desnutrición aguda, que se evalúa con el indicador peso para la talla.",
    source: { label: "OPS/OMS — Indicadores antropométricos de desnutrición" },
  },
  {
    id: "sp-047",
    topicId: "salud-publica",
    subtopic: "Programas nacionales de salud",
    difficulty: "basico",
    stem: "Un programa nacional de planificación familiar orientado a ampliar el acceso a métodos anticonceptivos y consejería tiene como objetivo de salud pública principal:",
    options: [
      "Reducir embarazos no planificados y contribuir a disminuir la mortalidad materna asociada",
      "Aumentar la tasa de natalidad sin ninguna condición",
      "Sustituir por completo el control prenatal",
      "Aplicarse únicamente a mujeres mayores de 40 años",
    ],
    correctIndex: 0,
    explanation:
      "El acceso a planificación familiar reduce embarazos no planificados y el intervalo intergenésico corto, ambos asociados a mayor riesgo materno-perinatal, contribuyendo así a reducir la mortalidad materna.",
    source: { label: "OPS/OMS — Salud sexual y reproductiva" },
  },
  {
    id: "sp-048",
    topicId: "salud-publica",
    subtopic: "Salud materno-infantil",
    difficulty: "intermedio",
    stem: "¿Cómo se calcula la razón de mortalidad materna?",
    options: [
      "Número de muertes maternas / número de mujeres en edad fértil × 1000",
      "Número de muertes maternas por causas relacionadas con el embarazo, parto o puerperio / número de nacidos vivos × 100,000",
      "Número de muertes maternas / número total de defunciones × 100",
      "Número de muertes maternas / número de partos institucionales únicamente",
    ],
    correctIndex: 1,
    explanation:
      "La razón de mortalidad materna se expresa como el número de muertes maternas por cada 100,000 nacidos vivos en un periodo determinado, un indicador clave de la calidad de la atención obstétrica de un país.",
    source: { label: "OPS/OMS — Indicadores de salud materna" },
  },
  {
    id: "sp-049",
    topicId: "salud-publica",
    subtopic: "Salud materno-infantil",
    difficulty: "basico",
    stem: "La tasa de mortalidad infantil se define como:",
    options: [
      "Muertes de niños menores de 5 años por cada 1000 nacidos vivos",
      "Muertes de niños menores de 1 año por cada 1000 nacidos vivos en un periodo determinado",
      "Muertes fetales por cada 1000 embarazos",
      "Muertes maternas por cada 1000 nacidos vivos",
    ],
    correctIndex: 1,
    explanation:
      "La tasa de mortalidad infantil mide las muertes de menores de 1 año por cada 1000 nacidos vivos, distinta de la tasa de mortalidad en menores de 5 años, que amplía el rango de edad.",
    source: { label: "OPS/OMS — Indicadores de salud materno-infantil" },
  },
  {
    id: "sp-050",
    topicId: "salud-publica",
    subtopic: "Salud materno-infantil",
    difficulty: "intermedio",
    stem: "La mortalidad neonatal, definida como las muertes ocurridas en los primeros 28 días de vida, se asocia principalmente con:",
    options: [
      "Enfermedades infecciosas adquiridas en la comunidad después del primer mes de vida",
      "Prematuridad, asfixia perinatal y malformaciones congénitas, ligadas a la atención del embarazo y el parto",
      "Accidentes de tránsito",
      "Enfermedades crónico-degenerativas del adulto",
    ],
    correctIndex: 1,
    explanation:
      "La mayoría de las muertes neonatales se relacionan con causas ligadas a la atención perinatal: prematuridad, complicaciones del parto (asfixia) y malformaciones congénitas, por lo que la calidad de la atención del embarazo y el parto es determinante.",
    source: { label: "OPS/OMS — Indicadores de salud materno-infantil" },
  },
  {
    id: "sp-051",
    topicId: "salud-publica",
    subtopic: "Salud materno-infantil",
    difficulty: "basico",
    stem: "El indicador \"porcentaje de partos atendidos por personal de salud calificado\" se utiliza como proxy de:",
    options: [
      "La calidad de la educación primaria de un país",
      "El acceso y la calidad de la atención obstétrica, relacionado con la reducción de la mortalidad materna y neonatal",
      "El nivel socioeconómico de un país exclusivamente",
      "La cobertura de vacunación infantil",
    ],
    correctIndex: 1,
    explanation:
      "La atención del parto por personal calificado (médico, enfermera obstetra) permite identificar y manejar oportunamente complicaciones, por lo que este indicador se asocia directamente con la reducción de la mortalidad materna y neonatal.",
    source: { label: "OPS/OMS — Indicadores de salud materna" },
  },
  {
    id: "sp-052",
    topicId: "salud-publica",
    subtopic: "Determinantes sociales de la salud",
    difficulty: "basico",
    stem: "Según la OMS, los determinantes sociales de la salud se definen como:",
    options: [
      "Únicamente los factores genéticos heredados",
      "Las circunstancias en que las personas nacen, crecen, viven, trabajan y envejecen, incluidos los sistemas que moldean esas condiciones",
      "Exclusivamente el acceso a hospitales",
      "El clima geográfico de una región, sin relación con factores sociales",
    ],
    correctIndex: 1,
    explanation:
      "Los determinantes sociales de la salud abarcan las condiciones sociales, económicas y ambientales en que las personas viven, así como los sistemas políticos y económicos que las generan, más allá del acceso directo a servicios médicos.",
    source: { label: "OMS — Comisión sobre Determinantes Sociales de la Salud" },
  },
  {
    id: "sp-053",
    topicId: "salud-publica",
    subtopic: "Determinantes sociales de la salud",
    difficulty: "intermedio",
    stem: "La asociación consistente entre mayor nivel educativo materno y menor mortalidad infantil ilustra el papel de qué tipo de determinante de la salud?",
    options: ["Determinante biológico", "Determinante social (educación)", "Determinante genético", "Determinante puramente ambiental físico"],
    correctIndex: 1,
    explanation:
      "La educación materna es uno de los determinantes sociales de la salud mejor documentados: se asocia con mejores prácticas de cuidado infantil, mayor uso de servicios de salud y menor mortalidad infantil, independientemente de factores biológicos.",
    source: { label: "OMS — Comisión sobre Determinantes Sociales de la Salud" },
  },
  {
    id: "sp-054",
    topicId: "salud-publica",
    subtopic: "Determinantes sociales de la salud",
    difficulty: "intermedio",
    stem: "¿Cuál es la diferencia entre equidad e igualdad en salud?",
    options: [
      "Son sinónimos exactos, sin diferencia práctica",
      "La igualdad implica dar lo mismo a todos; la equidad implica distribuir recursos según las necesidades de cada grupo para alcanzar resultados justos",
      "La equidad significa dar menos a quienes más necesitan",
      "La igualdad en salud es un concepto exclusivamente económico, sin relación sanitaria",
    ],
    correctIndex: 1,
    explanation:
      "La igualdad distribuye recursos de forma idéntica para todos, mientras que la equidad los distribuye según las necesidades de cada grupo, buscando eliminar diferencias injustas y evitables en los resultados de salud.",
    source: { label: "OMS — Comisión sobre Determinantes Sociales de la Salud" },
  },
];
