import type { Flashcard } from "@/types/content";

const BIO_SOURCES = {
  audesirk: { label: "Audesirk, Audesirk, Byers — Biología: La vida en la Tierra con Fisiología, 9.ª ed. (Pearson, 2012)" },
  solomon: { label: "Solomon, Berg, Martin — Biología, 9.ª ed. (Cengage Learning, 2013)" },
  curtis: { label: "Curtis, Barnes, Schnek, Massarini — Biología, 7.ª ed. (Panamericana, 2008)" },
  starr: { label: "Starr, Taggart — Biología: La Unidad y Diversidad de la Vida, 11.ª ed. (Cengage Learning, 2008)" },
};

const CHEM_SOURCES = {
  brown: { label: "Brown, LeMay, Bursten et al. — Química: La Ciencia Central, 1.ª ed. español (Pearson, 2021)" },
  chang: { label: "Chang, Goldsby — Química, 12.ª ed. (McGraw-Hill, 2016)" },
  petrucci: { label: "Petrucci, Herring, et al. — Química General, 11.ª ed. (Pearson, 2017)" },
  timberlake: { label: "Timberlake — Química General, Orgánica y Biológica: Estructuras de la Vida, 4.ª ed. (Pearson, 2013)" },
};

export const cienciasBasicasFlashcards: Flashcard[] = [
  {
    id: "fc-cb-001",
    topicId: "ciencias-basicas",
    subtopic: "Niveles de organización",
    front: "Enumera, de menor a mayor, los 12 niveles de organización biológica.",
    back: "Átomo → molécula → organelo → célula → tejido → órgano → sistema de órganos → organismo → población → comunidad → ecosistema → biosfera.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "fc-cb-002",
    topicId: "ciencias-basicas",
    subtopic: "Niveles de organización",
    front: "¿Qué es la homeostasis?",
    back: "La capacidad de un organismo de mantener condiciones internas relativamente estables (temperatura, pH, concentración de solutos) pese a las variaciones del ambiente externo.",
    source: BIO_SOURCES.audesirk,
  },
  {
    id: "fc-cb-003",
    topicId: "ciencias-basicas",
    subtopic: "Biomoléculas",
    front: "¿Por qué el carbono es el elemento base de la química orgánica?",
    back: "Porque tiene 4 electrones de valencia y puede formar hasta 4 enlaces covalentes estables, generando cadenas, ramificaciones y anillos que dan origen a moléculas complejas y diversas.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "fc-cb-004",
    topicId: "ciencias-basicas",
    subtopic: "Biomoléculas",
    front: "Menciona las 4 biomoléculas orgánicas principales y su monómero.",
    back: "Carbohidratos (monosacáridos), lípidos (ácidos grasos + glicerol, no son polímeros verdaderos), proteínas (aminoácidos), ácidos nucleicos (nucleótidos).",
    source: BIO_SOURCES.starr,
  },
  {
    id: "fc-cb-005",
    topicId: "ciencias-basicas",
    subtopic: "Biomoléculas",
    front: "¿Qué propiedad del agua le permite actuar como regulador térmico?",
    back: "Su alto calor específico (por los puentes de hidrógeno entre moléculas), que le permite absorber o liberar grandes cantidades de calor con cambios mínimos de temperatura.",
    source: BIO_SOURCES.audesirk,
  },
  {
    id: "fc-cb-006",
    topicId: "ciencias-basicas",
    subtopic: "Célula",
    front: "Enuncia los 3 postulados de la teoría celular.",
    back: "1) Todos los seres vivos están formados por una o más células. 2) La célula es la unidad estructural y funcional básica de la vida. 3) Toda célula proviene de una célula preexistente.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "fc-cb-007",
    topicId: "ciencias-basicas",
    subtopic: "Célula",
    front: "¿Cómo se diferencian difusión simple, difusión facilitada, ósmosis y transporte activo?",
    back: "Difusión simple: molécula pequeña a favor del gradiente, sin proteína ni ATP. Difusión facilitada: requiere proteína de canal/transportadora, a favor del gradiente, sin ATP. Ósmosis: agua a favor de su gradiente a través de membrana semipermeable. Transporte activo: en contra del gradiente, requiere ATP y proteína transportadora.",
    source: BIO_SOURCES.audesirk,
  },
  {
    id: "fc-cb-008",
    topicId: "ciencias-basicas",
    subtopic: "Célula",
    front: "¿Qué diferencia a la endocitosis de la exocitosis?",
    back: "Endocitosis: la célula incorpora material del exterior englobándolo en una vesícula formada por la membrana plasmática. Exocitosis: la célula libera material al exterior fusionando una vesícula interna con la membrana plasmática.",
    source: BIO_SOURCES.curtis,
  },
  {
    id: "fc-cb-009",
    topicId: "ciencias-basicas",
    subtopic: "Célula",
    front: "Menciona la función principal de: núcleo, mitocondria, RE liso, RE rugoso y aparato de Golgi.",
    back: "Núcleo: alberga y protege el ADN. Mitocondria: síntesis de ATP (respiración aeróbica). RE liso: síntesis de lípidos y detoxificación. RE rugoso: síntesis de proteínas (tiene ribosomas). Golgi: modifica, empaqueta y distribuye proteínas/lípidos.",
    source: BIO_SOURCES.curtis,
  },
  {
    id: "fc-cb-010",
    topicId: "ciencias-basicas",
    subtopic: "Célula",
    front: "¿Cuál es la diferencia estructural clave entre célula procariota y eucariota?",
    back: "La procariota carece de núcleo delimitado por membrana y de organelos membranosos; la eucariota posee núcleo verdadero y organelos membranosos especializados (mitocondrias, RE, Golgi, etc.).",
    source: BIO_SOURCES.curtis,
  },
  {
    id: "fc-cb-011",
    topicId: "ciencias-basicas",
    subtopic: "Metabolismo celular",
    front: "Enuncia la primera y segunda ley de la termodinámica aplicadas a los sistemas biológicos.",
    back: "1.ª ley: la energía no se crea ni se destruye, solo se transforma. 2.ª ley: toda transformación de energía aumenta la entropía del universo, y ninguna transformación es 100% eficiente (siempre se pierde algo de energía como calor).",
    source: BIO_SOURCES.starr,
  },
  {
    id: "fc-cb-012",
    topicId: "ciencias-basicas",
    subtopic: "Metabolismo celular",
    front: "¿En qué compartimento celular ocurre cada etapa de la respiración celular aeróbica?",
    back: "Glucólisis: citosol. Ciclo de Krebs: matriz mitocondrial. Cadena de transporte de electrones: membrana mitocondrial interna.",
    source: BIO_SOURCES.curtis,
  },
  {
    id: "fc-cb-013",
    topicId: "ciencias-basicas",
    subtopic: "Metabolismo celular",
    front: "¿Cómo aceleran las enzimas las reacciones bioquímicas?",
    back: "Disminuyendo la energía de activación necesaria para que ocurra la reacción, sin consumirse en el proceso ni alterar el resultado termodinámico final (no cambian si la reacción es favorable o no, solo la velocidad).",
    source: BIO_SOURCES.audesirk,
  },
  {
    id: "fc-cb-014",
    topicId: "ciencias-basicas",
    subtopic: "Metabolismo celular",
    front: "¿Cuál es la diferencia entre anabolismo y catabolismo?",
    back: "Anabolismo: construye moléculas complejas a partir de simples, consumiendo energía. Catabolismo: degrada moléculas complejas en simples, liberando energía.",
    source: BIO_SOURCES.starr,
  },
  {
    id: "fc-cb-015",
    topicId: "ciencias-basicas",
    subtopic: "División celular",
    front: "Enumera las fases del ciclo celular eucarionte.",
    back: "Interfase: G1 (crecimiento), S (síntesis/replicación del ADN), G2 (preparación final). Fase M: mitosis (división nuclear) + citocinesis (división del citoplasma).",
    source: BIO_SOURCES.curtis,
  },
  {
    id: "fc-cb-016",
    topicId: "ciencias-basicas",
    subtopic: "División celular",
    front: "¿Cuál es la diferencia fundamental entre mitosis y meiosis?",
    back: "Mitosis: 1 célula diploide → 2 células diploides genéticamente idénticas (crecimiento/reparación). Meiosis: 1 célula diploide → 4 células haploides genéticamente distintas (formación de gametos).",
    source: BIO_SOURCES.curtis,
  },
  {
    id: "fc-cb-017",
    topicId: "ciencias-basicas",
    subtopic: "División celular",
    front: "¿Qué es el entrecruzamiento (crossing-over) y cuándo ocurre?",
    back: "Intercambio de segmentos de ADN entre cromátidas de cromosomas homólogos, ocurre durante la profase I de la meiosis; aumenta la variabilidad genética de los gametos resultantes.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "fc-cb-018",
    topicId: "ciencias-basicas",
    subtopic: "Genética mendeliana",
    front: "Enuncia la 1.ª y 2.ª ley de Mendel.",
    back: "1.ª ley (segregación): los dos alelos de un gen se separan durante la formación de gametos, cada gameto recibe solo uno. 2.ª ley (distribución/segregación independiente): los alelos de genes en cromosomas diferentes se heredan de forma independiente.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "fc-cb-019",
    topicId: "ciencias-basicas",
    subtopic: "Genética mendeliana",
    front: "¿Cuál es la diferencia entre genotipo y fenotipo?",
    back: "Genotipo: la constitución genética (alelos) de un individuo. Fenotipo: la expresión observable de ese genotipo, resultado de la interacción entre genes y ambiente.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "fc-cb-020",
    topicId: "ciencias-basicas",
    subtopic: "Genética mendeliana",
    front: "¿Qué son los cromosomas homólogos?",
    back: "Un par de cromosomas (uno materno, uno paterno) que contienen los mismos genes en las mismas posiciones (loci), aunque pueden portar alelos diferentes para esos genes.",
    source: BIO_SOURCES.curtis,
  },
  {
    id: "fc-cb-021",
    topicId: "ciencias-basicas",
    subtopic: "ADN",
    front: "¿Cuáles son los 3 componentes de un nucleótido?",
    back: "Un grupo fosfato (ácido fosfórico), un azúcar de 5 carbonos (pentosa: desoxirribosa en ADN, ribosa en ARN) y una base nitrogenada.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "fc-cb-022",
    topicId: "ciencias-basicas",
    subtopic: "ADN",
    front: "¿Cuál es la regla de complementariedad de bases del ADN?",
    back: "Adenina se aparea con Timina (2 puentes de hidrógeno); Guanina se aparea con Citosina (3 puentes de hidrógeno).",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "fc-cb-023",
    topicId: "ciencias-basicas",
    subtopic: "ADN",
    front: "¿Por qué la replicación del ADN es semiconservativa?",
    back: "Porque cada molécula de ADN hija conserva una de las dos cadenas originales (que sirvió de molde) y sintetiza una nueva cadena complementaria; ninguna hija es completamente nueva ni completamente original.",
    source: BIO_SOURCES.solomon,
  },
  {
    id: "fc-cb-024",
    topicId: "ciencias-basicas",
    subtopic: "Estructura atómica",
    front: "Menciona las 3 partículas subatómicas, su carga y su ubicación.",
    back: "Protón: carga positiva, en el núcleo. Electrón: carga negativa, en la nube electrónica. Neutrón: sin carga, en el núcleo.",
    source: CHEM_SOURCES.chang,
  },
  {
    id: "fc-cb-025",
    topicId: "ciencias-basicas",
    subtopic: "Estructura atómica",
    front: "¿Qué son los isótopos?",
    back: "Átomos de un mismo elemento (mismo número de protones/número atómico) que difieren en su número de neutrones y, por tanto, en su número de masa.",
    source: CHEM_SOURCES.chang,
  },
  {
    id: "fc-cb-026",
    topicId: "ciencias-basicas",
    subtopic: "Tabla periódica",
    front: "¿Qué es la electronegatividad y cómo varía en la tabla periódica?",
    back: "Es la capacidad de un átomo de atraer hacia sí los electrones compartidos en un enlace. Aumenta de izquierda a derecha en un período y disminuye al descender en un grupo (el flúor es el elemento más electronegativo).",
    source: CHEM_SOURCES.brown,
  },
  {
    id: "fc-cb-027",
    topicId: "ciencias-basicas",
    subtopic: "Tabla periódica",
    front: "¿Qué es el número de Avogadro y para qué se usa?",
    back: "6.022 × 10²³ — el número de partículas (átomos, moléculas o iones) contenidas en un mol de sustancia. Conecta la escala atómica con la escala macroscópica (gramos).",
    source: CHEM_SOURCES.chang,
  },
  {
    id: "fc-cb-028",
    topicId: "ciencias-basicas",
    subtopic: "Tabla periódica",
    front: "¿Qué son los electrones de valencia?",
    back: "Los electrones del nivel de energía más externo de un átomo; determinan su reactividad química y su capacidad de formar enlaces.",
    source: CHEM_SOURCES.brown,
  },
  {
    id: "fc-cb-029",
    topicId: "ciencias-basicas",
    subtopic: "Nomenclatura química",
    front: "¿En qué se diferencian los sistemas de nomenclatura clásico, Stock y estequiométrico?",
    back: "Clásico: usa terminaciones -oso (menor estado de oxidación) / -ico (mayor). Stock: usa un número romano entre paréntesis tras el nombre del elemento. Estequiométrico: usa prefijos griegos (mono-, di-, tri-) para indicar cuántos átomos hay de cada elemento.",
    source: CHEM_SOURCES.chang,
  },
  {
    id: "fc-cb-030",
    topicId: "ciencias-basicas",
    subtopic: "Enlaces químicos",
    front: "¿Cuál es la diferencia entre enlace iónico, covalente polar, covalente apolar y metálico?",
    back: "Iónico: transferencia completa de electrones (metal + no metal). Covalente polar: compartición desigual de electrones (diferencia moderada de electronegatividad). Covalente apolar: compartición equitativa (electronegatividades similares). Metálico: cationes metálicos en un 'mar' de electrones deslocalizados.",
    source: CHEM_SOURCES.brown,
  },
  {
    id: "fc-cb-031",
    topicId: "ciencias-basicas",
    subtopic: "Reacciones químicas",
    front: "Enumera los 4 tipos principales de reacciones químicas.",
    back: "Síntesis (A + B → AB), descomposición (AB → A + B), desplazamiento simple (A + BC → AC + B), doble desplazamiento o metátesis (AB + CD → AD + CB).",
    source: CHEM_SOURCES.chang,
  },
  {
    id: "fc-cb-032",
    topicId: "ciencias-basicas",
    subtopic: "Reacciones químicas",
    front: "¿Por qué es necesario balancear una ecuación química?",
    back: "Para cumplir la ley de conservación de la masa (Lavoisier): el número de átomos de cada elemento debe ser igual en reactivos y productos. Se ajustan los coeficientes, nunca los subíndices de las fórmulas.",
    source: CHEM_SOURCES.chang,
  },
];
