import type { Flashcard } from "@/types/content";

export const cirugiaFlashcards: Flashcard[] = [
  {
    id: "fc-cx-001",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    front: "¿Qué es el signo de McBurney y qué evalúa?",
    back: "Dolor a la palpación en el punto de McBurney (unión del tercio externo con los dos tercios internos de la línea entre el ombligo y la espina ilíaca anterosuperior derecha), clásico de apendicitis aguda.",
    source: { label: "Schwartz's Principles of Surgery, 11.ª ed." },
  },
  {
    id: "fc-cx-002",
    topicId: "cirugia",
    subtopic: "Vía biliar",
    front: "¿Cuál es la tríada de Charcot y qué indica?",
    back: "Dolor en hipocondrio derecho, fiebre e ictericia. Indica colangitis aguda. Si se agregan hipotensión y alteración mental, se llama péntada de Reynolds (colangitis supurativa grave).",
    source: { label: "Sabiston Textbook of Surgery, 21.ª ed." },
  },
  {
    id: "fc-cx-003",
    topicId: "cirugia",
    subtopic: "Trauma",
    front: "¿Qué evalúa cada letra del ABCDE del ATLS?",
    back: "A: vía Aérea con control cervical. B: Buena respiración/ventilación. C: Circulación con control de hemorragia. D: Déficit neurológico (Glasgow, pupilas). E: Exposición y control de hipotermia.",
    source: { label: "ATLS Student Course Manual, 10.ª ed." },
  },
  {
    id: "fc-cx-004",
    topicId: "cirugia",
    subtopic: "Preoperatorio",
    front: "¿Qué es la clasificación ASA?",
    back: "Escala del estado físico preoperatorio: ASA I (sano), II (enfermedad sistémica leve), III (grave, limita actividad), IV (amenaza constante a la vida), V (moribundo, no sobrevive sin cirugía), VI (muerte cerebral, donante).",
    source: { label: "American Society of Anesthesiologists" },
  },
  {
    id: "fc-cx-005",
    topicId: "cirugia",
    subtopic: "Trauma",
    front: "¿Qué es la tríada de Beck?",
    back: "Hipotensión, ingurgitación yugular y ruidos cardíacos velados/apagados. Sugiere taponamiento cardíaco por trauma o derrame pericárdico agudo.",
    source: { label: "ATLS Student Course Manual, 10.ª ed." },
  },
  {
    id: "fc-cx-006",
    topicId: "cirugia",
    subtopic: "Heridas",
    front: "¿Cuáles son las 4 clases de heridas quirúrgicas del CDC?",
    back: "I: Limpia. II: Limpia-contaminada (apertura controlada de tracto GI/respiratorio/genitourinario). III: Contaminada (ruptura de técnica estéril, contenido GI derramado). IV: Sucia-infectada (infección clínica preexistente).",
    source: { label: "CDC — Guideline for Prevention of Surgical Site Infection" },
  },
  {
    id: "fc-cx-007",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    front: "¿Qué es la doctrina de Monro-Kellie?",
    back: "El volumen total de los contenidos intracraneales debe mantenerse constante porque el cráneo es un contenedor rígido. La sangre venosa y el LCR salen como mecanismo compensatorio ante un aumento de volumen (masa/sangre); al sobrepasar este límite, la PIC se eleva rápidamente.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "fc-cx-008",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    front: "¿Cómo se diferencian el hematoma epidural y el subdural en la TAC?",
    back: "Epidural: hiperdensidad en lente biconvexa, respeta las líneas de sutura. Subdural: hiperdensidad en forma de media luna/lenticular, NO respeta las líneas de sutura. El daño cerebral subyacente suele ser más severo en el subdural.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "fc-cx-009",
    topicId: "cirugia",
    subtopic: "Cicatrización de heridas",
    front: "¿Cuál es la diferencia entre cierre por primera, segunda y tercera intención?",
    back: "Primera intención: herida limpia cerrada con suturas de inmediato. Segunda intención: se deja abierta para cicatrizar por granulación y contracción. Tercera intención (cierre primario tardío): se deja abierta unos días y luego se cierra con suturas.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 2: Cicatrización de heridas" },
  },
  {
    id: "fc-cx-010",
    topicId: "cirugia",
    subtopic: "Cicatrización de heridas",
    front: "¿Qué es la úlcera de Marjolin?",
    back: "La transformación maligna de una herida crónica de larga duración que no cicatriza. Los bordes volteados de la herida son la diferencia clínica clave entre heridas malignas y no malignas.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 2: Cicatrización de heridas" },
  },
  {
    id: "fc-cx-011",
    topicId: "cirugia",
    subtopic: "Suturas de piel",
    front: "¿Qué diferencia a las suturas absorbibles de las no absorbibles?",
    back: "No absorbibles (seda, nylon, polipropileno): se usan para suturas cutáneas y deben retirarse. Absorbibles (poliglactina, ácido poliglicólico, polidioxanona): se degradan solas en 56-238 días; se usan en suturas subcutáneas/profundas.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 3: Suturas de piel" },
  },
  {
    id: "fc-cx-012",
    topicId: "cirugia",
    subtopic: "Colecistitis",
    front: "¿Cuál es la causa más frecuente de colecistitis aguda y su hallazgo clásico al examen físico?",
    back: "90-95% es secundaria a cálculos biliares que obstruyen el conducto cístico. El hallazgo clásico es el signo de Murphy positivo: detención de la inspiración con la palpación profunda del área subcostal derecha.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 4: Colecistitis" },
  },
  {
    id: "fc-cx-013",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    front: "¿Cuáles son las 3 zonas de lesión descritas por Jackson en una quemadura?",
    back: "Zona de coagulación (centro, tejido más dañado, necrótico), zona de éstasis (vasoconstricción/isquemia, similar a quemadura de 2do grado), y zona de hiperemia (mínima o nula cicatrización, similar a lesión de 1er grado).",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "fc-cx-014",
    topicId: "cirugia",
    subtopic: "Choque",
    front: "¿Cuáles son los 6 tipos de choque reconocidos actualmente?",
    back: "Hipovolémico, cardiogénico, séptico (vasodilatador), neurógeno, por traumatismo y obstructivo. Las 4 categorías clásicas de 1934 eran hipovolémico, vasógeno, neurógeno y cardiogénico.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 6: Choque - Schwartz" },
  },
  {
    id: "fc-cx-015",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    front: "¿A qué zona se refiere típicamente el dolor de origen en el hombro izquierdo?",
    back: "Corazón, cola del páncreas, bazo o hemidiafragma izquierdo. El dolor referido al hombro derecho se asocia a hígado, vesícula biliar o hemidiafragma derecho.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 8: Abdomen agudo" },
  },
];
