import type { Flashcard } from "@/types/content";

export const cirugiaFlashcards: Flashcard[] = [
  {
    id: "fc-cx-001",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    front: "¿Qué es el signo de McBurney y qué evalúa?",
    back: "Dolor a la palpación en el punto de McBurney (unión del tercio externo con los dos tercios internos de la línea entre el ombligo y la espina ilíaca anterosuperior derecha), clásico de apendicitis aguda.",
    source: { label: "Schwartz's Principles of Surgery, 11.ª ed." },
  },
  {
    id: "fc-cx-002",
    topicId: "cirugia",
    subtopic: "Vía biliar",
    front: "¿Cuál es la tríada de Charcot y qué indica?",
    back: "Dolor en hipocondrio derecho, fiebre e ictericia. Indica colangitis aguda. Si se agregan hipotensión y alteración mental, se llama péntada de Reynolds (colangitis supurativa grave).",
    source: { label: "Sabiston Textbook of Surgery, 21.ª ed." },
  },
  {
    id: "fc-cx-003",
    topicId: "cirugia",
    subtopic: "Trauma",
    front: "¿Qué evalúa cada letra del ABCDE del ATLS?",
    back: "A: vía Aérea con control cervical. B: Buena respiración/ventilación. C: Circulación con control de hemorragia. D: Déficit neurológico (Glasgow, pupilas). E: Exposición y control de hipotermia.",
    source: { label: "ATLS Student Course Manual, 10.ª ed." },
  },
  {
    id: "fc-cx-004",
    topicId: "cirugia",
    subtopic: "Preoperatorio",
    front: "¿Qué es la clasificación ASA?",
    back: "Escala del estado físico preoperatorio: ASA I (sano), II (enfermedad sistémica leve), III (grave, limita actividad), IV (amenaza constante a la vida), V (moribundo, no sobrevive sin cirugía), VI (muerte cerebral, donante).",
    source: { label: "American Society of Anesthesiologists" },
  },
  {
    id: "fc-cx-005",
    topicId: "cirugia",
    subtopic: "Trauma",
    front: "¿Qué es la tríada de Beck?",
    back: "Hipotensión, ingurgitación yugular y ruidos cardíacos velados/apagados. Sugiere taponamiento cardíaco por trauma o derrame pericárdico agudo.",
    source: { label: "ATLS Student Course Manual, 10.ª ed." },
  },
  {
    id: "fc-cx-006",
    topicId: "cirugia",
    subtopic: "Heridas",
    front: "¿Cuáles son las 4 clases de heridas quirúrgicas del CDC?",
    back: "I: Limpia. II: Limpia-contaminada (apertura controlada de tracto GI/respiratorio/genitourinario). III: Contaminada (ruptura de técnica estéril, contenido GI derramado). IV: Sucia-infectada (infección clínica preexistente).",
    source: { label: "CDC — Guideline for Prevention of Surgical Site Infection" },
  },
  {
    id: "fc-cx-007",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    front: "¿Qué es la doctrina de Monro-Kellie?",
    back: "El volumen total de los contenidos intracraneales debe mantenerse constante porque el cráneo es un contenedor rígido. La sangre venosa y el LCR salen como mecanismo compensatorio ante un aumento de volumen (masa/sangre); al sobrepasar este límite, la PIC se eleva rápidamente.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "fc-cx-008",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    front: "¿Cómo se diferencian el hematoma epidural y el subdural en la TAC?",
    back: "Epidural: hiperdensidad en lente biconvexa, respeta las líneas de sutura. Subdural: hiperdensidad en forma de media luna/lenticular, NO respeta las líneas de sutura. El daño cerebral subyacente suele ser más severo en el subdural.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "fc-cx-009",
    topicId: "cirugia",
    subtopic: "Cicatrización de heridas",
    front: "¿Cuál es la diferencia entre cierre por primera, segunda y tercera intención?",
    back: "Primera intención: herida limpia cerrada con suturas de inmediato. Segunda intención: se deja abierta para cicatrizar por granulación y contracción. Tercera intención (cierre primario tardío): se deja abierta unos días y luego se cierra con suturas.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 2: Cicatrización de heridas" },
  },
  {
    id: "fc-cx-010",
    topicId: "cirugia",
    subtopic: "Cicatrización de heridas",
    front: "¿Qué es la úlcera de Marjolin?",
    back: "La transformación maligna de una herida crónica de larga duración que no cicatriza. Los bordes volteados de la herida son la diferencia clínica clave entre heridas malignas y no malignas.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 2: Cicatrización de heridas" },
  },
  {
    id: "fc-cx-011",
    topicId: "cirugia",
    subtopic: "Suturas de piel",
    front: "¿Qué diferencia a las suturas absorbibles de las no absorbibles?",
    back: "No absorbibles (seda, nylon, polipropileno): se usan para suturas cutáneas y deben retirarse. Absorbibles (poliglactina, ácido poliglicólico, polidioxanona): se degradan solas en 56-238 días; se usan en suturas subcutáneas/profundas.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 3: Suturas de piel" },
  },
  {
    id: "fc-cx-012",
    topicId: "cirugia",
    subtopic: "Colecistitis",
    front: "¿Cuál es la causa más frecuente de colecistitis aguda y su hallazgo clásico al examen físico?",
    back: "90-95% es secundaria a cálculos biliares que obstruyen el conducto cístico. El hallazgo clásico es el signo de Murphy positivo: detención de la inspiración con la palpación profunda del área subcostal derecha.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 4: Colecistitis" },
  },
  {
    id: "fc-cx-013",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    front: "¿Cuáles son las 3 zonas de lesión descritas por Jackson en una quemadura?",
    back: "Zona de coagulación (centro, tejido más dañado, necrótico), zona de éstasis (vasoconstricción/isquemia, similar a quemadura de 2do grado), y zona de hiperemia (mínima o nula cicatrización, similar a lesión de 1er grado).",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "fc-cx-014",
    topicId: "cirugia",
    subtopic: "Choque",
    front: "¿Cuáles son los 6 tipos de choque reconocidos actualmente?",
    back: "Hipovolémico, cardiogénico, séptico (vasodilatador), neurógeno, por traumatismo y obstructivo. Las 4 categorías clásicas de 1934 eran hipovolémico, vasógeno, neurógeno y cardiogénico.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 6: Choque - Schwartz" },
  },
  {
    id: "fc-cx-015",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    front: "¿A qué zona se refiere típicamente el dolor de origen en el hombro izquierdo?",
    back: "Corazón, cola del páncreas, bazo o hemidiafragma izquierdo. El dolor referido al hombro derecho se asocia a hígado, vesícula biliar o hemidiafragma derecho.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 8: Abdomen agudo" },
  },
  {
    id: "fc-cx-016",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    front: "¿Qué signos clínicos sugieren fractura de la fosa craneal anterior vs. fosa media/posterior?",
    back: "Fosa anterior: equimosis periorbitaria (signo de mapache), rinorrea, lesión de pares I-VI. Fosa media/posterior: equimosis retroauricular (signo de Battle), otorrea/otorraquia, lesión de pares VII-VIII (media) o IX-XII (posterior).",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "fc-cx-017",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    front: "¿Cómo se revierte la anticoagulación por warfarina y por heparina en un paciente con TCE?",
    back: "Warfarina (Coumadin): plasma fresco congelado, vitamina K, concentrado de complejo protrombínico o factor VIIa. Heparina y heparina de bajo peso molecular: sulfato de protamina.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico (Tabla 6-6)" },
  },
  {
    id: "fc-cx-018",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    front: "¿Cuáles son los criterios de muerte cerebral?",
    back: "Escala de Coma de Glasgow = 3, pupilas no reactivas, ausencia de reflejos del tronco cerebral (oculocefálico, corneal, ojos de muñeca, nauseoso), ausencia de esfuerzo ventilatorio espontáneo (prueba de apnea), y ausencia de factores confundentes (intoxicación, hipotermia).",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "fc-cx-019",
    topicId: "cirugia",
    subtopic: "Cicatrización de heridas",
    front: "¿Cuál es la diferencia entre neuropraxia, axonotmesis y neurotmesis?",
    back: "Neuropraxia: desmielinización focal, sin lesión axonal (mejor pronóstico). Axonotmesis: interrupción axonal con preservación de la lámina basal de Schwann. Neurotmesis: transección completa del nervio (peor pronóstico, requiere reparación quirúrgica).",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 2: Cicatrización de heridas" },
  },
  {
    id: "fc-cx-020",
    topicId: "cirugia",
    subtopic: "Colecistitis",
    front: "¿Cuáles son los 3 tipos de anastomosis bilioentéricas para el drenaje de la vía biliar?",
    back: "Coledocoduodenostomía (anastomosis lateral con el duodeno), coledocoyeyunoanastomosis (en Y de Roux), y hepatoyeyunoanastomosis (para estenosis del colédoco u obstrucciones malignas periampollares).",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 4: Colecistitis" },
  },
  {
    id: "fc-cx-021",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    front: "¿Cuáles son las fórmulas usadas para calcular las necesidades calóricas en pacientes quemados?",
    back: "Ecuación de Harris-Benedict: considera género, edad, talla y peso (puede ser imprecisa en quemaduras <40% TBSA). Fórmula de Curreri: 25 kcal/kg/día + 40 kcal por cada % de TBSA quemada al día.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "fc-cx-022",
    topicId: "cirugia",
    subtopic: "Choque",
    front: "¿Qué mediador se eleva en el choque hemorrágico/séptico y se correlaciona con la mortalidad?",
    back: "La interleucina-6 (IL-6) se eleva como respuesta al choque hemorrágico, procedimientos quirúrgicos mayores o traumatismos; sus valores elevados se correlacionan con la mortalidad y contribuyen a la lesión pulmonar, hepática e intestinal (SDRA).",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 6: Choque - Schwartz" },
  },
  {
    id: "fc-cx-023",
    topicId: "cirugia",
    subtopic: "Shock - ATLS",
    front: "¿Cuáles son los 3 patrones de respuesta a la reanimación inicial con líquidos?",
    back: "Respuesta rápida: normalización hemodinámica (pérdida <15%). Respuesta transitoria: mejoría seguida de deterioro (pérdida 15-40%, sugiere sangrado persistente). Respuesta mínima o nula: requiere intervención inmediata (hemorragia grado IV, control quirúrgico urgente).",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 7: Shock - ATLS (Tabla 3-2)" },
  },
  {
    id: "fc-cx-024",
    topicId: "cirugia",
    subtopic: "Abdomen agudo",
    front: "¿Cuál es la presión intraabdominal normal y a partir de qué presión se define hipertensión abdominal?",
    back: "Normal: 5-7 mmHg en decúbito supino. Se considera anormalmente elevada por encima de 11 mmHg, graduándose en 4 niveles de gravedad; los grados 3-4 (>20 mmHg) suelen requerir descompresión quirúrgica.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 8: Abdomen agudo (Tabla 45-2)" },
  },
  {
    id: "fc-cx-025",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    front: "¿Cuáles son las 3 meninges y qué espacio hay entre ellas?",
    back: "Duramadre (adherida al cráneo; el espacio epidural está entre cráneo y duramadre), Aracnoides (el espacio subdural está entre duramadre y aracnoides, sitio de venas puente), Piamadre (adherida al cerebro; el espacio subaracnoideo, entre aracnoides y piamadre, contiene el LCR).",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "fc-cx-026",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    front: "¿Cuál es el signo clásico de la herniación uncal y su mecanismo?",
    back: "Dilatación pupilar (midriasis) ipsilateral asociada a hemiparesia contralateral. El uncus (lóbulo temporal medial) hernia por la muesca tentorial, comprimiendo el III par craneal (midriasis) y el tracto corticoespinal en el mesencéfalo (hemiparesia contralateral).",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "fc-cx-027",
    topicId: "cirugia",
    subtopic: "Trauma craneoencefálico",
    front: "¿Qué divide la tienda del cerebelo y qué estructura pasa por el hiato tentorial?",
    back: "La tienda del cerebelo divide la cavidad craneal en compartimento supratentorial e infratentorial (fosa posterior). El mesencéfalo pasa a través del hiato/muesca tentorial; el nervio oculomotor (III par) discurre por su borde y puede comprimirse en la herniación uncal.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 1: Trauma craneoencefálico" },
  },
  {
    id: "fc-cx-028",
    topicId: "cirugia",
    subtopic: "Cicatrización de heridas",
    front: "¿Cuál es la secuencia temporal de las células inflamatorias que invaden una herida?",
    back: "PMN/neutrófilos: primeras en llegar, pico a las 24-48h (fagocitosis). Macrófagos: concentración máxima a las 48-96h, esenciales para la cicatrización. Linfocitos T: pico alrededor de 1 semana, puente entre fase inflamatoria y proliferativa.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 2: Cicatrización de heridas" },
  },
  {
    id: "fc-cx-029",
    topicId: "cirugia",
    subtopic: "Cicatrización de heridas",
    front: "¿Cuál es la función principal del PDGF en la cicatrización?",
    back: "Es el factor quimiotáctico más potente para fibroblastos y participa en la angiogénesis. Se libera inicialmente de los gránulos alfa de las plaquetas durante la fase de hemostasia/inflamación.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 2: Cicatrización de heridas" },
  },
  {
    id: "fc-cx-030",
    topicId: "cirugia",
    subtopic: "Cicatrización de heridas",
    front: "¿Por qué el esófago y el recto tienen mayor riesgo de dehiscencia anastomótica?",
    back: "Son segmentos extraperitoneales que carecen de serosa, una capa clave para la resistencia mecánica temprana de una anastomosis intestinal.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 2: Cicatrización de heridas" },
  },
  {
    id: "fc-cx-031",
    topicId: "cirugia",
    subtopic: "Choque",
    front: "¿Qué factores del complemento se correlacionan con SDRA y disfunción multiorgánica en el choque?",
    back: "C3a, C4a y C5a: aumentan la permeabilidad vascular, contraen el músculo liso, liberan histamina/TNFα/IL-1 y promueven la adhesión de neutrófilos al endotelio. Su grado de activación se correlaciona con la intensidad de la lesión y el desarrollo de SDRA/MODS.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 6: Choque - Schwartz" },
  },
  {
    id: "fc-cx-032",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    front: "¿Cuáles son los signos de síndrome compartimental inminente en una quemadura circunferencial?",
    back: "Parestesias, dolor, disminución del llenado capilar y progresión a la ausencia de pulsos distales. El tratamiento es la escarotomía (rara vez necesaria en las primeras 8h salvo indicación); si la perfusión no mejora pese a la escarotomía, puede requerirse fasciotomía.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
  {
    id: "fc-cx-033",
    topicId: "cirugia",
    subtopic: "Quemaduras",
    front: "¿Qué indica el tiempo hasta la aparición del vómito tras una exposición a radiación?",
    back: "Es un indicador útil de la dosis de exposición: vómito en 1h sugiere una dosis mínima de 4 Sv, en 2h sugiere una dosis media letal de al menos 3 Sv, y su ausencia en 4h sugiere que no habrá efectos clínicos graves.",
    source: { label: "Resúmenes CPOEM — Cirugía, 1.ª ed. (2023), Cap. 5: Quemaduras" },
  },
];
