import type { Flashcard } from "@/types/content";

export const ginecoObstetriciaFlashcards: Flashcard[] = [
  {
    id: "fc-go-001",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    front: "¿Cómo se define preeclampsia con criterios de severidad?",
    back: "PA sistólica ≥160 o diastólica ≥110 mmHg, o proteinuria significativa más síntomas de severidad: cefalea, alteraciones visuales, dolor epigástrico/hipocondrio derecho, trombocitopenia <100,000, elevación de transaminasas, edema pulmonar o creatinina elevada.",
    source: { label: "ACOG Practice Bulletin — Gestational Hypertension and Preeclampsia" },
  },
  {
    id: "fc-go-002",
    topicId: "gineco-obstetricia",
    subtopic: "Hemorragia obstétrica",
    front: "¿Cuál es la causa más frecuente de hemorragia posparto y su manejo de primera línea?",
    back: "Atonía uterina (~70% de casos). Manejo: masaje uterino bimanual + uterotónicos (oxitocina de primera línea, luego ergometrina/misoprostol), y manejo quirúrgico si no responde.",
    source: { label: "FIGO/OMS — Manejo de la hemorragia posparto" },
  },
  {
    id: "fc-go-003",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    front: "¿Cuáles son los criterios de Amsel para vaginosis bacteriana?",
    back: "Se requieren 3 de 4: flujo blanco-grisáceo homogéneo, pH vaginal >4.5, prueba de aminas (KOH) positiva, presencia de 'clue cells' al microscopio.",
    source: { label: "CDC — STI Treatment Guidelines" },
  },
  {
    id: "fc-go-004",
    topicId: "gineco-obstetricia",
    subtopic: "Control prenatal",
    front: "¿Cuántos contactos prenatales mínimos recomienda la OMS?",
    back: "Al menos 8 contactos durante el embarazo (modelo OMS 2016), sustituyendo el modelo previo de 4 visitas, para reducir la mortalidad perinatal.",
    source: { label: "OMS — Recomendaciones sobre atención prenatal" },
  },
  {
    id: "fc-go-005",
    topicId: "gineco-obstetricia",
    subtopic: "Atención del parto",
    front: "¿Cuándo se define 'detención de la fase activa' del trabajo de parto?",
    back: "Ausencia de progreso de la dilatación cervical por ≥4 horas con dinámica uterina adecuada, o ≥6 horas con actividad uterina inadecuada, en fase activa (≥6 cm de dilatación).",
    source: { label: "ACOG/SMFM — Safe Prevention of the Primary Cesarean Delivery" },
  },
  {
    id: "fc-go-006",
    topicId: "gineco-obstetricia",
    subtopic: "Control prenatal",
    front: "¿Cómo se calcula la fecha probable de parto con la Regla de Naegele?",
    back: "Se suman 7 días al primer día de la FUR, se restan 3 meses y se suma 1 año, ajustando si el cálculo cruza de mes o de año.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 1: Atención prenatal" },
  },
  {
    id: "fc-go-007",
    topicId: "gineco-obstetricia",
    subtopic: "Control prenatal",
    front: "¿Cuál es la función principal de la hCG en el embarazo temprano y cuándo se detecta por primera vez?",
    back: "Previene la involución del cuerpo lúteo (principal fuente de progesterona en las primeras 6 semanas). Se detecta en sangre u orina 8-9 días después de la ovulación, con niveles máximos a los 60-70 días (9-10 semanas).",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 1: Atención prenatal" },
  },
  {
    id: "fc-go-008",
    topicId: "gineco-obstetricia",
    subtopic: "Fisiología del embarazo",
    front: "¿Cuánto aumenta el volumen sanguíneo materno durante el embarazo normal?",
    back: "La hipervolemia del embarazo normal promedia 40 a 45% por encima del volumen no gestacional, alcanzando su máximo cerca de las 32-34 semanas; el aumento en el volumen de eritrocitos es de aproximadamente 450 mL.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 2: Fisiología materna" },
  },
  {
    id: "fc-go-009",
    topicId: "gineco-obstetricia",
    subtopic: "Fisiología del embarazo",
    front: "¿Qué es el signo de Chadwick?",
    back: "La coloración violeta característica de la vagina y el cuello uterino durante el embarazo, resultado del aumento de la vascularización pélvica.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 2: Fisiología materna" },
  },
  {
    id: "fc-go-010",
    topicId: "gineco-obstetricia",
    subtopic: "Atención del parto",
    front: "¿Qué evalúan las cuatro maniobras de Leopold?",
    back: "1) Qué polo fetal ocupa el fondo uterino. 2) De qué lado está el dorso fetal. 3) Qué parte fetal se presenta sobre la pelvis (peloteo). 4) Grado de encajamiento de la presentación en la pelvis.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 3: Parto normal" },
  },
  {
    id: "fc-go-011",
    topicId: "gineco-obstetricia",
    subtopic: "Atención del parto",
    front: "¿Qué componentes califica el índice de Bishop?",
    back: "Dilatación cervical, borramiento (o longitud), estación fetal, consistencia del cuello uterino y posición del cuello uterino. Un puntaje ≥8 indica cuello favorable para inducción.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 3: Parto normal" },
  },
  {
    id: "fc-go-012",
    topicId: "gineco-obstetricia",
    subtopic: "Monitoreo fetal",
    front: "¿Qué caracteriza a la categoría II de FCF (ACOG), la más frecuente en la práctica clínica?",
    back: "Todos los trazados que no cumplen criterios de categoría I (normal, tranquilizador) ni de categoría III (anormal); son indeterminados y requieren vigilancia continua, evaluación y a veces medidas de reanimación intrauterina.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 4: Monitoreo fetal intraparto" },
  },
  {
    id: "fc-go-013",
    topicId: "gineco-obstetricia",
    subtopic: "Monitoreo fetal",
    front: "¿Qué son las unidades Montevideo y qué valor se considera actividad uterina adecuada?",
    back: "Suma de la intensidad de todas las contracciones uterinas en un periodo de 10 minutos, medida por catéter de presión intrauterina. Se considera actividad uterina adecuada a partir de 200 unidades Montevideo; <180 se asocia a detención de la fase activa.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 4: Monitoreo fetal intraparto" },
  },
  {
    id: "fc-go-014",
    topicId: "gineco-obstetricia",
    subtopic: "Atención del parto",
    front: "¿Cómo se diferencia la prolongación de la fase latente de un trastorno de la fase activa?",
    back: "Fase latente prolongada: >20 h en nulípara o >14 h en multípara, tratamiento preferido con reposo en cama. Trastornos de la fase activa (≥6 cm): prolongación (dilatación <1.2-1.5 cm/h) o detención (sin dilatación por ≥4 h con actividad adecuada, o ≥6 h con inadecuada).",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 5: Distocias" },
  },
  {
    id: "fc-go-015",
    topicId: "gineco-obstetricia",
    subtopic: "Puerperio",
    front: "¿En cuánto tiempo se completa la involución uterina posparto?",
    back: "El útero pesa cerca de 1,000 g inmediatamente posparto, ~500 g a la semana, ~300 g a las 2 semanas, y la involución se completa hacia las 4 semanas, cuando pesa casi 100 g.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 6: Puerperio" },
  },
  {
    id: "fc-go-016",
    topicId: "gineco-obstetricia",
    subtopic: "Puerperio",
    front: "¿Cómo se diferencia la melancolía posparto ('baby blues') de la depresión posparto mayor?",
    back: "La melancolía posparto es un estado de ánimo deprimido leve y autolimitado, común 2-3 días después del parto, que suele durar hasta 10 días. Si los síntomas persisten o empeoran más allá de ese plazo, se evalúa para depresión mayor.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 6: Puerperio" },
  },
  {
    id: "fc-go-017",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    front: "¿Cuáles son las 6 categorías clínicas del aborto espontáneo?",
    back: "Amenaza de aborto, aborto inevitable, aborto incompleto, aborto completo, aborto diferido (huevo muerto retenido) y aborto séptico (cualquiera de los anteriores complicado por infección).",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 7: Aborto" },
  },
  {
    id: "fc-go-018",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    front: "¿Cuándo se administra inmunoglobulina anti-D en el manejo del aborto?",
    back: "A todas las pacientes Rh D-negativas no aloinmunizadas, con 300 µg IM administrados después de la evacuación quirúrgica, o dentro de las 72 horas del diagnóstico de falla del embarazo si el manejo es médico o expectante.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 7: Aborto" },
  },
  {
    id: "fc-go-019",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    front: "¿Cuál es la tríada clásica del embarazo ectópico con rotura tubárica?",
    back: "Dolor abdominal bajo/pélvico agudo, menstruación retrasada (amenorrea) y sangrado o manchado vaginal.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 8: Embarazo ectópico" },
  },
  {
    id: "fc-go-020",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    front: "¿Qué es la 'zona discriminatoria' de β-hCG en el diagnóstico de embarazo ectópico?",
    back: "Nivel de β-hCG por encima del cual la imposibilidad de visualizar un embarazo intrauterino con ecografía transvaginal sugiere que el embarazo no es viable o es ectópico. Se establece habitualmente entre 1,500 y 2,000 mIU/mL.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 8: Embarazo ectópico" },
  },
  {
    id: "fc-go-021",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    front: "¿Qué hallazgo ecográfico clásico describe una mola hidatiforme completa?",
    back: "Una masa uterina ecogénica con numerosos espacios quísticos anecoicos, pero sin feto ni saco amniótico, descrita como imagen en 'tormenta de nieve'.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 9: Mola hidatiforme" },
  },
  {
    id: "fc-go-022",
    topicId: "gineco-obstetricia",
    subtopic: "Hemorragia obstétrica",
    front: "Menciona 4 factores de riesgo importantes para el desprendimiento de placenta.",
    back: "Desprendimiento previo (riesgo relativo 10-188), preeclampsia/hipertensión crónica, corioamnionitis, rotura prematura de membranas, tabaquismo y consumo de cocaína.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 10: Desprendimiento de placenta" },
  },
  {
    id: "fc-go-023",
    topicId: "gineco-obstetricia",
    subtopic: "Hemorragia obstétrica",
    front: "¿Cómo se distingue placenta previa, placenta baja y placenta previa marginal?",
    back: "Placenta previa: el orificio cervical interno está cubierto parcial o totalmente. Placenta baja: el borde placentario está dentro de 2 cm del orificio sin cubrirlo. Placenta previa marginal: el borde toca el orificio interno pero no lo cubre.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 11: Placenta previa" },
  },
  {
    id: "fc-go-024",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    front: "Menciona los criterios de severidad de la preeclampsia (además de PA ≥160/110).",
    back: "Trombocitopenia (<100,000/µL), insuficiencia renal (creatinina >1.1 mg/dL), afectación hepática (transaminasas 2x el límite superior + epigastralgia), síntomas de SNC (cefalea, visión borrosa, escotomas), o edema pulmonar.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 12: Trastornos hipertensivos del embarazo" },
  },
  {
    id: "fc-go-025",
    topicId: "gineco-obstetricia",
    subtopic: "Complicaciones del embarazo",
    front: "¿Qué pruebas complementarias ayudan a confirmar el diagnóstico de RPMO?",
    back: "Prueba de nitrazina (papel amarillo → azul con líquido amniótico), prueba de ferning (cristalización en patrón de helecho) y medición del pH vaginal (líquido amniótico >7.0 vs. pH vaginal normal 4.5-5.5).",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 13: Ruptura prematura de membranas ovulares" },
  },
  {
    id: "fc-go-026",
    topicId: "gineco-obstetricia",
    subtopic: "Fisiología del ciclo menstrual",
    front: "¿Cómo se corresponden las fases del ciclo ovárico con las del ciclo uterino?",
    back: "Fase folicular (ovario) ↔ fase proliferativa (endometrio), impulsadas por estrógenos crecientes. Fase lútea (ovario) ↔ fase secretora (endometrio), impulsada por la progesterona del cuerpo lúteo.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 14: Ciclo menstrual" },
  },
  {
    id: "fc-go-027",
    topicId: "gineco-obstetricia",
    subtopic: "Menopausia",
    front: "¿Cómo se caracteriza la transición menopáusica frente a la posmenopausia?",
    back: "Transición menopáusica: concentraciones elevadas de FSH con variaciones en la duración del ciclo. Menopausia: última menstruación seguida de 12 meses de amenorrea. Posmenopausia: el período posterior a la última menstruación.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 15: Menopausia" },
  },
  {
    id: "fc-go-028",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    front: "¿Cuál es el tratamiento inicial de la candidiasis vulvovaginal no complicada?",
    back: "Azoles tópicos en pautas cortas de 3 días, o fluconazol oral en dosis única de 150 mg, con eficacia similar; los síntomas persisten 2-3 días tras iniciado el tratamiento.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 16: Infecciones urogenitales y ETS" },
  },
  {
    id: "fc-go-029",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    front: "¿Qué es el 'sistema de valoración pictórica' de la hemorragia menstrual?",
    back: "Herramienta que asigna puntos según el grado de saturación de toallas/tampones usados durante la menstruación; una puntuación total mayor a 100 puntos es predictiva de menorragia (pérdida >80 mL).",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 17: Hemorragia uterina anormal" },
  },
  {
    id: "fc-go-030",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    front: "¿Cómo clasifica el Sistema Bethesda las lesiones escamosas cervicales potencialmente premalignas?",
    back: "Tres categorías: células escamosas atípicas (ASC, subdividida en ASC-US y ASC-H), lesión intraepitelial escamosa de bajo grado (LSIL, incluye CIN 1), y lesión intraepitelial escamosa de alto grado (HSIL, incluye CIN 2 y CIN 3).",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 18: Detección del cáncer de cérvix" },
  },
  {
    id: "fc-go-031",
    topicId: "gineco-obstetricia",
    subtopic: "Patología ginecológica",
    front: "¿Cuándo se prefiere la biopsia con aguja gruesa (BAG) sobre la punción-aspiración con aguja fina (PAAF) para una masa mamaria?",
    back: "La BAG se prefiere porque obtiene más tejido para estudios diagnósticos, incluyendo receptores de estrógeno/progesterona y Her2/neu, y en general reemplaza a la PAAF salvo para la aspiración de un quiste.",
    source: { label: "Resúmenes CPOEM — Ginecología y Obstetricia, 1.ª ed. (2023), Cap. 19: Detección del cáncer de mama" },
  },
];
