import type { Flashcard } from "@/types/content";

export const medicinaInternaFlashcards: Flashcard[] = [
  {
    id: "fc-mi-001",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    front: "¿Cuáles son los criterios ECG de IAM con elevación del ST?",
    back: "Elevación del ST ≥1 mm en 2 derivaciones contiguas de miembros, o ≥2 mm (hombres) / ≥1.5 mm (mujeres) en derivaciones precordiales, o bloqueo de rama izquierda nuevo con clínica compatible.",
    source: { label: "Fourth Universal Definition of Myocardial Infarction, 2018" },
  },
  {
    id: "fc-mi-002",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    front: "¿Qué significa cada letra de CURB-65?",
    back: "Confusión, Urea (BUN) elevada, frecuencia Respiratoria ≥30, presión arterial Baja (<90/60), edad ≥65 años. Cada ítem suma 1 punto para estratificar gravedad de neumonía.",
    source: { label: "BTS Guidelines for Community Acquired Pneumonia" },
  },
  {
    id: "fc-mi-003",
    topicId: "medicina-interna",
    subtopic: "Endocrinología",
    front: "¿Cuáles son los 4 criterios diagnósticos de diabetes mellitus?",
    back: "1) Glucemia en ayunas ≥126 mg/dL; 2) Glucemia 2h en PTOG ≥200 mg/dL; 3) HbA1c ≥6.5%; 4) Glucemia al azar ≥200 mg/dL con síntomas clásicos. Se requiere confirmación con 2 pruebas si el paciente está asintomático.",
    source: { label: "ADA — Standards of Care in Diabetes 2024" },
  },
  {
    id: "fc-mi-004",
    topicId: "medicina-interna",
    subtopic: "Nefrología",
    front: "¿Cómo se clasifica la ERC por TFG según KDIGO?",
    back: "G1 ≥90, G2 60-89, G3a 45-59, G3b 30-44, G4 15-29, G5 <15 mL/min/1.73m². Se combina con categoría de albuminuria (A1, A2, A3) para el pronóstico completo.",
    source: { label: "KDIGO Clinical Practice Guideline for CKD, 2024" },
  },
  {
    id: "fc-mi-005",
    topicId: "medicina-interna",
    subtopic: "Infectología",
    front: "¿Cuáles son los 3 componentes del qSOFA?",
    back: "Frecuencia respiratoria ≥22/min, alteración del estado mental (Glasgow <15), presión arterial sistólica ≤100 mmHg. ≥2 puntos sugiere alto riesgo de mala evolución por sepsis.",
    source: { label: "Surviving Sepsis Campaign, 2021" },
  },
  {
    id: "fc-mi-006",
    topicId: "medicina-interna",
    subtopic: "Hematología",
    front: "¿Qué diferencia a la anemia ferropénica de la anemia de enfermedad crónica en el perfil de hierro?",
    back: "Ferropénica: ferritina baja, TIBC/transferrina alta, saturación de transferrina baja. Enfermedad crónica: ferritina normal/alta (reactante de fase aguda), TIBC baja o normal.",
    source: { label: "Harrison's Principles of Internal Medicine, 21.ª ed." },
  },
  {
    id: "fc-mi-007",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    front: "¿Cuáles son las 4 clases funcionales NYHA?",
    back: "I: sin limitación. II: limitación leve, síntomas con esfuerzo ordinario. III: limitación marcada, síntomas con esfuerzo menor al ordinario. IV: síntomas en reposo.",
    source: { label: "New York Heart Association — Functional Classification" },
  },
  {
    id: "fc-mi-008",
    topicId: "medicina-interna",
    subtopic: "Gastroenterología",
    front: "¿Cuál es el manejo farmacológico inicial del sangrado variceal en cirrosis?",
    back: "Vasoconstrictor esplácnico (octreótide o terlipresina) + antibiótico profiláctico (ej. ceftriaxona) + endoscopía terapéutica temprana (<12h), junto con reanimación hemodinámica restrictiva.",
    source: { label: "AASLD Practice Guidance, 2023" },
  },
  {
    id: "fc-mi-009",
    topicId: "medicina-interna",
    subtopic: "Infectología",
    front: "¿A qué conteo de CD4 se inicia cada profilaxis primaria de infección oportunista en VIH?",
    back: "Pneumocystis jirovecii: CD4 <200 (TMP-SMX). Toxoplasma gondii: CD4 <100 (TMP-SMX). Complejo Mycobacterium avium (MAC): CD4 <50 (azitromicina).",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 1: VIH" },
  },
  {
    id: "fc-mi-010",
    topicId: "medicina-interna",
    subtopic: "Infectología",
    front: "¿Qué es el síndrome inflamatorio de reconstitución inmune (IRIS)?",
    back: "Empeoramiento paradójico de una infección oportunista preexistente (tratada o subclínica) tras iniciar TARV, causado por la respuesta inflamatoria exagerada de un sistema inmune en recuperación, pese a que el CD4 sube y la carga viral baja.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 1: VIH" },
  },
  {
    id: "fc-mi-011",
    topicId: "medicina-interna",
    subtopic: "Infectología",
    front: "Menciona 3 neoplasias definitorias de sida.",
    back: "Sarcoma de Kaposi (HHV-8), linfoma no Hodgkin, y cáncer cervical invasivo.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 1: VIH" },
  },
  {
    id: "fc-mi-012",
    topicId: "medicina-interna",
    subtopic: "Endocrinología",
    front: "¿Cuál es el protocolo de insulina IV para tratar la cetoacidosis diabética?",
    back: "Bolo IV de 0.1 U/kg seguido de infusión continua a 0.1 U/kg/h. Si la glucemia no baja, se duplica la velocidad de goteo. Se agrega glucosa a la solución cuando la glucemia llega a 250 mg/100 mL, y se reduce la insulina a 0.05-0.1 U/kg/h.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 3: Diabetes mellitus — control y tratamiento" },
  },
  {
    id: "fc-mi-013",
    topicId: "medicina-interna",
    subtopic: "Endocrinología",
    front: "¿Cuáles son los objetivos glucémicos recomendados para un paciente diabético hospitalizado?",
    back: "Pacientes graves: glucosa de 140-180 mg/100 mL. Pacientes no graves: glucemia preprandial <140 mg/100 mL y en otros momentos <180 mg/100 mL. El control muy estricto agrava resultados y aumenta hipoglucemia.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 3: Diabetes mellitus — control y tratamiento" },
  },
  {
    id: "fc-mi-014",
    topicId: "medicina-interna",
    subtopic: "Endocrinología",
    front: "¿Cómo se clasifican las complicaciones relacionadas con la diabetes según el Cuadro 419-1?",
    back: "Microvasculares: retinopatía, neuropatía, nefropatía. Macrovasculares: coronariopatía, arteriopatía periférica, enfermedad vascular cerebral. Otras: gastrointestinales, genitourinarias, dermatológicas, infecciosas, cataratas, glaucoma, enfermedad periodontal.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 4: Diabetes mellitus — complicaciones" },
  },
  {
    id: "fc-mi-015",
    topicId: "medicina-interna",
    subtopic: "Metabolismo",
    front: "¿Cuáles son los 5 componentes evaluados en los criterios NCEP:ATPIII de síndrome metabólico?",
    back: "Obesidad central (perímetro abdominal), hipertrigliceridemia ≥150 mg/dL, HDL bajo (<40 varones/<50 mujeres), presión arterial elevada (≥130/85), y glucosa plasmática en ayuno ≥100 mg/dL o DM2 diagnosticada. Se requieren 3 o más.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 5: Síndrome metabólico" },
  },
  {
    id: "fc-mi-016",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    front: "¿Cómo se clasifica la intensidad de la obstrucción del flujo de aire en EPOC según GOLD?",
    back: "Con FEV1/FVC <0.7 en todos los casos: I Leve (FEV1 ≥80% del predicho), II Moderada (50-79%), III Intensa (30-49%), IV Muy intensa (<30%).",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 6: Enfermedad pulmonar obstructiva crónica" },
  },
  {
    id: "fc-mi-017",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    front: "¿Cuál es el único tratamiento que ha reducido la mortalidad en pacientes con EPOC?",
    back: "El oxígeno complementario en pacientes con hipoxemia crónica.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 6: Enfermedad pulmonar obstructiva crónica" },
  },
  {
    id: "fc-mi-018",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    front: "¿Qué diferencia a los fármacos 'controladores' de los de 'rescate' en el tratamiento del asma?",
    back: "Controladores (uso diario, de fondo): corticosteroides inhalados, antileucotrienos, cromonas, anti-IgE. Rescate (alivio rápido de síntomas agudos): agonistas β2 de acción corta inhalados, anticolinérgicos.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 7: Asma bronquial" },
  },
  {
    id: "fc-mi-019",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    front: "¿Cómo se clasifica la presión arterial según el Cuadro 298-1?",
    back: "Normal: <120/<80. Prehipertensión: 120-139/80-89. Hipertensión etapa 1: 140-159/90-99. Hipertensión etapa 2: ≥160/≥100. Hipertensión sistólica aislada: ≥140/<90.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 8: Hipertensión arterial" },
  },
  {
    id: "fc-mi-020",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    front: "¿Cuáles son 4 causas secundarias importantes de hipertensión arterial y su hallazgo clave?",
    back: "Aldosteronismo primario (hipopotasemia no provocada, proporción aldosterona/renina >30:1), feocromocitoma (catecolaminas/metanefrinas urinarias elevadas), síndrome de Cushing (cortisol libre urinario elevado), coartación de aorta (pulsos femorales disminuidos, soplo interescapular).",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 8: Hipertensión arterial" },
  },
  {
    id: "fc-mi-021",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    front: "¿Cuáles son las contraindicaciones absolutas para el uso de fibrinolíticos en IAMCEST?",
    back: "ECV hemorrágico previo, ECV isquémico en los últimos 12 meses, neoplasia intracraneal/fístula/aneurisma, HTA severa no controlada, sospecha de disección aórtica, cirugía mayor <14 días, hemorragia activa interna, cirugía o traumatismo cerebral <2 meses.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 9: Infarto agudo de miocardio con elevación del ST" },
  },
  {
    id: "fc-mi-022",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    front: "¿Qué evalúa la clasificación de Killip en el IAMCEST?",
    back: "Estima el riesgo de muerte hospitalaria según disfunción ventricular: I sin signos de IC izquierda, II estertores/S3/taquipnea, III edema agudo de pulmón, IV choque cardiogénico (PAS <90 mmHg) con vasoconstricción periférica.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 9: Infarto agudo de miocardio con elevación del ST" },
  },
  {
    id: "fc-mi-023",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    front: "¿Qué predice el puntaje de riesgo TIMI en el síndrome coronario agudo sin elevación del ST?",
    back: "La mortalidad a 14 días, el infarto de miocardio nuevo o recurrente, y la isquemia severa con necesidad urgente de revascularización. Se calcula con 7 variables clínicas, 1 punto cada una.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 10: Infarto agudo de miocardio sin elevación del ST" },
  },
  {
    id: "fc-mi-024",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    front: "¿Cómo se clasifica la angina de pecho según la Canadian Cardiovascular Society (CCS)?",
    back: "Clase I: actividad física habitual no causa angina. II: limitación leve (caminar >2 cuadras/subir >1 tramo). III: limitación considerable (1-2 cuadras/1 tramo). IV: imposibilidad de realizar cualquier actividad física sin angina, puede aparecer en reposo.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 11: Angina de pecho estable" },
  },
  {
    id: "fc-mi-025",
    topicId: "medicina-interna",
    subtopic: "Cardiología",
    front: "¿Cuáles son los grupos farmacológicos base del tratamiento de la IC con fracción de expulsión reducida?",
    back: "IECA (o ARA) + bloqueadores β como base; se agregan antagonistas de mineralocorticoides (espironolactona/eplerenona), diuréticos para el control de volumen, y en casos seleccionados hidralazina/nitratos o ivabradina.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 12: Insuficiencia cardíaca" },
  },
  {
    id: "fc-mi-026",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    front: "¿Cómo se define el síndrome de distrés respiratorio agudo (SDRA)?",
    back: "Inicio agudo de infiltrados bilaterales, hipoxemia severa y edema pulmonar no explicado por falla cardíaca o sobrecarga de volumen.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 13: SARS-CoV-2 / COVID-19" },
  },
  {
    id: "fc-mi-027",
    topicId: "medicina-interna",
    subtopic: "Neumología",
    front: "¿En qué consiste la 'ventilación protectora pulmonar' en el manejo del SDRA?",
    back: "Programar el ventilador con un volumen tidal de 6 mL/kg de peso predicho (hasta 8 mL/kg si el paciente está agitado) y mantener la presión meseta ≤30 cm de agua, para evitar la sobredistensión alveolar.",
    source: { label: "Resúmenes CPOEM — Medicina Interna, 1.ª ed. (2023), Cap. 13: SARS-CoV-2 / COVID-19" },
  },
];
