import type { Flashcard } from "@/types/content";

export const pediatriaFlashcards: Flashcard[] = [
  {
    id: "fc-ped-001",
    topicId: "pediatria",
    subtopic: "Neonatología",
    front: "¿Qué 5 parámetros mide el APGAR?",
    back: "Apariencia (color), Pulso (FC), Gesto/irritabilidad refleja, Actividad (tono muscular), Respiración. Se evalúa al minuto 1 y 5 de vida, con puntaje de 0-2 por parámetro (máx. 10).",
    source: { label: "American Academy of Pediatrics" },
  },
  {
    id: "fc-ped-002",
    topicId: "pediatria",
    subtopic: "Nutrición",
    front: "¿Cómo se diferencia el Kwashiorkor del Marasmo?",
    back: "Kwashiorkor: edema (por hipoalbuminemia), lesiones cutáneas, cambios de cabello — desnutrición proteica predominante. Marasmo: emaciación severa sin edema — déficit calórico-proteico global.",
    source: { label: "OMS — Manejo de la desnutrición aguda severa" },
  },
  {
    id: "fc-ped-003",
    topicId: "pediatria",
    subtopic: "Enfermedad diarreica",
    front: "Según AIEPI, ¿qué signos clasifican 'algún grado de deshidratación'?",
    back: "Dos o más de: inquietud/irritabilidad, ojos hundidos, bebe con avidez/sediento, pliegue cutáneo que se deshace lentamente. Requiere Plan B (rehidratación oral supervisada).",
    source: { label: "OPS/OMS — AIEPI" },
  },
  {
    id: "fc-ped-004",
    topicId: "pediatria",
    subtopic: "Neonatología",
    front: "¿Por qué la ictericia neonatal en las primeras 24h siempre es patológica?",
    back: "La ictericia fisiológica aparece después del 2.º día de vida por inmadurez hepática normal. Si aparece <24h, sugiere hemólisis (incompatibilidad Rh/ABO), sepsis u otra causa patológica que requiere estudio urgente.",
    source: { label: "AAP — Clinical Practice Guideline: Hyperbilirubinemia in the Newborn" },
  },
  {
    id: "fc-ped-005",
    topicId: "pediatria",
    subtopic: "Urgencias pediátricas",
    front: "¿Cómo se diferencia clínicamente el crup de la epiglotitis?",
    back: "Crup: inicio gradual, tos perruna, estridor, disfonía, fiebre baja — tratar con dexametasona ± epinefrina nebulizada. Epiglotitis: inicio abrupto, fiebre alta, sialorrea, posición en trípode, sin tos perruna — emergencia de vía aérea.",
    source: { label: "AAP — Croup: Diagnosis and Management" },
  },
  {
    id: "fc-ped-006",
    topicId: "pediatria",
    subtopic: "Inmunizaciones",
    front: "¿Qué protege la vacuna pentavalente y cuándo se administra en Guatemala?",
    back: "Protege contra difteria, tos ferina, tétanos, hepatitis B y Haemophilus influenzae tipo b. Se aplica a los 2, 4 y 6 meses de edad según el esquema nacional del MSPAS.",
    source: { label: "MSPAS Guatemala — Esquema Nacional de Vacunación" },
  },
  {
    id: "fc-ped-007",
    topicId: "pediatria",
    subtopic: "Enfermedades exantemáticas",
    front: "¿Qué son las manchas de Koplik y qué enfermedad indican?",
    back: "Lesiones blanco-grisáceas sobre base eritematosa en la mucosa bucal, patognomónicas del sarampión; aparecen típicamente 1-2 días antes del exantema.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 1: Enfermedades exantemáticas" },
  },
  {
    id: "fc-ped-008",
    topicId: "pediatria",
    subtopic: "Enfermedades exantemáticas",
    front: "¿Cuál es la característica diagnóstica clave de la varicela?",
    back: "La coexistencia simultánea de lesiones en distintos estadios evolutivos (máculas, pápulas, vesículas y costras) en diferentes áreas del cuerpo.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 1: Enfermedades exantemáticas" },
  },
  {
    id: "fc-ped-009",
    topicId: "pediatria",
    subtopic: "Enfermedades exantemáticas",
    front: "¿Cuáles son los hallazgos clínicos clave de la escarlatina?",
    back: "Fiebre, faringitis, exantema papular áspero tipo 'papel de lija', lengua aframbuesada y líneas de Pastia (acentuación del exantema en pliegues cutáneos), causada por Streptococcus pyogenes.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 1: Enfermedades exantemáticas" },
  },
  {
    id: "fc-ped-010",
    topicId: "pediatria",
    subtopic: "Neonatología",
    front: "¿Cuáles son los 4 mecanismos de pérdida de calor en el recién nacido?",
    back: "Conducción (contacto con superficies frías), convección (corrientes de aire), radiación (hacia objetos fríos cercanos sin contacto) y evaporación (piel húmeda, sobre todo justo tras el nacimiento).",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 2: El recién nacido" },
  },
  {
    id: "fc-ped-011",
    topicId: "pediatria",
    subtopic: "Neonatología",
    front: "¿Cuáles son los factores de riesgo mayores para hiperbilirrubinemia neonatal grave?",
    back: "Ictericia en las primeras 24 horas, incompatibilidad de grupo sanguíneo con Coombs directo positivo, edad gestacional 35-36 semanas, hermano previo con fototerapia, cefalohematoma o hematomas significativos, lactancia materna exclusiva con pérdida de peso excesiva, y origen asiático oriental.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 3: Ictericia fisiológica" },
  },
  {
    id: "fc-ped-012",
    topicId: "pediatria",
    subtopic: "Neonatología",
    front: "¿Cuándo se administra la inmunoglobulina anti-D (RhoGAM) como profilaxis?",
    back: "De rutina alrededor de las 28 semanas de gestación a toda embarazada Rh negativa no sensibilizada, y nuevamente dentro de las 72 horas posparto si el recién nacido resulta Rh positivo.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 4: Enfermedad hemolítica del recién nacido" },
  },
  {
    id: "fc-ped-013",
    topicId: "pediatria",
    subtopic: "Neonatología",
    front: "¿Cuáles son las principales complicaciones asociadas a los lactantes prematuros de bajo peso al nacer, por sistema?",
    back: "Respiratorio: SDR, displasia broncopulmonar, apnea. Cardiovascular: conducto arterioso permeable. Gastrointestinal: enterocolitis necrosante, hiperbilirrubinemia. Metabólico: hipoglucemia, hipocalcemia. SNC: hemorragia intraventricular, retinopatía de la prematuridad. Renal: hiponatremia/hipernatremia.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 5: Prematuridad y crecimiento intrauterino retardado" },
  },
  {
    id: "fc-ped-014",
    topicId: "pediatria",
    subtopic: "Neonatología",
    front: "¿Qué beneficios tienen los corticoides prenatales en la prevención del SDR?",
    back: "Disminuyen la mortalidad global, la duración del soporte ventilatorio, el ingreso a UCIN, y la incidencia de hemorragia intraventricular grave, enterocolitis necrosante y sepsis de comienzo precoz, sin aumentar el riesgo de muerte materna, corioamnionitis o sepsis puerperal.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 6: Síndrome de dificultad respiratoria" },
  },
  {
    id: "fc-ped-015",
    topicId: "pediatria",
    subtopic: "Neonatología",
    front: "¿Cómo se clasifica la displasia broncopulmonar (DBP) en <32 semanas de edad gestacional?",
    back: "Leve: aire ambiente en semana 36 desde la última regla o al dar el alta. Moderada: necesidad de O2 <30% en la semana 36. Grave: necesidad de O2 ≥30% y/o presión positiva (VPP o CPAP nasal) en la semana 36.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 6: Síndrome de dificultad respiratoria" },
  },
  {
    id: "fc-ped-016",
    topicId: "pediatria",
    subtopic: "Crecimiento y desarrollo",
    front: "¿Qué son la 'permanencia del objeto' y la 'ansiedad ante extraños' y cuándo aparecen?",
    back: "Ambos hitos aparecen alrededor de los 9 meses: la permanencia del objeto es la comprensión de que los objetos siguen existiendo aunque no se vean; la ansiedad ante extraños es la angustia/aferramiento del lactante ante una persona desconocida.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 7: Patrones de crecimiento infantil" },
  },
  {
    id: "fc-ped-017",
    topicId: "pediatria",
    subtopic: "Nutrición",
    front: "¿Qué diferencia el índice 'peso para la talla' del índice 'talla/longitud para la edad'?",
    back: "Peso para la talla bajo (emaciación) refleja desnutrición aguda. Talla/longitud para la edad baja (talla baja) refleja el impacto acumulado de un déficit crónico (desnutrición crónica/retraso del crecimiento).",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 8: Índices e indicadores antropométricos" },
  },
  {
    id: "fc-ped-018",
    topicId: "pediatria",
    subtopic: "Inmunizaciones",
    front: "¿Qué contiene la vacuna SPR y cuándo se aplica según el esquema de Guatemala?",
    back: "Contiene virus vivos atenuados de Sarampión, Paperas y Rubéola. Esquema de 2 dosis: primera a los 12 meses, segunda a los 18 meses. No debe aplicarse antes de los 12 meses porque la respuesta inmune no es óptima.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 9: Inmunizaciones" },
  },
  {
    id: "fc-ped-019",
    topicId: "pediatria",
    subtopic: "Enfermedad diarreica",
    front: "¿Cuál es la composición de la solución de rehidratación oral (SRO) de baja osmolalidad de la OMS?",
    back: "75 mEq/L de sodio, 64 mEq/L de cloro, 20 mEq/L de potasio y 75 mmol/L de glucosa, con osmolaridad total de 245 mOsm/L — es el estándar global para el tratamiento de la deshidratación.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 10: Gastroenteritis aguda en niños" },
  },
  {
    id: "fc-ped-020",
    topicId: "pediatria",
    subtopic: "Nutrición",
    front: "¿Cómo se diferencian el Kwashiorkor, el Marasmo y el Kwashiorkor marásmico?",
    back: "Kwashiorkor: caracterizado por edema bilateral (con o sin emaciación). Marasmo: emaciación grave sin edema. Kwashiorkor marásmico: emaciación grave + edema — combina ambos cuadros.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 12: Nutrición, seguridad alimentaria y salud" },
  },
  {
    id: "fc-ped-021",
    topicId: "pediatria",
    subtopic: "Nutrición",
    front: "¿Qué es el síndrome de realimentación y cuál es su alteración central?",
    back: "Complicación potencialmente mortal de la rehabilitación nutricional agresiva en niños con desnutrición. El exceso de hidratos de carbono aumenta la insulina, causando hipofosfatemia grave (piedra angular), además de hipopotasemia e hipomagnesemia.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 12: Nutrición, seguridad alimentaria y salud" },
  },
  {
    id: "fc-ped-022",
    topicId: "pediatria",
    subtopic: "Infecciones respiratorias",
    front: "¿Qué patógenos bacterianos de neumonía predominan según la edad del niño?",
    back: "3 semanas-4 años: Streptococcus pneumoniae (el más común), también S. pyogenes y S. aureus. ≥5 años: Mycoplasma pneumoniae y Chlamydophila pneumoniae predominan (neumonía 'atípica').",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 13: Neumonía adquirida en la comunidad" },
  },
  {
    id: "fc-ped-023",
    topicId: "pediatria",
    subtopic: "Infecciones respiratorias",
    front: "¿Qué hallazgos definen una 'neumonía complicada'?",
    back: "Derrame pleural, empiema, absceso, fístula broncopleural, neumonía necrosante o síndrome de dificultad respiratoria aguda.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 13: Neumonía adquirida en la comunidad" },
  },
  {
    id: "fc-ped-024",
    topicId: "pediatria",
    subtopic: "Urgencias pediátricas",
    front: "¿Cuáles son los 5 tipos principales de choque?",
    back: "Hipovolémico (pérdida de precarga), cardiogénico (fallo de bomba), distributivo (tono vasomotor anómalo, incluye anafiláctico/neurogénico), obstructivo (impedimento físico al flujo cardíaco) y séptico (combinación de distributivo, hipovolémico y cardiogénico).",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 14: Estado de choque" },
  },
  {
    id: "fc-ped-025",
    topicId: "pediatria",
    subtopic: "Urgencias pediátricas",
    front: "¿Cómo se define el síndrome de respuesta inflamatoria sistémica (SRIS) en niños?",
    back: "2 de 4 criterios, de los cuales 1 debe ser temperatura anormal (>38.5°C o <36°C) o recuento de leucocitos anormal para la edad; los otros: taquicardia, y frecuencia respiratoria >2 DE por encima de lo normal o necesidad aguda de ventilación mecánica.",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 14: Estado de choque" },
  },
  {
    id: "fc-ped-026",
    topicId: "pediatria",
    subtopic: "Urgencias pediátricas",
    front: "¿Cuál es el manejo inicial estándar de reposición de líquidos en el choque hipovolémico pediátrico?",
    back: "Bolos IV de 20 mL/kg de suero salino isotónico, repetidos hasta 60-80 mL/kg según respuesta (frecuencia cardíaca, diuresis, relleno capilar <2 seg, nivel de consciencia); si no responde, iniciar vasopresores (noradrenalina o adrenalina).",
    source: { label: "Resúmenes CPOEM — Pediatría, 1.ª ed. (2023), Cap. 14: Estado de choque" },
  },
];
